### ISSUE TITLE
Add SHARE_BACKGROUND_VIDEO_AND_STICKER_IMAGE capability for Instagram stories shareSingle

### ISSUE THREAD

**Issue by FraserCampbell1** [react-native-share/react-native-share#1000]
## Describe the Feature
Feature request - Add SHARE_BACKGROUND_VIDEO_AND_STICKER_IMAGE capability for Instagram stories shareSingle. Essentially an extension of what the SHARE_BACKGROUND_AND_STICKER_IMAGE method does but for a background video. The use case for this is to have an exciting to look at story with video and sticker image - see the attached video for an example of this use case in action. (Spotify share instagram story)

https://user-images.githubusercontent.com/53017082/114772046-3d432380-9d65-11eb-9dc9-266169f180ad.mov

**Comment by jgcmarins** [comment]
related #940
