### ISSUE TITLE
Are `title` & `message` mandatory for Share.open?

### ISSUE THREAD

**Issue by mars-lan** [react-native-share/react-native-share#1011]
## Ask your Question
Both https://react-native-share.github.io/react-native-share/docs/share-open & [ShareOptions type](https://github.com/react-native-share/react-native-share/blob/master/src/types.ts#L85) suggest that `title` & `message` are mandatory, whereas if you're sharing files via `url` or `urls` fields, these two fields shouldn't actually be set.

**Comment by sorinsi** [comment]
I actually found a "bug" where I get ```Permission Denial: reading cl.json.RNShareFileProvider uri ... some more logs``` if there is no title or it is empty when I try to share a PDF so I guess it may be necessary for Android.

I didn't really investigate further so my best guess is that it is necessary to have some kind of title.

**Comment by seancheung** [comment]
And the typings are also incorrect. Those two fields are optional.
If they are set, sharing files or urls will be broken!

**Comment by Manouli** [comment]
I can confirm also that the typings seem incorrect.

**Comment by mikehardy** [comment]
@Manouli @seancheung hit that little pencil / edit button at the top of the file here on github and propose an edit!
