### ISSUE TITLE
duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by SupriyaGo** [react-native-share/react-native-share#1012]
getting error on ios in RNshare - duplicate symbols for architecture x86_64

I am using payUBiz skd on my project and getting this error when building the app because both the lib haveutils.m utils.h files.

How to fix this error?

**Comment by mikehardy** [comment]
Like this: https://github.com/react-native-share/react-native-share/issues/913#issuecomment-813446599 

- either propose a PR here that makes the name unique (prefix netinfo or something)
- hack your local code and use patch-package to persist the hack

**Comment by Talha-Jawed** [comment]
any luck how to resolve this issue? @SupriyaGo

**Comment by SupriyaGorai1995** [comment]
@Talha-Jawed no sir, I just used linking library for now.
