### ISSUE TITLE
Android Performance?

### ISSUE THREAD

**Issue by gburnett** [react-native-share/react-native-share#1014]
## Ask your Question
I find that performance can vary on Android devices.  Sometimes it takes a very short time to launch the native share interface.  Sometimes it can take 10 to 15 seconds.

Does anyone know what affects this?

It would be good to know how #646 was dealt with.

**Comment by MateusAndrade** [comment]
Hi @gburnett, with kind of files/content did you share(pdf, txt, etc)?

**Comment by gburnett** [comment]
@MateusAndrade It was pdf files.  I have since realised that this varied based on time taken to generate the file.  I'll close this issue since it's now clear that it is unrelated to this library.
