### ISSUE TITLE
Whatsapp Business Support Needed

### ISSUE THREAD

**Issue by vijaychouhan-rails** [react-native-share/react-native-share#1016]
## Describe the Feature
I found that here https://react-native-share.github.io/react-native-share/docs/share-single#supported-applications [Whatsapp](https://play.google.com/store/apps/details?id=com.whatsapp&hl=en) supported but [Whatsapp Business](https://play.google.com/store/apps/details?id=com.whatsapp.w4b&hl=en) not supported, could you please add support for WhatsApp Business Too

**Comment by andyrobert3** [comment]
https://github.com/react-native-share/react-native-share/pull/1036

I think this PR attempts to address it
