### ISSUE TITLE
Twitter sharing of base64 file in URL doesn't work as expected on iOS

### ISSUE THREAD

**Issue by Zygro** [react-native-share/react-native-share#1025]
### Steps to reproduce
1. use on iOS
```
Share.shareSinge({
     title: 'Share twitter',
     message: 'Message',
     social: Share.Social.TWITTER,
     url:'data:image/png;base64,...',
})
  ```

### Expected behaviour
I'm redirected to twitter with pre-filled image encoded by base64 in url

### Actual behaviour
Base64 url is filled in as text:
![Simulator Screen Shot - iPhone 11 - 2021-05-12 at 16 59 15](https://user-images.githubusercontent.com/9499194/117997650-71e5d300-b343-11eb-95df-b85803fa10ae.png)

### Environment
- **React Native version**: 0.63.4
- **React Native platform + platform version**: iOS 13.1.3

### react-native-share
**Version**: 6.0.1

**Comment by Zygro** [comment]
I have also tried the `file://path/to/file.png` and it also "shares" the URI as text

**Comment by PhongTV97** [comment]
add type: "image/jpeg" to options, it worked for me :)))

**Comment by Zygro** [comment]
Unfortunately it doesn't change anything for me :(

**Comment by bhavya420** [comment]
@Zygro did you find any solution to this?

**Comment by Zygro** [comment]
@bhavya420 unfortunately no, we redesigned the app to have the `Share.open` dialog, which works fine

**Comment by bhavya420** [comment]
@Zygro it is working for me now
I added 	
`<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>whatsapp</string>
		<string>instagram-stories</string>
                <string>instagram</string>
                <string>twitter</string>
	</array>`
and updgraded the version to 6.2.0, one of these things seems to fixed this

**Comment by akmaurya288** [comment]
is there any fix for this bug 
url is shown as text
![Simulator Screen Shot - iPhone 8 - 2021-08-18 at 12 20 00](https://user-images.githubusercontent.com/35041620/129851662-bf67c23d-f2fa-4697-b8ab-e1271aa01099.png)

**Comment by bhavya420** [comment]
@akmaurya288 have you added the below code in Info.plist
```
<key>LSApplicationQueriesSchemes</key>
	<array>
                <string>twitter</string>
	</array>

```

**Comment by eramudeep** [comment]
> I'm having a very similar issue. Using the `shareSingle` a URL to the video gets shared as text instead of the actual video. On Android sharing a video works as expected. Does anyone have any suggestions on this?

i was facing something similar, in my case its saying invalid media. 
i did convert the media to base64 and it worked for. 
But another issue arise. now i message and title is not appearing.
