### ISSUE TITLE
Message Field is no longer populated for Slack sharing on iOS

### ISSUE THREAD

**Issue by SheW0lf** [react-native-share/react-native-share#1027]
This issue seems to have started with the newest Slack app version for IOS. Previously this functionality worked as expected.

### Expected behaviour
The defined message property when sharing with slack should populate the message field.

### Actual behaviour
The message field is blank. Works as expected on Android.

### Environment
- **React Native version**: 0.62.2
- **React Native platform + platform version**: iOS 14.5.1
- **Typescript version** (if using typescript): 3.9.7

### react-native-share
**Version**: 3.6.0 (I tried updating to several newer versions of the library and the issue still persisted)

### Link to repo (highly encouraged)
Private Repo, cannot provide

**Comment by akash-gupt** [comment]
@SheW0lf got any sucess?

**Comment by OwenMelbz** [comment]
We've just noticed this is an issue also, wonder if anybody had any luck?

**Comment by fgarcilazo** [comment]
Was this issue resolved on the latest version?

**Comment by MR-AMDEV** [comment]
Still happening to me on **RN 0.77.1**. This isn't fixed.
