### ISSUE TITLE
Is there any way to know programatically that user closes share pop up?

### ISSUE THREAD

**Issue by Yandamuri** [react-native-share/react-native-share#1032]
I want to call some action when user closes share pop up. Is there any way to know that?

**Comment by akinncar** [comment]
If you talking about `Share.open`, this function is a promise, then you can call some function when the user rejects the share popup with a `.catch`, like suggested on documentation.

```js
Share.open(options)
  .then(res => {
    console.log(res);
  })
  .catch(err => {
    // call your action here
    err && console.log(err);
  });
```

Console when user closes the popup:
```shell
[Error: User did not share]
```

**Comment by Yandamuri** [comment]
@akinncar  Does catch execute only when share pop is closed or for some other errors as well? If the catch is responsible for handling errors, what type of errors can we expect?
