### ISSUE TITLE
Share multiple images in IG Post doesn't works.

### ISSUE THREAD

**Issue by chiny20035** [react-native-share/react-native-share#1033]
I'm trying to share a list of images to instagram feed section using shareSingle command:

`Share.shareSingle(  {
            social: Share.Social.INSTAGRAM,
            urls: values,
})`

**Problem**
**iOS**
Instagram is open perfectly but displaying the Story section instead of Feed Section. I want to display the post section with all images selected. 

**PD**: If I going to the Feed Section, all images are in there and all it's OK.

**Android**
Instagram is open perfectly but create a Story with all images  instead of a Feed with multiple images.

I tried with base64 images and with png images. 

Is it possible?

Best regards

**Comment by kaioduarte** [comment]
@chiny20035 I don't think this is possible, there is no mention of it in the documentation.

I also did a test on my phone and the option to share with the feed is only available for a single media.


https://user-images.githubusercontent.com/11046907/120866053-1a740500-c587-11eb-88d0-850a8bf04766.mp4

**Comment by chiny20035** [comment]
@kaioduarte but multiple images is soported. The problem is that just works for stories and this is not explained into the doc. Additionally when I set forceDialog in true for android, nothing happens. Is it OK?

**Comment by kaioduarte** [comment]
@chiny20035 I don't know about the `forceDialog` option, regarding the multiple sharing that's not explained on Instagram's documentation both for sharing to feed or stories.

Can you try to implement this suggestion and share your results?
https://stackoverflow.com/questions/50460270/posting-multiple-images-to-instagram-using-intents
