### ISSUE TITLE
shareSingle opens market places instead of sharing Instagram & Facebook stories 

### ISSUE THREAD

**Issue by OleksiyTrofimenko** [react-native-share/react-native-share#1042]
### Steps to reproduce
1. yarn add react-native-share
2. npx pod-install
3. create an example with a base64 image
4. create an action that triggers a library for a specific social network
5. update in info.plist key with values responded for required social network 
![info-plist](https://user-images.githubusercontent.com/43503615/121908173-67996900-cd35-11eb-9d04-b82c50d02455.png)
6. Action for Instagram stories
![fb-story](https://user-images.githubusercontent.com/43503615/121907912-2c973580-cd35-11eb-9bdd-4beef7a729f8.png)

7. Action for FB stories 
![in-story](https://user-images.githubusercontent.com/43503615/121907877-26a15480-cd35-11eb-8a93-0bf794889987.png)

### Expected behavior
Both actions should open relevant apps and provide a pre-defined image for story posting 

### Actual behavior
Both actions lead to **Apple Store** but both applications installed on the device and used active logged session

### Environment
- **React Native version**: "^3.8.3"
- **React Native platform + platform version**: Tested on iOS 14.4, IOS 14.5.1 and IOS 14.6
- **Typescript version** (if using typescript): "^3.8.3"

### react-native-share
**Version**: "^6.2.0",

**Comment by uniorunr** [comment]
@OleksiyTrofimenko 
As for Facebook Stories, you need to use `<string>facebook-stories</string>` instead of `<string>fb-stories</string>` in Info.plist.
Also, you need to specify `appId` or the FB Story edit window won't appear.

**Comment by Arkan4ik** [comment]
@uniorunr how to get appId? If I develop app where user can share post from my app. The behavior should be next: user click on button and facebook app opens in creating post/story screen with the last image in my assets. With instagram post/story no problem, but problem with facebook. Cant understand where to get this facebook appId?

**Comment by Richi2293** [comment]
Hi,

i ran into the same problem too
