### ISSUE TITLE
Google play console rejected, PendingIntent issue

### ISSUE THREAD

**Issue by bondanherumurti** [react-native-share/react-native-share#1043]
### Steps to reproduce
1. Install react-native-share
2. Submit app to google play console

### Expected behaviour
Google Play should accept the app

### Actual behaviour
Google play reject because of pendingIntent issue

<img width="967" alt="Screen Shot 2021-06-23 at 08 29 34" src="https://user-images.githubusercontent.com/1384256/123020887-3b4caf00-d3fd-11eb-8b3b-7cba96af4414.png">

I found this when I search my entire node modules on TargetChosenReceiver.java

```       
 final PendingIntent callback = PendingIntent.getBroadcast(reactContext, 0, intent,
 PendingIntent.FLAG_CANCEL_CURRENT | PendingIntent.FLAG_ONE_SHOT);
```

This is what google suggest

https://support.google.com/faqs/answer/10437428

### Environment
- **React Native version**: 0.61.5

### react-native-share
**Version**: "^2.0.0"

**Comment by mikehardy** [comment]
Interesting.

> How to fix “Implicit PendingIntent” alerts
> 
> Review your app for the location where a PendingIntent is created. For example, the following code creates a PendingIntent wrapping an implicit intent: 
> 
> ```java
> // Create an implicit base Intent and wrap it in a PendingIntent
> Intent base = new Intent("ACTION_FOO");
> base.setPackage("some_package");
> PendingIntent pi = PendingIntent.getService(this, 0, base, 0);
> ```
> 
> Google recommends that developers fix the vulnerability by applying any (or even better, all) of the following:
> 
>     Ensuring that the action, package, and component fields of the base Intent are set; 
>     Ensuring that the PendingIntent is only delivered to trusted components; 
 >    Using FLAG_IMMUTABLE (added in SDK 23) to create PendingIntents. This prevents apps that receive the PendingIntent from filling in unpopulated properties. In case the app also runs on devices running SDK 22 or older, we recommend developers to apply the previous options while strengthening the PendingIntent creation with the pattern:
> 
> ```java
> if (android.os.Build.VERSION.SDK_INT >= 23) {
> 
>   // Create a PendingIntent using FLAG_IMMUTABLE
> 
> } else {
> 
>   // Existing code that creates a PendingIntent
> 
> }
> ```

https://github.com/react-native-share/react-native-share/blob/4eaf491a1db32b60e79996369c6d79062eeb34eb/android/src/main/java/cl/json/social/TargetChosenReceiver.java#L55-L56

How did it go when you tried editing node_module to alter that file to optionally create the PendingIntent with FLAG_IMMUTABLE based on the VERSION.SDK_INT check they mention?

You can use patch-package to keep your work across yarn/npm installs while testing it. If they're documentation is correct then it should fix  your issue and get you approved, at which point it would be a great PR here

**Comment by mikehardy** [comment]
also - perhaps I'm just not using this functionality so my APK had the code minimized out during release build, but I use this module and just uploaded a new build to Play Store yesterday, and they approved it and released it :shrug:  ?

**Comment by bondanherumurti** [comment]
yes I use npx patch-package to fix it

I don't really have experience on JAVA so, I tried my best as long as it didn't crash. Anyone better at java might have better solution

```
        final PendingIntent callback = PendingIntent.getBroadcast(reactContext, 0, intent,
        PendingIntent.FLAG_IMMUTABLE | PendingIntent.FLAG_CANCEL_CURRENT | PendingIntent.FLAG_ONE_SHOT);
```

This is what I submit, I'm looking forward for 1x24hours from google to review again my app.

**Comment by mikehardy** [comment]
That is just coding it in without verifying build version code though. The code appears to check originally for lollipop mr1 which is API22, meaning API22 devices can get in here and execute the code, but the IMMUTABLE flag is only for API23 and up

So you need an extra conditional similar to the lollilpop_mr1 above, and you need to create one PendingIntent if < API23 that does not have IMMUTABLE, or if >=API23 create a different intent that does have the flag

**Comment by mikehardy** [comment]
Excellent that you're trying it though, it's not easy digging in and coding up stuff in unfamiliar languages but it can certainly be done :muscle:

**Comment by mussegam** [comment]
Hi,

my android knowledge is a bit lacking too, but after reading the docs I think this would work for both scenarios by making the intent explicit:

```
Intent intent = new Intent(sTargetChosenReceiveAction);
intent.setPackage(reactContext.getPackageName());
intent.setClass(context, TargetChosenReceiver.class);
```

**Comment by bondanherumurti** [comment]
Still rejected, I have changed the patch into 

```
        Intent intent = new Intent(sTargetChosenReceiveAction);
        intent.setPackage(reactContext.getPackageName());
        intent.putExtra(EXTRA_RECEIVER_TOKEN, sLastRegisteredReceiver.hashCode());
        
        if (android.os.Build.VERSION.SDK_INT >= 23) {
            PendingIntent callback = PendingIntent.getBroadcast(reactContext, 0, intent,
            PendingIntent.FLAG_IMMUTABLE);
        // Create a PendingIntent using FLAG_IMMUTABLE
            return callback.getIntentSender();
        } else {
        // Existing code that creates a PendingIntent
            PendingIntent callback = PendingIntent.getBroadcast(reactContext, 0, intent,
            PendingIntent.FLAG_CANCEL_CURRENT | PendingIntent.FLAG_ONE_SHOT);
            return callback.getIntentSender();
        }
```

Google still reject it, and I found nowhere pendingIntent again in my node_modules other than this one. I have emailed an appeal asking which pendingIntent is not comply, and it has been 5 days, they haven't reply it.

I am confuse right now, what to do

**Comment by bondanherumurti** [comment]
> Hi,
> 
> my android knowledge is a bit lacking too, but after reading the docs I think this would work for both scenarios by making the intent explicit:
> 
> ```
> Intent intent = new Intent(sTargetChosenReceiveAction);
> intent.setPackage(reactContext.getPackageName());
> intent.setClass(context, TargetChosenReceiver.class);
> ```

I'll try this making it explicit, I'll update the result

**Comment by bondanherumurti** [comment]
Hi guys, finally the app approved by google it should be fixed if you follow google suggestion here https://support.google.com/faqs/answer/10437428

Cheers
