### ISSUE TITLE
shareSingle open Play Store (I have app installed in my device)

### ISSUE THREAD

**Issue by nvrsantos** [react-native-share/react-native-share#1052]
## When I use shareSingle with any social the package open the Play Store in the social page same if in my device just social is installed!

**Android Version:** 11

```
Share.shareSingle({
  title: 'title test',
  message: `${message}`,
  url: `${HOST}/${user.id}`,
  social: Share.Social.WHATSAPP,
})
.then(res => console.log(res))
.catch(err => {
  console.log(err);
});
```

In console return `{"app": null, "message": true}`

**Comment by mikehardy** [comment]
What did you observe when you used the example app?

**Comment by nvrsantos** [comment]
Yea! That's how it worked

**Comment by mikehardy** [comment]
So, the example app works? If so, there's no issue here? The issues list here is focused on items that will result in a change in the module, i.e., issues. But I may be misunderstanding what you meant precisely by "That's how it worked"

**Comment by nvrsantos** [comment]
Yes it feature worked using example app...
Where can I found help? 

I updated my library, and now it's return `{"message": null, "success": true}` but yet open the Play Store...

**Comment by nvrsantos** [comment]
I solve this problem!

In the Android 11 some information about other apps are "blocked", for this we need use `<queries>` in `AndroidManifest.xml` for more details read [here](https://developer.android.com/about/versions/11/privacy/package-visibility).
[Implement queries in AndroidManifest](https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9)

**Comment by mikehardy** [comment]
@nvrsantos that's really interesting! Might be worth an edit API document here to put that link in - could save future people some time. Could you propose a PR to update the documentation?

**Comment by nvrsantos** [comment]
> @nvrsantos that's really interesting! Might be worth an edit API document here to put that link in - could save future people some time. Could you propose a PR to update the documentation?

Of course!

**Comment by nvrsantos** [comment]
@mikehardy PR opened in #1054
