### ISSUE TITLE
Cant share stiker to instagram stories

### ISSUE THREAD

**Issue by moseffect21** [react-native-share/react-native-share#1053]
### Steps to reproduce
1. get base64 background and sticker images
2. 
![image](https://user-images.githubusercontent.com/52028340/125471880-a62ebb81-4579-41a4-b82c-ac7d0dca44b1.png)

### Expected behaviour
background and sticker will shared to inst-stories on Android && ios

### Actual behaviour
on ios works fine, on android only background shared

### Environment
- RN-share version - 6.2.2
- RN version - 0.64.0

**Comment by moseffect21** [comment]
still opened

**Comment by moseffect21** [comment]
Problem solved. If anyone encountered this problem, I can write down the instructions

**Comment by erengamester** [comment]
i faced the same problem

**Comment by vikcodes** [comment]
@moseffect21 can you provide the instructions, also facing the same issue

**Comment by moseffect21** [comment]
> @moseffect21 can you provide the instructions, also facing the same issue

On Android, the sticker must be downloaded from your local phone storage. it is written in the Instagram documentation

In my case:
1) I download the sticker via url and save it on my phone and read as base64
![IMG_20211105_073755.jpg](https://user-images.githubusercontent.com/52028340/140459055-9ae951a0-8156-49b5-950a-df7cf97b5fb1.jpg)

2) send sticker from local phone storage to instagram as base 64
![IMG_20211105_073913.jpg](https://user-images.githubusercontent.com/52028340/140459071-9cb3ed5f-8a31-482e-a3a3-b8ea26fd72ac.jpg)
