### ISSUE TITLE
Can I control the apps that appear in the share menu?

### ISSUE THREAD

**Issue by gburnett** [react-native-share/react-native-share#1055]
I'm using the open method of react-native-share to share an html file on an android device.

When I share the file I thought there would be an option to share to the browser. There is no such option.

The docs suggests that I might be able to limit the apps in the share menu. I don't see anything that suggests that I can add apps to the share menu.

Is it possible to control the apps that appear in the share menu?

**Comment by MateusAndrade** [comment]
Hi @gburnett , the apps shown are specified by the OS showing the app compatible with the desired activity. Maybe you could use `Share.single` to use an specific app. Let me know if this helped you. 😄
