### ISSUE TITLE
Does this library will support Android API 30?  (Android 11) (SDK 30)

### ISSUE THREAD

**Issue by IhorFedorkiv94** [react-native-share/react-native-share#1064]
## Ask your Question
In 2021, we are continuing with our annual target API level update, requiring new apps to target API level 30 (Android 11) in August and in November for all app updates
[https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html](url)

**_react-native-share_** will be supported by SDK 30 (Android 11) ? 
Current version **_react-native-share_** lib

![image](https://user-images.githubusercontent.com/50927095/128211946-985a80db-16ad-4e2e-95ad-6058219092c2.png)

**Comment by mikehardy** [comment]
How did it go when you defined those variables in your root gradle project, and updated them to what you want, then tested it?

(spoiler alert: it works fine)
