### ISSUE TITLE
[Android S] FLAG_IMMUTABLE or FLAG_MUTABLE should be specified

### ISSUE THREAD

**Issue by robertying** [react-native-share/react-native-share#1073]
### Steps to reproduce
1. Change Android targetSdkVersion to 31 (S)
2. Call `share.open()`

### Expected behaviour
Sharing works when targeting Android 30

### Actual behaviour
Got an error saying:

```
Object {
  "error": "com.xxx.aaa: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.",
}
```

### Environment
- **React Native version**: 0.65.1
- **React Native platform + platform version**: Android S

### react-native-share
**Version**: 7.0.0

**Comment by mikehardy** [comment]
"PRs happily accepted!"

Here is a reasonable example of how to do it (since the flag did not exist before SDK Version 23 you have to be careful with how you add it, as react-native supports 21 still (and was at 16 until quite recently)

**Comment by robertying** [comment]
@mikehardy of course! I had to report the issue first. I will possibly come back with a PR when I have more time. 😄

**Comment by robertying** [comment]
Close by https://github.com/react-native-share/react-native-share/pull/1077
