### ISSUE TITLE
Is there url limit for sharing in android?

### ISSUE THREAD

**Issue by trumanfromkorea** [react-native-share/react-native-share#1081]
I'd want to share base64 image in my app.
It works well in iOS but not working in android.

When the size of image is small, 
feature works without image.
But when the size of image is large, it returns a .bin file.

Here's my code, can somebody help me?

```
// convert image
// url -> base64
    const encodeBase64Img = async () => {
        var xhr = new XMLHttpRequest();

        xhr.open("GET", content?.cover, true);
        xhr.responseType = "blob";

        xhr.onload = function (e) {
            var reader = new FileReader();
            reader.onload = function (event) {
                var res = event.target.result;
                // set image state
                setShareImage(res);
            }
            var file = this.response;
            reader.readAsDataURL(file)
        };
        xhr.send()
    }

    // share method
    const shareItems = async () => {
        const shareOptions = {
            title: 'Share Contents',
            message: 'sharing message',
            url: shareImage, // converted base64 image
        };
        Share.open(shareOptions)
            .then((res) => console.log(res))
            .catch((e) => console.log(e));
    }
```

**Comment by MateusAndrade** [comment]
Probably this is behavior is from the OS. Btw, what happens when you try to share the bin file?

**Comment by trumanfromkorea** [comment]
> Probably this is behavior is from the OS. Btw, what happens when you try to share the bin file?

Some devices show an alert like 'it couldn't be shared',
but some devices share .bin file with no problem.

**Comment by trumanfromkorea** [comment]
> > > Probably this is behavior is from the OS. Btw, what happens when you try to share the bin file?
> > 
> > 
> > Some devices show an alert like 'it couldn't be shared',
> > but some devices share .bin file with no problem.
> 
> Strange, maybe you can use a strategy to shorten the URLS. What do you think?

I'll try it.
But I think it won't work because the URL is gonna be a base64 format. 😭
Thank you for helping me. 😃
