### ISSUE TITLE
[Android 11] - share files from documentDir to external apps

### ISSUE THREAD

**Issue by kevinleemans** [react-native-share/react-native-share#1083]
Hi,

I was wondering if it is possible (or if the maintainers are currently working on a solve) to share files from the documentDir of your android phone to external apps.
I know you used to first copy the file to the downloadsDir to make it shareable to every external application, but since Android 11 the write_external_storage flag requires special permission from google to be used. Since the downloadDir is not accessible from your internal app storage this is kind of a problem.
Any ideas on this subject?

**Comment by mikehardy** [comment]
To set expectations, any work here will need to be done by some community member, and there is no one working on it at the moment.

In Android scoped storage (the new access regime) the app still has access by default to its own cache dirs and document dirs

The idea would be to copy from whatever system document dir the user allows access to - via a ContentResolver not direct file access, so it is allowed - into the apps cache dir or document dir since you cannot re-share directly I don't believe.

Then you share from there via a URI to a react-native-share content resolver (which I believe this module can already do?) which is allowed along as you grant permission on the URI for the content resolver (which I believe this module can already do?)

So, not sure about the "copy from non-app dir to app dir via ContentResolver" bit but that should be possible with some module, certainly - perhaps react-native-fs ? or maybe a code change here to "internalize" a file picked by the user, and I'm not sure about then sharing it back out, but that's the avenue to pursue via testing + code inspection for anyone that wants to check it out

**Comment by kevinleemans** [comment]
Alright, thanks for the clarification, I'll try to copy the file from the documentDir to another path of the documentdir (that is what you are suggesting, if i'm understanding your explanation correctly) and see if that changes anything. Otherwise if there is anybody out there that wants to pursue this issue, if this doesn't resolve it, adding a temporary read file permission to the app you want to share to using the android storage framework should work. But since I have no experience in writing native android code, I can't do it myself.

**Comment by kevinleemans** [comment]
update: copying the file to the same documentdir will allow the user to select from all installed apps that support sharing. However when trying to actually share the file, the external app can't read the file.

ex: I'm trying to share a file with whatsapp, I can select whatsapp in the react-native-share screen but when trying to send it says file format not supported.

I first thought the file was corrupted but it can be opened in a file viewer. So no luck there

**Comment by mikehardy** [comment]
What I was suggesting was copying it from whatever arbitrary system directory the file is in (a directory not owned by the app and thus without outbound permission but with inbound permission), and copying it the app's cache directory (now the app owns it and can grant outbound permission). Or similar. If that was understood and is what you tested, then as a hypothesis it may be busted, just wanted to try to clarify.

It may be that as an experiment even if that is what you were doing, that something about the copy or the share itself wasn't correct but that's unknown without a https://stackoverflow.com/help/minimal-reproducible-example

**Comment by kevinleemans** [comment]
Well, the file was in a directory owned by the app itself, however copying it again to the same directory did make it so the share screen had more applications you could choose from. Maybe a copy from a file makes it visible for other apps (since you are not trying to distribute/change the original)? 

Anyways on further inspection I think the external app still has no access to the internal app storage since the file size is 0, you are in essence trying to send an empty file. I tried several platforms (messenger, gmail, whatsapp, discord, messages,...) and all had the same issue. So basically the result stays the same, it is (as of time of writing) not possible to share a file from an internal app storage directory to an external application with react-native-share (not sure if this will ever work).

Now what I think, and I'm not entirely sure about this, is that the current react-native-share should ask the user for a temporary permission so that an external application can read the file from inside the internal app storage. I read this somewhere but unfortunately I can't seem to find the related article at the time of writing (my apologies).

Another solution that might work is to use the android storage framework api to store the file inside the mediaStore, if the files are inside the internal app storage, the app owns them and are thus not in need of the WRITE_EXTERNAL_STORAGE flag if you are not trying to alter them. But this is more an issue for libraries that save the files like react-native-fetch-blob. However I'm not entirely sure if react-native-share can access the mediaStore without the WRITE_EXTERNAL_STORAGE flag set...

As for a reproducable example, I have this in my companies application which I can not disclose. If I find the time to make a reproducable example in the near future, I will post it here.

Anyways thanks for taking the time for this!

**Comment by mikehardy** [comment]
RNShare is supposed to be able to share files via a FileProvider that the system accepts. It is a feature that is supposed to work.

https://github.com/react-native-share/react-native-share/blob/738d0230363c55b2380b72d79a42b635615dd2f4/android/src/main/AndroidManifest.xml#L4-L14

https://github.com/react-native-share/react-native-share/blob/main/android/src/main/java/cl/json/RNShareFileProvider.java
