### ISSUE TITLE
black image on single sharing instagram stories

### ISSUE THREAD

**Issue by lucassilvasg1** [react-native-share/react-native-share#1084]
### Steps to reproduce
1. Select share instagram stories
2. Options:
    backgroundImage: base64Image,
    stickerImage: base64Image.
    backgroundBottomColor: '#fefefe',
    backgroundTopColor: '#906df4',
    social: Share.Social.INSTAGRAM_STORIES
 
### Expected behaviour
Redirect to instagram stories with filled image

### Actual behaviour
Redirects to instagram stories but with black image

### Environment
- **React Native version**: 0.64.2
- **React Native platform + platform version**:Android 9.0

### react-native-share
**Version**: 6.0.1

**Comment by marf** [comment]
Same issue here.

**Comment by geroale** [comment]
We are experiencing the same issue

**Comment by geroale** [comment]
@lucassilvasg1 Have you found any workaround for this?

**Comment by lucassilvasg1** [comment]
> @lucassilvasg1 Have you found any workaround for this?

I had to use the social option: Share.Social.INSTAGRAM instead of social: Share.Social.INSTAGRAM_STORIES since I didn't find a solution

**Comment by marf** [comment]
Is this something which can be patched package side or is it a bug with the Instagram app which got updated and changed the API?

**Comment by mikehardy** [comment]
@marf investigation with some simple console.logs/native output should answer the question quickly I hope. This isn't a use case of mine so someone on this thread will have to dig in I think

**Comment by marf** [comment]
I managed to get it working by specifing manually the extyension when creating the background SharedFile class:

I edit this:

ShareFile backgroundAsset = new ShareFile(backgroundFileName, "background" , this.reactContext);

to this:

`ShareFile backgroundAsset = new ShareFile(backgroundFileName, "image/jpeg", "background" , this.reactContext);`

For some reason, it was trying to create a file with a null extension when I tried to specify the background file as base64.
