### ISSUE TITLE
Twitter composer view hides content under header

### ISSUE THREAD

**Issue by iway1** [react-native-share/react-native-share#1086]
### Steps to reproduce
1. Install library on iphone 11 with iOS 14+
2. Install twitter application
3. Call shareSingle

### Expected behaviour
Should show a composer that has all content visible.

### Actual behaviour
Header hides the user icon and the first two lines of the tweet message.

### Environment
- **React Native version**: 0.65
- **React Native platform + platform version**: iOS 14.0

### react-native-share
**Version**: 7.0.2

Perhaps this is related to the deprecation of SLComposeViewController?
![IMG_1979](https://user-images.githubusercontent.com/12774588/132403896-661902d2-a84e-41ee-9da5-c5cf2da9d3fb.jpg)

The above tweet has both an image and a message, but the message and user icon are covered up by the header.

I'd be happy to have a hacky way to fix this, I've tried adjusting the view's `layoutMargins` and other properties of the SLComposeViewController's layout but they seem to have no effect.

EDIT: The issue occurs with or without an image

**Comment by murat-mehmet** [comment]
This is still an issue with the latest version of X app. When sharing from other apps, the share dialog of X appears as a bottom sheet, but using this module it opens as a full page screen, which I believe is the reason of this problem. Is there any way to open X share dialog as bottom sheet?

**Comment by xieguanghui200888** [comment]
As a temporary fix, you can refer to
https://github.com/react-native-share/react-native-share/issues/930#issuecomment-2063384528
