### ISSUE TITLE
Docs Quality

### ISSUE THREAD

**Issue by skizzo** [react-native-share/react-native-share#1089]
Is there any way to improve the docs of this otherwise great package? There is no way of properly using e.g. Instagram share without going through all related Github issues, since neither the configuration nor the usage is properly explained in the docs.

**Comment by MateusAndrade** [comment]
Hi @skizzo , thanks for sharing this with us! We are always open to pull-requests. Do you have any of this issues? I would be glad to try helping you, to improve our docs. 😄
