### ISSUE TITLE
Startup crash on iOS 12 when using Xcode 13

### ISSUE THREAD

**Issue by chungweileong94** [react-native-share/react-native-share#1095]
### Steps to reproduce
1. Build and run on iOS 12 device

### Expected behaviour
Works without crashing

### Actual behaviour
Crash on app startup
`dyld: Library not loaded: /System/Library/Frameworks/LinkPresentation.framework/LinkPresentation`

### Environment
- **React Native version**: 0.65.1
- **React Native platform + platform version**: iOS 12.4
- **Typescript version** (if using typescript): 4.4.3

### react-native-share
**Version**: 7.1.0

### Link to repo (highly encouraged)
None

**Comment by chungweileong94** [comment]
I not sure why `#ifdef __IPHONE_13_0` in `RNShareActivityItemSource.m` doesn't prevent iOS 12 from hitting `LinkPresentation` error.
However, I managed to find a workaround by adding `s.ios.weak_framework = 'LinkPresentation'` to the podspec, thanks to [this](https://github.com/fluttercommunity/plus_plugins/pull/224/files)

**Comment by bhaltair** [comment]
me too

**Comment by chungweileong94** [comment]
> me too

Have you tried v7.1.1?

**Comment by KingAmo** [comment]
does this issue only exist when use Xcode 13 ? but why?

**Comment by chungweileong94** [comment]
> does this issue only exist when use Xcode 13 ? but why?

To be honest I have no idea why that's the case, build was success on both my machine & AppCenter, but the app will crash on iOS 12.

**Comment by KingAmo** [comment]
> > does this issue only exist when use Xcode 13 ? but why?
> 
> To be honest I have no idea why that's the case, build was success on both my machine & AppCenter, but the app will crash on iOS 12.

https://developer.apple.com/forums/thread/690551  seems like a bug in Xcode 13 ?
