### ISSUE TITLE
Share.single redirecting to google app store instead of installed instagram application

### ISSUE THREAD

**Issue by talhajibrantariq** [react-native-share/react-native-share#1100]
### Steps to reproduce
1. This is the code i'm using for it
const shareOptions = {
            title: 'Share via',
            message: 'some message',
            url: data.data.link,
            social: Share.Social.INSTAGRAM,
          };
          Share.shareSingle(shareOptions);
2. Here, it is also returning false although the application is installed
 await Share.isPackageInstalled('com.instagram.android')
        .then(response => {
          console.log(response);
          // { isInstalled: true/false, message: 'Package is Installed' }
        })
        .catch(error => {
          console.log(error);
          // { error }
        });
    }

3.

### Expected behaviour
The isPackageInstalled should return true, and the app should be redirected to instagram application instead of google playstore

### Actual behaviour
The is Package installed returns false, and app is redirected to playstore 

### Environment
- **React Native version**: 0.64.2
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
*Version**: npm version or "master" 7.1.0

### Link to repo (highly encouraged)
https://github.com/

**Comment by hongzhou85** [comment]
I got this redirected to instagram appstore instead of instagram story share screen.

**Comment by reberthkss** [comment]
Someone did discover how to solve that?

**Comment by MuhammadZulkifle** [comment]
> ### Steps to reproduce
> 1. This is the code i'm using for it
>    const shareOptions = {
>    title: 'Share via',
>    message: 'some message',
>    url: data.data.link,
>    social: Share.Social.INSTAGRAM,
>    };
>    Share.shareSingle(shareOptions);
> 2. Here, it is also returning false although the application is installed
>    await Share.isPackageInstalled('com.instagram.android')
>    .then(response => {
>    console.log(response);
>    // { isInstalled: true/false, message: 'Package is Installed' }
>    })
>    .catch(error => {
>    console.log(error);
>    // { error }
>    });
>    }
> 
> ### Expected behaviour
> The isPackageInstalled should return true, and the app should be redirected to instagram application instead of google playstore
> 
> ### Actual behaviour
> The is Package installed returns false, and app is redirected to playstore
> 
> ### Environment
> * **React Native version**: 0.64.2
> * **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
> * **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?
> 
> ### react-native-share
> _Version_*: npm version or "master" 7.1.0
> 
> ### Link to repo (highly encouraged)
> https://github.com/

Facing the same issue. Have you found any solution?

**Comment by mikehardy** [comment]
@MuhammadZulkifle you haven't specified nearly enough information for anyone to say. I doubt you are targeting Android 5 as mentioned in the issue? https://stackoverflow.com/help/how-to-ask
I would guess you are targeting newer Android platforms and have not considered this https://developer.android.com/about/versions/11/privacy/package-visibility

**Comment by Dakuan** [comment]
same issue, but with expo, share single opens the app store (even if target app is installed)

**Comment by MarcHbb** [comment]
Same issue for me, built with expo, even if I have already IG installed

**Comment by vincent-odukwe** [comment]
no solution on this still?

**Comment by MarcHbb** [comment]
Found how to fix it ! ( tested only on IOS )
I'm using expo but I think it the same for react native project.

In your Info.plist, you must list the app you want to use. This is how it detects whether redirect to store or open the app.

**Comment by michaelchangdk** [comment]
Could somebody elaborate on this Info.plist? I'm not running Expo, but I have the same problem about it redirecting to the App store.

**Comment by michaelchangdk** [comment]
Nevermind!! I got it 😅

**Comment by brunopintos** [comment]
@michaelchangdk how did you solve it without using Expo?

**Comment by sleekLancelot** [comment]
> @michaelchangdk how did you solve it without using Expo?

In your app.config.js file, inside the ios object.

**Comment by igorzheludkov** [comment]
> Found how to fix it ! ( tested only on IOS ) I'm using expo but I think it the same for react native project.
> 
> In your Info.plist, you must list the app you want to use. This is how it detects whether redirect to store or open the app. In my case ( Expo ) :
> 
> `"ios": { "infoPlist": { "LSApplicationQueriesSchemes": ["instagram", "instagram-stories"] },`

For the bare react native app add this into info.plist:

```
<key>LSApplicationQueriesSchemes</key>
<array>
	<string>instagram</string>
	<string>instagram-stories</string>
</array>
```

**Comment by Sadmountain** [comment]
> Nevermind!! I got it 😅

How did you do it? If I do this then still got the same issue that it is opening the app store instead of Instagram:
   "infoPlist": {
        "LSApplicationQueriesSchemes": [
          "instagram",
          "instagram-stories",
       
        ],
