### ISSUE TITLE
Share spreadsheet from based64 file name not working.

### ISSUE THREAD

**Issue by juzailie** [react-native-share/react-native-share#1102]
`var shareOptions = {
          title: shareFileName,
          failOnCancel: false,
          filename: shareFileName,
          type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
          url: dataBase64
        };`

![image](https://user-images.githubusercontent.com/8662739/134870487-8120c5c8-d253-4cbb-8f93-913bdf3ff58e.png)

What I did wrong here

**Comment by juzailie** [comment]
This lib is based on version 7.1.1

**Comment by mikehardy** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by cvharris** [comment]
Looks like this is an issue, I had to work around this by using [RNFS](https://github.com/itinance/react-native-fs), saving the file first, then using the `file://` url in order for anything to really work:

```js
const filename = 'file.xlsx'
const data = XLSX.write(workbook, { type: 'base64' })
const filePath = `${RNFS.DocumentDirectoryPath}/${filename}`

await RNFS.writeFile(filePath, data, 'base64')
await Share.open({
  url: `file://${filePath}`,
  filename
})
await RNFS.unlink(filePath)
```

Trying to `Share.open` the file with a `data:` uri never interpreted the mimetype, filename, or extension correctly, no matter how many different options I tried using. The example code in the original question seems to be what ought to work, at least from what is in the documentation.
