### ISSUE TITLE
[Android] Share.open return message as undefined on android device always once user share any content on other apps and return on actual app.

### ISSUE THREAD

**Issue by HirenTariwala** [react-native-share/react-native-share#1103]
### Steps to reproduce
1. Install app in android device with react-native-share
2. Share any image or message (Ex. Whatsapp)
3. Observe behavior that will stick it to Whatsapp not come back on your app again.
4. Press back 1/2 time now you again come on your app
5. Store Share. open output and observe it. 

### Expected behavior
1) It should be returned likewise what return on ios device.
2) It should return automatically on the actual app once the share is done. (This might not be possible but very helpful if we can archive this looks like android default share behavior.)

### Actual behaviour
ios output: {"message": "net.whatsapp.WhatsApp.ShareExtension", "success": true}
android output: {"message": undefined, "success": true}

### Environment
- **React Native version**: 0.63.4
- **React Native platform + platform version**:  Android
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: 7.1.1

**Comment by mikehardy** [comment]
I just tested this with a share to gmail and it went back to the app on Android 11 (OxygenOS running on a OnePlus 6T), so to me I don't reproduce this issue *in general*.
What version of Android etc? Does it happen on the emulator as well?
What specific share types behave the way you want and which do not?
Is there any documentation about the specific apps that don't work the way you want that shows it is possible or not to do so?
Is the code here following that documentation for the sharing, and still not working?

**Comment by HirenTariwala** [comment]
I am having android 11 oneplus 7. Please can you try with whatsapp

**Comment by HirenTariwala** [comment]
const shareRes = await Share.open({
          url: 'file://' + path,
          title: 'Test 3rd party share',
});

console.log('res', shareRes); 

It is working fine on ios but having an issue with android.

**Comment by mikehardy** [comment]
Yeah, I share to whatsapp and it leaves me in that conversation where the share went. For me, that's the behavior I want from WhatsApp, I just shared something to someone (which is like saying "hey look at this..." and usually I want to stay there to see what they say about the thing. I hit back two times and I'm in the app.

I think it's WhatsApp specific and I don't think it's a bug.

Pending this:
>  Is there any documentation about the specific apps that don't work the way you want that shows it is possible or not to do so?

Maybe it's a flag we could set on the share to whatsapp *if* such a flag existed and you wanted to make a PR to support it in an optional way with the default to the current behavior?

**Comment by HirenTariwala** [comment]
I don't have any specific docs for this

@mikehardy I've observed Instagram but behavior regarding Whatsapp same so we can't consider as bug but once i on my app it must return me where I shared.

**Comment by HirenTariwala** [comment]
@mikehardy tried with slack as well this time it return me on my app but output same message with undefined

**Comment by webyonet** [comment]
This issue only happens on `Android 11` and above. With `Android 11`, a similar structure came to `LSApplicationQueriesSchemes` in iOS.

see: [https://developer.android.com/training/package-visibility](url)

To solve the problem, edit `AndroidManifest.xml` as below:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="........">

    <uses-permission android:name="android.permission.INTERNET"/>
     .......

<!-- Package visibility Start-->
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="http"/> <!-- for browser -->
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https"/> <!-- for browser -->
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="whatsapp" /> <!-- for whatsapp -->
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="mailto" /> <!-- for email -->
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="instagram" /> <!-- for instagram -->
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="instagram-stories" /> <!-- for instagram stories-->
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="twitter" /> <!-- for twitter-->
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="fb" /> <!-- for facebook-->
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="tg" /> <!-- for telegram-->
        </intent>
    </queries>

<!-- Package visibility End-->

    <application
            android:name=".MainApplication"
            android:label="@string/app_name"
            android:icon="@mipmap/ic_launcher"
            android:roundIcon="@mipmap/ic_launcher_round"
........
```

**Comment by mikehardy** [comment]
@webyonet to be even more specific - assuming what you state is true and resolves the issue - this is for apps that *target* android 11 (api30), per the document you link. That's an important difference, my app targets api29 for instance so I will see different behavior on android 11 then an app that targets android 11 and runs on android 11

**Comment by webyonet** [comment]
@mikehardy yes i compile with android buildToolsVersion="30.0.3"
android build version is not specified in the opened issue and I solved the same problem with this method

**Comment by HirenTariwala** [comment]
@webyonet I've tried with Android 11 and Android 10 as well but it is not working. Here is my build config.

`        buildToolsVersion = "30.0.3"
        minSdkVersion = 27
        compileSdkVersion = 28
        targetSdkVersion = 30
        googlePlayServicesAuthVersion = "18.0.0"`

**Comment by HirenTariwala** [comment]
@webyonet Do you get package name in message when you share on any app?

**Comment by HirenTariwala** [comment]
@webyonet I'm not saying that the package is not working. It is working but for iOS I'm also getting activity name in message field alongside success: true but in android I'm only getting success: true and message field is undefined. So I want that message field to know on which app image was shared.

**Comment by mikehardy** [comment]
@HirenTariwala how interesting, I'm not aware of any cases where you would want compileSdkVersion to be lower than targetSdkVersion and I'm surprised that even works. I always though you would want buildTools and compileSdkVersion to be the same in general (this defines the set of symbols / APIs you may use in your code), minSdkVersion to be  your lowest possible compatible device, and targetSdkVersion to be your most up to date compatible API, as dictated by what Google will accept for distribution on Play Store (29 right now, about to be 30).

Anyway, it seems like this should be available https://developer.android.com/training/sharing/send#share-interaction-data if we inspect EXTRA_CHOSEN_COMPONENT in the callback intent.

Has anyone checked the android code here to see if we are doing that? If we are trying, has anyone inspected why it isn't working? If we are not doing that, a PR to do so would be welcome

**Comment by mikehardy** [comment]
That all looks good. The real substance of my comment is unaddressed though:

----

Anyway, it seems like this should be available https://developer.android.com/training/sharing/send#share-interaction-data if we inspect EXTRA_CHOSEN_COMPONENT in the callback intent.

Has anyone checked the android code here to see if we are doing that? If we are trying, has anyone inspected why it isn't working? If we are not doing that, a PR to do so would be welcome

**Comment by HirenTariwala** [comment]
@mikehardy here looks similar

https://github.com/react-native-share/react-native-share/blob/main/android/src/main/java/cl/json/social/TargetChosenReceiver.java#L52

 https://github.com/react-native-share/react-native-share/blob/main/android/src/main/java/cl/json/social/TargetChosenReceiver.java#L75

**Comment by mikehardy** [comment]
So, looks like the code is in there, that's great:

> If we are trying, has anyone inspected why it isn't working? 

Looks like the next step is to step through that or add debugging System.err.println's and see what's going on. Why isn't it coming back?

**Comment by HirenTariwala** [comment]
I've noticed that onRecived not calling

**Comment by gitVera** [comment]
> const shareRes = await Share.open({ url: 'file://' + path, title: 'Test 3rd party share', });
> 
> console.log('res', shareRes);
> 
> It is working fine on ios but having an issue with android.

the same. Android doesnt see response
