### ISSUE TITLE
Close share dialogue programmatically

### ISSUE THREAD

**Issue by nt555** [react-native-share/react-native-share#1106]
## Ask your Question

Is there a solution to close the share dialogue programmatically after session timeout due to user inactivity? 

Thank you in advance

**Comment by mikehardy** [comment]
Hi there! As far as I know, at least on Android the answer is no. That's a system dialog. It used to be that you could send a broadcast to close system dialogs even (not recommended, but possible), in current android versions that is considered a no-no and they restrict it heavily: https://developer.android.com/reference/android/content/Intent#ACTION_CLOSE_SYSTEM_DIALOGS

So unless you do some platform research and discover something I'm unaware of, the answer is no

If you do, then of course we can reopen perhaps as an enhancement request if you or someone is willing to submit a PR

**Comment by nt555** [comment]
Hi! Thank you for your quick response.
