### ISSUE TITLE
Can I change filename when I save to files?

### ISSUE THREAD

**Issue by faglo** [react-native-share/react-native-share#1121]
When I save with `saveToFiles: true` option(iOS)
File app gives **file** filename, can I change it?
![Снимок экрана 2021-11-04 в 04 35 03](https://user-images.githubusercontent.com/28590160/140242549-4aac69a0-ebe2-4eb0-88af-3cb34690e7d0.png)

**Comment by aonnikov** [comment]
No, it does not seem to be possible. The `file` filename is hardcoded in RNShareUtils.getPathFromBase64.
