### ISSUE TITLE
if increase targetSdkVersion on android(android 11), when share instagram not open app instagram but it goes to photo app

### ISSUE THREAD

**Issue by nokadiepdc** [react-native-share/react-native-share#1122]
### Steps to reproduce
1.  increase targetSdkVersion = 30(Follow the main android policy to push the app to the store) on device Android 11
2. buid app
3. share image or share video.

### Expected behaviour
open app instagram
### Actual behaviour
not open app instagram and open app photos (android 11) , android 10 working well
### Environment
- **React Native version**: 0.63.3
- **React Native platform + platform version**: Android 11
- device : pixel 3
### react-native-share
**Version**:  7.1.2

### Link to repo (highly encouraged)
                   const shareOptions = {
                          social: Share.Social.INSTAGRAM,
                          url: `data:image/${val.extension};base64,${resF}`,
                          type: `image/${val.extension}`,
                        };
                        const ShareResponse = Share.shareSingle(
                          shareOptions,
                        ).catch((err) => {
                          alert(err?.error?.message);
                        });

**Comment by mikehardy** [comment]
Please start here for information to fix your issue: https://github.com/react-native-share/react-native-share/issues/1009#issuecomment-824101426

If you could propose a PR to the README that describes this for Android 11+ that would be ideal - as this will come up for a lot of people as a duplicate I think

**Comment by mikehardy** [comment]
Actually the PR for docs has been done. https://github.com/react-native-share/react-native-share/pull/1054/files
