### ISSUE TITLE
Share.open promise not tell information about what user choose for share

### ISSUE THREAD

**Issue by pramahaditamaputra-ralali** [react-native-share/react-native-share#1123]
## Ask your Question

Share.open promise not tell information about what user choose for share, it just give information about {"message": undefined, "success": true} , i really need that information. please help 🙏🏻

**Comment by gupta-ji6** [comment]
+1 to this - I would like the ability to know what app the user used to share, if possible.
I can also contribute for the same if the maintainer can brief it about it a little.

**Comment by mikehardy** [comment]
No one will have time to brief you. You will have to read the docs and become the subject matter expert solo
My quick look at the docs on the native platform APIs indicated that it might be possible - it looked like maybe - but then a slightly deeper look made it seem like the platform simply did not give the information back.

Add native logging around the platform API calls logging out everything you send and everything that comes back and you'll see

**Comment by gupta-ji6** [comment]
@mikehardy totally makes sense & I respect maintainers time.
I'll look it up myself :)

**Comment by heresmyinfo** [comment]
It would be very useful to have this information - I will research it also.

**Comment by akimabs** [comment]
any update ?
