### ISSUE TITLE
 Share.shareSingle works but Share.open not working

### ISSUE THREAD

**Issue by tylim88** [react-native-share/react-native-share#1127]
I try it on redmi note 10 pro
```
							const shareImageBase64 = {
								title: 'title`,
								url: `data:image/png;base64,${base64String}`,
								subject: `subject`,
								social: 'whatsapp',
								type: 'image/*',
							}
							Share.shareSingle(shareImageBase64).catch(error =>
								console.error(error)
							)
```
shareSingle is working, I can share it to WhatsApp or whatever social 

```
							const shareImageBase64 = {
								title: 'title`,
								url: `data:image/png;base64,${base64String}`,
								subject: `subject`,
								type: 'image/*',
							}
							Share.open(shareImageBase64).catch(error =>
								console.error(error)
							)
```
open is not working, I cannot share to whatsapp, facebook, email etc etc, nothing works

there is also no error to log, in whatsapp it says the file formate is not supported, in facebook it says unable to load photo, in email it say unable to attach file

both shareSingle and open works in android emulator(API 29)

**Comment by ZeroByter** [comment]
I am having the same problem. Been scratching my head for literally 2 days trying to get `Share.open` to work but no matter what I do, it doesn't.

I just came across your issue, tried share.openSingle and indeed it works. What's going on here?

I am using
```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        ndkVersion = "21.4.7075529"
        androidXCore = "1.5.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

**Comment by meirstingz** [comment]
I have now the same problem ... did you solved it?
