### ISSUE TITLE
Sharing only on one media directly.

### ISSUE THREAD

**Issue by vseverestek** [react-native-share/react-native-share#1130]
## Ask your Question

Is it possible to share directly on email instead of showing all the options to share if email is passed in social?

**Comment by mikehardy** [comment]
I think you're looking for https://reactnative.dev/docs/linking#sendintent-android (on android at least)

with https://stackoverflow.com/questions/8701634/send-email-intent

for multi-platform it's more specific and needs more specific wrappers, https://github.com/chirag04/react-native-mail

the idea of "share" is top open the picker really, for specific types that are specialized I think you'll need a specific package
