### ISSUE TITLE
Sharing with Facebook messenger does not pre-populate message?

### ISSUE THREAD

**Issue by bertrand-caron** [react-native-share/react-native-share#1132]
### Steps to reproduce
1. Use the following call of `Share.open` on a physical iOS device (in my case, iPhone 12 Pro):

```
const result = await Share.open({
    title: 'Hello!',
    message: 'world',
    url: 'https://www.hello.com',
    subject: 'Hello world!',
})
```

2. In the share tray, use Messenger
3. The new message contains the URL, but not message.

### Expected behaviour
The new Messenger message contains the URL and message.

### Actual behaviour
The new message contains the URL, but not message.

NB, sharing with other apps (for instance WhatsApp) does populate the message properly.

### Environment
- **React Native version**: `0.65.1`
- **React Native platform + platform version**: iOS 10+
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment? `4.5.2`

### react-native-share
**Version**: npm version or "master" `7.3.2`

### Link to repo (highly encouraged)
Private, sorry :(

**Comment by hedenica** [comment]
Hi! I'm not entirely sure  but if I'm not mistaken Facebook does not allow devs to prefill the message field with text, it only allows URL links. (apparently you can only provide the text for the user to copy and then paste on the message field)

https://developers.facebook.com/docs/sharing/android
