### ISSUE TITLE
Share.share() is not working in redmi k23 mobile

### ISSUE THREAD

**Issue by arman-tdev** [react-native-share/react-native-share#1133]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by mikehardy** [comment]
This is literally the opposite of a useful bug report :sweat_smile: 
@arman-tdev https://stackoverflow.com/help/how-to-ask + https://stackoverflow.com/help/minimal-reproducible-example
