### ISSUE TITLE
inform that the number does not exist

### ISSUE THREAD

**Issue by JereLima** [react-native-share/react-native-share#1134]
Hello I would like to know if I can show a message if the whatsapp number doesn't exist.

currently when the number does not exist it opens directly on the forward screen

**Comment by mikehardy** [comment]
This is probably best asked on stackoverflow
Short answer is no, I do not think there is any way to do that. This module asks the system to share, the system opens the other app, and the other app is in control. So the other app can do whatever it wants and you have no ability to affect what it does at that point
