### ISSUE TITLE
how to know / inform with log or etc, if user / user tester was successfully sent message or sharing

### ISSUE THREAD

**Issue by ramms44** [react-native-share/react-native-share#1135]
## Ask
how to know / inform with log / methods or etc, if user / user tester was successfully sent message or sharing, thanks 👍

**Comment by mikehardy** [comment]
Have you searched the issues list? This is not possible with the APIs the system gives you. The system does not provide the information about where the share went, so this module transitively cannot provide the information about where the share went.

It's a useful idea so it comes up a lot, but unless you dig in and discover a way to do it with the native APIs, it is not possible

**Comment by ramms44** [comment]
> Have you searched the issues list? This is not possible with the APIs the system gives you. The system does not provide the information about where the share went, so this module transitively cannot provide the information about where the share went.
> 
> It's a useful idea so it comes up a lot, but unless you dig in and discover a way to do it with the native APIs, it is not possible

thanks 👍
