### ISSUE TITLE
iOS Whatsapp image shareSingle not working as expected

### ISSUE THREAD

**Issue by akshgods** [react-native-share/react-native-share#1143]
### Steps to reproduce
im using ios 15.2 , if we use shareSingle for only message it opening single user correctly.
where as we want to share image , its showing multiple options to choose from.

```
Share.shareSingle(shareOptions) is not behaving as expected on ios. Its showing options to choose
const shareOptions = {
title: 'some title',
message: 'some message',
url: base64image,
social: Share.Social.WHATSAPP,
}
Share.shareSingle(shareOptions);
```

### Expected behaviour
Need to open whatsapp for single user and share image and message

### Actual behaviour
Opening multiple selection from different app.
i can choose slack, teams or any other application to share including whatsapp.
even tho if we choose whats app,
we need to select user from app, need to share image

at this time message will not go.
imp: i need to set message:''
blank field otherwise nothing is working

important issue:
if we not have that number saved , then you need to first save the number.
:(
### Environment
 "react": "17.0.1",
 "react-native": "0.63.4",
- ios 15.2 , iphone 7 plus

### react-native-share
 "react-native-share": "^7.3.3",

**Comment by rohit75** [comment]
Facing the same issue, navigating to play store.
Any workarounds?

**Comment by fatihyildizhan** [comment]
I have similar issues with `Share.open` and `Share.shareSingle` on iOS.

```
"react-native": "^0.63.4",
"react-native-share": "^7.3.3"
```

-> This shares only message on WhatsApp.
```
const shareOptions: ShareOptions = {
      title: 'Title',
      url: base64image,
      failOnCancel: false,
      message: 'Message',
 };
await Share.open(shareOptions);
```

-> This shares only image on WhatsApp.
```
const shareOptions = {
      message: 'Message',
      url: base64image,
      social: Share.Social.WHATSAPP,
      whatsAppNumber: 'number'
 };
await Share.shareSingle(shareOptions);
```

**Comment by jaypateljetbro** [comment]
Any update on this? i am facing same issue.
