### ISSUE TITLE
App has come to the background(Android only)

### ISSUE THREAD

**Issue by cherot1k** [react-native-share/react-native-share#1147]
### Steps to reproduce
1. Open app
2. Use Shape.open function
3. Cancel sharing or share your file
### Expected behaviour
App state should not be changed. 

### Actual behaviour
App has come to the background(only Android).

### Environment
- **React Native version**: 0.64.2
- **React Native platform + platform version**: Android 10

### react-native-share
**Version**: 7.3.2

**Comment by mikehardy** [comment]
I don't reproduce this behavior in my app. I cancel the share and go right back to my app from the share sheet.
Possibly device specific.

**Comment by cherot1k** [comment]
> I don't reproduce this behavior in my app. I cancel the share and go right back to my app from the share sheet. Possibly device specific.

I can go back to use my app after cancelling or sharing file, but the state is changed to background in AppState.currentState, but it shoudn't.

**Comment by mikehardy** [comment]
That will be a react-native issue. The app *did* go in the background during the share - that share sheet is a system window, and the react-native window is no longer foreground. If it is not coming back to foreground correctly afterwards, that's a react-native lifecycle listener implementation problem and we can't help here.

I see react-native 0.64.x, react-native is on 0.67.1, update to current and re-test, pursue in react-native repo if the issue persists
