### ISSUE TITLE
Note: Don't forget change the android:name in package for the package id of the app that you will share!

### ISSUE THREAD

**Issue by MuhammadRafeh** [react-native-share/react-native-share#1149]
## Ask your Question

For sdk >= 30, we have to use queries tag. According to documentation we have to insert those queries tag.

```
<manifest package="com.example.game">
    <queries>
        <package android:name="com.example.store" />
        <package android:name="com.example.services" />
    </queries>
    ...
</manifest>
```

But I am unable to understand below line have a look
```
Don't forget change the android:name in package for the package id of the app that you will share!
```

Can someone help me? What to do next after adding those queries tag in manifest file?

**Comment by MuhammadRafeh** [comment]
@heracek @codeflows @kant @jnpdx Can anyone answer my question?

**Comment by veraldo** [comment]
Hi there, you'll need to declare the ids of the apps you intend to share to, inside the queries tag

As an example, if you'll share to WhatsApp:

```
<queries>
    <package android:name="com.whatsapp" />
</queries>
```

The fastest way to get this id would be visiting the Play Store page of the intended app, on a browser, and then checking it on the url 

`https://play.google.com/store/apps/details?id=com.whatsapp&hl=en&gl=US`
