### ISSUE TITLE
Share with instagram not working on IOS

### ISSUE THREAD

**Issue by keviocastro** [react-native-share/react-native-share#1153]
### Steps to reproduce
const shareOptions = {
      url: `data:image/png;base64,${image}`,
      social: Share.Social[type],
      forceDialog: true,
    };

Share.shareSingle(shareOptions);
    
No error logs found

### Expected behaviour
Open instagram to image share 

### Actual behaviour
No windows are open

### Environment
- **React Native version**: 0.66.0
- **React Native platform + platform version**: iOS 13
- **yarn 1.22.5

### react-native-share
**Version**: 7.3.5

**Comment by e-nouri** [comment]
I have the same problem on ios 13, any news on this bug ? are there any workarounds ?

**Comment by NitinTayal007** [comment]
I have the same issue on ios 13.

**Comment by Svarto** [comment]
@NitinTayal007 @e-nouri @keviocastro did you found a solution to this? I have the same issue
