### ISSUE TITLE
Instagram DM with shareSingle doesn't working on Android 12

### ISSUE THREAD

**Issue by omergilboa** [react-native-share/react-native-share#1158]
### Steps to reproduce
1. Use `shareSingle` method to share via Instagram DM
2. Run on device with OS Android 12

### Expected behaviour
Tell us what should happen

Open Instagram app on contacts screen to send DM to..

### Actual behaviour
Tell us what happens instead

Nothing happens (not even throwing an error).

### Environment
- **React Native version**: `0.66.4`
- **React Native platform + platform version**: Android 12
- **Typescript version** (if using typescript): `4.5.2`

### react-native-share
**Version**: `7.3.2`

**Comment by songhee24** [comment]
@omergilboa bro did you find a solution?

**Comment by omergilboa** [comment]
> @omergilboa bro did you find a solution?

unfortunately not :( i think IG deprecated that option since new API and Messenger is now cross (meta) app..
