### ISSUE TITLE
Share.shareSingle does nothing for Share.Soical.INSTAGRAM if Instagram app is not installed iOS

### ISSUE THREAD

**Issue by LydGol90** [react-native-share/react-native-share#1159]
### Steps to reproduce
```
Share.shareSingle({        
        social: Share.Social.INSTAGRAM,
        url: image,
        type: 'image/jpg'
})
```

### Expected behaviour
Takes you to instagram in the app store, like it does with Share.Social.INSTAGRAM_STORIES

### Actual behaviour
Nothing happens and there is no error

### Environment
- **React Native version**: 0.67.1
- **React Native platform + platform version**: Both

### react-native-share
**Version**: 7.3.6

I have checked in InstagramShare.m and I can see that in the method `savePictureAndOpenInstagram` there is no fallback if `canOpenUrl` is false, and so I think re-directing to the store there would solve the issue for ios.

**Comment by Miluaaa** [comment]
This happens even when Instagram is installed
