### ISSUE TITLE
Custom icon doesn't work

### ISSUE THREAD

**Issue by matmartic** [react-native-share/react-native-share#1160]
### Steps to reproduce
I use the [example with activityItemSources](https://react-native-share.github.io/react-native-share/docs/share-open#activityitemsources-ios-only) from the docs as a base

To start
```
Share.open({
        title: 'Test Title',
        message: 'Test Message',
      });
```

This produces

![image](https://user-images.githubusercontent.com/15280410/154763454-32cbf669-f091-4499-a07c-e313c39ae2ec.png)

Then using the example in the docs, 

```
Share.open({
        title: 'Test Title',
        message: 'Test Message',
        activityItemSources: [
          {
            placeholderItem: {
              type: 'url',
              content: base64logo,
            },
            item: {
              default: {
                type: 'text',
                content: 'Test content',
              },
            },
            linkMetadata: {
              title: 'Test linkMetadata title',
              icon: base64logo,
            },
          },
        ],
      });
```

This produces 

![image](https://user-images.githubusercontent.com/15280410/154763915-12affb4a-a18f-4677-bf5f-ad16744a4388.png)

If I remove the default title/message like this

```
      return _Share.open({
        activityItemSources: [
          {
            placeholderItem: {
              type: 'url',
              content: base64logo,
            },
            item: {
              default: {
                type: 'text',
                content: 'Test content',
              },
            },
            linkMetadata: {
              title: 'Test linkMetadata title',
              icon: base64logo,
            },
          },
        ],
      });
```

I get 

![image](https://user-images.githubusercontent.com/15280410/154763984-b8a24acd-56f2-459b-ba3d-90da21df1392.png)

I tried also passing an img url to placeholderItem/content, that produces

![image](https://user-images.githubusercontent.com/15280410/154764081-b4a279c5-60b9-4090-86ab-d30399777425.png)

Which is the Safari logo : This makes sense, you're saying "I'm sharing this url" so it shows the safari logo since that's the type of content you share.

I tried many different combinations of putting a url, base64 and a local img file either in placeholderItem/content or linkMetadata/icon but so far nothing that sticks.

The only way I found to make the image change is to *only* share a link with an img, in that case it does show the preview of the img : 

![image](https://user-images.githubusercontent.com/15280410/154764977-e5a0a84d-28ef-4c34-b85f-69c78c29a2ed.png)

### Expected behaviour
I'd like to be able to share a text and customize this icon 
![image](https://user-images.githubusercontent.com/15280410/154764397-4ecf1510-6ff6-4fd0-84f4-0fe23eeb7350.png)
If currently not supported, it would be good to know as well and potentially update the docs

### Actual behaviour
I haven't found a way to make it work.
Also I've found these tickets 
https://github.com/react-native-share/react-native-share/issues/804
https://github.com/react-native-share/react-native-share/issues/848#issuecomment-692418559
that show people with a similar issue
And this SO ticket where the user answers this isn't possible.. https://stackoverflow.com/questions/65239411/share-sheet-icon-on-react-native

### Environment
- **React Native version**: 0.63.30
- **React Native platform + platform version**: iOS 15.0, xcode 13.0
- **Typescript version** (if using typescript): 4.0.5

### react-native-share
**Version**: npm version or "master" 7.3.6, previously on 4.x.x, it was the same behaviour

### Link to repo (highly encouraged)
Private repo unfortunately

**Comment by mikehardy** [comment]
I don't think we have any special knowledge here, based on your set of links to other tickets, your actual testing, and reference to a stackoverflow answer I think you're the current subject matter expert.
If you want to go further and look at the actual APIs from the underlying platform and do some focused testing you could drive the point home, but for now at least it appears that you have answered your own question (given we don't have any other information on the subject) so if you wanted to update the docs with your testing results, a PR there seems like it would work

**Comment by hazrid93** [comment]
https://github.com/react-native-share/react-native-share/pull/1599 i solve this here
