### ISSUE TITLE
Share.shareSingle on Telegram opens telegram and then web-browser infinitely

### ISSUE THREAD

**Issue by informsharique** [react-native-share/react-native-share#1167]
### Steps to reproduce
1. use Share.shareSingle and pass the configOptions you want to add
2. use social: Share.social.TELEGRAM as mention in the docs
2. tap the button on which it was assigned to share to telegram

### Expected behaviour
It should open telegram once and be done with sharing

### Actual behaviour
It open telegram and then browser and then telegram again and it goes with this flow on and on indefinitely

### Environment
- **React Native version**: 0.67.1
- **React Native platform + platform version**: iOS 15.2
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment? 4.4.3

### react-native-share
**Version**: 7.3.2

### Link to repo (highly encouraged)
can't share private repo

**Comment by mikehardy** [comment]
Interesting, no one else has reported this, which is unexpected as it's a serious flaw if it's in the library.

> can't share private repo

Can you start with `npx react-native init TelegramShareRepo` and create a repo to share? I'm guessing it is something in your project vs actually in the module, and that will help show it

**Comment by jenshandersson** [comment]
We're seeing the same issue, stuck in a loop on iOS. But I think it's actually the Telegram iOS app that's broken. Works fine on desktop. https://github.com/TelegramMessenger/Telegram-iOS/issues/606

**Comment by ardiansyaherwin** [comment]
Hi I think it's due to the Telegram Preview link, they're updating the format to this

```
https://t.me/share/url?text=Your%20Message%20Here&url=https://yourwebsite.here
```

Actually the infinite loop happens on web browser, not sure if it's also affecting the native share.

**Comment by mikehardy** [comment]
PRs happily accepted :smile:

**Comment by AhmedAbuelenin** [comment]
I have an issue also with Share.shareSingle on telegram in android, every time it opens play store whether telegram app is installed or not.

I am using 
react-native: 0.67.3
react-native-share: 7.6.4,
