### ISSUE TITLE
null is not an object (evaluating '_reactNative.NativeModules.RNShare.FACEBOOK') with Expo Go

### ISSUE THREAD

**Issue by i8ramin** [react-native-share/react-native-share#1169]
### Steps to reproduce
1. Add `react-native-share` to Expo project (bare / ejected)
2. Run using `expo start -c` (seems to work fine when run via `expo run:ios`)
3. Error is thrown and app fails to load

### Expected behaviour
I expect that when running my app via `expo start` the module gets loaded properly. Which is the case when I run my app via `expo run:ios`. 

### Actual behaviour
When I start my app via `expo start` (dev server via the Expo Go app), the react-native-share module does not seem to be linked properly and I get the error `null is not an object (evaluating '_reactNative.NativeModules.RNShare.FACEBOOK')`

However, when I run my app via `expo run:ios`, it seems to work just fine.

Full stacktrace here:
```
TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNShare.FACEBOOK')
at http://192.168.1.64:19000/index.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:204032:23 in error
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at components/CartItemView.tsx:4:0 in <global>
```

### Environment
- **React Native version**: `0.64.3`
- **React Native platform + platform version**: `iOS  15.2`
- **Typescript version** (if using typescript): `4.3.5`

### react-native-share
**Version**:  `7.3.6`

### Link to repo (highly encouraged)
https://github.com/

**Comment by mikehardy** [comment]
With apologies, none of the maintainers here use Expo, and thus we can't support it really, I'd search for support on Expo support channels.
If there is a problem using non-expo / standard react-native commands please let us know
If you discover something Expo related that needs a PR, post a PR and we can merge it

**Comment by BelyaninD** [comment]
this won't work with expo go, build a dev client with expo-dev-client and use `expo start --dev-client`
