### ISSUE TITLE
Android error user did not share

### ISSUE THREAD

**Issue by MerijnCanvas** [react-native-share/react-native-share#1172]
### Steps to reproduce
1. Install the package into a fresh react-native project
2. Call Share.open(), we're calling it with a base64 image but I don't think that's the cause
3. Run on an android device, I'm using OnePlus 8

### Expected behaviour
I should get the message that the share was successful and which platform it was shared to

### Actual behaviour
I receive an error: `Error: User did not share` when sharing to Facebook and I receive `{"message": undefined, "success": true}` when sharing to Whatsapp

### Environment
- **React Native version**: 0.67.3
- **React Native platform + platform version**: Android 11 on an OnePlus 8

### react-native-share
**Version**: ^7.3.7

### Link to repo (highly encouraged)
https://github.com/MerijnCanvas/react-native-share-bug

**Comment by mikehardy** [comment]
Duplicate #1059
