### ISSUE TITLE
iOS - thumb in share modal

### ISSUE THREAD

**Issue by reberthkss** [react-native-share/react-native-share#1179]
## Ask your Question
Hi!

There is an option to specify the image preview in the share modal like image below?

<img width="298" alt="image" src="https://user-images.githubusercontent.com/54030471/162358297-7c77201f-cb23-4267-8bb8-3a4c42e98d5e.png">

**Comment by reberthkss** [comment]
> ## Ask your Question
> 
> Hi!
> 
> There is an option to specify the image preview in the share modal like image below?
> 
> <img alt="image" width="298" src="https://user-images.githubusercontent.com/54030471/162358297-7c77201f-cb23-4267-8bb8-3a4c42e98d5e.png">
![simulator_screenshot_9905AFD1-26FB-44E7-AC64-87F4185DA8F3](https://user-images.githubusercontent.com/54030471/162363728-0e9e3c84-1cb0-43f1-baae-c13d38413be3.png)

I managed to add the custom thumb preview with the following config: 

```json
{
            subject: 'Listen',
            title: 'Infinity',
            activityItemSources: [
                {
                    placeholderItem: {
                        type: 'text',
                        content: "radio"
                    },
                    item: {
                        default: {
                            type: 'url',
                            content: config.state.share.poster
                        },
                    },
                    subject: {default: 'Radio'},
                    linkMetadata: {
                        title: 'Infinity Radio!',
                    }
                },
            ],
        }
```

**But i didn't solved the problem with the title and description.**

**Comment by reberthkss** [comment]
As we can see, the title and description are set before image is load, but they change when load is complete =(

![Uploading simulator_screenshot_B86D6398-C4CF-4CEA-AED8-F7E3A0131412.png…]()
![simulator_screenshot_2C74BCD9-E7E3-434F-B171-852B97EB4DC3](https://user-images.githubusercontent.com/54030471/162364505-6e7b8a96-da45-4a03-8310-d09b96330e3a.png)

**Comment by mikehardy** [comment]
This sounds like it's an enhancement request really, and this module is open for PRs if they are reasonable
You'll have to check the platform native share APIs on apple and android developer site + stackoverflow perhaps for guidance, and experiment with the code.
