### ISSUE TITLE
Android 12 required AndroidManifest declarations missing could emit a warning

### ISSUE THREAD

**Issue by mikehardy** [react-native-share/react-native-share#1192]
Exactly that! This is strictly required for Android 12 - https://react-native-share.github.io/react-native-share/docs/install#adding-queries-for-the-android-necessary-for-sdk--30

Before closing this - perhaps the whole idea of the PR could be changed. Right now it's "this is not working on Android 12, let's force it", but the root cause was really "I did not forward port to Android 12 correctly". And the root cause happens because we all have too much to do to remember everything, this will happen to others. Is probably happening right now to others!

Perhaps the real PR could be:
- If API is >= Android 12
- And If the build is a debug build (signaling it is for development)
- And if ShareSingle is called
- And if we hit that NOT INSTALLED conditional block
- We somehow report this back to the javascript layer and do a console.warn about the possible issue so developers get a yellow box

The whole idea is to pop this up to developers so it's obvious.

We handle the response callback from native here:

https://github.com/react-native-share/react-native-share/blob/d018c3715ad60798e3c389a51eb71bd25a18209c/src/index.tsx#L98

We send status of just "true" if the share was accepted by the system:
https://github.com/react-native-share/react-native-share/blob/d018c3715ad60798e3c389a51eb71bd25a18209c/android/src/main/java/cl/json/RNShareModule.java#L51

Perhaps we could overload that return value from simple true/false to also potentially be a string containing a message indicating that the package wasn't found, and if we detect that we can do the console.warn ?

Thoughts?

_Originally posted by @mikehardy in https://github.com/react-native-share/react-native-share/pull/1191#discussion_r857820605_

**Comment by MateusAndrade** [comment]
Nice point, I think we can go with a warning when running this with a development build. I've some problems with logging stuff on production builds, since we can end up exposing implementation details through logcat, etc.
