### ISSUE TITLE
Share.open always in the catch on Android 11.00

### ISSUE THREAD

**Issue by Rossella-Mascia-Neosyn** [react-native-share/react-native-share#1201]
### Steps to reproduce
1. click on button for share

```ts
import Share from 'react-native-share';
import { Buffer } from 'buffer';

const convertUrlToBase64 = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url, true);
    xhr.responseType = 'arraybuffer';
    xhr.onload = () => {
      if (xhr.status === 200) {
        const base64 = Buffer.from(xhr.response).toString('base64');
        resolve(`data:image/jpeg;base64,${base64}`);
      } else {
        reject(new Error('Image not loaded'));
      }
    };
    xhr.send();
  });
};

const urls = [
  'https://static.silhouettedonna.it/wp-content/uploads/2015/08/hot-yoga.jpg',
  'https://www.roypet.it/wp-content/uploads/2021/04/gattino.jpg',
];

const shareOnSocial = async () => {
  const base64 = await Promise.all(urls.map(convertUrlToBase64));
  try {
    await Share.open({
      title: 'Scegli dove condividere',
      urls: base64,
      message: 'Please check this out.',
    }).then(result => console.log(result));
  } catch (error) {
    error && console.error(error);
  }
};

export default shareOnSocial;
```

### Expected behaviour
In spite of the sharing is successful it enters in any case in the catch

### Actual behaviour
It must not enter the catch when the sharing has been successful and instead must enter it if it is actually in error or if the user has canceled the sharing

### Environment
- **React Native version**: 0.68.0
- **React Native platform + platform version**: Android 11.00
- **Typescript version** 4.4.4

### react-native-share
**Version**: 7.4.1

**Comment by mikehardy** [comment]
in async code with await, the promise is consumed, there is no "then", so this code

```javascript
  try {
    await Share.open({
      title: 'Scegli dove condividere',
      urls: base64,
      message: 'Please check this out.',
    }).then(result => console.log(result));
```

is wrong I think

I think it should be

```javascript
  try {
    let result = await Share.open({
      title: 'Scegli dove condividere',
      urls: base64,
      message: 'Please check this out.',
    });
    console.log('result was: ' + result);
```

**Comment by Rossella-Mascia-Neosyn** [comment]
You're right but in reality I had only done a test even so it always enters the catch

```ts
const shareOnSocial = async () => {
  const base64 = await Promise.all(urls.map(convertUrlToBase64));
  try {
    const result = await Share.open({
      title: 'Scegli dove condividere',
      urls: base64,
      message: 'Please check this out.',
    });
    console.log(result.message);
  } catch (error) {
    error && console.error(error);
  }
};
```

**Comment by MateusAndrade** [comment]
Hi @Rossella-Mascia-Neosyn, can you share the native logs from Android after calling the `.open` function? Also, does this happens with newer versions: 12, 13?

**Comment by Rossella-Mascia-Neosyn** [comment]
![image](https://user-images.githubusercontent.com/79088170/169076150-83bed821-29b7-4907-b6aa-2e68540b33ad.png)
![image](https://user-images.githubusercontent.com/79088170/169076362-5de1124b-932a-4f0d-8119-a615d274e007.png)

**Comment by MateusAndrade** [comment]
@Rossella-Mascia-Neosyn sorry if you misunderstood me 😅. 

By "Android Logs", I mean the ones you can see using Android Studio with Logcat.  Maybe [this](https://developer.android.com/studio/debug/am-logcat) can help you to extract this.

**Comment by Rossella-Mascia-Neosyn** [comment]
I'm sorry I didn't understand

These are the logs after i hit the share key

![image](https://user-images.githubusercontent.com/79088170/169318510-39d81091-5655-49f6-b76d-d87cf4db2ad4.png)

**Comment by MateusAndrade** [comment]
> These are the logs after i hit the share button

No problem! Can you share the logs after opening the application and then calling the `Share.open`? Looking at this image, either it was cut at `sourceUrl`. Can you try searching for `ERROR` on these logs at Android Studio?  We have an `Sys.out` here: https://github.com/react-native-share/react-native-share/blob/61d5e0258bbbfb23f0f6480050166d56d2aa3a43/android/src/main/java/cl/json/RNShareModule.java#L157 

Also, you can try adding a breakpoint here: https://github.com/react-native-share/react-native-share/blob/61d5e0258bbbfb23f0f6480050166d56d2aa3a43/android/src/main/java/cl/json/RNShareModule.java#L151

@Rossella-Mascia-Neosyn does this happens with a fresh new project using Android 11? Unfortunately, I'm unable to debug this situation for now. 😢

**Comment by meirstingz** [comment]
if you are using huawei,
it's a known problem, you can chek this solution:
https://github.com/react-native-share/react-native-share/issues/643#issuecomment-641192985

**Comment by Neosyn-Alex-Ferreli** [comment]
Hi, i was struggling with this issue too. I was looking for a solution inside Meta Documentation and i find this:
https://developers.facebook.com/docs/sharing/android

When you implement sharing, your app should not pre-fill any content to share. Pre-filling content is inconsistent with the [Developer Policies](https://developers.facebook.com/devpolicy/#control).

Maybe it's impossible to do it from this new Developer Policies? Images seems to work, but seems impossible to place a text of a post.

**Comment by Nehal-Sanklecha** [comment]
@mikehardy I'll try but I don't have much experience with Android native code. I started with swift and then react-native. This could take time but would definitely be new learning. It would be very helpful if anyone else could also give it a look. Thanks!
