### ISSUE TITLE
Unable to share files as attachments when selecting Mail

### ISSUE THREAD

**Issue by my-name-is-nheo** [react-native-share/react-native-share#1202]
Failing to attach files when sharing through mail. Behaving correctly with message and other apps. 

### Expected behaviour
Share array of files strings as attachments to mail. 

### Actual behaviour
opening blank email with no attachments

### Environment
- **React Native version**:  RN 0.67.3
- **React Native platform + platform version**: iOS 15.4
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment? 4.4.4

### react-native-share
**Version**: npm version or "master" 8.1.4

<img width="518" alt="Screen Shot 2022-05-18 at 2 21 11 AM" src="https://user-images.githubusercontent.com/58013260/168971046-7bb0198b-2e3b-4ea6-8047-6311e709701a.png">

**Comment by mikehardy** [comment]
Hi there!
With apologies, an image is not a reproducible example in general text is strongly preferred - https://stackoverflow.com/help/how-to-ask

That said, this is not a use case of mine and I'm not sure who else might be listening, so my best advice is to step into the actual code to see what this module is doing in the Share methods + how it is calling the native APIs + and read the documentation on those APIs to see if they support multiple files attached at once to the underlying app. In some cases in the past it has simply been that it is not supported, in other cases there has been some trivial bug and a PR would fix it

While I don't have time to donate to fix your exact issue I will collaborate on any PR you come up with if needed, and help get it released
