### ISSUE TITLE
Error: app_is_not_active

### ISSUE THREAD

**Issue by lucasalvesa** [react-native-share/react-native-share#1205]
## Ask your Question
Hi everybody, I'm having a hard time trying to use 
```JS
Share.open(options)
  .then((res) => {
    console.log(res);
  })
  .catch((err) => {
    err && console.log(err);
  });
```
because everytime I try to share something using Android my terminal console returns this ` WARN  Possible Unhandled Promise Rejection (id: 1): Error: app_is_not_active`. It works perfectly fine with iOS... and I can't seem to find an answer for that. Thanks for the help in advance

**Comment by lucasalvesa** [comment]
To tell you the truth the actual piece of code I'm using is this:
```JS
Share.open(options).then(info => {
			instrumentOnClick({ campaignKindId, id, title, info });
		});
````

This `instrumentOnClick()` function is responsible for loging some important data to an external platform called Amplitude. That's what it does, nothing else. `campaignKindId, id, title, info` are all the data I need to send to this Amplitude platform and it works fine when I run the code in iOS simulator. But when I need Android to `instrumentOnClick` I get this _Possible Unhandled Promise Rejection Error: app_is_not_active_. And I'm quite sure that it's not the `.catch(err)` part becaus I've tried it before...

**Comment by mikehardy** [comment]
This is not a direct answer (sorry), but 

> Possible Unhandled Promise Rejection Error: app_is_not_active

is always a javascript error handling issue. It is not a problem with this module most likely, there is just a problem with however you are handling the exception

I must admit I started javascript programming already in the try/catch async/await era so I find it difficult to reason very will about the call().then().finally() structures even though yes they are similar. But I would add logging before and after every statement in there to see when the one causing the error is executed and carefully examine what you are doing until all errors are handled

**Comment by MateusAndrade** [comment]
Hi @lucasalvesa, probably this is related to Amplitude or something. Can you try adding a proper `try/catch` at the `instrumentOnClick` or check if everything is working with this library(amplitude)?
