### ISSUE TITLE
How to share full message to Telegram?

### ISSUE THREAD

**Issue by ksielyov** [react-native-share/react-native-share#1206]
I have some config:
![Снимок экрана 2022-05-30 в 18 00 48](https://user-images.githubusercontent.com/47862601/170997704-7bc8c21b-2d72-4236-b419-df7a8d9f871c.png)

It shares perfectly to WhatsApp, but in Telegram I can only sent url
![2022-05-30 18 03 08](https://user-images.githubusercontent.com/47862601/170998089-ec7391d4-614c-4aa3-95d6-674c7a18c49d.jpg)
.

**Comment by evasyuk** [comment]
yeap. I have the same issue.

Works perfectly with SMS(message field passed successfully), but with Slack and Telegram only link content being passed to 3rd party app
