### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNShare.FACEBOOK')

### ISSUE THREAD

**Issue by anjalijspaceo** [react-native-share/react-native-share#1207]
### Steps to reproduce
1. Installed package
2. Linked package
3. Import lib and getting this error

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**: 0.67.2"
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: ^7.5.0 npm version or "master"

### Link to repo (highly encouraged)
https://github.com/
![Screenshot 2022-05-31 at 1 07 06 PM](https://user-images.githubusercontent.com/106058588/171118570-3435c73b-a51a-41c0-a415-aa056ab8360e.png)

**Comment by mikehardy** [comment]
You have not correctly integrated the native module, so it's null when you call it

This is a classic build/integration error. Double-check your integration

https://search.brave.com/search?q=react-native+nativemodule+null

It will not result in any change to this module as it's a problem in the local project / following integration / build steps, so closing
