### ISSUE TITLE
iOS shareSingle WhatsApp is not working for image and message

### ISSUE THREAD

**Issue by fatihyildizhan** [react-native-share/react-native-share#1208]
### Steps to reproduce
1. Try to use shareSingle Whatsapp for image and message on iOS device.

```
const shareOptions = {
  title: "Share Content Title",
  message: "Welcome",
  url: base64image,
  social: Share.Social.WHATSAPP,
};

const ShareResponse = await Share.shareSingle(shareOptions);
```

### Expected behaviour
Needs to open whatsapp for single user and share Image and Message.

### Actual behaviour
There is no message. Only image appears.

### Environment
- **React Native version**: 0.63.4
- **iOS Device 15.5**
- **Typescript version** 4.4.4

### react-native-share
**Version**: 7.4.1
https://github.com/react-native-share/react-native-share/releases/tag/v7.4.1

**Comment by fatihyildizhan** [comment]
Anyone else having this problem?

**Comment by peetzweg** [comment]
Same for me.

**Comment by AhmedAbuelenin** [comment]
I am having the same issue with whatsapp trying to share only a url, nothing happened and whatsapp didn't open at all.

Also with telegram I receive an error "The operation couldn’t be completed. Not installed"
and It moves directly to app store on Telegram app even the app is already installed.

Environment
React Native version: 0.67.3
iOS Device 15.5
Typescript version 4.4.4

react-native-share
Version: 7.6.6

**Comment by vikas960188** [comment]
Hello Team,
I am also facing the same issue? Does any one get solution for that? 
Before it was working fine but now its not working.

Thanks in advance

**Comment by ilgiapa** [comment]
Hello Everyone,
The problem still persists.

I can share one image passing in the "url" property, but WhatsApp is not opening directly on the whatsAppNumber Chat.

```
    const shareOptions = {
      message: shareDataOptions.message,
      url: shareDataOptions.base64Image,
      social: Share.Social.WHATSAPP,
      whatsAppNumber: shareDataOptions.phoneNumber,
    };

   const ShareResponse = await Share.shareSingle(shareOptions);
```

Secondo question, it's possible to share multiple images with WA ? 

Thanks,

**Comment by fatihyildizhan** [comment]
Hi, this issue is still open.

**Comment by mikehardy** [comment]
We eagerly await+merge+release PRs from developers interested enough to contribute them

**Comment by akdj** [comment]
hello, issue not resolved, still cannot share image on Whatapp with singleShare -> it do a open native share menu with .wai file, that not singleShare should do

**Comment by hamza112255** [comment]
in singleShare only instagram open the native share bottom sheet with instagram only option and for other's some directly goes to the app without open bottom sheet native share and some goes to the playstore even app is installed in android i want for all single share it opens the native share bottom sheet like instagram only
