### ISSUE TITLE
Promise "open" is never resolved when saving the image

### ISSUE THREAD

**Issue by AndreiDanilkovich** [react-native-share/react-native-share#1214]
### Steps to reproduce
1. Call `const res = await Share.open({ url: imageUrl })`
2. Select "Save Image"

### Expected behaviour
The image should be saved and promise inside library should be resolved or rejected

### Actual behaviour
The image is saved and promise never resolved/rejected

### Environment
- **React Native version**: 0.63.4
- **React Native platform + platform version**: iOS 15.5

### react-native-share
**Version**: 7.6.0

![IMG_8839](https://user-images.githubusercontent.com/79085706/172422159-adea30d8-1e60-4076-bd70-c2a63c920390.PNG)

**Comment by khunghang16** [comment]
When i click save image, modal in react native auto close and freeze screen

**Comment by ferrannp** [comment]
@khunghang16 found anything on not auto-closing modal?

**Comment by cashcount** [comment]
Same

**Comment by hunglannn** [comment]
> When i click save image, modal in react native auto close and freeze screen

same issue. how did you fix it?

**Comment by Tharinducn** [comment]
I got this issue in iOS when opening the share modal on top of react-native-modal. Fixed it by closing the react-native-modal when the share modal opens
