### ISSUE TITLE
Promise "open" always catches error "User did not share" when sharing a file with E-mail

### ISSUE THREAD

**Issue by Youssef-Ayed** [react-native-share/react-native-share#1216]
### Steps to reproduce
Share.open({
      title: 'title',
      message: `Hello,
      You will find my file attached below.
      Sincerely.
      Sent via My App`,
      url: 'file://' + path,
      subject: shareSubject,
    })
      .then( () => {
        console.log("File shared!") 
      })
      .catch(err => console.log(err));
write this code and try to share a file via e-mail, you will find your e-mail has been sent but the promise still gets rejected

### Expected behaviour
After sending the file, the promise resolves
### Actual behaviour
Catches an error "User did not share"

### Environment
- **React Native version**: "0.68.2"
- **React Native platform + platform version**: Android 11

### react-native-share
**Version**: "^7.5.0"

### Link to repo (highly encouraged)
https://github.com/

**Comment by mikehardy** [comment]
I think this is a duplicate, note this comment and take heed - carefully read the comments and potential path to resolution https://github.com/react-native-share/react-native-share/issues/1059#issuecomment-1067999496
