### ISSUE TITLE
fix(ios): Build input file cannot be found: 'node_modules/react-native-share/ios/Utils.m'

### ISSUE THREAD

**Issue by theonetheycallneo** [react-native-share/react-native-share#1219]
### Steps to reproduce
1. Install latest react-native-share `7.6.1`
2. Compile the app
3. Note the error:

```
Showing All Errors Only
Build input file cannot be found: 'node_modules/react-native-share/ios/Utils.m'
```

It appears we are missing the Utils.m in the release or perhaps this should simply be removed from the ios project altogether:

https://github.com/react-native-share/react-native-share/blob/main/ios/RNShare.xcodeproj/project.pbxproj#L36-L37

### Expected behaviour
Tell us what should happen

App should compile.

### Actual behaviour
Tell us what happens instead

App errors on compile.

### Environment
- **React Native version**: 

```
"react": "17.0.2",
"react-native": "0.66.4",
```

- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

```
iOS: 12.0
Android: 6.0
```

- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

```
"typescript": "4.2.4"
```

### react-native-share
**Version**: `7.6.1`

### Link to repo (highly encouraged)
https://github.com/

**Comment by mikehardy** [comment]
I've seen this before I just don't remember where - it did not turn up in a search of issues

I seem to remember this happened when people were directly trying to build the RNShare project, and the basic solution was: don't do that, you have no need to do that

When using the module via cocoapods and react-native 0.60+ auto-linking, the pbxproj (which is incorrect, sure) is not consulted so it does not matter, and there should be no errors. I use this library personally, for it's intended use (auto-linked inside a react-native project) and it works.

So, to test the theory that you're trying to compile it directly - which should not be required - can you say exactly how you see this build failure? You have not included steps to reproduce ("compile the app" is not sufficient) or a sample repo so I can't do more than speculate

**Comment by crazycoder-io** [comment]
I got same error and i just followed the steps from document which is this -> https://react-native-share.github.io/react-native-share/docs/install/
