### ISSUE TITLE
isPackageInstalled returning wrong value

### ISSUE THREAD

**Issue by AliHaidar110** [react-native-share/react-native-share#1224]
### Steps to reproduce
1. invoking Share.isPackageInstalled("com.instagram.android"); in android

### Expected behaviour
returns {"isInstalled": true, "message": "Package is Installed"}

### Actual behaviour
{"isInstalled": false, "message": "Package is Installed"}

### Environment
- **React Native version**: "^0.64.2"
- **React Native platform + platform version**:Android 11

### react-native-share
**Version**: "^7.6.1"

**Comment by mikehardy** [comment]
I will bet you $1 it is this: https://react-native-share.github.io/react-native-share/docs/install#adding-queries-for-the-android-necessary-for-sdk--30

If I am right, could you edit the docs page for "isPackageInstalled" and cross-link that installation step?

**Comment by AliHaidar110** [comment]
tried 
`
<package android:name="com.instagram" />
<package android:name="com.instagram.android" />
<package android:name="com.instagram.store" />
`

**Comment by AliHaidar110** [comment]
tried 
`
<package android:name="com.instagram" />
<package android:name="com.instagram.store" />
<package android:name="com.instagram.services" />
<package android:name="com.instagram.android" />
<package android:name="com.instagram.store" />
<package android:name="com.instagram.android.store" />
<package android:name="com.instagram.services" />
<package android:name="com.instagram.android.services" />
`

**Comment by AliHaidar110** [comment]
what I am thinking is that I am getting the correct message {"isInstalled": false, "message": "**Package is Installed**"}
meaning 
`  isPackageInstalled(packageName: string): Promise<IsPackageInstalledResult | never> {
    if (Platform.OS === 'android') {
      return new Promise((resolve, reject) => {
        NativeModules.RNShare.isPackageInstalled(
          packageName,
          (error) => {
            return reject({ error });
          },
          (isInstalled) => {
            return resolve({
              isInstalled,
              message: 'Package is Installed',
            });
          },
        );
      });
    } else {
      throw new Error('Not implemented');
    }
  },
} as const;`
the callback for isPackageInstalled true is being invoked but the arg is false

**Comment by AliHaidar110** [comment]
worked, for some reason, Instagram was uninstalled from the simulator -_-
