### ISSUE TITLE
Is it possible to shareSingle to iMessage?

### ISSUE THREAD

**Issue by buog** [react-native-share/react-native-share#1229]
I noticed Locket lets shareSingle to iMessage. I was wondering how they did this?

https://user-images.githubusercontent.com/47714021/174459703-1136a7c5-c58a-4c0e-976a-7f6d9f2350d4.MP4

**Comment by didiabel** [comment]
i believe you have to check out 
https://developer.apple.com/documentation/messageui/mfmessagecomposeviewcontroller
to send imessages for now
