### ISSUE TITLE
Share option for "Instagram Direct" and "Instagram Post" 📷

### ISSUE THREAD

**Issue by runtothedoor** [react-native-share/react-native-share#1234]
## Describe the Feature

A method for both "Direct" and "Post" Instagram Sharing...

     Share.shareSingle({
        text: ...,
        social: Share.Social.INSTAGRAM_DIRECT
      })
      
      Share.shareSingle({
       url: ...,
       social: Share.Social.INSTAGRAM_POST
     })
      
 Just like this feature on spotify...
 <img width="180" src="https://user-images.githubusercontent.com/28831375/176033173-af3affd6-6a0a-4aad-894e-ce3d284ba613.png"/>      
      

      
## Possible Implementations
**Direct:**
`com.instagram.direct.share.handler.DirectShareHandlerActivity` on android intent may work for direct but I have no idea if an implementation for IOS is possible... 

**Post:**
`com.instagram.share.handleractivity.ShareHandlerActivity` on android

**Comment by gabrielfvf7** [comment]
> com.instagram.direct.share.handler.DirectShareHandlerActivity

@runtothedoor and how do you share only text do direct using this lib?
