### ISSUE TITLE
problems with sending files via Skype and line (Android )

### ISSUE THREAD

**Issue by viet-nguyen-1926** [react-native-share/react-native-share#1235]
## Ask your Question

I'm developing an apps that has the functionality to send some documents via other apps, include via skype and Line. The problem is that if I want  to share via skype  and Line using  Intent  my document(document  is photos and text), skype and Line ignore the text and attaches only photo to the message.

 Can i share text and image same time ?

**Comment by mikehardy** [comment]
Have you checked previous issues?

https://github.com/react-native-share/react-native-share/issues?q=is%3Aissue+share+text+image

I'm not sure you can. If you can, it may be specific to the target you try.

If you try and it does not work, and you dig in to node modules to troubleshoot why only one or the other works, you may find it is just a limitation of the target and there is nothing we can do here.

If you try and it does not work, and you dig in to node modules to troubleshoot and are able to fix it, a PR would be great

**Comment by viet-nguyen-1926** [comment]
Thanks your information.
Maybe these issues are not related to my problems.
