### ISSUE TITLE
Share open is not working in redmi

### ISSUE THREAD

**Issue by meirstingz** [react-native-share/react-native-share#1237]
### Steps to reproduce
1.  await Share.open({      
                    subject: 'my subject',
                    url: `file:///storage/emulated/0/Download/my-folder/my-file.pdf`, (is a base64 file)
                    title: 'my title'
                    message: `my message`,
                  });

### Expected behaviour
share.open() will open the share popup with a list of apps to share with

### Actual behaviour
share.open() is openning the share popup but without any apps to share with

if i remove the url param it works fine

shareSingle() works fine

in other phones (samsung, huawei) it works fine

### Environment
- **Redmi note 9 pro **

- **React Native version**:  0.63.3
- **platform version**: , Android 10

### react-native-share
npm 7.6.4 and tried 3.0.0 either

**Comment by retyui** [comment]
you need to add a `QUERY_ALL_PACKAGES` permission:

```html
<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
```

more: https://github.com/react-native-share/react-native-share/issues/1009#issuecomment-824101426

**Comment by camboYY** [comment]
not work for me
