### ISSUE TITLE
Sharing audio and video file as base64 string not working in ios

### ISSUE THREAD

**Issue by sasilta** [react-native-share/react-native-share#1238]
Hello, 

I am trying to share  audio and video file in email. I tried using base64 string (cannot rely on url since the link is visible and i do not want to display it). The behavior is working as expected in android but it is not loading any file in ios. How can this be solved?

**Comment by AliHaidar110** [comment]
hello, can you share any code?

**Comment by eramudeep** [comment]
i tried sharing the video url 

`const opt= {
message: "test status for video 5",
title: "Rectangle Center Alignment Video Demo Group",
url: "file:///var/mobile/Containers/Data/Application/D1F63F59-EAE4-4296-894F-057C9517066E/Documents/5_CUSTOMIZED.mp4"
}`

throwing error can not share this item.

**Comment by andrefangeloni** [comment]
@sasilta what you did to resolve this issue?
