### ISSUE TITLE
Can't exclude Markup on iOS after adding 'markupAsPDF' to excludedActivityTypes

### ISSUE THREAD

**Issue by GieblerGary** [react-native-share/react-native-share#1239]
### Steps to reproduce
1. Add 'markupAsPDF' to excludedActivitiesTypes
2. Run app on iOS 15.5
3. Share PDF file

### Expected behaviour
You should not see Markup in the options

### Actual behaviour
You see Markup in the options and if you select it you can markup the PDF

### Environment
- **React Native version**: 0.64.0
- **React Native platform + platform version**: iOS 15.5
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment? 4.2.3

### react-native-share
**Version**: master (7.6.4)

**Comment by WooHao** [comment]
Seems excludedActivityTypes not working.
