### ISSUE TITLE
Android app crashes with error: null is not an object (evaluating '_reactNative.NativeModules.RNShare.FACEBOOK')

### ISSUE THREAD

**Issue by GieblerGary** [react-native-share/react-native-share#1240]
### Steps to reproduce
1. npm install react-native-share --save
2. import Share and add code
3. run on Android

### Expected behaviour
App should run on Android without crashing due to above error

### Actual behaviour
App crashes on Android phone with above error

### Environment
- **React Native version**: 0.64.0
- **React Native platform + platform version**: Samsung Galaxy S8 Android Version 9
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment? 4.2.3

### react-native-share
**Version**: master(7.6.4)

App runs correctly on iOS.  Tried all of the suggestions online about this issue - nothing resolves it.

**Comment by mikehardy** [comment]
"null is not an object" when you are evaluating a native module is typically a failure to correctly integrate + pod install + build + deploy code you think you are deploying to the running device

So the javascript is there and tries to hit a native module but the native module doesn't exist for some reason

That's the normal reason anyway. Perhaps `npx react-native-clean-project` and triple-check all steps in install + build + run process

**Comment by GieblerGary** [comment]
Hi Mike,
Thanks for the quick reply.  I've tried npx react-native-clean-project and in fact after my first failed attempt to integrate react-native-share, I checked out our current branch and repeated the whole installation process a second time with the same results.  Everything is working properly on iOS (except for removing Markup), and I've added dozens of modules in the past successfully with our Android app, so I'm at a loss with this issue and trying to resolve it which has forced us to place the whole sharing feature on hold for iOS as well since the mere presence of importing causes the Android app to crash. I will say that npm react-native-clean-project hangs on 'wipe system iOS Pods cache' and 'update iOS Pods' so I simply answer 'N' to them and they shouldn't affect the Android build anyway.  I just checked out the project, cleaned it again, and am running it and will look at the output to see what errors show up.  Thanks again.

**Comment by GieblerGary** [comment]
I have the following suggested lines:
apply from: "../../node_modules/react-native/react.gradle"
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

**Comment by GieblerGary** [comment]
ext.kotlin_version = '1.3.50'
    ext {
        minSdkVersion = 23
        compileSdkVersion = 30
        targetSdkVersion = 30
        supportLibVersion = "28.0.0"
        kotlinVersion = "1.3.50"
    }

**Comment by mikehardy** [comment]
You might look carefully at the result of auto-linking output during the build, perhaps there is a message there indicating whether it is being included or not, and if so why not? There was this recently, as an example of what can go wrong https://github.com/invertase/react-native-google-mobile-ads/issues/151

**Comment by GieblerGary** [comment]
I was able to get it to run in Android Studio (still crashes from the terminal) but now that I'm trying to add a file provider I get the errors:
Class 'MainApplication' must either be declared abstract or implement abstract method 'getFileProviderAuthority()' in 'ShareApplication'
and
Method does not override method from its superclass

**Comment by GieblerGary** [comment]
I was finally able to run it from Android Studio but it doesn't run from the terminal command prompt

**Comment by GieblerGary** [comment]
Now that I have the Android version running - I tried to email a PDF file and all I got was a local link to the file not the actual file.  I implemented the file provider - isn't that supposed to copy the file?

**Comment by GieblerGary** [comment]
This is what I get in the email (bundle ID changed to protect company)
/data/user/0/com.company.app/files/health/Agreement.pdf

What do I need to put in the file paths.xml file?

**Comment by mikehardy** [comment]
If I recall correctly we have an example that demonstrates everything and works? I'm traveling so won't have any time to look in detail at anything, apologies. Hopefully examining the example helps.

**Comment by Dakuan** [comment]
this means it will fail for expo users

**Comment by wodin** [comment]
> this means it will fail for expo users

Could you elaborate? Here's an Expo app based on the RN Share example app that works for me:

https://github.com/wodin/RNShare

**Comment by MarcHbb** [comment]
Had the same issue with expo managed workflow.
Tried to use @wodin repo and launched it, the issue was gone.
But I've found another issue, singleShare always redirect to the appstore

**Comment by tscans** [comment]
> > this means it will fail for expo users
> 
> Could you elaborate? Here's an Expo app based on the RN Share example app that works for me as long as you build with EAS Build:

How do you get around the error with this though? I understand it might not work with Expo Go - but how do you avoid the error mentioned above? Is it because your project is JS and not TS?

**Comment by wodin** [comment]
@tscans I assume you mean this error?

```
null is not an object (evaluating '_reactNative.NativeModules.RNShare.FACEBOOK')
```

That error is caused by the native code being missing from the app.
So e.g. if you try to run the app in Expo Go it will give you errors like that because the native code for RN Share is not built into Expo Go.

That's why you should build a development client, which is basically a custom version of Expo Go, that has *your* dependencies built in. As long as you built it after installing `react-native-share`, it will have access to the RN Share native code, so you should not get the above error.

**Comment by whyaftab** [comment]
> 

will this work in pre release version in managed workflow? 
https://docs.expo.dev/guides/sharing-preview-releases/

**Comment by wodin** [comment]
It will not work with Expo Go, but it should work fine if you build with `eas build --profile development` (which will give you basically a custom version of Expo Go that includes all of your dependencies. And it should also work fine if you build with `eas build --profile preview`.

See:
* [Development Builds](https://docs.expo.dev/development/introduction/)
* [Internal distribution](https://docs.expo.dev/build/internal-distribution/)

and also the "Internal Distribution" section on the page you linked to.

**Comment by josedavidgc** [comment]
From Expo you can use the "react-native-share" plugin. Expo has two workflows: "managed" and "bare", the workflow to use is the bare one. You can see more information here: <a href="https://docs.expo.dev/introduction/managed-vs-bare/">https://docs.expo.dev/introduction/managed-vs-bare/</a>

In a few steps it would be:

- Install the "react-native-share" plugin.
- eas build --profile development --platform ios
- eas build --profile development --platform android
- expo start --dev-client

You should follow the instructions to install the generated files for iOS and Android from the Expo page. You can now continue working from Expo.

**Comment by wodin** [comment]
@josedavidgc there is no need to use the Bare workflow, and in fact what you are describing is not the bare workflow. With the bare workflow you would not be adding config plugins etc., except maybe if you did that before running `npx expo prebuild` in order to switch to the bare workflow.

Your instructions are basically correct (although these days you should use `npx expo start` instead of `expo start` and you no longer have to specify `--dev-client`.)

I think their terminology is a bit unclear at the moment because using config plugins and dev clients is still "managed". But you can no longer use Expo Go (... except if you [avoid calling custom native code when running in Expo Go](https://docs.expo.dev/bare/using-expo-client/)) and you can't build the app with the classic `expo build`.

**Comment by josedavidgc** [comment]
@wodin what I wrote above is what worked and still works for me, step by step. Not only with this plugin but with others. Getting to this solution cost me a lot of headaches and a lot of time reading blah,blah,blah from guys like you who only tangle with words and not with facts. I have given my solution and explained it very clearly. I don't have time to argue and I suggest that instead of nagging with so much theory, give a solution to the problem raised here.

**Comment by wodin** [comment]
@josedavidgc yes, as I said, your instructions are correct. But those instructions do not imply the Bare workflow.

**Comment by vincent-odukwe** [comment]
@wodin the package works when using the general share, but when using a specific social in this case instagram.
it keeps navigating me to the app store.

Below is my code and the error I am getting

```
import React, { useRef, useEffect, useState } from 'react';
import {
  View,
  StyleSheet,
  Text,
  TouchableOpacity,
  Platform,
  Linking,
} from 'react-native';
import { captureRef } from 'react-native-view-shot';
import Share from 'react-native-share';

const ShareableReactImage = () => {
  const viewRef = useRef();
  const [showInstagramStory, setShowInstagramStory] = useState(false);

  // useEffect(() => {
  //   if (Platform.OS === 'ios') {
  //     Linking.canOpenURL('instagram://')
  //       .then(val => {
  //         console.log('val: ', val);
  //         setShowInstagramStory(val);
  //       })
  //       .catch(err => {
  //         console.log(err);
  //         // console.error(err);
  //       });
  //   } else {
  //     Share.isPackageInstalled('com.instagram.android')
  //       .then(({ isInstalled }) => setShowInstagramStory(isInstalled))
  //       .catch(err => console.error(err));
  //   }
  // }, []);

  const shareDummyImage = async () => {
    // try {
    //   const uri = await captureRef(viewRef, {
    //     format: 'png',
    //     quality: 0.7,
    //   });
    //   if (!showInstagramStory) {
    //     await Share.shareSingle({
    //       stickerImage: uri,
    //       // method: Share.InstagramStories.SHARE_STICKER_IMAGE,
    //       social: Share.Social.INSTAGRAM_STORIES,
    //       backgroundBottomColor: '#FF0000',
    //       backgroundTopColor: '#FF0000',
    //     });
    //   } else {
    //     await Share.open({ url: uri });
    //   }
    // } catch (err) {
    //   console.error(err);
    // }
    const shareOptions = {
      // title: 'Share file',
      // failOnCancel: false,
      // url: 'https://images.pexels.com/photos/1387174/pexels-photo-1387174.jpeg',
      message: encodeURI(
        'Checkout the great search engine: https://google.com',
      ),
      social: Share.Social.INSTAGRAM,
    };
    Share.shareSingle(shareOptions)
      .then(res => {
      console.log(res);
    })
      .catch(err => {
      err && console.log(err);
    });
  };

  return (
    <View>
      <View style={{ padding: 20, alignItems: 'center' }} ref={viewRef}>
        <Text
          style={{
            fontSize: 20,
            fontWeight: '600',
            textAlign: 'center',
            paddingBottom: 20,
          }}>
          Don't be a dummy!
        </Text>
        <View style={styles.dummy}></View>
        <Text
          style={{
            fontSize: 26,
            fontWeight: '700',
            textAlign: 'center',
            paddingTop: 20,
          }}>
          LEARN REACT NATIVE
        </Text>
      </View>
      <TouchableOpacity style={{ marginTop: 30 }} onPress={shareDummyImage}>
        <Text
          style={{
            fontSize: 20,
            fontWeight: '700',
            textAlign: 'center',
            color: 'red',
          }}>
          {showInstagramStory ? 'Share Instagram Story' : 'Share'}
        </Text>
      </TouchableOpacity>
    </View>
  );
};

export default ShareableReactImage;

const styles = StyleSheet.create({
  dummy: {
    width: 0,
    height: 0,
    borderTopWidth: 120,
    borderTopColor: 'yellow',
    borderLeftColor: 'black',
    borderLeftWidth: 120,
    borderRightColor: 'black',
    borderRightWidth: 120,
    borderBottomColor: 'yellow',
    borderBottomWidth: 120,
    borderTopLeftRadius: 120,
    borderTopRightRadius: 120,
    borderBottomRightRadius: 120,
    borderBottomLeftRadius: 120,
  },
});
```

`LSApplicationQueriesSchemes`

```
      "infoPlist": {
        "LSApplicationQueriesSchemes": [
          "googlechromes",
          "comgooglemaps",
          "instagram",
          "instagram-stories",
          "facebook-stories",
          "fb-stories",
          "fb"
        ],
        "NSLocationAlwaysUsageDescription": "App uses your location to accurately determine which events are near you",
        "NSLocationWhenInUseUsageDescription": "App uses your location to accurately determine which events are near you",
        "NSLocationUsageDescription": "App uses your location to accurately determine which events are near you",
        "NSPhotoLibraryUsageDescription": "App uses the access to your photos to make the creation of events more perzonalized",
        "NSPhotoLibraryAddUsageDescription": "App uses the access to your photos to make the creation of events more perzonalized"
      },
```

`Error`

```
Object {
  "error": Object {
    "code": "ECOM.RNSHARE1",
    "domain": "com.rnshare",
    "message": "The operation couldn’t be completed. Not installed",
    "nativeStackIOS": Array [
      "0   Promo                               0x000000010334ac20 RCTJSErrorFromCodeMessageAndNSError + 116",
      "1   Promo                               0x000000010334ab6c RCTJSErrorFromNSError + 256",
      "2   Promo                               0x00000001032e1394 __41-[RCTModuleMethod processMethodSignature]_block_invoke_4.110 + 132",
      "3   Promo                               0x0000000103211ff0 -[InstagramShare shareSingle:failureCallback:successCallback:] + 1784",
      "4   Promo                               0x0000000103214f5c -[RNShare shareSingle:failureCallback:successCallback:] + 1276",
      "5   CoreFoundation                      0x00000001c3d05b24 6B22DD81-3585-3BE6-BC77-BA19810EC0F2 + 138020",
      "6   CoreFoundation                      0x00000001c3d23610 6B22DD81-3585-3BE6-BC77-BA19810EC0F2 + 259600",
      "7   CoreFoundation                      0x00000001c3d5a5fc 6B22DD81-3585-3BE6-BC77-BA19810EC0F2 + 484860",
      "8   Promo                               0x00000001032e33e4 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1828",
      "9   Promo                               0x00000001032e6f20 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 1156",
      "10  Promo                               0x00000001032e68c0 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 144",
      "11  Promo                               0x00000001032e6824 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28",
      "12  libdispatch.dylib                   0x00000001c39e2e6c E3EA4F63-5D11-342A-AF19-9F58DBC8E259 + 7788",
      "13  libdispatch.dylib                   0x00000001c39e4a30 E3EA4F63-5D11-342A-AF19-9F58DBC8E259 + 14896",
      "14  libdispatch.dylib                   0x00000001c39f2f48 E3EA4F63-5D11-342A-AF19-9F58DBC8E259 + 73544",
      "15  libdispatch.dylib                   0x00000001c39f2b98 _dispatch_main_queue_callback_4CF + 44",
      "16  CoreFoundation                      0x00000001c3d35800 6B22DD81-3585-3BE6-BC77-BA19810EC0F2 + 333824",
      "17  CoreFoundation                      0x00000001c3cef704 6B22DD81-3585-3BE6-BC77-BA19810EC0F2 + 46852",
      "18  CoreFoundation                      0x00000001c3d02bc8 CFRunLoopRunSpecific + 600",
      "19  GraphicsServices                    0x00000001dfe6e374 GSEventRunModal + 164",
      "20  UIKitCore                           0x00000001c6676b58 137A95AA-DA6D-332C-BC01-E13BB9B6E317 + 5327704",
      "21  UIKitCore                           0x00000001c63f8090 UIApplicationMain + 364",
      "22  Promo                               0x0000000102f8d7ec main + 104",
      "23  dyld                                0x0000000106ad1da4 start + 520",
    ],
    "userInfo": Object {
      "NSLocalizedFailureReason": "Not installed",
    },
  },
}
```

**Comment by tero-paananen** [comment]
I had to **manually link** this react-native-module to the project to get out from this same error. Autolinking of other modules work well.

```
"react": "18.0.0",
"react-native": "0.69.4",
"react-native-share": "7.9.0",
```

**Comment by tero-paananen** [comment]
> I am using react-native 0.69.x and this module in its current version and do not have to manually link
> Perhaps there is some build time error / warning that would indicate why auto-linking is not working @tero-paananen ?

My mistake we had autolinking disabled of this module in react-native.config.json
```
'react-native-share': {
      platforms: {
       android : null, // this disables autolinkin of this module on Android - do not use set this !
      },
    },
```
