### ISSUE TITLE
[Share.open] excludedActivityTypes allow specific android package names but TypeScript interface don't

### ISSUE THREAD

**Issue by runtothedoor** [react-native-share/react-native-share#1241]
`(property) ShareOptions.excludedActivityTypes?: ActivityType[] | undefined`

![image](https://user-images.githubusercontent.com/28831375/176799224-94c71d71-32ae-4aa5-a391-3b11997e123a.png)

https://github.com/react-native-share/react-native-share/blob/3038dd4d3b315eaad08e259528ce176a0afa85bd/android/src/main/java/cl/json/social/ShareIntent.java#L62

**Comment by GieblerGary** [comment]
I should have included this:

  const message: ActivityType = 'message'
  const markupAsPDF: ActivityType = 'markupAsPDF'
  const assignToContact: ActivityType = 'assignToContact'
  const saveToCameraRoll: ActivityType = 'saveToCameraRoll'

**Comment by 3GOMESz** [comment]
> 
Thank you but I've already opened a PR that solves this. If you want a hint, instead of forcing the type of each string you can type the entire array. 

`excludedActivityTypes: [message,
markupAsPDF,
assignToContact,
saveToCameraRoll, 
"x",
"y"
"z"] as ActivityType[]`
