### ISSUE TITLE
Send Direct Message with Image In Instagram

### ISSUE THREAD

**Issue by Johnsondhoni07** [react-native-share/react-native-share#1244]
Share open is working fine with Whatsapp while sharing image plus message link but when it comes to instagram it only shares Image in direct message as well as the stories no message or link is added with the image in instagram. I have attached the images of whatsapp and instagram share.

`response = {
            message: 'message with some link' ,
            url: base64Image,
            title: 'title',
          };

try {
        const result = await Share.open(response);
        handleClose();
      } catch (err) {
        console.log(err);
        handleClose();
      }

![MicrosoftTeams-image](https://user-images.githubusercontent.com/82214675/177720748-c697c886-d9c3-4ba6-978d-c910204ec255.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/82214675/177720766-67c5ee51-ba0d-40da-b662-d485e5221c05.png)

`

Above Code is Working Fine for Whatsapp

**Comment by Shehryar2** [comment]
any clue for instagram because my message with image is not working only image attached but not the message or title.

**Comment by Johnsondhoni07** [comment]
Hello @Shehryar2, I don't found any way to resolve this issue on Instagram.  I think it is based on Instagram policy and works better on other social media.  So leave it as it is until the update comes from the author
