### ISSUE TITLE
instagram redirect on success not working

### ISSUE THREAD

**Issue by eyal94** [react-native-share/react-native-share#1245]
Hello everyone, im facing the exact same problem this guy had:

> Hi guys, I have run into an issue with sharing a story on Instagram. After sharing a story I am not taken back to my app but to the Instagram feed instead.
> 
> ### Steps to reproduce
> ```
> await Share.shareSingle({
>   social: Share.Social.INSTAGRAM_STORIES,
>   backgroundVideo: 'file:///localfile.mp4',
> })
>   .then((response) => {
>     console.log(response);
>   })
>   .catch((err) => {
>     console.log(err);
>   });
> ```
> 
> ### Expected behaviour
> Redirect back to my react-native app after successfully sharing a story with {success: true} in the response(this is how it works for facebook stories)
> 
> ### Actual behaviour
> After sharing a story I'm redirected to the Instagram feed in my Instagram app. I need to press the "back" arrow on my phone to go back to my react-native app but then I get {"message": "CANCELED", "success": false} even though the story was shared successfully.
> 
> ### Environment
> * **React Native version**: 0.64.2
> * **React Native platform + platform version**: Android 9.0
> 
> ### react-native-share
> **Version**: 7.0.2
> 
> ### Link to repo (highly encouraged)
link:
https://github.com/react-native-share/react-native-share/issues/1087#issue-990828541

it is marked as closed however it doesnt seem as if it was taken care of - is this being worked on or am I missing something here?

**Comment by flavioafm** [comment]
Same issue, but I'm using Share.open();

**Comment by sleep9** [comment]
Same on IOS. both facebook and IG have the same behavior.
