### ISSUE TITLE
Can't exclude AirDrop via excludedActivityTypes

### ISSUE THREAD

**Issue by ptreitler** [react-native-share/react-native-share#1246]
### Steps to reproduce
1. Add `excludedActivityTypes: [ "airDrop" ]` to ShareOptions
2. Use the above to share text + an image
3. Run the app on iOS (tested with iOS 15.5), click share

### Expected behaviour
Airdrop should be excluded from the activities selection

### Actual behaviour
AirDrop still shows up in the activities selection

### Environment
- **React Native version**: 0.69.1
- **React Native platform + platform version**: iOS 15.5
- **Typescript version**: 4.3.5

### react-native-share
**Version**: 7.6.4

**Comment by WooHao** [comment]
same problem.
anyone knows why?

**Comment by hankyulkim93** [comment]
@ptreitler @WooHao Had a similar issue with Message. For some reason, `'message'` doesn't work, but `'com.apple.UIKit.activity.Message'` does. Maybe `'com.apple.UIKit.activity.AirDrop'` will work?

**Comment by kkpeng** [comment]
> @ptreitler @WooHao Had a similar issue with Message. For some reason, `'message'` doesn't work, but `'com.apple.UIKit.activity.Message'` does. Maybe `'com.apple.UIKit.activity.AirDrop'` will work?

Yes, but it does not work for third-party programs, such as AirDroid (com.sandstudio.airdroid.iphone.ShareExtension), WeChat (com.tencent.xin.sharetimeline)
