### ISSUE TITLE
share open/single not working on android 10 Honor 9x

### ISSUE THREAD

**Issue by NitinTayal007** [react-native-share/react-native-share#1247]
Steps to reproduce
Share text + an image
Run the app on android 10 Honor 9x click share

Expected behaviour
Image should share on mentioned apps(WhatsApp, Telegram, Instagram), share open should work

Actual behaviour
On click nothing is being share even not opening any app

Environment
React Native version: 0.64.2
Typescript version: 4.4.3
react-native-share
Version: 7.4.1

**Comment by retyui** [comment]
you need to add a `QUERY_ALL_PACKAGES` permission:

```html
<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
```

more: https://github.com/react-native-share/react-native-share/issues/1009#issuecomment-824101426
