### ISSUE TITLE
Share.open method doesn't work if user have more than one whatsapp installed in the device.

### ISSUE THREAD

**Issue by kv77724-dot** [react-native-share/react-native-share#1249]
### Steps to reproduce
1.Clone the whatsapp in you device.
2.Try to share anything using Share.open() method.
3.Click on whastapp logo. 

### Expected behaviour
Tell us what should happen
When trying to share using whatsapp it should open WhatsApp and let the user select the contact he want to share message to.

### Actual behaviour
Tell us what happens instead
When clicking on whatsapp logo, share Sheet closes automatically.

### Environment
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 87.03 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 7.21.1 - /opt/homebrew/bin/npm
    Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 28, 29, 30, 31
      Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-24 | ARM 64 v8a, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.68.0 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
- **React Native platform + platform version**:Android 10,11, etc

### react-native-share
**Version**: 7.0.0 

### Link to repo (highly encouraged)
https://github.com/react-native-share/react-native-share.

**Comment by mikehardy** [comment]
Clone how? Please include exact steps, I'm unfamiliar with app cloning.

**Comment by pranav-lio** [comment]
Share.shareSingle() will also not work If you have Dual or Parallel apps enabled. @kv77724-dot  did you find any work around.
