### ISSUE TITLE
Feature Request: Expo Plugin & Expo Documentation

### ISSUE THREAD

**Issue by BrodaNoel** [react-native-share/react-native-share#1252]
## Describe the Feature
I was checking that now we have support for `react-native-share` on `Expo` (https://expo.canny.io/feature-requests/p/support-for-react-native-share)

Do you know if it's necessary to create a `plugin` for being compatible with Expo (as it's mentioned in the link). Or is it ready to go?

What about adding some documentation about it for Expo users in the README file?

**Comment by Dakuan** [comment]
works straight away on ios, fails on android

**Comment by tscans** [comment]
Would also love to see this implemented.

**Comment by mikehardy** [comment]
I'm not aware of any of the maintainers here using Expo, so this would require an Expo user (or users) stepping up to contribute + maintain the plugin. That's how it has worked in the other repos I've maintained.

**Comment by MateusAndrade** [comment]
> I'm not aware of any of the maintainers here using Expo, so this would require an Expo user (or users) stepping up to contribute + maintain the plugin. That's how it has worked in the other repos I've maintained.

I don't have experience using expo, but would like to give it a try in order to add support for this library. Do you have any examples that we can use @mikehardy? 👀

**Comment by BrodaNoel** [comment]
Here is the Expo Config doc: https://docs.expo.dev/guides/config-plugins/

**Comment by BrodaNoel** [comment]
Sentry: https://github.com/expo/sentry-expo
Implementation: https://github.com/expo/sentry-expo/blob/main/plugin/src/withSentry.ts

**Comment by mikehardy** [comment]
Yeah if you look at app, perf, crashlytics modules in react-native-firebase you'll see three incl with unit tests, and there is a PR right now open for auth module in PR queue. Looks pretty simple depe on the needs, but the config plugin APIs themselves seem to move more than you'd think and require semi regular forward ports/ dependen updates/ testing so the maintenance over time is some to consider

**Comment by BrodaNoel** [comment]
@josedavidgc yes. That's the flow for installing everything. But then open Android and it crashes, as far the issue reports can tell. Check the other comments in this thread.

iOS works straightforward, but crashes in android. And seems like it may be related to the missing plug-in

**Comment by fendermany** [comment]
I tried to create custom-plugin for that, but unfortunately it doesn't work after rebuild:

I have error: "Native module RNShare tried to override RNShareModule. Check the getPackages() method in being created twice. If this was your intention, setcanOverrideExistingModule=true. This errormay also be present if the package is present only once in getPackages() but also automatically added later during build time by autolinking. Try removing the existing entry and rebuild". I checked all requires steps with "expo run:android", and don't have problem with plugin implementation. Looks like its need linking, but I don't know what exactly. Any ideas?

This is plugin: 

`const configPlugins = require("@expo/config-plugins");

function applyPackage(mainApplication) {
  const RNSharePackageImport = `import cl.json.RNSharePackage;`;
  const ShareApplicationImport = `import cl.json.ShareApplication;`;
  const RNShareAddPackage = `packages.add(new RNSharePackage());`;

  if (!mainApplication.includes(RNSharePackageImport)) {
    mainApplication = mainApplication.replace(
        /package com.sparly.reactnative;/,
        `package com.sparly.reactnative;\n${RNSharePackageImport}`
    );
  }

  if (!mainApplication.includes(ShareApplicationImport)) {
    mainApplication = mainApplication.replace(
        /package com.sparly.reactnative;/,
        `package com.sparly.reactnative;\n${ShareApplicationImport}`
    );
  }

  if (!mainApplication.includes(RNShareAddPackage)) {
    mainApplication = mainApplication.replace(
        /return packages;/,
        "\n    " + RNShareAddPackage + "\n    return packages;\n    "
    );
  }

  return mainApplication;
}

function applySettings(gradleSettings) {
  const RNShareSettings = `include ':react-native-share'
  project(':react-native-share').projectDir = new File(rootProject.projectDir,    '../node_modules/react-native-share/android')`;

  // Make sure the project does not have the settings already
  if (!gradleSettings.includes(`include ':react-native-share'`)) {
    return gradleSettings + RNShareSettings;
  }

  return gradleSettings;
}

function applyImplementation(appBuildGradle) {
  const RNShareImplementation = "implementation project(':react-native-share')";
  // Make sure the project does not have the dependency already
  if (!appBuildGradle.includes(RNShareImplementation)) {
    return appBuildGradle.replace(
        /dependencies\s?{/,
        "dependencies {\n    " + RNShareImplementation
    );
  }
  return appBuildGradle;
}

const withAndroidRNShare = function (expoConfig) {
  expoConfig = configPlugins.withMainApplication(expoConfig, function (config) {
    config.modResults.contents = applyPackage(config.modResults.contents);
    return config;
  });
  expoConfig = configPlugins.withAppBuildGradle(expoConfig, function (config) {
    config.modResults.contents = applyImplementation(
        config.modResults.contents
    );
    return config;
  });
  expoConfig = configPlugins.withSettingsGradle(expoConfig, function (config) {
    config.modResults.contents = applySettings(config.modResults.contents);
    return config;
  });
  return expoConfig;
};
exports["default"] = withAndroidRNShare;
`

**Comment by mikehardy** [comment]
I don't think a custom expo plugin is needed, unless there is no existing config plugin to add the android packages you want in query items 

https://developer.android.com/guide/topics/manifest/queries-element
https://react-native-share.github.io/react-native-share/docs/install#adding-queries-for-the-android-necessary-for-sdk--30

your plugin above is actually duplicating what auto-linking gets you for free, which results in two native modules in the android runtime at once which is why you get the error you get, and your config plugin is not a) defining queries as required b) attempting to do a file provider as an option which may be required c) attempting to add storage permission for base64 files (which may not be a good idea these days but I'm not sure, I don't use that feature)

I'm not sure why you wouldn't use https://docs.expo.dev/versions/latest/sdk/sharing/

**Comment by fendermany** [comment]
> I don't think a custom expo plugin is needed, unless there is no existing config plugin to add the android packages you want in query items

I tried to add query items. It's a little bit of changed behavior, but I really can't open Instagram stories from my app on Android.

```
const { withAndroidManifest } = require("@expo/config-plugins");

module.exports = function androidManifestPlugin(config) {
  return withAndroidManifest(config, async (config) => {
    let androidManifest = config.modResults.manifest;
    // androidManifest["queries"] = [
    //   ...androidManifest["queries"],
    //   packageVisibilityList,
    // ];

    androidManifest["uses-permission"] = [
      ...androidManifest["uses-permission"],
      obj,
    ];

    return config;
  });
};

let obj = {
  $: {
    "android:name": "android.permission.QUERY_ALL_PACKAGES",
  },
};

// const packageVisibilityList = [
//   {
//     intent: [
//       {
//         action: {
//           $: {
//             "android:name": "com.instagram.share.ADD_TO_STORY",
//           },
//         },
//         data: {
//           $: {
//             "android:mimeType": "image/*",
//           },
//         },
//       },
//     ],
//   },
//   {
//     intent: [
//       {
//         action: {
//           $: {
//             "android:name": "android.intent.action.SEND",
//           },
//         },
//         data: {
//           $: {
//             "android:mimeType": "image/*",
//           },
//         },
//       },
//     ],
//   },
//   {
//     package: {
//       $: {
//         "android:name": "com.instagram.android",
//       },
//     },
//   },
//   {
//     package: {
//       $: {
//         "android:name": "com.facebook.android",
//       },
//     },
//   },
//   {
//     package: {
//       $: {
//         "android:name": "com.facebook.katana",
//       },
//     },
//   },
//   {
//     package: {
//       $: {
//         "android:name": "com.twitter.android",
//       },
//     },
//   },
// ];
```

>I'm not sure why you wouldn't use https://docs.expo.dev/versions/latest/sdk/sharing/

Good idea. Thank you!

**Comment by naftalimurgor** [comment]
Hello,
Was this ever resolved?

**Comment by anthlasserre** [comment]
If you want to use it with an Expo managed workflow project. Here is a feature request to support the integration easily.

https://github.com/react-native-share/react-native-share/pull/1606
