### ISSUE TITLE
Using Share.shareSingle not working, it redirect to the app page in appstore, regardless of the app used

### ISSUE THREAD

**Issue by MarcHbb** [react-native-share/react-native-share#1253]
### Expected behaviour
Open share for specific app ( IG story, FB story ... )

### Actual behaviour
Redirect to app store page of the app I want to use, even if I already it, with it latest version

### Environment
- **React Native version**: 17.0.2
- **Expo**: SDK 45

### react-native-share
**Version**: 7.6.6

### Link to repo (highly encouraged)
https://github.com/wodin/RNShare

I want to mention that Share.open is working perfectly

**Comment by noitscassie** [comment]
Also seeing this issue running on a Pixel 5

**Comment by Xplosive06** [comment]
I have almost the same problem with Twitter. shareSingle is opening the Twitter app then crash. It's working perfectly on Android and perfectly with Share.open on both platforms.

I get this error:

```text
{
  "error": {
    "code": "ECOM.RNSHARE1",
    "domain": "com.rnshare",
    "message": "The operation couldn’t be completed. Not installed",
    "nativeStackIOS": [
      "0   myApp                            0x0000000102cd4ae0 RCTJSErrorFromCodeMessageAndNSError + 112",
      "1   myApp                            0x0000000102cd4a20 RCTJSErrorFromNSError + 256",
      "2   myApp                            0x0000000102c64f88 __41-[RCTModuleMethod processMethodSignature]_block_invoke_4.110 + 152",
      "3   myApp                            0x0000000102bb82cc -[GenericShare shareSingle:failureCallback:successCallback:serviceType:inAppBaseUrl:] + 2156",
      "4   myApp                            0x0000000102bbbb67 -[RNShare shareSingle:failureCallback:successCallback:] + 855",
      "5   CoreFoundation                      0x00000001119aa47c __invoking___ + 140",
      "6   CoreFoundation                      0x00000001119a7872 -[NSInvocation invoke] + 305",
      "7   CoreFoundation                      0x00000001119a7b05 -[NSInvocation invokeWithTarget:] + 70",
      "8   myApp                            0x0000000102c674e6 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2534",
      "9   myApp                            0x0000000102c6b97a _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 1402",
      "10  myApp                            0x0000000102c6b22c _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 156",
      "11  myApp                            0x0000000102c6b189 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25",
      "12  libdispatch.dylib                   0x0000000114993876 _dispatch_call_block_and_release + 12",
      "13  libdispatch.dylib                   0x0000000114994a56 _dispatch_client_callout + 8",
      "14  libdispatch.dylib                   0x00000001149a1e20 _dispatch_main_queue_callback_4CF + 1073",
      "15  CoreFoundation                      0x000000011191185d __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9",
      "16  CoreFoundation                      0x000000011190c0ba __CFRunLoopRun + 2772",
      "17  CoreFoundation                      0x000000011190b103 CFRunLoopRunSpecific + 567",
      "18  GraphicsServices                    0x00000001156e1cd3 GSEventRunModal + 139",
      "19  UIKitCore                           0x0000000126758e63 -[UIApplication _run] + 928",
      "20  UIKitCore                           0x000000012675da53 UIApplicationMain + 101",
      "21  myApp                            0x00000001026dde38 main + 104",
      "22  dyld                                0x000000010de47e1e start_sim + 10",
      "23  ???                                 0x0000000205a0351e 0x0 + 8684320030",
      "24  ???                                 0x00000002059fe000 0x0 + 8684298240"
    ],
    "userInfo": { "NSLocalizedFailureReason": "Not installed" }
  }
}
```

My [github issue](https://stackoverflow.com/questions/73203969/react-native-share-the-operation-couldn-t-be-completed-not-installed).

**Comment by Xplosive06** [comment]
So we found a workaround by changing a little piece of code in GenericShare.m from the package:

Line 20:

From that:

```swift
    if(![serviceType isEqualToString:@"com.apple.social.twitter"] && [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:inAppBaseUrl]]) {
```

To:
```swift
    if([serviceType isEqualToString:@"com.apple.social.twitter"] && [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:inAppBaseUrl]]) {
```
Just remove the exclamation mark after the if.

This is probably a temporary fix, but it works for now.

**Comment by DanKellyRedcat** [comment]
I am seeing the same or similar issue when trying to use SMS. If the phone has a different app set as the default messaging app then it just opens the Google Play store and shows 'Something went wrong. Try again' with a button that just refreshes to the same error. 

This is on a Samsung running Android version 12 which works fine if the Samsung Messages app is set to default

**Comment by vincent-odukwe** [comment]
Same issue with instagram
keeps opening the app store

**Comment by ushyDev** [comment]
Same issue with insta stories

**Comment by VictorGarcia** [comment]
Hi, in my case (I have an app developed with Expo, trying to share with Instagram on iOS) the problem why it was redirecting to the app store is that I had not whitelisted the URL schema for Instagram in Info.plist.

For expo you can do that through the `app.json` file:

`
"ios": {
      "infoPlist": {
        "LSApplicationQueriesSchemes": ["instagram", "instagram-stories"]
      },
`

Hope this helps :)

**Comment by ansh** [comment]
@VictorGarcia Thank you for this.

I was getting the `"NSLocalizedFailureReason": "Not installed",` error with the message ` "message": "The operation couldn’t be completed. Not installed",` but turns out I just had to add the scheme to `LSApplicationQueriesSchemes` just like you suggested!

**Comment by MarcHbb** [comment]
@VictorGarcia Thanks god ! 🔥

**Comment by bmitioglov** [comment]
@VictorGarcia man you are a genius, thank you so much!!!
