### ISSUE TITLE
shareSingle not working when sharing story to Instagram [Android]

### ISSUE THREAD

**Issue by Antonio-Melo** [react-native-share/react-native-share#1256]
### Steps to reproduce
1. Use share Share.shareSingle

### Expected behaviour
This was working before for me. Some users started reporting that they couldn't use the share. The normal flow is the app leaving the current screen and to open instragram with the story.

### Actual behaviour
Instead of going to Instagram, it opens a white screen and after a while either goes back to the app or crashes.

I imagine that this is something on Instagram side, since it was working for me and my code didn't change. Works on some devices tho

### Environment
- **React Native version**: 0.68.1
- **React Native platform + platform version**: I was able to replicate in Android 10. Target sdk verion: 31
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment? 4.4.4

### react-native-share
**Version**: npm version or "master": 7.6.6

**Comment by septpointdeux** [comment]
Hello, quite the same for me, it was working before on Android (still works on IOS)

It launches Instagram then Instagram crashes, if i only use the backgroundImage it works, but with an additional sticker (that worked before) it crashes.

note : I have seen that my Instagram app has been updated the first august, i suspect this is it.
Moreover in the official documentation, i do not remember to had seen : 

```
String sourceApplication = "com.my.app";
the intent.putExtra("source_application", sourceApplication);
```

Maybe it is now required by Instagram ?

React Native version: 0.68.1 
react-native-share: 7.6.6

**Comment by Antonio-Melo** [comment]
@septpointdeux I tried forking the repository and add the:
`intent.putExtra("source_application", sourceApplication);` inside the method _shareStory_ in the file `InstagramStoriesShare`, but it didn't fix the issue. Le me know if you find a solution for this

**Comment by aliceInWahed** [comment]
having the same issue. any updates on this?

**Comment by aliceInWahed** [comment]
hi @Antonio-Melo & @septpointdeux, after I added the `type: 'image/*'`, share to instagram is working fine.

```
Share.shareSingle({
      title: shareData.title,
      message: shareData.description,
      url: state.shareImage,
      subject: shareData.title,
      social: Share.Social.INSTAGRAM,
      type: 'image/*'  // required for sharing to INSTAGRAM
    });
```

Please refer to the documentation > https://react-native-share.github.io/react-native-share/docs/share-single#supported-options

**Comment by septpointdeux** [comment]
> hi @Antonio-Melo & @septpointdeux, after I added the `type: 'image/*'`, share to instagram is working fine.
> 
> ```
> Share.shareSingle({
>       title: shareData.title,
>       message: shareData.description,
>       url: state.shareImage,
>       subject: shareData.title,
>       social: Share.Social.INSTAGRAM,
>       type: 'image/*'  // required for sharing to INSTAGRAM
>     });
> ```
> 
> Please refer to the documentation > https://react-native-share.github.io/react-native-share/docs/share-single#supported-options
> 
> RN-share version - 7.8.0@latest

Your method concern sharing an instagram post, in this thread we speak about Instagram Story ;)

**Comment by septpointdeux** [comment]
I do not have crashes anymore ! I have not modified nothing.
I have just seen that my Redmi Note 10 had MiUI updated. Maybe it is related, no way to be sure.

**Comment by NikkiFremming** [comment]
I am having the same issue for sharing to instagram stories for android users - the app is opening to camera roll or google photos. Any update?

**Comment by mikehardy** [comment]
There are reports here that instagram apparently made a parameter mandatory (or started enforcing it, either way: a parameter that is now truly mandatory) and that a PR here might fix it.

There are reports that it fixed itself, perhaps with another Instagram app update.

I'm not sure what action needs to be taken, but the action items are either 1) post a PR to send the new mandatory parameter and verify on a device that is currently crashing that it no longer crashes or 2) confirm that the Instagram app will stop crashing in new updates via some sort of link to instagram release notes or similar

There are no secret updates though, if you think "I want to ask for updates", think instead "I will research and post the update I want, with some new information or test result that will advance the issue, or I will just post a reaction on the issue, subscribe to it using the button on the right, and wait so I don't generate notifications for everyone that do not contain actionable info"

**Comment by umeshbhati2022** [comment]
any update regarding this issue please inform??

**Comment by mikehardy** [comment]
@umeshbhati2022 this is an open source repository, that means you are the developer not the user. You are on the development team of the module. Welcome! There will be updates as and when developers (could be you!) do what I mention:

>  the action items are either 1) post a PR to send the new mandatory parameter and verify on a device that is currently crashing that it no longer crashes or 2) confirm that the Instagram app will stop crashing in new updates via some sort of link to instagram release notes or similar

And as I mention explicitly:

> There are no secret updates though, if you think "I want to ask for updates", think instead "I will research and post the update I want, with some new information or test result that will advance the issue, or I will just post a reaction on the issue, subscribe to it using the button on the right, and wait so I don't generate notifications for everyone that do not contain actionable info"

You seem to have ignored that completely, and generated content-free notifications for everyone.

**Comment by umeshbhati2022** [comment]
Hii @mikehardy &  sorry for my above comment 

but when i open the instagram app with share.open method (here working fine as expected result) than after when i share the content (img or video in base64 format) via shareSingle method as instagram story that working fine with a some frequent white screen comes between navigation to instagram story from my app in android.

# Environment

### React Native version: "0.66.1",
###  react-natve-share: '7.3.2"
### sdk versions:
        [minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30]



actualy i am new  for how to  handle native api of an particular os in react native  and collaborating to open source
so if you know a good and in depth knowledge resource regarding to how to work with native api.
please guide or share that resources link

**Comment by mikehardy** [comment]
Interesting - okay, those are old versions - react-native is 0.70.1 / react-native-share is 7.9.0, so reproducing this in current versions would be useful. Also, I cannot understand from your description what the *exact* steps to reproduce are. Ideally with a code snippet demonstrating the API usage and when the unwanted things happen 

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by serdarsg** [comment]
I used example project to reproduce, 
```
  const shareOptions = {
     title: 'Share image to instastory',
     backgroundImage:"https://www.setaswall.com/wp-content/uploads/2017/10/Colorful-Sky-Wallpaper-720x1280.jpg",
     social: Share.Social.INSTAGRAM_STORIES,
     appId: '****',
      stickerImage:"https://images.wallpapersden.com/image/wxl-4k-beautiful-landscape-digital-art_73919.jpg"
     };

```
It doesnt work in my android device.

With the same project, same device, I only switched backgroundImage and stickerImage with base64 instead of image link. Btw, I converted the same files to base64, because I wanted to be sure about it's not about image size, type etc. It works. I couldn't find why it happened, because in the [docs](https://react-native-share.github.io/react-native-share/docs/share-single/)

`stickerImage: 'data:image/png;base64,<imageInBase64>', //or you can use "data:" link
`
I tried to use in various configurations but I couldn't be sucessfull when i pass url link directly. So if your app is working correctly, with image url options. Could you share with us please.

**Comment by OskarEichler** [comment]
We are facing the same issue - latest version of react-native 0.70.4 and react-native-share 8.0.0

```
                  Share.shareSingle({
                    backgroundImage: uri,
                    backgroundBottomColor: '#121212',
                    backgroundTopColor: '#6AA4E0',
                    attributionURL: 'https://songstats.com',
                    social: Share.Social.INSTAGRAM_STORIES,
                    appId: 'xxxx',
                  })
```

iOS works perfectly, and Facebook works on Android - however Instagram Stories on Android just opens a white instagram app and immediately returns. Any clues are highly appreciated!

**Comment by OskarEichler** [comment]
Update: This seems to be an issue with Instagram on Android 13!!

https://developers.facebook.com/community/threads/427404476078182/

I just tested on Android 12 and the exact same code works just fine. Probably an issue that Instagram needs to fix on their end!

**Comment by dydent** [comment]
Hi :D 

Has anyone updates on this?

**Comment by sleekLancelot** [comment]
appending "data:image/png;base64," to the base 64 string and passing it to the uri key solved the issue on android for me.

this is my code:
```
try {
            if (Platform.OS === 'android') {
                const isInstalled = await checkIfInstagramIsInstalled()
    
                if (!isInstalled) {
                    return
                }
            }

            const shareOptions = {
                url: `data:image/png;base64,${base64String}`,
                title: 'Instagram post',
                message: caption,
                subject: 'Instagram post',
                social: Share.Social.INSTAGRAM,
                type: 'image/*',
            };

            const shareResponse = await Share.shareSingle(shareOptions);
        } catch (error) {
            console.log('Error sharing to instagram:', error)
        }
```
