### ISSUE TITLE
React native base64 image and message share not working by sharing on Skype, Instagram

### ISSUE THREAD

**Issue by neonithya** [react-native-share/react-native-share#1259]
Expected behaviour
react-native-share in passing two params image url as base64 and text message.Trying to share these params on Skype, but only the image is sharing.Message text is not visible
Anyone have any idea so please help on this.

Environment
"react-native": "0.69.3",
 "react-native-share": "^7.6.6",
 "rn-fetch-blob": "^0.12.0"

 Here is my code

shareImageWithText() {
    let imagePath = null;
    RNFetchBlob.config({
      fileCache: true,
    })
      .fetch('GET', imgUrl)
      .then(resp => {
        // the image path you can use it directly with Image component
        imagePath = resp.path();
        return resp.readFile('base64');
      })
      .then(base64Data => {
        var imageUrl = 'data:image/png;base64,' + base64Data;
        let shareOptions = {
          title: 'image',
          message: webUrl,
          url: imageUrl,
          subject: 'Subject',
          type: "image/png"
        };
        Share.open(shareOptions)
          .then(res => {
            console.log(res);
          })
          .catch(err => {
            err && console.log(err);
          });
        // remove the file from storage
        return fs.unlink(imagePath);
      });
  }

**Comment by choijiho0021** [comment]
any solution?
exactly same issue to me....
