### ISSUE TITLE
Problems with bluetooth sharing: base64 - Android 

### ISSUE THREAD

**Issue by sdandois** [react-native-share/react-native-share#1262]
After sharing a base64 file by bluetooth, the promise is rejected.

### Steps to reproduce
1. Share a base64 file:

```js
import base64 from 'base-64';
import Share from 'react-native-share';

Share.open({
    url: 'data:text/plain;base64,' + base64.encode('Este es mi archivo favorito'),
    filename: 'mi-archivo',
    type: 'text/plain',
    title: 'Share',
})
    .catch(error => {
        console.log({ error })
    })

```

2. Choose "Bluetooth" option
3. Select device to share.

### Expected behaviour
The catch callback isn't called.

### Actual behaviour
When going back to the app, the catch callback is triggered.

error.message is `User did not share`

### Environment
- **React Native version**: 0.67.3
- **React Native platform + platform version**: Android 9
- **Typescript version** (if using typescript): only javascript

### react-native-share
**Version**: "7.8.0" 

### Link to repo (highly encouraged)
If I can, I'll add it later.

**Comment by mikehardy** [comment]
@chulanovskyi-bs  Using the `adb logcat` you should examine the output, to see what the platform is logging during the reproduction. In general though, there's not enough information here to troubleshoot and the original author does not seem to have an interest in determining root cause so it went stale
https://stackoverflow.com/help/how-to-ask

**Comment by iamjon** [comment]
@mikehardy I''m also having the same issue like @chulanovskyi-bs it was when attaching to email via uri

There was a ton of stuff in the logcat, I tried clearing it right before I clicked on the send button in the email client and cutting it off right after. 

I'm attaching two logcats, one that I filtered in the android studio to only show my app and the full log

I'll be very happy to continue debugging but I'm afraid I need a bit more direction.

Here is my logcat for the issue
[locat-full.txt](https://github.com/react-native-share/react-native-share/files/9810315/locat-full.txt)
[logcat-filtered.txt](https://github.com/react-native-share/react-native-share/files/9810314/logcat-filtered.txt)

**Comment by mikehardy** [comment]
Hey there -

Just pasting in the text using markdown formatting is easier, it doesn't require a download and spawn a text reader which isn't even possible when people trying to help you are mobile. This is the snippet

```

                                                                                                    java.lang.SecurityException: Permission Denial: reading cl.json.RNShareFileProvider uri content://com.priority_software.template.rnshare.fileprovider/rnshare_sdcard/storage/emulated/0/Android/data/com.priority_software.template/cache/Download/1227903166802.html from pid=8678, uid=1000 requires the provider be exported, or grantUriPermission()
                                                                                                    	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:832)
                                                                                                    	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:694)
                                                                                                    	at android.content.ContentProvider$Transport.query(ContentProvider.java:233)
                                                                                                    	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1179)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1143)
```

So you have a searchable error

 https://search.brave.com/search?q=java.lang.SecurityException%3A+Permission+Denial%3A+reading+cl.json.RNShareFileProvider+uri+content%3A%2F%2Fcom.priority_software.template.rnshare.fileprovider%2Frnshare_sdcard%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fcom.priority_software.template%2Fcache%2FDownload%2F1227903166802.html+from+pid%3D8678%2C+uid%3D1000+requires+the+provider+be+exported%2C+or+grantUriPermission()&source=desktop

https://stackoverflow.com/questions/70920104/java-lang-securityexception-permission-denial-cannot-get-file-from-uri

https://github.com/react-native-share/react-native-share/issues?q=is%3Aissue+java.lang.SecurityException+%3A+Permission+Denial%2C+cannot+get+file+from+URI+

https://github.com/react-native-share/react-native-share/issues/808

Looks like a tough one to crack. You asked for more direction, I would follow a path where you investigate the FileProvider definition in AndroidManifest from this module to make sure it is exported, I would also check the Intent that is constructed in the share and make sure it has all the flags required to grant URI permission to the receiving apps opening it. I would do all of this using the example app from this repo to make sure it was reproducible.

**Comment by iamjon** [comment]
@mikehardy thank you so much for your help. 
It seems when upgrading I didn't review the installation instructions properly and that was the cause of the share denial which as you said was in the AndroidManifest and the instructions are here for anyone who stumbles upon this from the internet:
https://react-native-share.github.io/react-native-share/docs/install

Unfortunately, while the Permission Denial exception is handled the behavior is still the same, I share a file with gmail it sends the file no problem but I still get "User did not share"

I think it might be related to the <queries> but I'm not too sure.


`
0-19 10:11:35.912  3148  5217 D EGL_emulation: app_time_stats: avg=498.82ms min=497.00ms max=499.93ms count=3
10-19 10:11:35.945   378   511 D AudioFlinger: mixer(0x7b0fd341fa70) throttle end: throttle time(36)
10-19 10:11:35.981  3148  3148 W auct    : START TRACE Compose Send <877422c0d6f07c7d00000183ef15542d>@3795571.711639
10-19 10:11:35.992   355   355 D goldfish-address-space: claimShared: Ask to claim region [0x3f645c000 0x3f6a88000]
10-19 10:11:36.009   381   381 I BpBinder: onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
10-19 10:11:36.027  3148  7001 W Gmail   : Gmail:No collectionId found for event forward
10-19 10:11:36.028  3148  7001 W Gmail   : Gmail:No itemId found for event forward
10-19 10:11:36.028  3148  7001 W Gmail   : Gmail:No collectionId found for event forward
10-19 10:11:36.028  3148  7001 W Gmail   : Gmail:No itemId found for event forward
10-19 10:11:36.033  3148  3193 D StrictMode: StrictMode policy violation: android.os.strictmode.DiskReadViolation
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1199)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1000)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:145)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.content.ContentResolver.query(ContentResolver.java:1238)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.content.ContentResolver.query(ContentResolver.java:1151)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.content.ContentResolver.query(ContentResolver.java:1107)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at cnd.i(PG:3)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at cnd.a(Unknown Source:11)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at com.android.emailcommon.provider.Mailbox.b(PG:4)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at com.android.emailcommon.provider.Mailbox.h(PG:1)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at com.android.email.provider.EmailProvider.Z(PG:1)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at com.android.email.provider.EmailProvider.call(PG:27)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.content.ContentProvider.call(ContentProvider.java:2464)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.content.ContentProvider$Transport.call(ContentProvider.java:512)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.content.ContentResolver.call(ContentResolver.java:2450)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at android.content.ContentResolver.call(ContentResolver.java:2430)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at dye.e(PG:2)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at dyc.a(PG:2)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at aunx.d(PG:1)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at auio.run(PG:6)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at vfy.run(PG:4)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at vfn.run(Unknown Source:7)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at vfi.run(Unknown Source:7)
10-19 10:11:36.033  3148  3193 D StrictMode: 	at java.lang.Thread.run(Thread.java:920)

`

**Comment by mikehardy** [comment]
That's a separate issue, difficult to resolve, you can search the list for it. In general just trust the user did what they want and move on after giving them the opportunity

**Comment by iamjon** [comment]
@mikehardy I think I did find something while debugging this which seems to be at the root of of both my issue and the initial one.

When debugging I put a break point here:
`// removed @Override temporarily just to get it working on different versions of RN
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == SHARE_REQUEST_CODE) {
            if (resultCode == Activity.RESULT_CANCELED) {
                TargetChosenReceiver.sendCallback(true, false, "CANCELED");
            } else if (resultCode == Activity.RESULT_OK) {
                TargetChosenReceiver.sendCallback(true, true);
            }
        }
    }`

And no matter what, whether successful nor not it always returned cancelled.

[I checked on the web](https://www.google.com/search?q=RESULT_CANCELED+ACTION_SEND+site:stackoverflow.com&client=ubuntu&channel=fs&sxsrf=ALiCzsbgbdF6GjIBA9x0AinhJb_xJ-otDw:1666179628721&ei=LOJPY4m5K9D97_UP1aWiyAs&start=10&sa=N&ved=2ahUKEwiJ_5rnmuz6AhXQ_rsIHdWSCLkQ8NMDegQIKBAW&biw=1846&bih=1088&dpr=1)


And from what I can see as soon [ACTION_SEND](https://developer.android.com/reference/android/content/Intent#ACTION_SEND) has not output so using it with startActivityForResult will always return 0
