### ISSUE TITLE
Allow email sharing to use the default mail app

### ISSUE THREAD

**Issue by higgsboz-beam** [react-native-share/react-native-share#1264]
## Describe the Feature
Ideally, when choosing `Share.Social.Email` for the `shareSingle` share option, it will link out to the **default** mail app for the user. On iOS for example, if the user has Gmail as their default mail app and does not have an account on the native mail app, nothing happens when `shareSingle` is called.

**Comment by xavax31** [comment]
Same case, this returns an error:
'The operation couldn’t be completed. Mail services are not available'
