### ISSUE TITLE
Incorrect/missing documentation for iOS sharing with text message?

### ISSUE THREAD

**Issue by rolfb** [react-native-share/react-native-share#1266]
In the documentation for [iOS](https://react-native-share.github.io/react-native-share/docs/share-open) there might be two issues.

1. Doesn't specify adding `sms` to `LSApplicationQueriesSchemes`, which it probably needs to for SMS/iMessage? I could be wrong on this.
2. If `messages` is set to `null` like docs specifies the message will actually be empty when shared to Messages, but if the whole key is removed it works fine. This could be just an issue with Share.open, not single sharing.

Before (message is shared as empty):
```javascript
{
  // For sharing text.
  placeholderItem: { type: 'text', content: message },
  item: {
    default: { type: 'text', content: message },
    message: null, // Specify no text to share via Messages app.
  },
  linkMetadata: {
    // For showing app icon on share preview.
    title: message,
  },
}
```

After (works):
```javascript
 {
  // For sharing text.
  placeholderItem: { type: 'text', content: message },
  item: {
    default: { type: 'text', content: message },
  },
  linkMetadata: {
    // For showing app icon on share preview.
    title: message,
  },
}
```

Hope it helps someone, sorry for not making a pull request at this time.

**Comment by vikas960188** [comment]
Hello Friend,
With single share on whatsapp - Image + caption is not working, do you have any solution for that?

**Comment by Robiullah2244** [comment]
Any solution?
