### ISSUE TITLE
 Is there an option for the text to be applied next to the app icon thumbnail? not "message" option

### ISSUE THREAD

**Issue by daheeahn** [react-native-share/react-native-share#1267]
Hi, I wanted to apply text to the red box, so I used the ```message``` option. Is there another option to change only the text that will be applied to that red box?

![스크린샷 2022-08-18 오후 5 32 13](https://user-images.githubusercontent.com/38369729/185349438-8df5fdb1-4449-4fe6-b406-9d6c9790d3a9.png)

**Comment by gfaraj** [comment]
I would also like to know if there's a way to customize that. It says "Plain Text and 1 link" currently for me.

**Comment by gfaraj** [comment]
@daheeahn did you ever find out?
