### ISSUE TITLE
Share.shareSingle Social.Telegram does not work on Android if user is not logged in

### ISSUE THREAD

**Issue by gabrieldonadel** [react-native-share/react-native-share#1270]
### Steps to reproduce
1. On an Android device make sure you have telegram installed
2. Logout from your telegram account and close the telegram app
3. On the react-native app call `Share.shareSingle({ social: Social.Telegram, ... })`
4. Observe the telegram app not opening and no error being thrown 

### Expected behaviour

Either the telegram app should be opened or an error should be thrown 

### Actual behaviour

Telegram app does not open and no error is thrown 

### Environment
- **React Native version**: 0.68.2
- **React Native platform + platform version**: Android 12
- **Typescript version** (if using typescript): 4.7.4

### react-native-share
**Version**: 7.0.0

**Comment by gabrieldonadel** [comment]
Any updates on this?

**Comment by mikehardy** [comment]
Looks like it's not a popular use case. I'd suggest cracking open the module code in node_modules and instrumenting it + examining API inputs/outputs - self-service
