### ISSUE TITLE
How can we share image and link in WhatsApp/chat app

### ISSUE THREAD

**Issue by knightmate** [react-native-share/react-native-share#1273]
## Ask your Question

Hello team, i have tried multiple ways given in your documentation for sharing images with text/links in WhatsApp but I want not able to send them. I was able to send a link or image BUT when sending a link in a message props image is not being sent!
I want to send as below image
If anyone can help here please comment
 
![IMG_20220906_155448 (1)](https://user-images.githubusercontent.com/24593518/188635650-4d1dd4f4-82a8-47d6-87d7-718882992270.jpg)

**Comment by ivanichi** [comment]
looks like base64 is not shipped intact or related to file size. i have the same problem

**Comment by mikehardy** [comment]
What you are seeing @knightmate is what's called the "link preview" that whatsapp fetches dynamically *from* the link. There's a lot of information online about how to make your website respond to those, with what you want.

@ivanichi do you have observed facts you can demonstrate with a reproduction to back that assertion?

**Comment by ivanichi** [comment]
@mikehardy yes, i looked at the logs, for images with small size base64 like 2Kb or 7kb never show up, just output ( file.null ). for 10Kb 10490 chars, it can appear, and there also shows base64 code is not all transported in whatsapp, always truncated,  
![Screenshot_2596](https://user-images.githubusercontent.com/891930/190949281-f47acc53-62df-46ee-aa59-8789f62de0da.png)
![Screenshot_2598](https://user-images.githubusercontent.com/891930/190949306-e27dbd78-6927-470b-8cdc-9be044b89997.png)

**Comment by aleena-adnan1** [comment]
any luck in this ?

**Comment by abdelrahman11-rabie** [comment]
any updates  ?
