### ISSUE TITLE
Unable to share Text message in Instagram and Facebook

### ISSUE THREAD

**Issue by Sivakumar415** [react-native-share/react-native-share#1275]
When I try to share image along with text, only the image is shared in Instagram and Facebook, I am unable to share text message in Instagram and Facebook.

**Comment by mikehardy** [comment]
"Kindly do the needful"? :thinking: - that is...a confusing way to interact with an open source project where you yourself are actually the developer in concert with everyone else, not just a user.

https://stackoverflow.com/help/how-to-ask
https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

Kindly investigate more, provide more details, and ideally if you need a fix fast kindly provide a PR ?

**Comment by Sivakumar415** [comment]
Okay, Thanks
