### ISSUE TITLE
insta share not working for first time it redirected through social share once shared vai insta isInstalled is returned true otherwise false

### ISSUE THREAD

**Issue by dhruvpvx** [react-native-share/react-native-share#1278]
### Steps to reproduce
1.use Share.Single({}) and add instagram option
2.this will open social share option and when you choose instagram 
3. the next time it redirects to the instagram 

### Expected behaviour
const insta = 'com.instagram.android';
const {isInstalled} = await Share.isPackageInstalled(insta);
isInstalled to be true

### Actual behaviour
const insta = 'com.instagram.android';
const {isInstalled} = await Share.isPackageInstalled(insta);
isInstalled is false

### Environment
- **React Native version**: 0.66.1
- **React Native platform + platform version**: Android 11 and 12
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: 7.9.0

https://user-images.githubusercontent.com/59329978/191230594-855f466e-c109-4cd9-98e0-a54cc9e132dd.mp4

**Comment by mikehardy** [comment]
https://github.com/react-native-share/react-native-share/issues?q=is%3Aissue+use-query

https://github.com/react-native-share/react-native-share/issues/1009#issuecomment-824101426
