### ISSUE TITLE
Sharing a video to IG stories does not auto split it on iOS

### ISSUE THREAD

**Issue by KristineTrona** [react-native-share/react-native-share#1279]
### Expected behaviour
When sharing a video longer than 15 seconds to IG stories it should be automatically split into 15 second pieces (4 pieces max). 
This works correctly on Android, but not on iOS.

### Actual behaviour
On iOS the video is not auto split, which is already visible in the preview before posting and once posted the video shows only the first 15 seconds of it. 

If I download the same video on my device and share it directly from camera roll to IG stories, then it is split correctly.

### Environment
- **React Native version**: `0.63.2`
- **React Native platform + platform version**: iOS 15.6.1
- **Typescript version** (if using typescript): `3.9.7`

### react-native-share
**Version**: `7.9.0`

### Link to reproduction PR using the example app

https://github.com/react-native-share/react-native-share/pull/1280

**Comment by mikehardy** [comment]
Unfortunately, I don't see anything online about this being a supported feature of Instagram Stories.
They indicate clearly in their documentation that video is limited to 20 seconds: https://developers.facebook.com/docs/instagram/sharing-to-stories

If their app is doing anything else I would consider it undocumented, and it is unsurprising that it skews by platform, I'm not sure you'll be able to fix this.

The only documentation I can see is that apparently "Reels" are taking over but have a poorly-documented internal style, you might play with that as an alternative + future style? https://developers.facebook.com/docs/instagram-api/guides/content-publishing#reel-posts

**Comment by KristineTrona** [comment]
@mikehardy thank you for looking into this. We did a bit more investigation on this on our end and it seems that [IG is aware of this problem](https://developers.facebook.com/support/bugs/2460738884231389/) and has chosen to not fix it for now. We have raised the issue again with them and hope they will implement support for it in the future, but for now I am closing this issue.
