### ISSUE TITLE
How to share [AirDrop ONLY] ?

### ISSUE THREAD

**Issue by Soul-Clinic** [react-native-share/react-native-share#1281]
![Photo 3](https://user-images.githubusercontent.com/5283548/191846504-59289202-eaea-41ed-af0a-c0087783740b.jpeg)

How can I remove other options(including Copy Photo/Add to Album), and keep Air Drop only in iOS? 
I think this is the solution but it's with Swift, I'm using React Native:  
https://stackoverflow.com/questions/28607781/share-via-airdrop-only

**Comment by mikehardy** [comment]
Hi there! If you would like an airdrop-only feature in this module, and it does not exist already, you'll need to make a pull request that implements that feature (using similar APIs, but in objective-c here) and exposes it in the javascript layer so you may use it in react-native

There are other examples of new features which you may use as a guide - here is one - do not be afraid of the amount of code, if you actually look at it, you will see almost all of it is boilerplate, and easy to understand and it is highly likely that if this is a feature you need and you want to do it, you can do it https://github.com/react-native-share/react-native-share/pull/761/files

**Comment by das-SOFT** [comment]
@Soul-Clinic Can You please share code for airdrop in react native. I want to do in my app.

Thanks in advance
