### ISSUE TITLE
Add SnapChat and Instagram sharing for iOS

### ISSUE THREAD

**Issue by hsw48** [react-native-share/react-native-share#1283]
Title says it all I think

**Comment by mikehardy** [comment]
On the contrary, with respect: PRs say it all
Issues are just wishes when they are feature requests...

**Comment by hsw48** [comment]
Was actually expecting someone to say I missed something in the documentation considering sharing via Snapchat and Instagram was added 4 years ago for Android. Good to know I wasn't mistaken though.

**Comment by mikehardy** [comment]
I see Instagram, but not Snapchat https://github.com/react-native-share/react-native-share/tree/main/ios

**Comment by hsw48** [comment]
https://github.com/react-native-share/react-native-share/pull/219

**Comment by hsw48** [comment]
You mean for iOS? This is PR from over 4 years ago https://github.com/react-native-share/react-native-share/pull/219

**Comment by mikehardy** [comment]
That PR appears to have died for lack of attention to required feedback (that is: fixing conflicts so it is merge-able)
I shared a link that in fact shows Instagram objects in the directly tree. But none for snapchat

**Comment by bhatvikrant** [comment]
Is there a way to share to Snapchat stories on IOS?
