### ISSUE TITLE
ERROR  Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by marina-contai** [react-native-share/react-native-share#1286]
When my app is on the targetSdkVersion = 31 plataform android, the method Share.open return this error:

Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE 
if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles."}

 my application dont use PendingIntent, someone have a idea for fix it?

Typescript = "^4.3.2" react-native:  react-native: 0.67.3

**Comment by mikehardy** [comment]
This does not happen with current versions, I use this library and target 31+

https://github.com/react-native-share/react-native-share/pull/1077

**Comment by bitfabrikken** [comment]
Just in case anyone also encounters this on Android.
I got this error too after upgrading react-native-share.
A full clean before build did the trick.

```
cd android
./gradlew clean
```
