### ISSUE TITLE
File Manager Option not available

### ISSUE THREAD

**Issue by Czino** [react-native-share/react-native-share#1293]
### Steps to reproduce
I'm using this bit of code
```
Share.open({
  title: destinationFileName,
  url: `file://${RNFS.DocumentDirectoryPath}/${destinationFileName}`,
  subject: destinationFileName,
})
```

### Expected behaviour
Ability to store file on local file system

<img width="367" alt="image" src="https://user-images.githubusercontent.com/42438775/195842076-85efe8e9-8973-4341-a2bc-eb1176c73a9d.png">

### Actual behaviour
Android users (mostly GrapheneOS and CalyxOS) cannot see the option "File Manager" or "Copy to"

<img width="292" alt="image" src="https://user-images.githubusercontent.com/42438775/195841957-d6ccc62c-ff95-48fc-a2a1-c7792d65cd9a.png">

### Environment
- **React Native version**: `0.68.0`
- **React Native platform + platform version**: Android (random, mostly GrapheneOS, CalyxOS)
- **Typescript version**: `4.6.3`

### react-native-share
**Version**: `7.9.0`

**Comment by DavidInojosa** [comment]
I am also having this problem
