### ISSUE TITLE
Send Message  to Multiple Contacts through WhatsApp

### ISSUE THREAD

**Issue by ashknik** [react-native-share/react-native-share#1295]
## Describe the Feature
 const shareOptions = {
      title: 'Share via',
      message: `DEMO MESSAGE`,
      social: Share.Social.WHATSAPP,
       whatsAppNumber: "9199999999",  //Share to a single Number
    };

## Possible Implementations
 const shareOptions = {
      title: 'Share via',
      message: `DEMO MESSAGE`,
      social: Share.Social.WHATSAPP,
      whatsAppNumber: "9199999999,9199999999,9199999999",  //Allow Sharing to multiple Contacts
    };

## Related Issues
Currently works only for single number

**Comment by mikehardy** [comment]
Hey there!
The first question to answer is whether the WhatsApp APis actually support it or not, for a few feature requests here it is actually just not possible, so check in to that first.

Second question is: are you willing to implement it? Someone that needs the feature will have to develop the feature, stated differently: if it is possible and you need it you will probably need to post the PR yourself. This module merges+releases things really quickly though!
