### ISSUE TITLE
Having Issues w/ Sharing To Facebook & Copying Text

### ISSUE THREAD

**Issue by natealmeida185** [react-native-share/react-native-share#1297]
How do I prevent the Share menu from closing when a user clicks the copy text button?

Also when sharing text and an image on Facebook, the text is not being displayed for the user to post, only the image. 
- this must be a bug or feature that should be implemented.
- currently testing on **Android**

**Comment by mikehardy** [comment]
https://stackoverflow.com/help/how-to-ask (mixing issues in one issue is usually not good, there are not many details here, like versions of software in use, versions of things in execution environment)

https://stackoverflow.com/help/minimal-reproducible-example (exact steps to reproduce, code if possible)
