### ISSUE TITLE
Share.open() not showing message within a Facebook News Feed Post

### ISSUE THREAD

**Issue by natealmeida185** [react-native-share/react-native-share#1300]
### Steps to reproduce:
1. Use Share.open()
1. Share message and URL image to Facebook News Feed
2. News feed post is generated and the message is not there (only the image)

### Expected behaviour:
Both the message and URL passed into the shareOptions should be displayed in a News Feed Post on Facebook

### Actual behaviour:
Only the URL image being passed as a shareOptions is being created within the Facebook News Feed Post on Facebook

### Environment:
- **React Native version**: **18**
- **React Native platform: **Android, v.11**

### react-native-share:
**Version**: ^7.9.0

Code:
<img width="1012" alt="Capture" src="https://user-images.githubusercontent.com/70350322/196953370-4a26f22b-d477-415a-8191-3c392b5e744e.PNG">

**Comment by mikehardy** [comment]
Hey @natealmeida185 :wave: !
What did you see when you reached in to node_modules to add some inputs / outputs logging for the methods you are using in the javascript, and same in the android Java code to add some System.err.println (visible in `adb logcat` as app runs) statements with intputs and outputs for the APIs it calls to see how the data is flowing?
All the code's available it should be possible for you to quickly diagnose this and propose a PR if it affects you

**Comment by natealmeida185** [comment]
Hello Mike, could you please explain the steps to debug the javascript code? When I console.log my result in the .then(), it only prints when something is successfully shared. Which is an object that contains a successful field and a message which is undefined (which shouldn't be the case because message is set in my options).
The image is showing in my Facebook post but the message is not. This seems like a bug with react-native-share and my Android version.

**Comment by natealmeida185** [comment]
As far as the java code, I am unsure where I should be printing statements. Like the file name and such. Idk where that stuff is located for react-native-share

**Comment by mikehardy** [comment]
No, this isn't a use case of mine so it's not important to my business, and I'm out of volunteer time. You'll have to roll up your sleeves and figure it out, as I did when getting started. A bit time-consuming but useful knowledge to have
