### ISSUE TITLE
Expo iOS - Share.shareSingle crash without error

### ISSUE THREAD

**Issue by mgiorgi-github** [react-native-share/react-native-share#1302]
Hi,
i'm try to use react-native-share into Expo app, with Share.open all work fine but with Share.shareSingle the app crash without error into console, i use this options:

{
  social: Share.Social.INSTAGRAM,
  url: 'data:image/png;base64,<imageInBase64>',
  type: 'image/*'
}

The image is a base64 string.

I've added also LSApplicationQueriesSchemes into app.json:

    "ios": {
      "buildNumber": "1",
      "bundleIdentifier": "exposhare.demo.com",
      "supportsTablet": true,
      "infoPlist": {
        "LSApplicationQueriesSchemes": ["fb","facebook-stories","instagram", "instagram-stories"]
      }
    },

How can i do?
Thanks

**Comment by bhatvikrant** [comment]
I am also facing this issue

**Comment by adnandothussain** [comment]
Any update on it?
