### ISSUE TITLE
Android: share callback missing for Instagram

### ISSUE THREAD

**Issue by mgiorgi-github** [react-native-share/react-native-share#1303]
### Steps to reproduce
Share an image to Instragram app from Android device

### Expected behaviour
Bet onShare callback with "success: true"

### Actual behaviour
No callback

This is my share report:

**Android**

Facebook:
onShare:  Object {
  "message": undefined,
  "success": true,
}

Instagram: 
No callback

**iOS**

Facebook:
onShare:  Object {
  "message": "com.apple.UIKit.activity.PostToFacebook",
  "success": true,
}

Instagram:
onShare:  Object {
  "message": "com.burbn.instagram.shareextension",
  "success": true,
}

Is possible see a callback for Android-Instragram too?

Thanks

**Comment by roli5005** [comment]
Any news regarding this issue? It is still reproducing on Android
