### ISSUE TITLE
Developer wanted to enhance instagram / facebook stories share with app ID parameter

### ISSUE THREAD

**Issue by zerakacordo** [react-native-share/react-native-share#1304]
### Steps to reproduce
1. Share to Instagram or Facebook with Stories now requires Facebook App ID in their request as of October 2022.
2. Read at https://developers.facebook.com/docs/instagram/sharing-to-stories

### Expected behaviour
Should allow a parameter for Facebook APP ID.

### Actual behaviour
-

### Environment
-

### react-native-share
7.9.1

**Comment by mikehardy** [comment]
Happy to merge any + all reasonable PRs!

**Comment by mikehardy** [comment]
https://developers.facebook.com/blog/post/2022/10/10/introducing-important-update-to-Instagram-sharing-to-stories/

> All developers who have integrated previously without sending a Facebook App ID will need to make this change by no later than November 30, 2022, to avoid disruption to their integration with our platform. After November 30, 2022, users of your app will lose access to share your content to Instagram Stories if you have not implemented this change.

https://developers.facebook.com/docs/instagram/sharing-to-stories/

**Comment by ZerakPalani** [comment]
Thank you for the quick response! Thought I would share it here. If nobody gets it fixed I might try to create a PR to it, I am just not sure exactly how it works yet (I will look into all of the features I need for my app and try to create PRs so that everybody can have these).
