### ISSUE TITLE
ios shared url not showing preview image

### ISSUE THREAD

**Issue by tara-singh-danu** [react-native-share/react-native-share#1306]
### Steps to reproduce
let options = {
      title: "Test,
      url: shortLink,
    }

### Expected behaviour
It should display the preview image of url shared on the shared platform

### Actual behaviour
Not displaying the preview of url

### Environment
- **React Native version**:0.68.2
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: 7.9.1

**Comment by mattpilleul** [comment]
Hi ! Setting only url field will display image preview but combined with other params not currently working. Hope someone could check this feature !
