### ISSUE TITLE
Facebook app does not open when we use Share.singleshare on IOS

### ISSUE THREAD

**Issue by akinkarayun** [react-native-share/react-native-share#1307]
await Share.shareSingle({
       url: preview,  // URL HERE İS A CAPTURED IMAGE FROM APP
        social: Share.Social.FACEBOOK,
 })

Info.plist file

<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>whatsapp</string>
		<string>fb</string>
		<string>twitter</string>
		<string>instagram</string>
		<string>instagram-stories</string>
		<string>facebook-stories</string>
	</array>

### Expected behaviour
İt supposed to open the Facebook app but ıt does not
### Actual behaviour
 ıt redırect us to web browser

### Environment
- React Native version: 70+
- React Native platform + platform version: iOS 9.0+
- Typescript version: 3.8 +

### react-native-share
Version:latest

**Comment by akinkarayun** [comment]
Answering my own question

node_modules -> react-native-share -> ios -> GenericShare.m

just change the whole file with the code down below:


//
//  GenericShare.m
//  RNShare
//
//  Created by Diseño Uno BBCL on 23-07-16.
//  Copyright © 2016 Facebook. All rights reserved.
//

#import "GenericShare.h"

@implementation GenericShare
    RCT_EXPORT_MODULE();
- (void)shareSingle:(NSDictionary *)options
    failureCallback:(RCTResponseErrorBlock)failureCallback
    successCallback:(RCTResponseSenderBlock)successCallback
    serviceType:(NSString*)serviceType
    inAppBaseUrl:(NSString *)inAppBaseUrl {

    NSLog(@"Try open view");
    if([serviceType isEqualToString:@"com.apple.social.twitter"] && [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:inAppBaseUrl]]) {
        SLComposeViewController *composeController = [SLComposeViewController  composeViewControllerForServiceType:serviceType];

        NSURL *URL = [RCTConvert NSURL:options[@"url"]];
        if (URL) {
            if (URL.fileURL || [URL.scheme.lowercaseString isEqualToString:@"data"]) {
                NSError *error;
                NSData *data = [NSData dataWithContentsOfURL:URL
                                                     options:(NSDataReadingOptions)0
                                                       error:&error];
                if (!data) {
                    failureCallback(error);
                    return;
                }
                UIImage *image = [UIImage imageWithData: data];
                [composeController addImage:image];

            } else {
                [composeController addURL:URL];
            }
        }

        if ([options objectForKey:@"message"] && [options objectForKey:@"message"] != [NSNull null]) {
            NSString *text = [RCTConvert NSString:options[@"message"]];
            [composeController setInitialText:text];
        }


        UIViewController *ctrl = RCTPresentedViewController();
        [ctrl presentViewController:composeController animated:YES completion:Nil];
        successCallback(@[@true, @""]);
      }else if([serviceType isEqualToString:@"com.apple.social.facebook"] && [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:inAppBaseUrl]]) {
        SLComposeViewController *composeController = [SLComposeViewController  composeViewControllerForServiceType:serviceType];

        NSURL *URL = [RCTConvert NSURL:options[@"url"]];
        if (URL) {
            if (URL.fileURL || [URL.scheme.lowercaseString isEqualToString:@"data"]) {
                NSError *error;
                NSData *data = [NSData dataWithContentsOfURL:URL
                                                     options:(NSDataReadingOptions)0
                                                       error:&error];
                if (!data) {
                    failureCallback(error);
                    return;
                }
                UIImage *image = [UIImage imageWithData: data];
                [composeController addImage:image];

            } else {
                [composeController addURL:URL];
            }
        }

        if ([options objectForKey:@"message"] && [options objectForKey:@"message"] != [NSNull null]) {
            NSString *text = [RCTConvert NSString:options[@"message"]];
            [composeController setInitialText:text];
        }


        UIViewController *ctrl = RCTPresentedViewController();
        [ctrl presentViewController:composeController animated:YES completion:Nil];
        successCallback(@[@true, @""]);
      }
       else {

        NSString *errorMessage = @"Not installed";
        NSDictionary *userInfo = @{NSLocalizedFailureReasonErrorKey: NSLocalizedString(errorMessage, nil)};
        NSError *error = [NSError errorWithDomain:@"com.rnshare" code:1 userInfo:userInfo];

        NSLog(@"%@", errorMessage);
        failureCallback(error);

        NSString *escapedString = [options[@"message"] stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLHostAllowedCharacterSet]];

        if ([options[@"social"] isEqualToString:@"twitter"]) {        
          NSString *URL = [NSString stringWithFormat:@"https://itunes.apple.com/app/twitter/id333903271", escapedString, options[@"url"]];
          [self openScheme:URL];
        }

        if ([options[@"social"] isEqualToString:@"facebook"]) {   
          NSString *URL = [NSString stringWithFormat:@"https://itunes.apple.com/app/facebook/id284882215", options[@"url"]];
          [self openScheme:URL];
        }

      }
  }
  - (void)openScheme:(NSString *)scheme {
      UIApplication *application = [UIApplication sharedApplication];
      NSURL *schemeURL = [NSURL URLWithString:scheme];

      if ([application respondsToSelector:@selector(openURL:options:completionHandler:)]) {
          if (@available(iOS 10.0, *)) {
              [application openURL:schemeURL options:@{} completionHandler:nil];
          }
          NSLog(@"Open %@", schemeURL);
      }

  }

  @end


This is a temporary solutıon, I need the contrıbuters to check my answer and guıde me.

**Comment by mikehardy** [comment]
Hi there :wave: 

> Version:latest

"latest" is meaningless, versions change quickly - please specify the actual version in use

It helps to post your idea as a PR so the code changes are visible in context, linking to any available upstream / SDK documentation to explain why you propose to use the underlying APIs in some new way

**Comment by matthops** [comment]
> if([serviceType isEqualToString:@"com.apple.social.twitter"] && [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:inAppBaseUrl]]) {

Correct me if i'm wrong, but by removing the bang from the first part of this guard, are you not completely changing the purpose of this section of code?
