### ISSUE TITLE
Where can I get full Single share Documentation ?

### ISSUE THREAD

**Issue by amalmohann-dgnl** [react-native-share/react-native-share#1311]
The Documentation for the single share is not complete, 

https://react-native-share.github.io/react-native-share/docs/share-single/

it supports share to multiple apps, but only few of the configurations are added in the documentation.

can you complete the existing Documentation

**Comment by mikehardy** [comment]
Hi there! This is an open source repository, you are not just the user, you *are* the developer!

> can you complete the existing Documentation

We're not sure what the gaps are, but we're happy to merge any PR you post to complete the existing documentation
