### ISSUE TITLE
Update docs: User permission is required to save images to camera roll

### ISSUE THREAD

**Issue by paulbreslin** [react-native-share/react-native-share#1318]
## Describe the Feature
Docs should mention that a user's permission is required in order to save images to the camera roll. I spent a little while trying to figure out why that option wasn't appearing in the Share sheet, before realising permissions were the issue.

## Possible Implementations
Add a note about the required `Info.plist` keys, similar to the [react-native-camera-roll](https://github.com/react-native-cameraroll/react-native-cameraroll#usage) docs.

**Comment by mikehardy** [comment]
Please propose a PR for the same - it's about as fast as opening an issue... we can merge quickly
