### ISSUE TITLE
Does not return result object on Android

### ISSUE THREAD

**Issue by snikoletopoulos** [react-native-share/react-native-share#1324]
### Steps to reproduce
Share a link with Share.open

### Expected behaviour
Share returns the result with the action as message

### Actual behaviour
On iOS it works fine, on Android it returns an error "The User did not share" as soon as the modal opens up.

### Environment
- **React Native version**: 0.70.5
- **React Native platform + platform version**: Android
- **Typescript version** (if using typescript): 4.9.3

### react-native-share
**Version**: 8.0.0

**Comment by zgordon02** [comment]
I'm experiencing the same issue. On iOS I get the success response, but on Android my catch block runs regardless of the share's status

**Comment by mikehardy** [comment]
On Android there were some issues (you should search the issues here to confirm, please) where status was not reported *from the system APIs* correctly. So no return status on Android was reliable, all we could know was "share dialog *opened* successfully or not", we could not know whether the share itself was performed or to what app etc. So as long as there is not an error, take that to mean this and only this as signal vs noise: the share dialog opened

I think that's the best the Android platform allows. I am open to concrete evidence to the contrary based in experimentation using the native Android sharing APIs with instrumentation showing the results and return values from those APIs. That could form the basis of a successfully merged PR that alters android share return value behavior here

**Comment by nghiadqdev** [comment]
but my task has to check what app the user selects, any issues to fix it?

**Comment by mikehardy** [comment]
@nghiadqdev your comment reads to me like "I read your comment and I don't like it. I don't like the way the platform behaves, what can I do?". I don't know. Learn to like it (that is: by altering requirements), or do the exploratory work to prove my comment wrong with experimental evidence.
