### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNShare.FACEBOOK')

### ISSUE THREAD

**Issue by D0nVitalio** [react-native-share/react-native-share#1325]
### Steps to reproduce
1. expo init project1
2. npm start, then stop
3. npm i react-native-share
4. add one line to default code of project1 "import Share from 'react-native-share';"
5. npm start

### Environment
- **React Native version**: latest 0.70
- **React Native platform + platform version**: Android Virt Device Api30
- **Typescript version** (if using typescript): my Win10 runing tsc -v says no such program

npx expo -v 0.4.10
npm version 8.19.2

cmd.exe output:
Android Bundling complete 7223ms
 ERROR  TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNShare.FACEBOOK')
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by mikehardy** [comment]
So with Expo, you'll have to figure out how to build non-Expo native modules into the app. Otherwise when you go to use the non-Expo native module, it won't be there and you'll get null.

**Comment by sheldon-ouma-sudo** [comment]
how can you build non-Expo module for the react native share for expo specifically

**Comment by D0nVitalio** [comment]
did not solve it, so moved from Expo to React

**Comment by mikehardy** [comment]
Typically the implementation path is for someone to implement an Expo config plugin which makes the necessary native code/config mods to the Expo project's native files during build. Or you use Expo share. Or you don't use Expo. Config plugins are the thing nowadays though. No one has proposed a PR with one of those for here though, likely because Expo has it's own share module
