### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by ganjarpuja94** [react-native-share/react-native-share#1327]
Error Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles."

on React Native 0.66.3

 buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        excludeAppGlideModule = true
        supportLibVersion = "30.0.2"
        googlePlayServicesVersion = "17.0.0"
        firebaseMessagingVersion = "21.0.0"
        playServicesVersion = "17.0.0"
        androidMapsUtilsVersion = "2.2.3"
        ndkVersion = "21.4.7075529"

dependencies {

    def work_version = "2.8.0-alpha02"

    implementation("androidx.work:work-runtime:$work_version"){
        force = true
    }

**Comment by mikehardy** [comment]
Failure to search issues list prior to opening issue: https://github.com/react-native-share/react-native-share/issues?q=is%3Aissue+FLAG_IMMUTABLE

released a fix more than a year ago
