### ISSUE TITLE
it only open the app,  it doesn't share the url information

### ISSUE THREAD

**Issue by techday84** [react-native-share/react-native-share#1331]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen
If I click on whatsapp icon, this action calls  toShare.shareSingle(Object.assign(shareOptionsWhatsapp));  and It should will open the whatsapp app and will share the link that is inside shareOptionsWhatsapp.

### Actual behaviour
Tell us what happens instead
when I click on whatsapp icon, whatsapp is open but I don't share any url information. I check the url information in a console.log and the information is ok, but only whatsapp is opened. I don't see the url information on whatsapp.

### Environment
- **React Native version**: 
 "react": "18.1.0",
 "react-native": "0.70.5",

### react-native-share
**Version**: npm version or "master"
"react-native-share": "^7.9.0",

Hi! I don't know what is happenning because the code before it works. Now if I try to share a link on whatsapp, the app is opened but not shows the url that is on shareOptionWhatsapp.

 let shareOptionsWhatsapp = {
         title: "xxx",
         message: 'xxxx',
         url: 'https://www.google.com',
         social: "whatsapp",
       };
 <TouchableOpacity  onPress={()=>{
                   onCancel();
                   setTimeout(() => {
                     Share.shareSingle(Object.assign(shareOptionsWhatsapp));
                   },300);
                 }}>
                <Icon name="whatsapp"
              style={styles.whatsapp_icon}
            />
             </TouchableOpacity>

**Comment by techday84** [comment]
After upgrading to the android sdk version >=30, you will have to add the query parameter of all the apps you want to share to.

 <queries>
    <package android:name="com.google.android.youtube" />
    <package android:name="com.facebook.katana" />
    <package android:name="com.facebook.orca" />
    <package android:name="com.facebook.mlite" />
    <package android:name="com.facebook.lite" />
    <package android:name="org.telegram.messenger" />
    <package android:name="com.whatsapp" />
  </queries>
This code snipet is for istagram, telegram, facebook and whatsapp.

**Comment by VaibhavValere** [comment]
<queries>
    <package android:name="com.skype.raider" />
    <package android:name="com.twitter.android" />
  </queries>

**Comment by VaibhavValere** [comment]
For Skype and twitter
