### ISSUE TITLE
Not able to share image with message in iOS Whatsapp, Facebook

### ISSUE THREAD

**Issue by BajajSaajan** [react-native-share/react-native-share#1334]

**Comment by BajajSaajan** [comment]
ReactNativeBlobUtil.config({
        fileCache: true,
    })
        .fetch("GET", imageUrl)
        .then((resp) => {
            return resp.readFile("base64");
        })
        .then((base64Data) => {
            const image = "data:image/png;base64," + base64Data;
            let shareImage = {
                message: "Description " +  productName + "\n" + "\n" +  url,
                urls: [image],
            };
            Share.open(shareImage)
                .then((res) => {
                    console.log(res);
                })
                .catch((err) => {
                    err && console.log(err);
                });
        });

This is my above code. Imageurl is image url which is coming in the api response, converting into base64 and passing in share action options.

**Comment by mikehardy** [comment]
Have you searched the issues list? This is a duplicate of so many I think

**Comment by BajajSaajan** [comment]
@mikehardy I've seen the list. I'm able to share the image without message at the whatsapp but not with message.

**Comment by Samykills** [comment]
any update here? @BajajSaajan did u manage to make it work somehow ?

**Comment by BajajSaajan** [comment]
@Samykills Not yet. I'm sharing image without message. If you have any update let me know.

**Comment by akdj** [comment]
hello, issue not resolved, still cannot share image on Whatapp with singleShare -> it do a open native share menu with `.wai` file, that not singleShare should do
