### ISSUE TITLE
Can't able to figure out how to show image in dialog window with title, can anyone guide and suggest the solution?

### ISSUE THREAD

**Issue by ubaidimranofficial** [react-native-share/react-native-share#1338]
I'm using shareSingle for the extension but can't able to figure out how to show the preview image with the title.
![image](https://user-images.githubusercontent.com/79653852/209697012-f54eb1d0-2bd2-40e4-89f5-da123cee041b.png)

**Comment by LahmerIlyas** [comment]
Same thing here.

**Comment by alizaib1217** [comment]
Could you share your code snippet.

**Comment by panktiszluck** [comment]
Hi, setting `type: 'image/png'` fixed for me.
