### ISSUE TITLE
How to share plain text with instagram direct 

### ISSUE THREAD

**Issue by mathpal2021** [react-native-share/react-native-share#1340]
i am using this version (^8.0.1) of react-native-share for react-native both android and ios.. i am using this code for

 const shareOptions = {
      message: `share some text`,
      social: Share.Social.INSTAGRAM,
      url: 'instagram://share',
    };
    try {
      const ShareResponse = await Share.shareSingle(shareOptions);
      console.log('ShareResponse =>', ShareResponse);
    } catch (error) {
      console.log('Error =>', error);
    }

**but instagram direct not opeing. please help me.**

**Comment by gabrielfvf7** [comment]
I'm facing the same issue

**Comment by samdyra** [comment]
is there any workaround for this?
