### ISSUE TITLE
Can't able to share audio with IOS.

### ISSUE THREAD

**Issue by nitinf22labs** [react-native-share/react-native-share#1343]
### Steps to reproduce
1. Select audio url 
2. Convert it to base64
3. use **Share.shareSingle** and in url pass -> `'data:audio/mp3;base64,${AUDIO_BASE64}';` ( tried with `audio/mp3` and `audio/mpeg` )

### Expected behaviour
Audio should be share with base64

### Actual behaviour
Right now it's considering base64 as text

### Environment
- **React Native version**: 0.67.2

### react-native-share
**Version**: ^8.0.1

**Comment by benkhlifafahmi** [comment]
+1

**Comment by nitinf22labs** [comment]
@benkhlifafahmi  Solved in this PR
https://github.com/react-native-share/react-native-share/pull/1344
