### ISSUE TITLE
Share on instagram story doesn't work on Android

### ISSUE THREAD

**Issue by Pietro-Putelli** [react-native-share/react-native-share#1345]
In my React Native app I'm using the following code to share content on instagram stories.
On iOS, it works fine; however, on Android, it does not resolve the promise and does not display any error.

```
import { default as RNShare } from "react-native-share";

const shareOnInstagram = async (callback) => {
  const imageUrl =
    "https://images.unsplash.com/photo-1556035511-3168381ea4d4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1674&q=80";

  /* Download image using expo-file-system */
  const base64 = await downloadImage({ url: imageUrl, isBase64: true });

  const shareOptions = {
    backgroundImage: imageUrl,
    stickerImage: "data:image/png;base64," + base64,
    backgroundBottomColor: "#fefefe",
    backgroundTopColor: "#906df4",
    social: RNShare.Social.INSTAGRAM_STORIES,
    appId: META_API_KEY,
  };

  RNShare.shareSingle(shareOptions).catch((err) => {
    console.log(err);
  });

  callback();
};
```

Here's the specs:

```
"react-native": "^0.70.6"
"react-native-share": "^8.0.1"
```

**Comment by Svarto** [comment]
@Pietro-Putelli Did you find a solution to this? I have the same issue on Android.

**Comment by Pietro-Putelli** [comment]
Maybe try to check if the base64 image is not malformed, I don't know why but sometimes it can be.

**Comment by bhatvikrant** [comment]
I am also facing this

**Comment by Svarto** [comment]
Check that you have added the right intents, need to be added before building to I believe android manifest

**Comment by bhatvikrant** [comment]
@Svarto I'm using an expo managed app, anything for that?

**Comment by Svarto** [comment]
> @Svarto I'm using an expo managed app, anything for that?

I assume you are also using EAS build. Create a custom plugin, with something like this (this is just want I'm using, fixes it for Facebook, twitter and Instagram):

```
const { 
   AndroidConfig, 
   ConfigPlugin, 
   withAndroidManifest, 
 } = require("expo/config-plugins"); 
  
 // Use these imports in SDK 46 and lower 
 // import { AndroidConfig, ConfigPlugin, withAndroidManifest } from '@expo/config-plugins'; 
 // import { ExpoConfig } from '@expo/config-types'; 
  
 // Using helpers keeps error messages unified and helps cut down on XML format changes. 
 const { 
   addMetaDataItemToMainApplication, 
   getMainApplicationOrThrow, 
   writeAndroidManifestAsync, 
 } = AndroidConfig.Manifest; 
  
 // Write in the apps we want to shareSingle to inside the Android manifest 
 // to give them visibility after privacy updates to Android 12 
 module.exports = config => { 
   return withAndroidManifest(config, async config => { 
     config.modResults = await setCustomConfigAsync(config, config.modResults); 
     return config; 
   }); 
 }; 
  
 // Splitting this function out of the mod makes it easier to test. 
 async function setCustomConfigAsync(config, androidManifest) { 
   androidManifest.manifest.queries[0].package = [ 
     { $: { "android:name": "com.instagram.android" } }, 
     { $: { "android:name": "com.twitter.android" } }, 
     { $: { "android:name": "com.facebook.katana" } }, 
   ]; 
  
   return androidManifest; 
 }
```

**Comment by bhatvikrant** [comment]
I was actually getting the error message: `Value for backgroundImage cannot be cast from Double to String`
And doing this solved it for me: 

Step 1: Converted the image to base64 using some online tool and stored it as a variable
```js
export const bgImage =
  "data:image/png;base64," + "iVBORw0KGgoAAAANSUhEUgAAAtAAAAUACAYAAABuzmU9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAA ................"
```

Step 2: pass this `bgImage` variable to react-native-share's `backgroundImage`
```js
  await Share.shareSingle({
          appId: "", // NOTE: replace this app Id from your facebook developer account
          stickerImage: uri,

          social: Share.Social.INSTAGRAM_STORIES,
          backgroundBottomColor: "#1D1D1D",
          backgroundTopColor: "#1D1D1D",

          backgroundImage: bgImage, // <-- Important part
        });
```

**Comment by bhatvikrant** [comment]
@adnandothussain not sure about IG feed, but I got it working for IG stories.

**Comment by adnandothussain** [comment]
Can you please let me know how you implemented for stories?

**Comment by bhatvikrant** [comment]
@adnandothussain I actually wrote a blogpost explaining the entire process, [you can find the blog here.](https://vikrantbhat.hashnode.dev/a-step-by-step-guide-to-share-images-from-your-expo-react-native-app-to-instagram-stories)

**Comment by Pietro-Putelli** [comment]
Now I'm facing another problem, when I try to share on instagram, it open the photo library on Android.

**Comment by bibhuti9** [comment]
same issue for me : when I try to share on instagram, it open the photo library on Android.

**Comment by bibhuti9** [comment]
Add this queries into your androidManifset,xml file


 
     <queries>
      <package android:name="com.google.android.youtube" />
      <package android:name="com.facebook.katana" />
      <package android:name="com.facebook.orca" />
      <package android:name="com.facebook.mlite" />
      <package android:name="com.facebook.lite" />
      <package android:name="org.telegram.messenger" />
      <package android:name="com.whatsapp" />
      <package android:name="com.instagram.android" />
    </queries>

**Comment by Giasinit** [comment]
> Add this queries into your androidManifset,xml file
> 
> ```
>  <queries>
>   <package android:name="com.google.android.youtube" />
>   <package android:name="com.facebook.katana" />
>   <package android:name="com.facebook.orca" />
>   <package android:name="com.facebook.mlite" />
>   <package android:name="com.facebook.lite" />
>   <package android:name="org.telegram.messenger" />
>   <package android:name="com.whatsapp" />
>   <package android:name="com.instagram.android" />
> </queries>
> ```

I'm trying it

**Comment by Giasinit** [comment]
to fix it... every time the app doesn't find instagram... you need to have it open with "share.open" by selecting instagram story, so that your app can figure out instagram's existence... and then go back and click on the share story button you created for the app... and this time it should recognise it.
for now i don't know how to fix it automatically

**Comment by davidwinograd1** [comment]
Any updates on this?

**Comment by Giasinit** [comment]
Hi! I've actually found the solution, which you can see in this example repository I created: [https://github.com/GiaFlix/Spotify-lyrics-social-share-RN](https://github.com/GiaFlix/Spotify-lyrics-social-share-RN).

You basically need to copy and paste this file [https://github.com/GiaFlix/Spotify-lyrics-social-share-RN/blob/main/plug.js](https://github.com/GiaFlix/Spotify-lyrics-social-share-RN/blob/main/plug.js) into your project and add the plugin mentioned in the `app.json` file, which you can find here: [https://github.com/GiaFlix/Spotify-lyrics-social-share-RN/blob/main/app.json](https://github.com/GiaFlix/Spotify-lyrics-social-share-RN/blob/main/app.json).

If you want to be sure not to make any mistakes, simply follow what you see in my repository. 

In essence, your app needs to recognize the existence of certain apps, but you should specify them. If you look at `plug.js`, there are some packages I've included, which are the most well-known social media platforms. These should suffice, but if needed, you can add others.

If you follow these instructions, you should be able to resolve all your issues.

P.S. Please note that it doesn't work with iOS.

N.B. If I've helped you, I'd appreciate receiving a star on the repository.

**Comment by davidwinograd1** [comment]
> https://github.com/GiaFlix/Spotify-lyrics-social-share-RN/blob/main/app.json

Just tried this, but unfortunately it did not work. Still nothing happens when I click on my instagram stories button on Android.

**Comment by Giasinit** [comment]
@davidwinograd1 , could you share with me the code you've written to share Instagram stories? There might be a crucial element missing, namely the PNG in the sticker.

In the native code of the library, you can see that by default, the developers of this library have included only PNGs as stickers.

P.S. Please remember not to share your `appId` with me, but you will need it to make it work. In case of doubt, I'll assume you've done the `appId` correctly.

P.P.S. Just a reminder, to reply to me, you need to tag me, otherwise, I won't receive any notifications!

**Comment by davidwinograd1** [comment]
@Giasinit 

here is my code!

```
const shareToInstagramStories = async (bite) => {
    const shareOptions = {
      backgroundVideo: bite.url,
      type: 'video/mp4',
      social: Share.Social.INSTAGRAM_STORIES,
      appId: ...,
      forceDialog: true,
      useInternalStorage: true,
    };

    Share.shareSingle(shareOptions)
      .then((res) => {
        console.log(res);
      })
      .catch((err) => {
        console.error(err);
      });
  };
```

**Comment by Giasinit** [comment]
@davidwinograd1 give me an hour and a half to get home so I can check this bookshop

**Comment by Giasinit** [comment]
@davidwinograd1, are you certain about `type: 'video/mp4'`? I couldn't find any information regarding a 'type' attribute for Instagram sharing.

**Comment by Giasinit** [comment]
@davidwinograd1, are you sure that "stickerImage" isn't required? On line 53 of the library (https://github.com/react-native-share/react-native-share/blob/main/android/src/main/java/cl/json/social/InstagramStoriesShare.java), it mentions that an error is returned in its absence.

**Comment by Giasinit** [comment]
@davidwinograd1 have you solved?
