### ISSUE TITLE
Instagram Story share requires an appId based on Meta policy.

### ISSUE THREAD

**Issue by MarcHbb** [react-native-share/react-native-share#1347]
### Steps to reproduce
Use share single for Instargram story as describe in the documentation : https://react-native-share.github.io/react-native-share/docs/share-single

### Expected behaviour
Open Intragram app to share the story 

### Actual behaviour
Error message : Instagram Story share requires an appId based on Meta policy.

### Environment
- **React Native version**: 0.69.6
- **React Native platform + platform version**: IOS 16.1

### react-native-share
**Version**: ^8.1.0

### Link to repo (highly encouraged)
 https://react-native-share.github.io/react-native-share/docs/share-single

**Comment by Lg0gs** [comment]
@MarcHbb 
You just need to specify Facebook App ID
