### ISSUE TITLE
TouchableOpacity freeze for a second when share onPress

### ISSUE THREAD

**Issue by MarcHbb** [react-native-share/react-native-share#1349]
### Steps to reproduce

```

const shareToInstagramStory = async () => {
      const shareOptions = {
            backgroundImage: "urlToImg",
            stickerImage: img,
            attributionURL: 'http://deep-link-to-app', //in beta
            social: Share.Social.INSTAGRAM_STORIES,
            appId: "XXX"
        };

        try {
            const response = await Share.shareSingle(shareOptions);
        } catch (error) {
            console.log('Error =>', error);
        }
    };
    
return (
<TouchableOpacity activeOpacity={1}  onPress={shareToInstagramStory}>
    <Text>Share</Text>
</TouchableOpacity>
)
```

### Expected behaviour
TouchableOpacity get his default behaviour 

### Actual behaviour
TouchableOpacity freeze until the app redirect to Instagram. I need to hide it with **activeOpacity** so there's no UI bug.
Just wanted to know if it's a normal behaviour or if it happens to someone ? The code is not that big to make something freeze ...

### Environment
- **React Native version**: 0.69.0

### react-native-share
**Version**: master

**Comment by zispidd** [comment]
+1
