### ISSUE TITLE
Facebook shareSingle

### ISSUE THREAD

**Issue by MarcHbb** [react-native-share/react-native-share#1350]
## Ask your Question
Can you provide a facebook exemple for shareSingle ?

**Comment by mabarm** [comment]
Hi, A demo example

 const shareToFacebook = async () => {
    const shareOptions = {
      title: 'shareVia',
      // message: 'I am message',
      // caption: 'I am a caption',
      url: 'https://www.google.com/',
      social: Share.Social.FACEBOOK,
      // contentDescription: 'Facebook sharing is easy!',
      // quote: 'I am quote',
      type: 'url',
    };

    try {
      const ShareResponse = await Share.shareSingle(shareOptions);
      console.log('Responsefb =>', ShareResponse);
    } catch (error) {
      console.log('Error =>', error);
    }
  };
