### ISSUE TITLE
attributionURL doesn't work on iOS instagram story

### ISSUE THREAD

**Issue by Pietro-Putelli** [react-native-share/react-native-share#1354]
### Steps to reproduce

```
export const shareOnInstagram = async (sourceBase64, callback) => {
  const shareOptions = {
    backgroundImage: "https://..../source.png",
    stickerImage: "data:image/png;base64," + sourceBase64,
    social: RNShare.Social.INSTAGRAM_STORIES,
    appId: META_API_KEY,
    attributionURL: "http://www.google.com/"
  };

  RNShare.shareSingle(shareOptions)
    .then(callback)
    .catch((err) => {
      callback();
      console.log(err);
    });
};
```

### Expected behaviour

As mentioned in the documentation the expected behaviour is that the source once tapped on instagram stories it must show the attribution url I have set, but it does't work.

**On iOS, it shares the source and background, and all works well, but on Android, it doesn't even open Instagram.**

### Environment
- **React Native version**:  ^0.70.6,
- **React Native platform + platform version**: iOS 16.0

### react-native-share
**Version**: ^8.0.1

**Comment by Svarto** [comment]
attributionURL was documented to be deprecated by Instagram, it was a beta feature that is no longer available.

I have the same issue as you on Android, with the same setup as yours (except w/o the attributionURL), instagram stories is not opened on Android any longer.

**Comment by ebellumat** [comment]
There's some alternative to show links on Instagram Stories? I mean, it's 2024 and for the Spotify still working.

**Comment by Paul12pp** [comment]
any update?
