### ISSUE TITLE
How can I copy extra data to the clipboard (like the URL) to use it in instagram stories?

### ISSUE THREAD

**Issue by AlexRequelme** [react-native-share/react-native-share#1358]
## Ask your Question
How can I copy extra data to the clipboard (like the URL) to use it in Instagram stories?
To share on Instagram stories, the stickers are copied to the clipboard, when I copy the URL to the clipboard in the then() or finally() method of singleSghare() Instagram shows me a black screen.

**Comment by mannyuiux** [comment]
@alexrequelme did you find any solution for this? facing the same issue

**Comment by shimevaily** [comment]
any solution?

**Comment by AdePhil** [comment]
Check https://github.com/react-native-share/react-native-share/issues/1388#issuecomment-2337694021
