### ISSUE TITLE
Unable to open base64 image with Telegram

### ISSUE THREAD

**Issue by chhornponleu** [react-native-share/react-native-share#1359]
### Steps to reproduce
1. Call open with base64
```
Share.open({
    title: 'Checkout my photo',
    message: 'Checkout my photo',
    url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgA....'
});
```
2. Select telegram
3. Select contact to send to and then  click Send

_Then nothing happen_

### Expected behaviour
It should send image to selected contact on Telegram and then return to the app. 

_Sending via email, Facebook, ... works fine._

### Actual behaviour
The send now button is pressable, but no action triggered.

### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by mdibaiee** [comment]
We are experiencing the same issue, most apps work, but Telegram does not work with base64 files.
