### ISSUE TITLE
How to open pdf from server url?

### ISSUE THREAD

**Issue by naimur978** [react-native-share/react-native-share#1360]
How to open pdf using live URL (e.g. https://www.africau.edu/images/default/sample.pdf)?

I'm getting this message in the log: 
" err [Error: Failed to find configured root that contains /https:/www.africau.edu/images/default/sample.pdf]"

**Comment by MateusAndrade** [comment]
> How to open pdf using live URL (e.g. https://www.africau.edu/images/default/sample.pdf)?
> 
> I'm getting this message in the log: " err [Error: Failed to find configured root that contains /https:/www.africau.edu/images/default/sample.pdf]"

Before opening the PDF you will need to download it, you can use some libraries like rn-fetch-blob, etc. And then share the file/path to it.
