### ISSUE TITLE
Preview not showing anything on android

### ISSUE THREAD

**Issue by pierroo** [react-native-share/react-native-share#1365]
### Steps to reproduce
1. share.open with url + message
2. the share sheet will not display either text or img
3. strangely, once I finalized the share (by email for example), the message and image do appear in the content (from the app being shared to, not from the share sheet)

### Expected behaviour
I want to see both message and url img in the preview sheet

### Actual behaviour
Nothing visible except the platform where to share

### Environment
- **React Native version**: 0.69.7
- **React Native platform + platform version**: Android 13

### react-native-share
**Version**: 8.2.1

Weirdest thing is, once shared the image and message displays in final shared input (but not in the share sheet still)
PLUS, if I remove url then I can see the message in the preview.

The url is base64, properly formatted since we can see it once shared.

```
Share.open(
          {
            message: `Blabla hello world`,
            url: base64_img, // remove this, and the message can be previewed
           type: => tried 'image/png' / 'image.jpeg' / 'base64' to no avail
          },
        )
```

**Comment by anisurrahman072** [comment]
Any solution please @pierroo . Could you please help me. Facing same problem. Even file is not sharing

**Comment by pierroo** [comment]
Unfortunately no solution found yet...

**Comment by anisurrahman072** [comment]
Thanks bro for immediate update.
