### ISSUE TITLE
[iOS] Not opening Facebook app and bad URL when sharing base64 image

### ISSUE THREAD

**Issue by jeemercado** [react-native-share/react-native-share#1367]
On iOS, shareSingle to facebook does not open facebook app but opens browser instead
On iOS, shareSingle to facebook with image (base64) results to bad url

### Environment
- **React Native version**: 0.66.5
- **React Native platform + platform version**: iOS 16
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment? 3.9.10

### react-native-share
**Version**: 8.2.0

**Comment by arekm213** [comment]
I have same issue with react-native 0.68.6

**Comment by mikesunsky** [comment]
Did you resovle it ? i got the same error,  can you help me ?

**Comment by mikesunsky** [comment]
@jeemercado
