### ISSUE TITLE
IOS Crashing when calling method open() 🥶

### ISSUE THREAD

**Issue by thlindustries** [react-native-share/react-native-share#1371]
# **Description**
- My app just crash when I call the method open() and give me an error that I have no clue
- This could be a silly question/doubt but for some reason I'm not able to use Share from "react-native-share" neither from "react-native",
- I know that you guys might want to know more info and details so just ask me here and I'll provide, I can't share the project because its private
- I've tried to reproduce this error creating a brand new RN project and I wasn't able to do that (mysterious issue ... :()
- I'm not sure if it's related to it but I found this issue (no solutions yet)  [Issue](https://github.com/facebook/react-native/issues/33644) 

# **Some Info**
  - "react-native-share": "7.3.2"
  - "react-native": "0.61.5"
  - "react": "16.9.0"

[Podfile](https://gist.github.com/thlindustries/2a09525e9498d666935414f9d5d542b5)

```json
"dependencies": {
    "apollo-server-express": "2.14.1",
    "axios": "0.19.0",
    "axios-retry": "1.2.0",
    "batch-stream": "0.1.3",
    "body-parser": "1.18.3",
    "class-transformer": "0.2.0",
    "class-validator": "0.9.1",
    "compression": "1.7.3",
    "copyfiles": "2.1.0",
    "core-js": "3.0.0-beta.11",
    "cors": "2.8.5",
    "crypto-js": "^4.0.0",
    "dd-trace": "2.20.1",
    "dotenv": "6.1.0",
    "express": "4.16.4",
    "geolib": "2.0.24",
    "gerador-validador-cpf": "3.1.3",
    "graphql": "14.1.1",
    "i18n": "0.8.3",
    "iplocation": "6.1.0",
    "jsonschema": "1.2.4",
    "jsonwebtoken": "8.4.0",
    "lodash": "4.17.11",
    "lodash-contrib": "^4.1200.1",
    "lodash-move": "1.1.1",
    "logfmt": "^1.3.2",
    "memjs": "1.3.0",
    "moment": "2.22.2",
    "moment-timezone": "0.5.27",
    "mongoose": "5.3.13",
    "ms": "^2.1.2",
    "newrelic": "7.2.0",
    "oauth2-server": "^3.1.1",
    "reflect-metadata": "0.1.12",
    "routing-controllers": "0.7.7",
    "sanitize-html": "1.20.1",
    "semver": "5.6.0",
    "soap": "0.25.0",
    "ts-node": "8.10.2",
    "twilio": "3.24.0",
    "type-graphql": "0.17.6",
    "typedi": "0.8.0",
    "typeorm": "0.2.9",
    "typeorm-routing-controllers-extensions": "0.2.0",
    "typeorm-typedi-extensions": "0.2.1",
    "typescript": "3.9.5",
    "unleash-client": "^3.15.0",
    "winston": "^3.8.2"
  },
  "resolutions": {
    "mongodb": "3.1.10",
    "@types/mongodb": "3.6.10",
    "@types/express": "4.17.4",
    "@types/express-serve-static-core": "4.17.30"
  },
  "devDependencies": {
    "@types/i18n": "0.8.3",
    "@types/jest": "^27.4.0",
    "@types/jsonwebtoken": "8.3.0",
    "@types/lodash": "4.14.118",
    "@types/moment-timezone": "0.5.9",
    "@types/mongoose": "5.3.1",
    "@types/node": "8.0.19",
    "@typescript-eslint/eslint-plugin": "^5.9.1",
    "@typescript-eslint/parser": "^5.9.1",
    "apollo-boost": "^0.4.9",
    "cross-fetch": "^3.0.6",
    "eslint": "^8.6.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-prettier": "^4.0.0",
    "foreman": "3.0.1",
    "jest": "^27.5.1",
    "jest-sonar-reporter": "^2.0.0",
    "nodemon": "1.18.9",
    "prettier": "2.5.1",
    "rimraf": "2.6.2",
    "ts-jest": "^27.1.3",
    "tslint": "5.11.0"
  }
```
## Output of ***npx react-native info***
```sh
System:
    OS: macOS 12.5
    CPU: (10) x64 Apple M1 Pro
    Memory: 17.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.17.3 - ~/Desktop/git/br-raia-app-hybrid/native/node_modules/.bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 32, 33
      Build Tools: 28.0.3, 29.0.3, 30.0.2, 30.0.3, 33.0.0
      System Images: android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
```

## **Here is what I've already tried:**
  - Uninstalled and installed the latest version
  - Manual linking and auto linking
  - double checked the path dir and base64 file (this is not the problem cause when I just call the function to open with a string the same error happens)
    - tried `${filePath}` ;  `file://${filePath}` ; `file:/${filePath}`   (I'm pretty sure that this is not the problem)
 

 
## Some screenshots

_______________________________________________________________________________

#### This happens when I try to call the share function with a message (following the docs https://reactnative.dev/docs/0.61/share)

```ts
import {Share} from "react-native"
```

- function:
<img src="https://i.imgur.com/G7SwmMV.png" alt="A cute kitten" width="400"/>

- Error:
<img src="https://i.imgur.com/CHgdZ8y.png" alt="A cute kitten" width="400"/>
_______________________________________________________________________________

#### This happens when I try to call the open() method with a base64 file

- This is how I'm using the function:
<img src="https://i.imgur.com/axKNdzW.png" alt="A cute kitten" width="400"/>

- This is the bug:
<img src="https://i.imgur.com/w0EvYoQ.png" alt="A cute kitten" width="400"/>
_______________________________________________________________________________

#### This error also happens for me when I try to use the native share component

```ts
import {Share} from "react-native"
```

- function:
<img src="https://i.imgur.com/px0OQbV.png" alt="A cute kitten" width="400"/>

- Error:
<img src="https://i.imgur.com/cgUA0mA.png" alt="A cute kitten" width="400"/>
_______________________________________________________________________________

#### I'm trying to find some solution for this issue but until now I wasn't able to get through it and if someone have any clue I'll really appreciate your help

**Comment by thlindustries** [comment]
No solutions, no answers:

Github-actions: close issue 🤡

**Comment by anurag-dadheech** [comment]
Facing the same issue post upgrading to RN 0.71.7
