### ISSUE TITLE
title and subject ignored when sharing by email: only message

### ISSUE THREAD

**Issue by pierroo** [react-native-share/react-native-share#1372]
### Steps to reproduce
1. share.open
2. pick gmail for example
3. both the title and the content will take the "message" option, and completely ignore both "title" and "subject" option

### Expected behaviour
title of email should be title (or subject)

### Actual behaviour
mentioned in point 3
This happens on iOS ONLY

### Environment
- **React Native version**: 0.69.7
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: 8.2.1

### Link to repo (highly encouraged)
https://github.com/

**Comment by huonw** [comment]
This seems to depend on the email client:

- Apple Mail: the subject is set to the `subject` key, and the body is set to `message`, as expected ✅ 
- GMail, Spark: the subject and body are both set to `message` ❌
