### ISSUE TITLE
Facebook stories option instantly redirects to source application.

### ISSUE THREAD

**Issue by kanelloc** [react-native-share/react-native-share#1377]
### Steps to reproduce
1. Run the example application
2. Press `Share to FB story` button

### Expected behaviour
Should open the Facebook application and navigate the user to the story creation screen.

### Actual behaviour
Opens Facebook application but instantly re-opens `source` application

### Environment
- **React Native version**: 0.66.4
- **React Native platform + platform version**: iOS 16.3.1
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?: 4.2.4

### react-native-share
**Version**: "master"

### Screen recording
https://user-images.githubusercontent.com/17724315/227488785-111634e1-d26d-4ecc-ad7d-f2fbafd57546.mp4

**Comment by tallinndolls** [comment]
I had similar issue when I omitted the backgroundImage option. Maybe this helps.

**Comment by nscerrimt** [comment]
hi @kanelloc, I am experiencing the same issue, did you manage to get around this please?

**Comment by daniyalrathore14** [comment]
Any update on this??
its still not working on iOS

**Comment by shimevaily** [comment]
the same issue here, any solution?
