### ISSUE TITLE
Im using expo, and react-native 0.71.4, getting error: TypeError: Cannot read property 'FACEBOOK' of null, js engine: hermes

### ISSUE THREAD

**Issue by Danizoo** [react-native-share/react-native-share#1378]
### Steps to reproduce
1. Init an expo app
2. install react-native-share following installation guide: npm i react-native-share --save
3. run the app on expo go
4. import Share from "react-native-share";

### Expected behaviour
App should simply work. Nothing has been altered in the code except importing Share from react-native-share.
By installation guide, other than npm i react-native-share --save is required if using react-native >= 0.6. I'm using 0.71.4.

### Actual behaviour
App stops working, getting an error:
"TypeError: Cannot read property 'FACEBOOK' of null, js engine: hermes"

### Environment
- **React Native version: 0.71.4**:
- **React Native platform + platform version**: Android

### react-native-share
**Version**: 8.2.1

**Comment by mikehardy** [comment]
> run the app on expo go

Expo Go does not support native modules not already built in to Expo Go. It's in the documentation for Expo Go

**Comment by Danizoo** [comment]
Oh.... thank you.
So, if I'm using expo go to run and test my app, I simply can't use react-native-share?

Is there another way to run and test the app that will make it possible to use react-native-share?
If I'll make a standalone apk, will react-native-share work?

Thanks.

**Comment by fdacio** [comment]
i too got this same issue.

**Comment by fdacio** [comment]
I am also having this same issue

**Comment by farmstrong8** [comment]
@punjasin @fdacio you should use expo dev client if you want to use a package with native modules

**Comment by anthlasserre** [comment]
If you want to use it with an Expo managed workflow project. Here is a feature request to support the integration easily.

https://github.com/react-native-share/react-native-share/pull/1606
