### ISSUE TITLE
react native share ios image with text(caption) in whatsapp

### ISSUE THREAD

**Issue by subhahu-reddy** [react-native-share/react-native-share#1382]
Wanted to share image along with text but in ios WhatsApp I observed that I can share only one of both like if I share image URL and message then message take priority 

Please let me the know the way to achieve image with caption using react-native-share in whatsapp

**Comment by fadlimp** [comment]
need your advice to solve this problem. thanks

**Comment by Whitelotuscorp** [comment]
There is an any update on this issue?
Because same issue appears for me
When we share message + base64 image in iPhone Whatsapp only Message can send not image

**Comment by zunkraz** [comment]
same problem, i only can share one of both

**Comment by blyszcz** [comment]
> There is an any update on this issue? Because same issue appears for me When we share message + base64 image in iPhone Whatsapp only Message can send not image



> same problem, i only can share one of both

@zunkraz @Whitelotuscorp  @subhahu-reddy 
Could you kindly share the code for image sharing on WhatsApp? Currently, my functionality is limited to sharing text messages, even when I pass blob path to as `url`

**Comment by UTLgovindvarshney** [comment]
@blyszcz, facing same issue in my application as well, when sharing a image and a text over WhatsApp it's only sharing the text, any lead how to fix this?

**Comment by ya-nsh** [comment]
Here is the code snippet that makes use of react-native-view-shot package to capture the image of the JSX component and share it to other media platforms. Both the message and the picture is shared  for email, messages but only the message is visible for WhatsApp with no image

```javascript
 <Button
                    onPress={async () => {
                        ref.current.capture().then(async uri => {
                            const shareOptions = {
                                title: 'My Steps',
                                message: milestoneSharingMessage || '',
                                url: uri,
                            };

                            await Share.open(shareOptions);
                        });
                    }}>
```

**Comment by yashgada** [comment]
@UTLgovindvarshney Did you find a fix?

**Comment by keuvy** [comment]
it seems like I have the same problem with PDF

**Comment by sjonchhe** [comment]
has someone found any fix for this?

**Comment by ramssutharr** [comment]
facing similar issue

**Comment by BusyInfotech** [comment]
Not able to share only PDF using single share in iOS

**Comment by jy1989** [comment]
same problem in "react-native-share": "^9.4.1",

**Comment by vivek0046** [comment]
any update on this?

**Comment by heytonytan** [comment]
How did you even share image only? I was looking into the Objective-C code and only saw text and video sharing. Is it time to hack something together.. 😀

**Comment by KwanYee-RytBank** [comment]
hey all, did you find a workaround to this issue?
