### ISSUE TITLE
Share to Instagram Story and allow pasting a link

### ISSUE THREAD

**Issue by kandarpdave** [react-native-share/react-native-share#1388]
Hello,
(iOS) Is there a way to Share to Instagram Story, but also keep the copied url to Clipboard available so that user can paste as a Link on IG story? Sharing to IG story works, but, I believe, because pasteboard needs to be used, it overwrites the already copied url.

Edit: I've also tried using the sticker image with attributionURL. While it does make the sticker clickable in the "post story" mode, nothing happens once the story is published. Am I missing something?

**Comment by robert-go** [comment]
We can't do that
because IG uses information from Clipboard
https://developers.facebook.com/docs/instagram/sharing-to-stories/?locale=en_US#ios-developers

**Comment by luciilucii** [comment]
There's a workaround for that. in iOS you can set a timer to below 1 sec. After starting the share flow, you trigger that timer, then copy the link in the clipboard. 

it's not 100% reliable, especially on instagram app start, because it might trigger before

**Comment by wajahatshaw** [comment]
@kandarpdave I'm facing this issue when sharing to instagram story using my react native app
This error **the app you shared from doesn't currently support sharing to stories**

Is anyone aware of this error as i already added a Facebook App ID and Instagram ID in the wrapper function but no luck still getting this error. My code looks like this 

` const shareToInstagramStory = async () => {
    const shareOptions = {
      title: 'Share image to instastory',
      backgroundImage: images.image1,
      social: Share.Social.INSTAGRAM_STORIES,
      appId: '219376304', //instagram appId
    };

    try {
      const ShareResponse = await Share.shareSingle(shareOptions);
      console.log('Response =>', ShareResponse);
      setResult(JSON.stringify(ShareResponse, null, 2));
    } catch (error) {
      console.log('Error =>', error);
      setResult('error: '.concat(getErrorString(error)));
    }
  };`

**Comment by RafaelSassano** [comment]
Any advances here for Android?

**Comment by NiccoloCase** [comment]
@wajahatshaw have you found a solution? I have the same error message

**Comment by Daviddavidov98** [comment]
Looking for a solution here as well 🙌🏼

**Comment by Daviddavidov98** [comment]
> There's a workaround for that. in iOS you can set a timer to below 1 sec. After starting the share flow, you trigger that timer, then copy the link in the clipboard.
> 
> it's not 100% reliable, especially on instagram app start, because it might trigger before

Do you have a code snippet of this 🙏🏼

**Comment by ebellumat** [comment]
Ok, how to use this workaround?

**Comment by shimevaily** [comment]
any solution?

**Comment by suenacita1** [comment]
Wanted to check in here to see if others have found a solution or some sample code on the iOS workaround

**Comment by AdePhil** [comment]
You can use this in the component that handles the share. Listen to Appstate changes for the states inactive or background then copy the content you want to the clipboard. 

const [urlCopied, setUrlCopied] = useState(false);
  const appState = useRef(AppState.currentState);

  useEffect(() => {
    const subscription = AppState.addEventListener("change", (nextAppState) => {
      if (appState.current.match(/inactive|background/)) {
        console.log("App has gone to background");
        if (!urlCopied) {
          Clipboard.setString(websiteLink);
          setUrlCopied(true);
        }
      }
      appState.current = nextAppState;
    });

    return () => {
      subscription.remove();
    };
  }, [urlCopied]);

**Comment by shimevaily** [comment]
> You can use this in the component that handles the share. Listen to Appstate changes for the state inactive or background then copy the content you want to the clipboard.
> 
> ```ts
> const [urlCopied, setUrlCopied] = useState(false);
>   const appState = useRef(AppState.currentState);
> 
>   useEffect(() => {
>     const subscription = AppState.addEventListener("change", (nextAppState) => {
>       if (appState.current.match(/inactive|background/)) {
>         if (!urlCopied) {
>           Clipboard.setString(websiteLink);
>           setUrlCopied(true);
>         }
>       }
>       appState.current = nextAppState;
>     });
> 
>     return () => {
>       subscription.remove();
>     };
>   }, [urlCopied]);
> ```

this does not work for iphone

**Comment by Paul12pp** [comment]
any update?

**Comment by mikehardy** [comment]
https://medium.com/hackernoon/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b
