### ISSUE TITLE
Message + URL with Facebook Share don't work on IOS & Android

### ISSUE THREAD

**Issue by MatteoGauthier** [react-native-share/react-native-share#1392]
### Steps to reproduce
1. 
```js

  const shareOptions = {
    title: 'Share via',
    message: 'Messsage',
    url: sharedEntity.url,
    social: Share.Social.FACEBOOK,
    type: 'url',
  };

  try {
    await Share.shareSingle(shareOptions);
  } catch (error) {
    console.error(error);
  }
```

### Expected behaviour
Content field filled

### Actual behaviour

![image](https://user-images.githubusercontent.com/32040951/235639408-7123cf7c-1cae-4a66-bf21-9619a794bf89.png)

### Environment
```
 System:
    OS: macOS 12.5.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 19.21 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 107.0.1
    Safari: 15.6.1
  npmPackages:
    react-native: 0.70.8 => 0.70.8
```
### react-native-share
`7.9.1`

**Comment by mysport12** [comment]
I believe Facebook stopped allowing pre-population of the field and will only grab any hashtags in your message. Instagram goes even further and throws an error message if you try and share an image url with a message (working on a patch now for our specific use case).

**Comment by MatteoGauthier** [comment]
> I believe Facebook stopped allowing pre-population of the field and will only grab any hashtags in your message. Instagram goes even further and throws an error message if you try and share an image url with a message (working on a patch now for our specific use case).

Thanks for your reply, here is the article on the Facebook Developer website that confirm your thoughts https://developers.facebook.com/docs/apps/review/prefill

**Comment by pke** [comment]
That makes share functions completely useless. What are those companies thinking?

**Comment by ghmeec** [comment]
facebook the same issue, any work around this?

**Comment by sanyagoel** [comment]
same issue w me any fix?
