### ISSUE TITLE
Sharing a base64 Image breaks package

### ISSUE THREAD

**Issue by marcosrdz** [react-native-share/react-native-share#1393]
### Steps to reproduce
1. Get the toDataURL object from react-native-qrcode-svg
2. Pass it Share.open as:
 qrCode.current.toDataURL((data: string) => {
      const shareImageBase64 = {
        url: `data:image/png;base64,${data}`,
      };
      Share.open(shareImageBase64).catch((error: any) => console.log(error));
});

### Expected behaviour
Thumbnail preview generated and ability to share image or save image as in previous releases

### Actual behaviour
base64 is handled as literal string to share

### Environment
- React Native: 71.6:

### react-native-share
8.2.2

### Link to repo (highly encouraged)
https://github.com/BlueWallet/BlueWallet

**Comment by dtembo98** [comment]
Am facing a similar issue if not the same,
```
 "expo": "^47.0.0",
 "react-native-share": "^8.2.2",
 "react-native": "0.70.5"

const handleOnSharePress = async () => {
    try {
      const shareResult = await Share.shareSingle({
        social: Share.Social.INSTAGRAM,
        url: `data:image/png;base64,${photoUri}`,
        type: "image/*",
      })

      console.log("ShareResult ", shareResult)
      socket.emit("mobile:photoReceived", sessionId)
      navigation.navigate("MainFlow", {
        screen: "Coupon",
      })
    } catch (error) {
      console.log("Error", error)
    }
  }

 ```

**Comment by Vorob-Astronaut** [comment]
for me it also does not work. 
<img width="810" alt="Screenshot 2023-05-06 at 2 22 56 AM" src="https://user-images.githubusercontent.com/5957210/236588074-17042c91-f9cf-496b-abbb-c4521a747a67.png">

**Comment by jhsonmac** [comment]
Hello, any solution for this problem?
