### ISSUE TITLE
Facebook share is not working in iOS even after adding LSApplicationQueriesSchemes

### ISSUE THREAD

**Issue by jabirmhd** [react-native-share/react-native-share#1395]
### Steps to reproduce
1. Create sharing option with ``social: Share.Social.FACEBOOK``
2. Call ``Share.shareSingle`` with that option

```
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fb</string>
		<string>facebook</string>
		<string>facebook-stories</string>
		<string>mailto</string>
		<string>twitter</string>
		<string>instagram-stories</string>
		<string>instagram</string>
	</array>
```
I have Facebook app installed already.

### Expected behaviour
It should open the Facebook app's share dialog.

### Actual behaviour
It is opening Facebook URL in a browser.

`{"error": {"code": "ECOM.RNSHARE1", "domain": "com.rnshare", "message": "The operation couldn’t be completed. Not installed", "nativeStackIOS": ["0   Lounges                             0x0000000102bafbac RCTJSErrorFromCodeMessageAndNSError + 112", "1   Lounges                             0x0000000102bafafc RCTJSErrorFromNSError + 236", "2   Lounges                             0x0000000102b4c6d0 __41-[RCTModuleMethod processMethodSignature]_block_invoke_4.56 + 132", "3   Lounges                             0x0000000102a95cf8 -[GenericShare shareSingle:failureCallback:successCallback:serviceType:inAppBaseUrl:] + 1760", "4   Lounges                             0x0000000102a9973c -[RNShare shareSingle:failureCallback:successCallback:] + 328", "5   CoreFoundation                      0x00000001c28d7cf4 6A07CBE8-4F65-3DBC-B59D-C1A188A7B95D + 470260", "6   CoreFoundation                      0x00000001c2885d94 6A07CBE8-4F65-3DBC-B59D-C1A188A7B95D + 134548", "7   CoreFoundation                      0x00000001c28857ac 6A07CBE8-4F65-3DBC-B59D-C1A188A7B95D + 133036", "8   Lounges                             0x0000000102b4e6ec -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1808", "9   Lounges                             0x0000000102b525ec _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 1596", "10  Lounges                             0x0000000102b51de4 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 128", "11  Lounges                             0x0000000102b51d58 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28", "12  libdispatch.dylib                   0x00000001c9d2c320 B74732B5-D7FE-34A4-9346-41945701F020 + 8992", "13  libdispatch.dylib                   0x00000001c9d2deac B74732B5-D7FE-34A4-9346-41945701F020 + 16044", "14  libdispatch.dylib                   0x00000001c9d3c6a4 B74732B5-D7FE-34A4-9346-41945701F020 + 75428", "15  libdispatch.dylib                   0x00000001c9d3c2f4 _dispatch_main_queue_callback_4CF + 44", "16  CoreFoundation                      0x00000001c28fdd18 6A07CBE8-4F65-3DBC-B59D-C1A188A7B95D + 625944", "17  CoreFoundation                      0x00000001c28df650 6A07CBE8-4F65-3DBC-B59D-C1A188A7B95D + 501328", "18  CoreFoundation                      0x00000001c28e44dc CFRunLoopRunSpecific + 612", "19  GraphicsServices                    0x00000001fdb5035c GSEventRunModal + 164", "20  UIKitCore                           0x00000001c4c7037c B0858D8E-7220-37BF-873F-ECC2B0A358C3 + 3789692", "21  UIKitCore                           0x00000001c4c6ffe0 UIApplicationMain + 340", "22  Lounges                             0x00000001024895c4 main + 100", "23  dyld                                0x00000001e1d78dec 41605DC7-F412-37D1-B51B-FEE1A26701E9 + 89580"], "userInfo": {"NSLocalizedFailureReason": "Not installed"}}}`

### Environment
- **React Native version**: 0.71.7
- **React Native platform + platform version**: iOS 16.4.1
-  **Typescript version** : 4.8.4

### react-native-share
**Version**: 8.2.2

**Comment by lucianobracco-geojam** [comment]
the same is happening to me with instagram-stories

**Comment by ya-nsh** [comment]
Here is the code snippet that makes use of react-native-view-shot package to capture the image of the JSX component and share it to other media platforms. This works for email, messages but does not work for WhatsApp.

```javascript
 <Button
                    onPress={async () => {
                        ref.current.capture().then(async uri => {
                            const shareOptions = {
                                title: 'My Steps',
                                message: milestoneSharingMessage || '',
                                url: uri,
                            };

                            await Share.open(shareOptions);
                        });
                    }}>
```

**Comment by norbertsongin** [comment]
Having the same problem with facebook. Adding these doesn't seem to change anything https://github.com/react-native-share/react-native-share/issues/384#issuecomment-628746445

**Comment by joaolvcas** [comment]
same issue for both to me when.

**Comment by uhhhsoyan** [comment]
same issue for me

**Comment by uhhhsoyan** [comment]
For now I resolved this by downgrading from 9.2.3 to 7.9.1, with react-native 0.72.4. I did not test any other versions - we are in the process of a major upgrade of react native and various packages, and 7.9.1 is the version we used previously with no issue. The below payload works as expected on iOS after downgrading:

```js
const facebookShareOptions = {
      social: Social.Facebook,
      type: 'url',
      url: link,
    };
await Share.shareSingle(facebookShareOptions);
```

**Comment by Arjan-Zuidema** [comment]
Not stale, problem still exists

**Comment by gyhyfj** [comment]
same problem

**Comment by MorganDavid** [comment]
same problem

**Comment by omkar2737** [comment]
Same problem @norbertsongin can you look into this it opens url of facebook in safari

**Comment by raj1823** [comment]
Facing same issue even after adding instagram and instagram-stories to plist file. It only allows reels.

**Comment by ebellumat** [comment]
Facing the same issue here, Facebook in iOS opens Safari, stories work is intermitent. #1523

**Comment by lpjjj1222** [comment]
same problem

**Comment by Splicer97** [comment]
same problem

**Comment by khacbac** [comment]
same here

**Comment by sleep9** [comment]
same

**Comment by fekajin** [comment]
same issue still continues

**Comment by fedpre** [comment]
Experiencing the same issue on v12.0.3 when sharing to facebook it opens a url and not the app. facebook-stories works fine

**Comment by carlos3g** [comment]
same
