### ISSUE TITLE
Cannot read property 'FACEBOOK' of null

### ISSUE THREAD

**Issue by GovanDBT** [react-native-share/react-native-share#1398]
## How do i fix the "Cannot read property 'FACEBOOK' of null problem
i just installed react-native-share in my expo project version 0.71.8 and everytime i import it i get the error message i mentioned above. I tried reinstalling it again, check other sources for solutions but can't figure out what the problem is.

### How i installed it
npm install react-native-share (for android)

**Comment by priyanshi-zepto** [comment]
i am also facing the same issue

**Comment by GovanDBT** [comment]
I think it doesn't work on react-native expo (not completely sure) but I think that's the problem coz I'm using Expo-CLI.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by julianxlozano** [comment]
facing the same issue

**Comment by AndresdoSantos** [comment]
I have the same problem, using `Android` and `iOS`, also if using `.shareSingle()` or `.open()`

**Comment by RoshaanAli** [comment]
try this one
```
Share.shareSingle({
            title: "TITLE",
            message: "MESSAGE",
            url: "URL",
            social: Share.Social.FACEBOOK,
            type: 'url',
          })
        .then((res) => { console.log(res) })
        .catch((err) => { err && console.log(err); });
```
