### ISSUE TITLE
codegenSpec not being installed 

### ISSUE THREAD

**Issue by ViniciusUrias** [react-native-share/react-native-share#1403]
### Steps to reproduce
1. Install 9.0.0 version of react-native-share in a react-native "0.71.3" version

### Expected behaviour
Should install codegenSpec folder

### Actual behaviour
codegenSpec folder not being installed, what gives me build error

### Environment
- **React Native version**: 0.71.3
- **React Native platform + platform version**:  Android 12.0
- **Typescript version** 4.8.4

### react-native-share
**Version**:  9.0.0

**Comment by efstathiosntonas** [comment]
same here on rn 0.71.11

**Comment by hengkx** [comment]
same 0.72-rc6

**Comment by yberstad** [comment]
I also have the same issuen on 0.72-rc6

**Comment by ajiehatajie** [comment]
same in 0.71.11

**Comment by Soul-Clinic** [comment]
Same in 0.71.8 
But I copy the file(& folder, ./codegenSpec/NativeRNShare.ts) to node_modules/react-native-share/ , it works!

**Comment by MateusAndrade** [comment]
Do you know any details about it @zabojad ?

**Comment by zabojad** [comment]
@MateusAndrade the `codegenSpec` should definitively be part of the module to work correctly.

**Comment by MateusAndrade** [comment]
> @MateusAndrade I haven't checked how the publishing of this module works. Should the `codegenSpec` folder be listed in the [files node of the package.json](https://github.com/react-native-share/react-native-share/blob/main/package.json#L16) to be part of the npm module released?

Yes! I added it here: https://github.com/react-native-share/react-native-share/commit/9fdcd200bbb75a225c84a9c93447f5c3f6842dd1. This should trigger a hotfix release in some minutes.

**Comment by efstathiosntonas** [comment]
@MateusAndrade it works now, thanks.

**Comment by vieiramanda11** [comment]
Hey @MateusAndrade

I have a React Native app that has iOS and web versions. I'm rendering the share component only on iOS and it's building correctly but when I start my app on the web I'm still seeing these issues with codegenSpec:


```
ERROR in ./node_modules/react-native-share/lib/module/helpers/android.js:3
Module not found: Can't resolve '../../codegenSpec/NativeRNShare'
  1 | import { PermissionsAndroid } from 'react-native';
  2 | 
> 3 | import NativeRNShare from '../../codegenSpec/NativeRNShare';
  4 | import { getAndroidVersion } from './platform';
  5 | 
  6 | export async function checkAndroidPermissionsForUrls(urls: string[]) {

ERROR in ./node_modules/react-native-share/lib/module/index.js:1
Module not found: Can't resolve '../codegenSpec/NativeRNShare'
> 1 | import NativeRNShare from '../codegenSpec/NativeRNShare';
  2 | 
  3 | import Overlay from './components/Overlay';
  4 | import Sheet from './components/Sheet';
```
Versions on my app:

"react-native": "0.71.3",
 "expo": "^48.0.19",
 "react-native-share": "^9.2.1"

**Comment by zabojad** [comment]
I'm not sure about what should be done here to support the web target as well 🤔...

**Comment by zabojad** [comment]
@vieiramanda11 you were using `react-native-share@8.x` on web target before and it was working ?

**Comment by vieiramanda11** [comment]
> @vieiramanda11 you were using `react-native-share@8.x` on web target before and it was working ?

No, I installed this week for a new feature on my iOS app. It's not something that I want to use on the web it's just that is broken this version if I add it on the code :/

**Comment by vieiramanda11** [comment]
> @vieiramanda11 OK then why just not importing it if Platform == 'web' ?

This is what I'm currently doing. I'm not rendering the component which uses react-native-share on the web but still, I got this error that odegenSpec/NativeRNShare module is not found

**Comment by el-lsan** [comment]
I'm getting the same error using:

`"react-native-share": "9.4.1",`
`"react-native": "0.71.13",`

```
Unable to resolve module ../codegenSpec/NativeRNShare from /Users/ehsan/Documents/RNApp/node_modules/react-native-share/lib/commonjs/index.js: 

None of these files exist:
  * node_modules/react-native-share/lib/codegenSpec/NativeRNShare(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs)
  * node_modules/react-native-share/lib/codegenSpec/NativeRNShare/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.cjs|.native.cjs|.cjs)
  41 | });
  42 | exports.default = void 0;
> 43 | var _NativeRNShare = _interopRequireDefault(require("../codegenSpec/NativeRNShare"));
     |                                                      ^
  44 | var _Overlay = _interopRequireDefault(require("./components/Overlay"));
  45 | var _Sheet = _interopRequireDefault(require("./components/Sheet"));
  46 | var _Button = _interopRequireDefault(require("./components/Button"));

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```

![Simulator Screenshot - iPhone 13 - 2023-09-12 at 13 21 52](https://github.com/react-native-share/react-native-share/assets/1249548/c7abfc3b-12bb-4244-9aae-1744d40cbe0f)

**Comment by ghiculescualexandru** [comment]
This still happens on the latest version.

**Comment by hichemfantar** [comment]
I'm getting this problem on my unit tests with Jest

**Comment by sohaibrumi511** [comment]
it's **_"react-native-share": "^10.0.2"_** for me and it throws the error that metro couldn't find this package in the node-modules.

**Comment by XilinJia** [comment]
it's "react-native-share": "^10.0.2" for me and it throws the error that metro couldn't find this package in the node-modules.

Why is this closed?

**Comment by joshmohrer** [comment]
same here

**Comment by hichemfantar** [comment]
@MateusAndrade @zabojad should this be reopened or should a new issue be created?

**Comment by Fiszy** [comment]
Go into node_modules > react-native-share 

The copy codegenSpec folder and paste it into lib folder

Then reload your application then it will work

**Comment by Fiszy** [comment]
Go into node_modules > react-native-share

Then copy codegenSpec folder and paste it into lib folder

Then reload your application then it will work

**Comment by thongle12** [comment]
Still getting the errors
