### ISSUE TITLE
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found.

### ISSUE THREAD

**Issue by Oriole-Alex** [react-native-share/react-native-share#1414]
### Steps to reproduce
1. Fresh React Native 0.72.1 build and newArchEnabled=true
2. Instal react-native-share
3. run npm start
4. Console throws error and refuses to launch app
5. App launches without issue after removing react-native-share and running npm start again.

### Expected behaviour
App should load correctly.

### Actual behaviour
Error's on load with the following: 
"Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes"

AND

"error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
C:\ReactNative\fairartfair\node_modules\react-native-share\android\src\newarch\cl\json\RNShare.java:16: error: RNShare is not abstract and does not override abstract method getTypedExportedConstants() in NativeRNShareSpec public class RNShare extends NativeRNShareSpec { ^ C:\ReactNative\fairartfair\node_modules\react-native-share\android\src\newarch\cl\json\RNShare.java:32: error: getConstants() in RNShare cannot override getConstants() in NativeRNShareSpec public Map<String, Object> getConstants() { ^ overridden method is final Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. 2 errors FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':react-native-share:compileDebugJavaWithJavac'. > Compilation failed; see the compiler error output for details. * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 40s."

### Environment
- **React Native version**: 0.72.1
- **React Native platform + platform version**: Pixel 4XL - Android 13
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment? 4.8.4 (which is the default that comes in a fresh react-native install as of today).

### react-native-share
**Version**: 9.2.0

**Comment by sam-uraii** [comment]
Same Error?? In android...
worked fine in iOS...

**Comment by thienphuc718** [comment]
Fixed it by manually install the package on android using the docs: https://react-native-share.github.io/react-native-share/docs/install/#android-install

**Comment by Oriole-Alex** [comment]
Unfortunately just tried installing it again along with the manual steps for android without any lucky, with the error: 

error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
C:\ReactNative\fairartfair\node_modules\react-native-share\android\src\newarch\cl\json\RNShare.java:16: error: RNShare is not abstract and does not override abstract method getTypedExportedConstants() in NativeRNShareSpec public class RNShare extends NativeRNShareSpec { ^ C:\ReactNative\fairartfair\node_modules\react-native-share\android\src\newarch\cl\json\RNShare.java:32: error: getConstants() in RNShare cannot override getConstants() in NativeRNShareSpec public Map<String, Object> getConstants() { ^ overridden method is final Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. 2 errors FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':react-native-share:compileDebugJavaWithJavac'. > Compilation failed; see the compiler error output for details.

**Comment by jaaywags** [comment]
I am also having this issue on iOS.

React Native Version: 0.71.10

**Comment by bhupendra1011** [comment]
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary.  
any workaround, like downgrading version ? thanks

**Comment by tremblerz** [comment]
For me, it works on iOS but on Android, it gives the same error.
RN version: 0.72.3
RN share version: 9.2.3

**Comment by mohammadgharouni** [comment]
i have the same issue

**Comment by jpbalut** [comment]
Same issue here, for both Android and iOS
"react-native": "0.71.8",
"react-native-share": "^9.2.3",

**Comment by butri71** [comment]
Same issue on both iOS and Android. 

Looks like it doesn't work with Expo managed apps.

"react-native": "0.70.8",
"react-native-share": "^9.3.0",

I get same error: `Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary.`

**Comment by arnaldomoschetto** [comment]
This is because you need to link the library manually sometimes

`react-native link react-native-share`

This library depends on android native implementation

**Comment by iamyamar** [comment]
installed react-native-share@7.9.1 that worked for me if this too doesnt work try with react-native-share@8.2.2. these two are the most used react-native-share versions

**Comment by harsh-dhillon** [comment]
Are devs still ignoring this issue or we have a solution for this yet?

**Comment by mikehardy** [comment]
@harsh-dhillon in an open source repository *you are the dev*

If you need it fixed, fix it. There's no code fairy, just programmers. You're a programmer.

**Comment by Anibalfermandois** [comment]
Had to take the hard choice of migrating to expo-sharing and really the whole expo ecosystem, expo-router, expo-notifications, ect. Concerning sharing i found success with sharing images from the phones library but not yet from my own apps files.

**Comment by MD-Aadil-Shafi** [comment]
HI Guys use react native default "Share" instead of external library. 
It'll solve your issues.
link:
https://reactnative.dev/docs/share?language=typescript

**Comment by jaaywags** [comment]
> use react native default "Share" instead of external library. 

Isn’t this for sharing stuff from our app to other apps? We are trying to go the other way. Share stuff from other places to our app.

**Comment by mikehardy** [comment]
For expo folks, this is a module that isn't included in Expo Go, so you have to do the prebuild step for expo and then locally compile. The Expo Go app won't work for you for this module or any module not included in Expo Go.
