### ISSUE TITLE
Error: -source 1.7 does not support lambda expressions

### ISSUE THREAD

**Issue by azkbo** [react-native-share/react-native-share#1416]
### Steps to reproduce
1. yarn start
2. yarn android

### Actual behaviour
BUILD FAILED 

/Users/xxx/node_modules/react-native-share/android/src/main/java/cl/json/RNSharePackage.java:29: Error: -source 1.7 does not support lambda expressions
        return () -> {
                  ^
  (Use -source 8 or later to enable lambda expressions)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-share:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

### Environment
- **React Native version**: 0.65.1
- **React Native platform + platform version**: Android 8.1

### react-native-share
**Version**: 9.1.1

**Comment by HoangNgocThang** [comment]
"react-native-share": "^9.2.1",

error: lambda expressions are not supported in -source 7
        return () -> {
                  ^
  (use -source 8 or higher to enable lambda expressions)
