### ISSUE TITLE
is it working with expo? because i didn't make it work

### ISSUE THREAD

**Issue by brkkrbbrk** [react-native-share/react-native-share#1422]
```
Share.shareSingle({
       social: Share.Social.INSTAGRAM,
       backgroundVideo: videoURL,
       url: videoURL,
       type: "video/*",
     })
       .then((res) => {
         console.log(res);
       })
       .catch((err) => {
         err && console.log(err);
       });
```

I used this and installed with:
<code>npx expo install react-native-share</code>

**Comment by HadiaRafiq** [comment]
React native share does not work directly with expo. You need to import it conditionally and for testing you need to make a dev-client build to test it on expo, check this [link](https://docs.expo.dev/develop/development-builds/create-a-build/) 

```
const isExpoGo = Constants.executionEnvironment === ExecutionEnvironment.StoreClient;
let Share;
if (!isExpoGo) {
  Share = require("react-native-share").default;
}
```

**Comment by anthlasserre** [comment]
If you want to use it with an Expo managed workflow project. Here is a feature request to support the integration easily.

https://github.com/react-native-share/react-native-share/pull/1606
