### ISSUE TITLE
Support for Instagram's Threads app with shareSingle.

### ISSUE THREAD

**Issue by mdb-ko** [react-native-share/react-native-share#1424]
## Describe the Feature
Support for Instagram's Threads app with shareSingle .

## Possible Implementatio
none

## Related Issues
none

**Comment by MateusAndrade** [comment]
> any updates on it?
> 
> @mdb-ko do you know package name for threads social?

New PRs are welcome! AFAIK, this can be inspected using Google-Play/AppStore web-pages to access the reverse domain.
