### ISSUE TITLE
shareSingle hanging on iOS after bringing the app to foreground

### ISSUE THREAD

**Issue by ice-orion** [react-native-share/react-native-share#1427]
### Steps to reproduce
1. Add a button that calls `shareSingle({url: 'url', message: 'message', social: Social.Whatsapp})` // or Telegram or Instagram or Googleplus
2. Press the button -> WhatsApp is opened
3. Get back to the app
4. Press the button right away the app is resumed (to press it as soon as the app becomes foreground is important)

### Expected behavior
WhatsApp is opened 

### Actual behavior
The app hangs for ~3 seconds then WhatsApp is opened

### Environment
- **React Native version**: 0.70.8
- **React Native platform + platform version**: iOS

### react-native-share
**Version**: 8.0

I debugged the problem and it turned out that in those providers (WhatsApp, Telegram, Instagram, Googleplus) on iOS a deprecated function is used: https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl

So e.g. in `WhatsAppShare.m`
Instead of 
```
[[UIApplication sharedApplication] openURL: whatsappURL];
resolve(@[@true, @""]);
```
There should be 
```
[[UIApplication sharedApplication] openURL:whatsappURL options:@{} completionHandler:^(BOOL success) {
        if (success) {
            resolve(@[@true, @""]);
        } else {
            return reject(@"com.rnshare", [NSString stringWithFormat:@"Unable to open URL: %@", url], nil);
        }
}];
```

I have a patch but it's for the 8.0 version (i tried the latest version - 9.2.2 but it doesn't work for me as expected, when i use shareSingle for Twitter and it's not installed on the device - in 8.0 it opens a browser, in 9.2.2 it does nothing):
[react-native-share+8.0.0.patch](https://github.com/react-native-share/react-native-share/files/12028102/react-native-share%2B8.0.0.patch)

**Comment by DnEgorWeb** [comment]
It shouldn't be closed since the issue persists. WhatsApp snippet above worked for me, but I didn't try the entire patch.
