### ISSUE TITLE
'RNShare' could not be found. Verify that a module by this name is registered in the native binary.

### ISSUE THREAD

**Issue by jaskaran-5ingh** [react-native-share/react-native-share#1430]
### Steps to reproduce
Install package in expo using yarn

### Expected behavior
Share should be work.

### Actual behavior
Uncaught Error : 
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary.
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

**Comment by HadiaRafiq** [comment]
react-native-share does not work directly in expo, you need to make development build for this and import the package conditionally
This is how we are using in our project 
```
const isExpoGo = Constants.executionEnvironment === ExecutionEnvironment.StoreClient;
let Share;
if (!isExpoGo) {
  Share = require("react-native-share").default;
}
```

**Comment by arnaldomoschetto** [comment]
This is because you need to link the library manually sometimes

`react-native link react-native-share`

This library depends on android native implementation

**Comment by suXXVI** [comment]
im also having this issue, did you ever find a fix for this?

**Comment by arnaldomoschetto** [comment]
@suXXVI here it worked by rebuilding the application, in new versions of RN it makes the native library link automatically when you rebuild it.

**Comment by crystalarcus** [comment]
> react-native-share does not work directly in expo, you need to make development build for this and import the package conditionally This is how we are using in our project
> 
> ```
> const isExpoGo = Constants.executionEnvironment === ExecutionEnvironment.StoreClient;
> let Share;
> if (!isExpoGo) {
>   Share = require("react-native-share").default;
> }
> ```

where to place this, in which file i mean ?

**Comment by marcosdanielr** [comment]
You need use expo-dev-client.

**Comment by nagisaando** [comment]
I see the same issue still on Expo

**Comment by crystalarcus** [comment]
> I see the same issue still on Expo. Did anyone find workaround?

React Native Share don't run on expo. You need to you development build from EAS and install it in your phone. The dev build works natively so it can run React Native Share. Running Expo will give u error. 
But one thing, dev build runs with Expo's dev tools, so it gives performance lag sometimes, If you want to use expo than just comment out React-Native-Share imports: 
`// import Share from 'react-native-share';`
than you won't get errors but won't be able to use share. You can uncomment it before making production build. Just test it in development build before you do.

**Comment by script8888** [comment]
> I see the same issue still on Expo. Did anyone find workaround?

Hey, didi you find a workaround? pls share

**Comment by dev-joaovitor** [comment]
expo 52.0.26
react native 0.76.6

i needed a solution to share an image only on instagram. (i still think this problem doesn't make sense, `Sharing.shareAsync(...)` would work fine for me).

i found this module but i ran into the same issue.

i understood that this module will not work outside of native environment because it relies on native packages or whatever.

this is an extended version of the piece of code i saw above, which have worked for me.

```ts
// app/utils/sharing.ts
import Constants, { ExecutionEnvironment } from 'expo-constants';

const isExpoGo = Constants?.executionEnvironment === ExecutionEnvironment.StoreClient;

async function shareImage(imageUri: string, type?: string, social?: string) {
    if (isExpoGo) {
        const Sharing = require("expo-sharing");

        return Sharing.shareAsync(imageUri);
    }

    const RNShare = require("react-native-share").default;

    return RNShare.shareSingle({
        social: social ?? RNShare?.Social?.INSTAGRAM as any,
        url: imageUri,
        type: type ?? "image/*",
    });
}

export { shareImage };
```

since you can't use `react-native-share` on expo go, you won't want to deal with that ugly crash screen, so `expo-sharing` will replace it when using expo go.

adjust it to fit your needs. =)
