### ISSUE TITLE
Share.shareSingle() is always opening appleStore on IOS

### ISSUE THREAD

**Issue by joaolvcas** [react-native-share/react-native-share#1433]
I made this source below to open instagram and facebook stories to users share, but even having the application installed and opening the appleStore always.
```
  const shareOptionsIntagram = {
    appId: '*************',
    stickerImage: uri,
    social: Share.Social.INSTAGRAM_STORIES,
    backgroundBottomColor: colors.blue,
    backgroundTopColor: colors.blue,
  };

  const shareOptionsFacebook = {
    appId: '*************',
    stickerImage: uri,
    social: Share.Social.FACEBOOK_STORIES,
    backgroundBottomColor: colors.blue,
    backgroundTopColor: colors.blue,
  };

return (
 <ShareOptionWapper>
          <ShareOptionConteinar
            onPress={async () => await Share.shareSingle(shareOptionsIntagram)}
            style={{
              justifyContent: 'space-between',
              paddingTop: 16,
              height: 110,
            }}
          />
</ ShareOptionWapper>
)
```
### Steps to reproduce
1. Create a singleShare and select Share.Social.INSTAGRAM_STORIES or Share.Social.FACEBOOK_STORIES on IOS device
2. Try to share something and it will gonna appleStore, even though the app is downloaded

### Expected behavior
Open instagram stories and facebook stories in their respective apps

### Actual behavior
Open AppleStore

### Environment
- **React Native version**: 0.71.7
- **Typescript version**: 5.04

### react-native-share
**Version**: 9.2.3

### Link to repo (highly encouraged)
https://github.com/Riderize/client-mobile-v2

**Comment by michaelchangdk** [comment]
Oh - I found a closed issue. This solved it for me:

https://github.com/react-native-share/react-native-share/issues/1100

**Comment by joaolvcas** [comment]
wow, thanks! I will gonna try it!

**Comment by brunopintos** [comment]
@michaelchangdk how did you solved it for react native apps, without using Expo?

**Comment by ktleary** [comment]
I ran into this issue and finally found via https://developer.apple.com/forums/thread/689011 that if you have more than 50 urlschemes in LSApplicationQueriesSchemes in plist, it will not work. After going below 50 it started working again.
