### ISSUE TITLE
Share.open() not sharing images in android

### ISSUE THREAD

**Issue by kp2206** [react-native-share/react-native-share#1434]
Im using the latest version of react-native-share for sharing images from my app using share.open(). 

The Share.open() works fine on IOS, but sharing options don't open on Android, and no error is thrown as well.

Can anyone help me with this issue?

**Comment by neyosoft** [comment]
I am also experiencing the issue. share.open() shared the media but doesn't resolve the promise. When canceling the share modal also, the promise is not resolved.

**Comment by neyosoft** [comment]
I can confirm this issue has been fixed in this PR: https://github.com/react-native-share/react-native-share/pull/1449
The latest version is working fine
