### ISSUE TITLE
Sharing image to instagram returns "Something went wrong" error if permissions for Photos not set to "All photos"

### ISSUE THREAD

**Issue by matmartic** [react-native-share/react-native-share#1436]
### Steps to reproduce
This is mainly a request to update [docs here](https://react-native-share.github.io/react-native-share/docs/share-single#share-image-to-instagram). I struggled for a while to understand the error until eventually I realized it was a permissions issue. Maybe the docs could reflect this in a brief 1-2 sentence. What's especially frustrating is sharing to Stories works fine with "Selected photos" permission, but for Social.Instagram, it only works with "All photos" permission.

**Comment by jgcmarins** [comment]
@matmartic thanks for the report. We appreciate your suggestion.
Would you mind opening a PR adding that to the docs?

**Comment by matmartic** [comment]
Hi @jgcmarins , [here's](https://github.com/react-native-share/react-native-share/pull/1465) a quick PR updating the docs for this specific use case.
