### ISSUE TITLE
shareSingle -> Instagram opens an intermediary bottom sheet on Android while it doesn't on ios

### ISSUE THREAD

**Issue by matmartic** [react-native-share/react-native-share#1437]
Not sure if bug or feature, but using shareSingle with `social: Social.InstagramStories,` opens IG on stories (expected behaviour). But doing the same with `social: Social.Instagram,` opens an intermediary bottom sheet from which I can choose Feed among other options (unexpected since this doesn't happen on ios).  Is there any way to go directly to instagram share to feed rather than this in between step?

The other problem I have is that I'm sharing a base64 image, but the bottom sheet shows me `image.null` as follows

![image](https://github.com/react-native-share/react-native-share/assets/15280410/9beb700f-a078-4fe9-8a31-b73fcecd9382)

Other than that the sharing itself works fine.

### Steps to reproduce
1. Call shareSingle
```ts
        await RNShare.shareSingle({
          social: Social.Instagram,
          url: `data:image/png;base64,${b64data}`,
          type: 'image/*',
        });
```
2. Get bottom sheet

### Expected behavior
I would expect the same behaviour as ios : open directly instagram on feed share.
If not possible to open directly, I would expect to be able to give a filename so users dont see "image.null", I tried filename/message/title/subject, but none of them modify "image.null".

### Actual behavior
The bottom sheet shown above, and no option to change "image.null"

### Environment
- **React Native version**: 0.71.8
- **React Native platform + platform version**: Android 11
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment? 4.9.4

### react-native-share
**Version**: npm version or "master" 9.2.3

**Comment by fi-workers-developer** [comment]
Also same to me

**Comment by interstates21** [comment]
Replacing image/* with image/png (matching base64) removed image.null for me

**Comment by brandonbarrosogarcia** [comment]
Happens the same to me, any news on this or any fix? please.
