### ISSUE TITLE
Share instagram stories `Share.shareSingle(shareOptions)` redirecting to Gallery in android.

### ISSUE THREAD

**Issue by umarabdullah23** [react-native-share/react-native-share#1441]
### Steps to reproduce
My code is as following

`	const shareOptionsInstagramStories = {

			stickerImage: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==',

			backgroundBottomColor: '#fefefe',

			backgroundTopColor: '#906df4',

			appId: '******',

			social: Share.Social.INSTAGRAM_STORIES,
};
 Share.shareSingle(shareOptionsInstagramStories); `

### Expected behavior
Redirect to instagram stories

### Actual behavior
Redirects to Gallery

**Comment by zulalnb** [comment]
Facing same issue.

**Comment by interstates21** [comment]
Same

**Comment by interstates21** [comment]
Looks like it redirects to the Gallery if backgroundImage or stickerImage is invalid

I tried to use a remote url and had been redirected to the gallery, 
with a localUrl it seems to work


 ```
    const downloaded = await RNFetchBlob.config({
        fileCache: true,
        appendExt: 'png'
      }).fetch('GET', matchCardUrl);

      const localFileUri = `file://${downloaded.path()}`;
      
      await Share.shareSingle({
        backgroundImage: `file://${localFileUri}`,
        social: Social.InstagramStories,
        appId: 'com.instagram.android',
        type: 'image/*'
      });

```

**Comment by davidwinograd1** [comment]
Any updates on this?

**Comment by davidwinograd1** [comment]
> Facing same issue.

did you fix it?

**Comment by Giasinit** [comment]
@davidwinograd1, is really simple, just look at the android native code they have written for this library.
as you can see, the sticker MUST be of type "image/png", while backgroundImage MUST be of type "image/jpeg".
as for the "type" parameter, apparently it does not exist for android, or at least I have version 9.2.3, and everything works!

**Comment by davidwinograd1** [comment]
but what if I'm uploading a video, aka the backgroundVideo prop? @Giasinit

**Comment by Giasinit** [comment]
@davidwinograd1 with regard to the backgroundVideo prop the type must be 'video/*', so you're OK as far as the last issue is concerned. the only thing is that in my opinion you don't have the thing I showed you in the screenshot of the last issue.

**Comment by zulalnb** [comment]
The solution is add package visibility if you use SDK>=30

[document](https://react-native-share.github.io/react-native-share/docs/install#adding-queries-for-android-necessary-for-sdk--30)

**Comment by choijiho0021** [comment]
> The solution is add package visibility if you use SDK>=30
> 
> [document](https://react-native-share.github.io/react-native-share/docs/install#adding-queries-for-android-necessary-for-sdk--30)

Perfect solution. Thank you
