### ISSUE TITLE
Error: Couldn't share to Instagram, You can only share multiple photos and videos in the Instagram app

### ISSUE THREAD

**Issue by davidskaarup** [react-native-share/react-native-share#1442]
### Steps to reproduce
```
  const shareResponse = await Share.open({
      type: "image/jpeg",
      url: "file://path/to/file.jpg",
    })
```

### Expected behavior
Should be able to share via Instagram. Other socials work fine.

### Actual behavior
Couldn't share to instagram
You can only share multiple photos and videos in the Instagram app

![IMG_3867](https://github.com/react-native-share/react-native-share/assets/9447649/7fd85f02-e3e6-47d1-9870-e13eda7625c3)

### Environment
- **React Native version**: 0.71.8

### react-native-share
**Version**: Tried on both 8.2.2 and 9.2.3

**Comment by ayushranjan619** [comment]
Facing the same problem. Cannot share multiple photos from photos app to Instagram story

**Comment by alimohsinz** [comment]
facing same issue unable to share image to instagram

**Comment by zwebie** [comment]
Facing the same issue trying to share from a website when running navigator.share to instagram

**Comment by hehooleehoo** [comment]
We have the same issue

**Comment by hehooleehoo** [comment]
For others who come across this:

I missed a couple of steps in the install guide. Make sure you add `LSApplicationQueriesSchemes` to your infoPlist (see installation steps)

I then had an unrelated issue with sharing to socials on iOS - this comment from [vajid-khan](https://github.com/vajid-khan) saved the day!
https://github.com/react-native-share/react-native-share/issues/861#issuecomment-696616474
