### ISSUE TITLE
Fix issue build with CircleCI

### ISSUE THREAD

**Issue by MateusAndrade** [react-native-share/react-native-share#1445]
iOS builds are failing on CircleCI, probably due to a update with macOS runners: https://app.circleci.com/pipelines/github/react-native-share/react-native-share/1147/workflows/f1562ef5-ef4e-44f5-af24-79a613b19b4d/jobs/4378

**Comment by cctv1005s** [comment]
I could help to fix it, let me take a look

**Comment by MateusAndrade** [comment]
> I could help to fix it, let me take a look

Nice, let me know if you need any support.

**Comment by MateusAndrade** [comment]
Fixed with https://github.com/react-native-share/react-native-share/pull/1457
