### ISSUE TITLE
Allow custom title on WhatsApp Image share

### ISSUE THREAD

**Issue by ktleary** [react-native-share/react-native-share#1448]
### Steps to reproduce
1. Share a base64 image via shareSingle whatsApp on ios
2. The ios share menu opens instead of WhatsApp
3. The title displayed is "whatsAppTmp" 

### Expected behavior
1. Ideally it would open WhatsApp directly
2. If it must open in the native share sheet, it should accept a custom title instead of hardcoded 'whatsAppTmp'
3. It would be great if other apps besides WhatsApp don't appear on the list as the "/whatsAppTmp.wai" throws errors if you select a different app than WhatsApp from the sharesheet (for example if you select a mail app from the list)

### Actual behavior
- The ios share menu opens instead of WhatsApp
- The title displayed is "whatsAppTmp" 

### Environment
-  "react-native": "0.71.12", 
- ios 16 physical device

### react-native-share
 -  "react-native-share": "^9.2.3",

### Code Snippet

```
 case 'whatsapp':
      const combinedMessageUrl = `${content.message} ${content.url}`;
      shareOptions = {
        title: 'test title', //content.title,
        message: encodeURI(combinedMessageUrl),
        url: content.base64,
        subject: 'test subject',
        fileName: 'test filename',
        fileNames: ['test'],
        social: Share.Social.WHATSAPP,
      };
      console.log('whatsapp', shareOptions);
      /*
      
          whatsapp 
          Object
          fileName: "test filename"
          fileNames: Array(1)
          message: "...."
          social: "whatsapp"
          subject: "test subject"
          title: "test title"
          url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAtA
         __proto__: Object
*/
      break;
      //...
        Share.shareSingle(shareOptions)
      .then(() => handleShareStatus())
      .catch(error => console.log('shareToPlatform error', error));
      
```      

Without being familiar with the code, it seems that image shares fall into the ` if (imageURL.fileURL || [imageURL.scheme.lowercaseString isEqualToString:@"data"]) {` case and are hardcoded to `stringByAppendingPathComponent:@"/whatsAppTmp.wai"];` and the `presentOpenInMenuFromRect` resulting share sheet displays the name of the hardcoded file name.

**Comment by vivekUnified** [comment]
Same happens to me, whatAppTmp is displayed. with base64 image sharing
