### ISSUE TITLE
Share.shareSingle(shareOptions) to specific whatsApp number

### ISSUE THREAD

**Issue by ademir10** [react-native-share/react-native-share#1450]
Hello guys!
I'm trying to send a message using ShareSingle resource to Android, where i need to find automatically the whatsApp number in my shareOptions:

var shareOptions = {
                    title: '',
                    message: text,
                    social: Share.Social.WHATSAPP,
                    whatsAppNumber: '+5511970395230',
                };
await Share.shareSingle(shareOptions);

WhatsApp is opened but i need to search this number to send the message.
Do you know if have something else more to do?

Could you help me, please? Thank you!

**Comment by ademir10** [comment]
is anybody there? any suggestion guys?

**Comment by vaish8529** [comment]
Use whatsAppNumber: "9199999999",  // country code + phone number

**Comment by ankitOnecode** [comment]
The issue I'm encountering is that if a phone number is not saved in the contact list, the first time I attempt to send a message, it prompts me to share the contact. When I navigate back, it opens the customer chat without the default text. However, upon trying to share the contact again, it works correctly.



`const shareConfig = {
    message,
    url: base64Image,
    social:
      whatsappType === 'WHATSAPP_FOR_BUSINESS'
        ? Share.Social.WHATSAPPBUSINESS
        : Share.Social.WHATSAPP,
    whatsAppNumber: '915678723452',
  } as ShareSingleOptions

  await Share.shareSingle(shareConfig)`
