### ISSUE TITLE
Sharing a file + message via WhatsApp does not work on iOS latest anymore

### ISSUE THREAD

**Issue by PeterHasitschka** [react-native-share/react-native-share#1460]
Hi guys!

I'm facing a very strange behavior I could not resolve so far.
Since it only occurs on WhatsApp combined with iOS 16.6 (or at least after 16.4) when I try to combine `message` + file (via local `url`), i assume this might be a bug.

In my app the user can share a file including a message.
On EVERY Service or Messenger this works fine, except WhatsApp on iOS latest.
It also worked fine before updating iOS to 16.6.x.
The same behavior was also reported by my customers using this version.

### Steps to reproduce
1. Try to share a file + message via `Share.open` on iOS latest with WhatsApp using the following ShareOptions:
```JavaScript
{
    "filename": "Test_Table_2023-09-08_12-03-44",
    "failOnCancel": false,
    "subject": "*** Tablelle 'Test Table'",
    "message": "Ihre *** Tabelle 'Test_Table_2023-09-08_12-03-44' befindet sich im Anhang als CSV-Datei.",
    "type": "text/csv",
    "showAppsToView": true,
    "url": "file:///private/var/mobile/Containers/Data/Application/F8C7F09C-45FE-4E79-BCE6-07B7EB13DAD9/tmp/Test_Table_2023-09-08_12-03-44.csv"
}
```
3. Click on Person you want to send it
4. Only the message appears.

### Expected behavior
Sharing a file including a message works on WhatsApp on iOS latest.
It works on ANDROID and EVERY APPLICATION which supports message + file EXCEPT WhatsApp on iOS 16.6.

### Actual behavior
The file name appears before selecting a WhatsApp recipient.
Then the Message-Screen appears. Unfortunately only the message is shown but not the file.
**It works if i remove the message** from the options. However this is not an option, since the message content is important (e.g. for sending via mail).

![IMG_5593](https://github.com/react-native-share/react-native-share/assets/7084114/1974f9f2-9821-4d9c-9306-406b03cd03c2)

![IMG_5594](https://github.com/react-native-share/react-native-share/assets/7084114/010e2bf3-5202-464c-b227-ca621ce00eb0)

![IMG_5595](https://github.com/react-native-share/react-native-share/assets/7084114/21e52385-45bb-4617-a0ce-16e92460ccfc)

### Environment
- **React Native version**: 0.72.4
- **React Native platform + platform version**: iOS 16.6
- **Typescript version** (if using typescript): 4.8.4

### react-native-share
**Version**: 9.4.0

Any help would be appreciated.
Thanks and greetings from Austria

**Comment by adilijaz** [comment]
I am having the same issue. I am sending base64 image in URL but it's not working in iOS.

**Comment by abhishekjmd** [comment]
getting the same issue in android as well

**Comment by ijhar-nivoda** [comment]
@PeterHasitschka have you found any work around  ?

**Comment by bijomon-tolexo** [comment]
@PeterHasitschka Let us know if you have found any work around?

**Comment by PeterHasitschka** [comment]
Unfortunately I did not find any workaround but removing the message on iOS.

**Comment by abraham-alizor** [comment]
I'm having this same issue

**Comment by ArthurSimoess** [comment]
I have the same issue for ios, but in android works. I really need to send a url with a message to whatsapp. Someone know other way to do it?

**Comment by komalpdeveloper** [comment]
Has anyone found a solution to this issue ? Please let me know.

**Comment by OAllanFernando** [comment]
Pleace god help us
