### ISSUE TITLE
Sharing through telegram opens it inside the app

### ISSUE THREAD

**Issue by Dyachenko022** [react-native-share/react-native-share#1461]
The title says it. When trying to share through Telegram, it opens inside the same window. This behaviour doesn't happen when choosing whatsapp, for example, or any other application.
I'm guessing that's just the way Telegram behaves, but perhaps there are ways to open it in separate window?

**Comment by Nachox07** [comment]
Same issue with these versions in Android. Also, once you go back, the sharing action failed.
```
"react-native": "0.72.4",
"react-native-share": "^9.4.1"
```
