### ISSUE TITLE
Exclude own (Ios) app from sharesheet?

### ISSUE THREAD

**Issue by AdnanAshraf-gol** [react-native-share/react-native-share#1476]
## Ask your Question

Is there anyway we can exclude our own app from the sharesheet?
I have tried ```excludedActivityTypes:['my app identifie']``` , but its not working.
any help would be appreciated.

**Comment by AdnanAshraf-gol** [comment]
https://github.com/react-native-share/react-native-share/labels/question

**Comment by freethejazz** [comment]
According to [this 2 year old response](https://developer.apple.com/forums/thread/689062) on the Apple forums, it's not possible to exclude activities other than the built-in system types. Not definitive proof of accuracy, but incidentally the instagram app shows up when you try to share from instagram, so I imagine this is a hard limitation.
