### ISSUE TITLE
canOpenURL reports wrong value for ig stories url

### ISSUE THREAD

**Issue by yspreen** [react-native-share/react-native-share#1477]
On my iPhone 15 Pro on iOS 17.0.3 the share functionality doesn't work for IG stories. It goes to the App Store instead. I've confirmed that this is because canOpenURL returns false even though removing that safety check is totally fine and the sharing works as expected.

**Comment by valentinchelle** [comment]
same issue - following

**Comment by yspreen** [comment]
bump, not stale.
