### ISSUE TITLE
Share.shareSingle not working

### ISSUE THREAD

**Issue by canpoyrazoglu** [react-native-share/react-native-share#1479]
### Steps to reproduce
Have the following code:

 ```
await Share.shareSingle({
        url: URL //link to my valid URL,
        title: 'My App Name',
        social: target,
    });
```
- When the target is Facebook it works though it doesn't open the app, it opens Facebook in Safari.
- When target is Twitter, nothing happens. Objective-C side shows success though nothing comes up. Twitter app isn't installed though I'd expect Twitter to open in Safari (just like Facebook does) which doesn't happen.
- When target is Instagram, Instagram app opens up but brings up a share sheet with the latest photo in my camera roll.
- When target is Facebook Messenger, (I don't have it installed) it brings up app store page for Facebook Messenger to install.
- When target is Telegram, (I don't have it installed) it brings up app store page for Telegram to install.
- When target is WhatsApp, (I don't have it installed) nothing happens. If it opens App Store page if Facebook Messenger and Telegram if they are not installed, I'd expect the same behavior with WhatsApp too.

### Expected behavior
Target social platform's app, or if not installed, web version if available, should open with my URL prepopulated.

### Actual behavior
Share.shareSingle works only with Facebook, and even in that case it opens up Facebook web in Safari instead of the Facebook app, which is installed on my device.

### Environment
- **React Native version**: 0.72.4
- **React Native platform + platform version**: iOS 17.1
- **Typescript version** (if using typescript): 5.0.4

### react-native-share
**Version**: 9.4.1

**Comment by nejdetkadir** [comment]
I'm having same issue on IOS 🔴

**Comment by gyhyfj** [comment]
same problem

**Comment by Splicer97** [comment]
same problem

**Comment by andriy-zahura** [comment]
If you are using either bare react native or an ejected expo project, did you add 

```
	<key>LSApplicationQueriesSchemes</key>
    <array>
        <string>fb</string>
        <string>twitter</string>
        <string>whatsapp</string>
        <string>instagram</string>
        <string>linkedin</string>
        <string>snapchat</string>
        <string>tg</string>
    </array>
```

to your `Info.plist` ? If not, add a string per each external app you want to use and rebuild the app

**Comment by Splicer97** [comment]
> If you are using either bare react native or an ejected expo project, did you add 
> 
> ```
> 	<key>LSApplicationQueriesSchemes</key>
>     <array>
>         <string>fb</string>
>         <string>twitter</string>
>         <string>whatsapp</string>
>         <string>instagram</string>
>         <string>linkedin</string>
>         <string>snapchat</string>
>         <string>tg</string>
>     </array>
> ```
> 
> to your `Info.plist` ? If not, add a string per each external app you want to use and rebuild the app

I use this library in  react native project and I added this keys in Info.plist file
