### ISSUE TITLE
URL icons don't work at all

### ISSUE THREAD

**Issue by avr6ude** [react-native-share/react-native-share#1480]
### Steps to reproduce
1. Use the following code
```typescript
const url = `https://app.link/${feedId}/${postId}`
  const message = 'message'
  const thumbnailImage = `data:image/png;base64,${base64image}'`
  const options: ShareOptions = Platform.select({
    ios: {
      failOnCancel: false,
      message: message,
      activityItemSources: [
        {
          placeholderItem: {
            type: 'url',
            content: url,
          },
          item: {
            default: {
              type: 'url',
              content: url,
            },
          },
          thumbnailImage: {
            default: thumbnailImage,
          },
          linkMetadata: {
            title: text,
            url,
            image: thumbnailImage,
          },
        },
      ],
    },
    default: { url, message: `${message}: ${url}` },
  })
  await Share.open(options)
```
2. <img width="361" alt="SCR-20231106-qmns" src="https://github.com/react-native-share/react-native-share/assets/26382613/a3514c26-4a10-4981-abc9-a05bc585ac82">
### Expected behavior
Icons should show up 

### Actual behavior
No icons show up

### Environment
- **React Native version**: 0.71.7
- **React Native platform + platform version**: iOS 17
- **Typescript version*

* (if using typescript): 4.9.4

### react-native-share
**Version**: 9.4.1

### Link to repo (highly encouraged)
https://github.com/

**Comment by melyux** [comment]
Same
