### ISSUE TITLE
Share didn't seem work if device has the Instagram Lite app, does this package support?

### ISSUE THREAD

**Issue by abburiv** [react-native-share/react-native-share#1481]
## Share to Instagram Lite App not Working
We are using this package to share content to Instagram, Facebook and other social apps.
Recently our team and users facing share problems when Instagram Lite app was installed. Share component not giving Instagram share options when the Insta Lite app installed unlike the original app.

Any body tried the same and is there any alternatives to fix this limitation?

**Comment by choijiho0021** [comment]
https://react-native-share.github.io/react-native-share/docs/install

  <key>LSApplicationQueriesSchemes</key>
  <array>
    <string>whatsapp</string>
    <string>mailto</string>
    <string>instagram</string>
    <string>instagram-stories</string>
    <string>fb</string>
    <string>facebook-stories</string>
  </array>
