### ISSUE TITLE
root path security issue

### ISSUE THREAD

**Issue by allen-hsu** [react-native-share/react-native-share#1491]
### Steps to reproduce
plz ref here: 
https://developer.android.com/privacy-and-security/risks/file-providers
https://mas.owasp.org/MASVS/05-MASVS-STORAGE/

I think shouldn't to use root-path, because can let anyone to access your file 

### Expected behavior
Don't use `<root-path>`

### Actual behavior
use `<root-path>`

### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by mikehardy** [comment]
PRs happily accepted
