### ISSUE TITLE
Support for sharing attachment or text only on email and Slack

### ISSUE THREAD

**Issue by lakshyastech** [react-native-share/react-native-share#1503]
Is there any option in the this library to share attachments or text only specifically on email and Slack, without showing all the other sharing options available on the device? I'm working on an application where users need to share content via email and Slack, but we want to restrict the sharing options to just these platforms. Any guidance on how to achieve this would be greatly appreciated.

**Comment by srinu6** [comment]
Can you please verify this by modifying `info.plist` for iOS

![image](https://github.com/react-native-share/react-native-share/assets/46079085/4e71ea5f-fc7f-47f0-b896-16299da6a391) 

[Refer this](https://react-native-share.github.io/react-native-share/docs/install)

**Comment by albertovasquez** [comment]
He is stating he wants the list limited to just those two applications, not that he wants to support them.
