### ISSUE TITLE
How to show a link below the user name on Instagram Stories? 

### ISSUE THREAD

**Issue by ebellumat** [react-native-share/react-native-share#1519]
## How to show a link below the user name on Instagram Stories? 
In Spotify and Apple Music, it's possible to have a small link below instagram stories share, "Play with spotify", i tested the `attributionURL` property but notthing happens in my story, i mean, a background and a sticker is good, but without a link is useless. Is any configuration we need to do in Meta platforms? The icon and the text looks like something custom.

![image](https://github.com/react-native-share/react-native-share/assets/26942680/57b4497d-7ceb-4d88-8dfe-7a33b32f12fb)

**Comment by albertovasquez** [comment]
I wouldn't say useless, but yes this would be an amazing feature to add.

**Comment by calija** [comment]
+1

**Comment by XEmAX32** [comment]
+1

**Comment by Nitrammets** [comment]
+100

**Comment by mikehardy** [comment]
You all realize that posting +anything as a comment adds no value, and instead just generates notification spam for people right?

It's bad behavior, a negative contribution.

**Comment by Nitrammets** [comment]
> You all realize that posting +anything as a comment adds no value, and instead just generates notification spam for people right?
> 
> It's bad behavior, a negative contribution.

If I was a maintainer, I think having an indication of what users want is a good thing. I agree that this is a low quality and effort way of expressing this, but it's still one.
