### ISSUE TITLE
(Android) Share.single with instagram shows image.null text on share screen

### ISSUE THREAD

**Issue by goyalshubham13** [react-native-share/react-native-share#1530]
### Steps to reproduce
1. use `Share.single` to share image with `instagram`

code I am using
```
const shareOptions = {
        url: `data:image/jpg;base64,${base64Image}`,
        social: Share.Social.INSTAGRAM,
        type: 'image/*',       
};
 const t = await Share.shareSingle(shareOptions);
```

### Expected behavior
Sharing is working fine, its just share activity is showing `image.null` text.

### Actual behavior
should show file name? or something else?

<img width="528" alt="Screenshot 2024-05-20 at 12 32 16 PM" src="https://github.com/react-native-share/react-native-share/assets/2923879/c8569e24-f17a-48cd-bad1-a5535cd23cbc">

### Questions:
 - What this title supposed to be?
 - Can we show a thumbnail of the image here?
 - I tried passing `title` and `message` but that doesnt go to instagram. Is there a way to achieve that?

### Environment
- **React Native version**: `0.71.14`
- **React Native platform + platform version**: Android 10

### react-native-share
**Version**: `10.2.0`

**Comment by devjointoit** [comment]
this comment from another issue helped me

https://github.com/react-native-share/react-native-share/issues/1437#issuecomment-1726520385

however, was still not able to show the name/image itself in this inner instagram modal
