### ISSUE TITLE
ShareSingle's result.success immediately resolving as false

### ISSUE THREAD

**Issue by x64Eddie** [react-native-share/react-native-share#1534]
## Ask your Question
Hi all! I am wondering if anyone could shine some light on this issue that I am facing for `shareSingle()`. I have the following code:
```typescript
      const shareOptions = {
        message: 'Some text',
        url: url,
        social: Social.Sms,
        appId: <APPID>,
        recipient: phone,
      };

      Share.shareSingle(shareOptions)
        .then(data => {
          //data.success always resolves immediately to false.
          onShare?.(data.success);
        })
        .catch((err: any) => {
          log.error('Error on sharing: ', err);
        });
```
However, the result from sharing always immediately resolves as false. Everything else works fine. It is opening the messaging app with the desired information. Unless I am misunderstanding this, the result should resolve as true if the user send the message? I did have success using `open()`, it resolves based on if the user send the shared or not. Thank you in advance!

----
version: `10.1.0`
react-native: `0.73.5`
ios version: `17.5.1`

**Comment by ibash-corpusant** [comment]
Looks like there's currently a bug where on ios the result is resolved with an array when a map is expected.
https://github.com/react-native-share/react-native-share/blob/df44b22184217c74c4932fb2d2337b47e1f84cb3/ios/InstagramStories.m#L80

https://github.com/react-native-share/react-native-share/blob/df44b22184217c74c4932fb2d2337b47e1f84cb3/src/index.tsx#L82

**Comment by danibalcr** [comment]
> Looks like there's currently a bug where on ios the result is resolved with an array when a map is expected.
> 
> https://github.com/react-native-share/react-native-share/blob/df44b22184217c74c4932fb2d2337b47e1f84cb3/ios/InstagramStories.m#L80
> 
> https://github.com/react-native-share/react-native-share/blob/df44b22184217c74c4932fb2d2337b47e1f84cb3/src/index.tsx#L82

And how can a Map be resolved as expected? Do you know how to do it? Is there a solution?

**Comment by ibash-corpusant** [comment]
After inspecting the code it appears that the promise is almost always resolved with success set to true.

The only exception I could find is if the share is canceled on android: https://github.com/react-native-share/react-native-share/blob/df44b22184217c74c4932fb2d2337b47e1f84cb3/android/src/main/java/cl/json/RNShareImpl.java#L55

So I opted to ignore the success result and instead just handle errors in a try/catch.
