### ISSUE TITLE
SMS on iOS fails to open

### ISSUE THREAD

**Issue by walshie4** [react-native-share/react-native-share#1536]
### Steps to reproduce
1. Call `shareSingle` with the social param being `Share.Social.SMS`

### Expected behavior
Tell us what should happen

Messages should open with the given message in the prompt

### Actual behavior
Tell us what happens instead

Receive an error saying `[Error: Sms services is not available.]`

### Environment
- **React Native version**: `0.71.2`
- **React Native platform + platform version**: iOS 12.4
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment? 4.8.4

### react-native-share
**Version**: npm version or "master" 10.0.2

**Comment by idrisssakhi** [comment]
Sms services is not available only throws when you test on Emulator, also for sharing throught SMS you need to provide recipient for it to work => 
        const shareResponse = await Share.shareSingle({
          ...shareOptionsSms,
          //   url: `liist://join-list-${sharableUrl}`
          recipient: '0666666666'
        });

**Comment by walshie4** [comment]
Interesting, had been running into the issue of `recipient` not being provided.  There is no way around that, a number always has to be provided?
