### ISSUE TITLE
File sharing from internal storage to external storage - Android 14

### ISSUE THREAD

**Issue by taatiq882** [react-native-share/react-native-share#1543]
So following are the configurations that I am using. 

```
     
        const filePath = `${RNFetchBlob.fs.dirs.CacheDir}/${filename}`;
        await RNFetchBlob.fs.writeFile(filePath, attachmentBase64, 'base64');

        let shareOptions = {
            filename: `${name}.json`,
            subject: "TESTING - Subjecyt",
            url,
            failOnCancel: false,
            type: 'application/json',
            url: `file://${filePath}`
        };
```

On Android 13 it does open the sheet and it also shows the option to save to external storage, 
**but on android 14 its not showing at all.**

**Comment by anferrat** [comment]
It is probably about RECEIVER_EXPORTED & RECEIVER_NOT_EXPORTED for Android 14. it was discussed [here](https://github.com/react-native-share/react-native-share/issues/1463).

Try to reinstall react-native-share.
