### ISSUE TITLE
Share.open saying it needs 3 arguments and only received 1 - ios

### ISSUE THREAD

**Issue by jamieGardyn** [react-native-share/react-native-share#1546]
### Steps to reproduce
const shareOptions = {
    title: 'Share',
    message: `You've gotta check out ...`,
    subject: 'Check out my site!',
    type: 'url',
    url: `https://...'
}

Share.open(shareOptions)
      .then((res) => { }
      .catch((err) => { console.log(err.message) }

### Expected behavior
This should share and go to the .then when done

### Actual behavior
On share it is going straight to the .catch and logging "Cannot read property 'success' of undefined"
In RN simulator it is giving me error of RN.share was called with 1 argument but expects 3
FWIW - the share works - but it goes to the .catch instead of the .then and I thus can't log a successful share, instead I log an error even when it is not.

### Environment
- **React Native version**: 0.72.6
- **React Native platform + platform version**: iOS - Android works
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: 10.2.0 and 10.2.1

### Link to repo (highly encouraged)
https://github.com/

**Comment by luwa-star** [comment]
I am experiencing the same issue. It started. when I upgrade my project from 0.72 to 0.74.2. Can the team help resolve this asap?

**Comment by amarstb** [comment]
@jamieGardyn @luwa-star any success on this?
