### ISSUE TITLE
shareSingle fb messenger on IOS, empty link and no preview

### ISSUE THREAD

**Issue by LukasMod** [react-native-share/react-native-share#1547]
### Steps to reproduce
1. Call    
``` 
await Share.shareSingle({
             url: 'test',
             social: Social.Messenger,
                });
```
2. Share the message via Facebook Messenger on iOS with a few people.

### Expected behavior
The Messenger modal should open and send the predefined message to the selected user.

### Actual behavior
The modal opens and allows user selection, but there is no message preview. After pressing "send," it changes to "sent," but nothing is actually sent. On Android, it works correctly for every user, but on iOS, it sometimes sends the message (even without a preview) and sometimes does not. We suspect it may be related to end-to-end encryption on their (fb) side.

I checked MessengerShare.m and saw that it mostly opens fb-messenger://share?link={url}. I wonder if this deeplink is still valid and if anyone knows a better one.

Using `Share.open` works fine with messenger on iOS, but the modal that is opened is a bit different
Is there a way to call it directly instead of shareSingle with Social.Messenger? To get same result as from Share.open but without this first modal to choose app.

### Environment
 - **React Native**: 0.73.8,
- **React Native platform + platform version**: iOS 17.5.1, on Android its working
- **Typescript version**: 5.04

### react-native-share
     "react-native-share": "^10.2.1",

**Comment by mieszko4** [comment]
In my case, I tried the following on iOS:
```ts
Share.shareSingle({
  social: Share.Social.MESSENGER,
  url: "https://google.com",
  failOnCancel: false,
})
```

1. If Messenger app was opened before then it shows correctly the share modal with link preview ✅ 
2. If Messenger app was not opened before then it opens Messenger app, shows the share modal with link preview then right away closes that modal ❌

**Comment by mieszko4** [comment]
Also the base64 url does not work on iOS:

```ts
Share.shareSingle({
  social: Share.Social.MESSENGER,
  url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
  type: "image/png",
  failOnCancel: false,
})
```

On Android it is all good.

**Comment by bfelbo** [comment]
This is not stale

**Comment by fekajin** [comment]
issue is still continues

**Comment by mikehardy** [comment]
It should be somewhat obvious that PRs are really needed, +1ing etc doesn't move it forward but there's not a lot of spare maintainer time in the react-native ecosystem, sometimes as a library user you have to donate some time yourself to dig in and determine why a bug is happening, fix it, and post up a PR

**Comment by ntkzwane** [comment]
> Also the base64 url does not work on iOS:
> 
> Share.shareSingle({
>   social: Share.Social.MESSENGER,
>   url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA...",
>   type: "image/png",
>   failOnCancel: false,
> })
> On Android it is all good.

Managed to work around this by setting the `filename` on share options
