### ISSUE TITLE
Share button doesn't do anything on Android

### ISSUE THREAD

**Issue by IgorGanapolsky** [react-native-share/react-native-share#1550]
### Steps to reproduce
1. Add `"react-native-share": "^10.2.1",` to your package.json
2. Launch the app on Android 14
3. Press the Share button

### Expected behavior
A menu should appear to select a channel for sharing

### Actual behavior
Nothing happens

### Environment
- **React Native version**: 0.73.8
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc Android 14
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment? 5.0.4

### react-native-share
10.2.1

**Comment by IgorGanapolsky** [comment]
The issue is actually Not with `react-native-share` library.  It is with building dynamic links:
```
    // Generate dynamic link from boat share link
    const dynamicLink = await DynamicLinks.buildDynamicLink({
      title,
      link: shareLinkWithUTMS,
      imageUrl: image,
    });

```

**Comment by URvesh109** [comment]
Try this: https://medium.com/@siddhantshelake/fixing-broadcastreceiver-crashes-and-metro-server-issues-in-android-14-3b7d05939a43

**Comment by Vepsur** [comment]
> Try this: https://medium.com/@siddhantshelake/fixing-broadcastreceiver-crashes-and-metro-server-issues-in-android-14-3b7d05939a43

It's working like a charm, thanks!

P.S. For the other devs: in the article, the author used unnecessary [dependency](https://github.com/JetBrains/java-annotations). So, if you don't need it, be patient and fix the example a little bit

**Comment by mswieboda** [comment]
> Try this: https://medium.com/@siddhantshelake/fixing-broadcastreceiver-crashes-and-metro-server-issues-in-android-14-3b7d05939a43

Agreed, this info worked like a charm for me too. Would be great if this was added in the https://react-native-share.github.io/react-native-share/docs/install instructions somewhere, since it's now required for latest RN / android
