### ISSUE TITLE
Facebook opens in browser, X, both broken.

### ISSUE THREAD

**Issue by sleep9** [react-native-share/react-native-share#1551]
### Expected behavior
Facebook app should open and post should be composed, same with X (twitter)

### Actual behavior
Facebook opens in browser, X crashes

"react-native": "0.74.2", iOS 17.5.1,"typescript": "~5.3.3", npm 10.2.4

"react-native-share": "^10.2.1" and 8.0.1 both tested.

**Comment by sleep9** [comment]
To anyone looking to get this library working take a look at the native code and just make your changes accordingly. Each platform has differing logic in the implementation.

**Comment by krisnapy** [comment]
Do you have a solution for the share single facebook?

**Comment by sleep9** [comment]
Yes the following works to post to facebook. However it does not return correctly see https://github.com/react-native-share/react-native-share/issues/1555

`await Share.shareSingle({
                social:Share.Social.FACEBOOK_STORIES,  
                appId:$YOUR_APP_ID,
                backgroundImage: $URI_OF_FILE_NOT_BASE64,
                failOnCancel:true
                })`
