### ISSUE TITLE
shareResponse always returning false.

### ISSUE THREAD

**Issue by sleep9** [react-native-share/react-native-share#1555]
```
try {         shareResponse = await Share.shareSingle({
                    social:Share.Social.INSTAGRAM,  
                    url:shareURI,
                    failOnCancel:true
                });
            } catch (error) {

                console.log('post abandoned: ', error);
                return;
            }

console.log('shareResponse: ', shareResponse);

```
"react-native": "0.74.2", iOS 17.5.1,"typescript": "~5.3.3", npm 10.2.4
"react-native-share": "^10.2.1"

### Expected behavior
On post success return success:true and on post cancel either get caught by the catch or return success:failure

### Actual behavior
Always returns success:failure

**Comment by lyqandy** [comment]
Got same issue.
