### ISSUE TITLE
Sharing PDF File On Whatsapp Error On IOS In Release Build

### ISSUE THREAD

**Issue by Khaptikma** [react-native-share/react-native-share#1556]
### Steps to reproduce
1. The usual "Share.open()" on a pdf file
2. Share it to Whatsapp app on IOS

### Expected behavior
On IOS, pdf file can be shared and downloaded normally as pdf file with .pdf extension on whatsapp

### Actual behavior
This is only happen in release build / App Store release. On IOS, shared pdf file displayed and downloaded from Whatsapp with no extension at all (should be "file.pdf") or changed into other extension like "file.bin".

But In apps other than Whatsapp, it's correctly shared and downloaded as pdf file. On Android, everything is fine.

### Environment
- **React Native version**: 0.64.4
- **React Native platform + platform version**: iOS 17.5.1, Iphone XR

### react-native-share
**Version**: ^8.0.1

![Untitled](https://github.com/user-attachments/assets/61249b97-b2dc-4a7e-8cfa-68132d4e89b0)
![wa](https://github.com/user-attachments/assets/54b813ab-d85c-4fcd-af5b-a587b2127f2e)

**Comment by marciofaria-git** [comment]
HI Khaptikma, i dont know why, but if i use the ```saveToFiles: true``` in shareOptions, i can save the pdf with de correctly extension, but not send directly on whatsapp, for now i using like this way.

**Comment by davidfeldt** [comment]
I found this to be useful for iOS sharing Base64 PDF issue: https://react-native-share.github.io/react-native-share/docs/share-remote-file
