### ISSUE TITLE
Specify zoom of picture when sharing to instagram stories

### ISSUE THREAD

**Issue by ryelibra37** [react-native-share/react-native-share#1560]
Sharing a picture to instagram stories works well, but as my image is a very similar aspect ratio to the story window the picture is full zoomed in intially and looks strange, until you manually resize the image in the story window. I was wondering if there was a way to specific this zoom level via this package when sharing to instagram? 

I'm taking a screenshot of a component in on my screen, and allowing users to share to socails like this:

```
const shareLog = () => {
    if(viewShotRef.current && viewShotRef.current.capture){
      viewShotRef.current.capture().then(uri => {
        const shareOptions = {
          title: 'Share',
          url: uri,
          message: 'Look at this!',
        };
        Share.open(shareOptions)
          .then((res) => {
            console.log(res)
          })
          .catch((err) => {
            console.log(err)
          });
      });
    }
  }
```

**Comment by danibonilha** [comment]
I don't know if there's a way to do that using `Share.open`, but as a "workaround" you could use `shareSingle` specifically for instagram and instead of using `backgroundImage` you could use `stickerImage`. This will make the image not take the fullscreen size.
