### ISSUE TITLE
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found.

### ISSUE THREAD

**Issue by MattJones2000** [react-native-share/react-native-share#1561]
### Steps to reproduce
1. run npx expo run:android on an emulator, error will occur once app is built

Full error:
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","LogBox","SourceCode","Timing","AppState","BlobModule","WebSocketModule","DevSettings","DevToolsSettingsManager","Networking","Appearance","DevLoadingView","HeadlessJsTaskSupport","DeviceInfo","UIManager","ImageLoader","SoundManager","IntentAndroid","DeviceEventManager","RNCSafeAreaContext","NativeAnimatedModule","I18nManager","RNCAsyncStorage"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","RedBox","BugReporting","LinkingManager","NativeReactNativeFeatureFlagsCxx","RNSModule","PlatformLocalStorage","RNC_AsyncSQLiteDBStorage","RNShare"]}, js engine: hermes

### Expected behavior
App should not be receiving this error

### Actual behavior
App receives the error on EMULATOR only. The same build works perfectly fine on a physical tablet that I have hooked up to my pc.

### Environment
-  "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.1",
- Note: using expo for this project, and more specifically the development builds
- Android target version: 34
- Android minimum: 23

- Not using typescript

### react-native-share
-react-native-share@10.2.1

### Link to repo (highly encouraged)
Repo is private, sorry!

**Comment by MattJones2000** [comment]
Update!

I found a way to fix my particular issue by performing "wipe data" on my tablet emulator in android studio. It's strange this fixed this as i've never had to do this with any other react native library

Note that none of the below solutions worked before this: (These usually fix any react native package issues I have)
- npx expo run:android (rebuilding)
- re-installing the library
- Updating all npm packages
- going to android folder and running ./gradlew clean
- restarting android studio

I hope this helps someone! If anyone else is still having issues with this, I have also heard that expo-sharing is a great library to use when in the expo environment.

**Comment by Chipzstar** [comment]
> Update!
> 
> I found a way to fix my particular issue by performing "wipe data" on my tablet emulator in android studio. It's strange this fixed this as i've never had to do this with any other react native library
> 
> Note that none of the below solutions worked before this: (These usually fix any react native package issues I have)
> 
> * npx expo run:android (rebuilding)
> * re-installing the library
> * Updating all npm packages
> * going to android folder and running ./gradlew clean
> * restarting android studio
> 
> I hope this helps someone! If anyone else is still having issues with this, I have also heard that expo-sharing is a great library to use when in the expo environment.

This worked for me. Thank you!
