### ISSUE TITLE
Instagram Share on iOS 18 not working (BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).)

### ISSUE THREAD

**Issue by mangBert** [react-native-share/react-native-share#1579]
### Steps to reproduce
1. Share Instagram

BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).

Suggested solution:
InstagramShare.m
      // [[UIApplication sharedApplication] openURL: shareURL]; // This is deprecated please remove and use below code
       UIApplication *application = [UIApplication sharedApplication];
        [application openURL:shareURL options:@{} completionHandler:^(BOOL success) {
            if (success) {
                 NSLog(@"Opened url");
            }
        }];

### Expected behavior
It should share on Instagram messaging

### Actual behavior
Doing nothing, logs in xcode: (BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).)

### Environment
- **React Native version**: 0.74
- **React Native platform + platform version**: iOS 18
- **Typescript version** (if using typescript): 5.0.4

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by isBatak** [comment]
We are facing the same issue. Is there any workaround until this gets fixed?

**Comment by toffeantyri** [comment]
I have it problem too

**Comment by mikehardy** [comment]
PRs happily accepted
