### ISSUE TITLE
Share.open not working properly with Gmail on iOS

### ISSUE THREAD

**Issue by sendaimono** [react-native-share/react-native-share#1585]
I have an issue with sharing  message via gmail on iOS (no matter the type). Case is that the `message` is set as an title. I saw that there was [fix created for this problem](https://github.com/react-native-share/react-native-share/pull/1540). Is there some other way to make it work?

here is example code
```
const title = 'My title';
const message = `My message`;

const options = Platform.select({
	default: {
		title,
		subject: title,
		message,
	},
	ios: {
		activityItemSources: [
			{
				// For sharing text
				placeholderItem: { type: 'text', content: title },
				item: {
					default: { type: 'text', content: message },
					message: null, // Specify no text to share via Messages app.
				},
				subject: { default: title },
				linkMetadata: {
					// For email
					title: title,
				},
			},
		],
	},
});

const result = await Share.open(options);
```

**Comment by anil-punchh** [comment]
Any update on this issue, as I'm also getting the same problem with Gmail. 

The subject is the same as body message for IOS only. In Android working fine like subject and message both are different.

I'm using this version - "10.0.2"
