### ISSUE TITLE
Sharing in instagram chat send the message plus a null message

### ISSUE THREAD

**Issue by donaitorin** [react-native-share/react-native-share#1620]
### Steps to reproduce
1. share a simple message or an image to an instagram chat:

await RNShare.open({
     message: 'Test message',
});

### Expected behavior
The user should receive only the message or the image

### Actual behavior
The user receive the message or the image plus a message with the text "null"

### Environment
- **React Native version**: 0.76.5
- **React Native platform + platform version**: Android 12 (but the same is happening in other versions that i tested)
- **Typescript version** (if using typescript): "~5.3.3"

### react-native-share
**Version**: "^11.0.3"

**Comment by Facuiguacel** [comment]
Its an Instagram-side bug. It happens to me even when sharing from my photos gallery.

**Comment by donaitorin** [comment]
@Facuiguacel interesting, i just tested it and you are correct, sharing in android from the gallery will also send the image and a null message, i guess we can only wait for instagram to fix this, in ios it works correctly
