### ISSUE TITLE
How can i fix this

### ISSUE THREAD

**Issue by jeeva2334** [react-native-share/react-native-share#1621]
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary. [Component Stack]

im using expo.
plugin : 
[
        "react-native-share",
        {
          "ios": [
            "whatsapp"
          ],
          "android": [
            "com.whatsapp"
          ]
        }
      ]

my sharing part: 
 if (news?.image) {
                const filename = 'shared-image.jpg';
                const filepath = `${FileSystem.cacheDirectory}${filename}`;
                
                // Download the image
                await FileSystem.downloadAsync(news.image, filepath);
                await Share.shareSingle({
                    social: Social.Whatsapp,
                    url: filepath,
                    message: message
                })
            } else {
                await Share.shareSingle({
                    social: Social.Whatsapp,
                    message: message
                })
            }

**Comment by mikehardy** [comment]
> Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNShare' could not be found. Verify that a module by this name is registered in the native binary. [Component Stack]

So you have not correctly built the native code

> im using expo.

Right, so you have not correctly learned how to use expo to integrate custom native code. You've got some expo docs reading to do - this is not a repo problem and there is no action here
