### ISSUE TITLE
IOS: Expo plugin prebuild fails occasionally when `props` parameter is undefined, or `LSApplicationQueriesSchemes` is an object

### ISSUE THREAD

**Issue by duncanlutz** [react-native-share/react-native-share#1623]
### Steps to reproduce
1. Create a new Expo project using `npx create-expo-app`
2. Install plugin using `expo install react-native-share`
3. Try prebuilding using `expo prebuild`

### Expected behavior
Tell us what should happen
Prebuild should complete with no errors

### Actual behavior
Tell us what happens instead
Prebuild is currently throwing an error due to LSApplicationQueriesSchemes coming through as an object (this may be an edge case, it doesn't seem like the expected type at least)

### Environment
- **React Native version**: 0.76.5
- **React Native platform + platform version**: n/a
- **Typescript version** (if using typescript): n/a

### react-native-share
**Version**: 12.0.3

### Link to repo (highly encouraged)
https://github.com/duncanlutz/react-native-share-issue

**Comment by duncanlutz** [comment]
Did this a bit out of order but I have a pull request with a fix ready for this:
https://github.com/react-native-share/react-native-share/pull/1622

**Comment by mikehardy** [comment]
@duncanlutz fantastic, thank you!
