### ISSUE TITLE
Attribute provider is also present at 'react-native-image-crop-picker'

### ISSUE THREAD

**Issue by EyalSi** [react-native-share/react-native-share#202]
using the package react-native-image-crop-picker, I was trying to change the provider suffix to share - in both AndroidManifest.xml and MainApplication.java setting authorities to: ${applicationId}.share

Hence getting the following error:
Anyone has a suggestion what can be done?
10x,

D:\Data\Projects\Anashim\android\app\src\main\AndroidManifest.xml:34:11-55 Error:
      Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.anashim.share) from AndroidManifest.xml:34:11-55
     is also present at [Anashim:react-native-image-crop-picker:unspecified] AndroidManifest.xml:15:13-60 value=(com.anashim.provider).
     Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:32:7-37:18 to override.

**Comment by prtkkmrsngh** [comment]
You should follow the suggestion shown in the build log.
Add this to AndroidManifest.xml:
```
<provider
  android:name="android.support.v4.content.FileProvider"
  android:authorities="${applicationId}.provider"
  android:exported="false"
  android:grantUriPermissions="true">
  <meta-data
    tools:replace="android:resource"
    android:name="android.support.FILE_PROVIDER_PATHS"
    android:resource="@xml/application_file_paths" />
</provider>
```

Add this to res/xml/application_file_paths.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <external-path name="external_files" path="." />
</paths>
```

**Comment by antonkulyk** [comment]
I also use `react-native-image-crop-picker`. I've added the code above to AndroidManifest and application_file_paths.xml and now I get the next error on Android when trying to share something
![screenshot_20180222-190503](https://user-images.githubusercontent.com/17258145/36552824-7ec73cdc-1803-11e8-979e-41d85d2b2abc.jpg)

**Comment by michaelmika** [comment]
I have the same issue! @prtkkmrsngh suggestions did not help me. Then, the file isnt found. Is there a way? This should not be so difficult! :(

**Comment by prtkkmrsngh** [comment]
Replace ${applicationId} with your package name e.g. `com.diggica`

**Comment by ricardochen** [comment]
if (Platform.OS === 'ios') {
        let arr = uri.split('/')
        const dirs = RNFetchBlob.fs.dirs
        filePath = `${dirs.DocumentDir}/${arr[arr.length - 1]}`
    } else {
        filePath = uri
    }

    RNFetchBlob.fs.readFile(filePath, 'base64')
        .then((data) => {
            // handle the data ..
            console.log(data)
            const IMAGE = 'data:image/png;base64,'+data
            let shareImageBase64 = {
                title: "React Native",
                message: "Hola mundo",
                url: IMAGE,
                subject: "Share Link" //  for email
            };
    
    
            Share.open(shareImageBase64);
        })

**Comment by koo27** [comment]
just remove the following section from `AndroidManifest.xml`
```
<provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="${applicationId}.provider"
        android:grantUriPermissions="true"
        android:exported="false">
        <meta-data
          android:name="android.support.FILE_PROVIDER_PATHS"
          android:resource="@xml/filepaths" />
      </provider>
```

This is because you have same record FILE_PROVIDER_PATHS in react-native-image-crop-picker (in its own AndroidManifest.xml file), so you don't need to duplicate it nor replace it.
