### ISSUE TITLE
 Fatal Exception: com.facebook.react.bridge.NoSuchKeyException url

### ISSUE THREAD

**Issue by compojoom** [react-native-share/react-native-share#240]
I'm sure this was working with previous versions, but today crashlytics reported the following error:
```
 Fatal Exception: com.facebook.react.bridge.NoSuchKeyException url
com.facebook.react.bridge.ReadableNativeMap.getNullableValue (ReadableNativeMap.java:128)
com.facebook.react.bridge.ReadableNativeMap.getString (ReadableNativeMap.java:168)
cl.json.social.ShareIntent.getFileShare (ShareIntent.java:74)
cl.json.social.ShareIntent.open (ShareIntent.java:37)
cl.json.social.SingleShareIntent.open (SingleShareIntent.java:57)
cl.json.social.EmailShare.open (EmailShare.java:20)

```

I checked on iOS and the implementation there was working just fine. I thought that I haven't linked something on Android, but it turned out that if I don't provide an url in my shareOptions, then the app crashes with the above message. If I provide url: '', or a real url, then it works fine. 
I didn't want to have an url in my share message, that's why I wasn't adding one. 
I think that the app shouldn't crash when we haven't provided an url... Or is the url really required for something on android?

**Comment by enieber** [comment]
@compojoom this issue can be closed?

**Comment by compojoom** [comment]
I haven‘t tested the new version. If it is working there then I‘m fine with closing this.
