### ISSUE TITLE
Image Sharing for WhatsApp is not working

### ISSUE THREAD

**Issue by iSaadSalman** [react-native-share/react-native-share#280]
So I'm saving a screenshot locally and passing the URI to Share options. Its working fine for every platform except Whats App.
 
`let shareOptions = {
      title: "Share",
      url: this.state.cameraRollUri,
      type: 'image/png',
      message: "Here it is",
      subject: "Share Link", //  for email,
    };

  
    Share.open(shareOptions)`

Just message appears but no image

**Comment by jgcmarins** [comment]
@iSaadSalman application is crashing?
Do you have a stack trace?

**Comment by iSaadSalman** [comment]
No it’s not crashing. Just the image is not being shared in WhatsApp. Check the description I wrote in op.

**Comment by jgcmarins** [comment]
Is it happening on both platforms?

**Comment by iSaadSalman** [comment]
@jgcmarins Just testing on iOS right now. It's happening there.

**Comment by iSaadSalman** [comment]
@jgcmarins Do you have any idea what could be the problem?

**Comment by gaganjot-singh01** [comment]
Same problem

**Comment by jgcmarins** [comment]
@iSaadSalman can you try master?

**Comment by iSaadSalman** [comment]
@jgcmarins I tried by overwriting the module in node_modules since I'm not able to update via npm.

I'm receiving this build error in Xcode:
` Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_InstagramShare", referenced from:
      objc-class-ref in libRNShare.a(RNShare.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by iSaadSalman** [comment]
@jgcmarins any update?

**Comment by jgcmarins** [comment]
@iSaadSalman I could not take a deeper look.
But if you want to help us, PRs are welcome.

**Comment by jgcmarins** [comment]
> @jgcmarins I tried by overwriting the module in node_modules since I'm not able to update via npm.
> 
> I'm receiving this build error in Xcode:
> Undefined symbols for architecture arm64: "_OBJC_CLASS_$_InstagramShare", referenced from: objc-class-ref in libRNShare.a(RNShare.o) ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

Your link is wrong here.
I recommend to remove all node_modules, install lib again, following [README](https://github.com/react-native-community/react-native-share/blob/master/README.md) and also link again.

**Comment by kkbhav** [comment]
@iSaadSalman can you please check after removing 'message' from options, if it is working or not. Whatsapp only allows one of them to be used, i.e. you can only use message or url at a time for whatsapp.

**Comment by iSaadSalman** [comment]
@kkbhav sorry for the very late reply.  Yeah you are right if I remove the message image shows up

**Comment by jgcmarins** [comment]
Is this a bug or what? Can we close this one?
@iSaadSalman what do you think? README must be updated?

**Comment by iSaadSalman** [comment]
@jgcmarins Well if the message overwriting URL is enforced, this but has been resolved

**Comment by iSaadSalman** [comment]
@jgcmarins If you can, maybe add a readme note about this so people know

**Comment by ahaus** [comment]
The problem with message override still exists. Url does not work if I add a message field. Tested with version 1.1.3.

**Comment by KPS250** [comment]
The issue is only on iOS. For Android it works well. Any update on this?

**Comment by tktdw** [comment]
share image on WA work on my Device, and shareOption like this 

> let shareOptions = {
title: "",
url: this.state.cameraRollUri,
message: "",
subject: "", // for email,
}

then i add code 

> } else if  ([options[@"url"] rangeOfString:@"wai"].location != NSNotFound || [options[@"url"] rangeOfString:@"png"].location != NSNotFound || [options[@"url"] rangeOfString:@"jpg"].location != NSNotFound) {
            NSLog(@"Sending whatsapp image");
            
            documentInteractionController = [UIDocumentInteractionController interactionControllerWithURL:[NSURL fileURLWithPath:options[@"url"]]];
            documentInteractionController.UTI = @"net.whatsapp.image";
            documentInteractionController.delegate = self;
            [documentInteractionController presentOpenInMenuFromRect:CGRectMake(0, 0, 0, 0) inView:[[[[[UIApplication sharedApplication] delegate] window] rootViewController] view] animated:YES];
            NSLog(@"Done whatsapp image");
            successCallback(@[]);

on file WhatsAppShare.m line 49

>if ([options[@"url"] rangeOfString:@"wam"].location != NSNotFound || [options[@"url"] rangeOfString:@"mp4"].location != NSNotFound) {
            .....
            successCallback(@[]);
// add code here
        } else {
            text = (NSString*)CFBridgingRelease(CFURLCreateStringByAddingPercentEscapes(NULL,(CFStringRef) text, NULL,CFSTR("!*'();:@&=+$,/?%#[]"),kCFStringEncodingUTF8));
            ......
            }
        }

**Comment by farhanaslam5151** [comment]
url property will not work on android, try this
 onSharePress = (image) => Share.share({
        title: 'Pk Flyer offer',
        message: 'your message here  '+image,
        url: Platform.OS === 'ios' ? image : '' //this will work only on android
        subject: 'Offer'
    });

**Comment by LionelLindt** [comment]
> url property will not work on android, try this
> onSharePress = (image) => Share.share({
> title: 'Pk Flyer offer',
> message: 'your message here '+image,
> url: Platform.OS === 'ios' ? image :"" //this will work only on ios
> subject: 'Offer'
> });

`Share.share` is a method from [React Share](https://facebook.github.io/react-native/docs/share), and not from this library, here it is `open`.

**Comment by EnclaveAnthony** [comment]
> share image on WA work on my Device, and shareOption like this
> 
> > let shareOptions = {
> > title: "",
> > url: this.state.cameraRollUri,
> > message: "",
> > subject: "", // for email,
> > }
> 
> then i add code
> 
> > } else if  ([options[@"url"] rangeOfString:@"wai"].location != NSNotFound || [options[@"url"] rangeOfString:@"png"].location != NSNotFound || [options[@"url"] rangeOfString:@"jpg"].location != NSNotFound) {
> > NSLog(@"Sending whatsapp image");
> 
> ```
>         documentInteractionController = [UIDocumentInteractionController interactionControllerWithURL:[NSURL fileURLWithPath:options[@"url"]]];
>         documentInteractionController.UTI = @"net.whatsapp.image";
>         documentInteractionController.delegate = self;
>         [documentInteractionController presentOpenInMenuFromRect:CGRectMake(0, 0, 0, 0) inView:[[[[[UIApplication sharedApplication] delegate] window] rootViewController] view] animated:YES];
>         NSLog(@"Done whatsapp image");
>         successCallback(@[]);
> ```
> 
> on file WhatsAppShare.m line 49
> 
> > if ([options[@"url"] rangeOfString:@"wam"].location != NSNotFound || [options[@"url"] rangeOfString:@"mp4"].location != NSNotFound) {
> > .....
> > successCallback(@[]);
> > // add code here
> > } else {
> > text = (NSString*)CFBridgingRelease(CFURLCreateStringByAddingPercentEscapes(NULL,(CFStringRef) text, NULL,CFSTR("!*'();:@&=+$,/?%#[]"),kCFStringEncodingUTF8));
> > ......
> > }
> > }

Yes. It works. But we need sharing with a caption. Does anyone have a solution for this?

**Comment by prajnarobo** [comment]
> > share image on WA work on my Device, and shareOption like this
> > > let shareOptions = {
> > > title: "",
> > > url: this.state.cameraRollUri,
> > > message: "",
> > > subject: "", // for email,
> > > }
> > 
> > 
> > then i add code
> > > } else if  ([options[@"url"] rangeOfString:@"wai"].location != NSNotFound || [options[@"url"] rangeOfString:@"png"].location != NSNotFound || [options[@"url"] rangeOfString:@"jpg"].location != NSNotFound) {
> > > NSLog(@"Sending whatsapp image");
> > 
> > 
> > ```
> >         documentInteractionController = [UIDocumentInteractionController interactionControllerWithURL:[NSURL fileURLWithPath:options[@"url"]]];
> >         documentInteractionController.UTI = @"net.whatsapp.image";
> >         documentInteractionController.delegate = self;
> >         [documentInteractionController presentOpenInMenuFromRect:CGRectMake(0, 0, 0, 0) inView:[[[[[UIApplication sharedApplication] delegate] window] rootViewController] view] animated:YES];
> >         NSLog(@"Done whatsapp image");
> >         successCallback(@[]);
> > ```
> > 
> > 
> > on file WhatsAppShare.m line 49
> > > if ([options[@"url"] rangeOfString:@"wam"].location != NSNotFound || [options[@"url"] rangeOfString:@"mp4"].location != NSNotFound) {
> > > .....
> > > successCallback(@[]);
> > > // add code here
> > > } else {
> > > text = (NSString*)CFBridgingRelease(CFURLCreateStringByAddingPercentEscapes(NULL,(CFStringRef) text, NULL,CFSTR("!*'();:@&=+$,/?%#[]"),kCFStringEncodingUTF8));
> > > ......
> > > }
> > > }
> 
> Yes. It works. But we need sharing with a caption. Does anyone have a solution for this?

Any solution for this?

**Comment by msaqlain** [comment]
Facing same issue any update?

**Comment by EnclaveAnthony** [comment]
It is impossible. Just share only message or image. Not both.

**Comment by msaqlain** [comment]
@EnclaveAnthony Is there any way we can send two messages in one share. One for image and next for message.

**Comment by tktdw** [comment]
from this latest [release note for Whatsapp](https://faq.whatsapp.com/en/iphone/23559013). Enclave is right

**Comment by shreyakupadhyay** [comment]
I have found a working workaround for this problem. Currently, I also use it in one of my applications. You can directly plug and play the below **onClick** function on a button press.

**RNFS.downloadFile**, downloads the remote image using **URL** and save it to a path. 
**RNFS.readFile**, converts the locally saved file data to base64 which is supported directly by Whatsapp and other applications.

```
async onClick(url, id){
        const path = `${RNFS.DocumentDirectoryPath}/${id}.jpg`;
        await RNFS.downloadFile({ fromUrl: url, toFile: `file://${path}` }).promise
            .then((res) => {
                return res;
            })
            .catch((err) => {
                return err;
            });
        RNFS.readFile(`file://${path}`, 'base64').then((res) => {
            let shareOptionsUrl = {
                title: 'My Application',
                message: 'Use my application',
                url: `data:image/jpeg;base64,${res}`, // use image/jpeg instead of image/jpg
                subject: 'Share information from your application'
            };
            Share.open(shareOptionsUrl);
        })
    }
```

**Url** is the image remote URL and **id** is some unique identifier for that image.

**Comment by tarbundiyahitesh21** [comment]
**Share.shareSingle(options)** share image on whatsapp is not working while **Share.open(options)** working perfectly.
any solution ?
