### ISSUE TITLE
Add .npmignore file for future release.

### ISSUE THREAD

**Issue by kkbhav** [react-native-share/react-native-share#300]
add following lines in file:
example/*
assets/*

**Comment by jgcmarins** [comment]
I don't think we should take it to 1.0.28, since there's lot's of breaking changes

**Comment by jgcmarins** [comment]
hey, @kkbhav could you please join here: https://join.slack.com/t/rn-community/shared_invite/enQtMzY0MDgxODcwOTYyLWEwNWY3Njc0Mzg1MzllYWVhNTU4NTY5MGY5NjQ2ZWM1MGFkY2QzMTljYWY2NzE0NTU4MmM3NTBkY2ZiZmIzMWY
?

**Comment by enieber** [comment]
maybe in version **1.0.29** @kkbhav @jgcmarins

**Comment by jgcmarins** [comment]
no, at least a minor change, something like `1.1.0`

**Comment by kkbhav** [comment]
@jgcmarins I have joined the slack group. and yes there are some big changes, so we should move the version to 1.1.0

BTW, what are the timelines for the release
