### ISSUE TITLE
iOS sharing attaches [appname].app file

### ISSUE THREAD

**Issue by nickmccomb** [react-native-share/react-native-share#306]
When the following code is used on iOS, the sharing function attaches a 'sparkplugs.app' file to the message, which then fails on everything (Facebook, Insta, Snapchat etc) except for email.

It works fine on Android (doesn't attach a file).  On iOS it does attach a file, which fails sending to everything except email.  The file is named after my app 'sparkplugs', so the attached file is 'sparkplugs.app'.  No idea why it tries to attach this.  It doesn't even open on a Mac when trying to open the file when the email is received.

**How to stop the file being attached on iOS?**

``` 
  shareNumber = (number) =>{
    let options = {
      title: "sparkplugs",
      message: "My phone number is " + number + "\n\nwww.sparkplugs.io",
      subject: this.props.name + "'s phone number",
      url:''
    };

    Share.open(options)
    .then((res) => { console.log(res) })
    .catch((err) => { err && console.log(err); });
  }
```

**Comment by rheng001** [comment]
Facing the same issue

**Comment by sujitpk-perennial** [comment]
+1

**Comment by sujitpk-perennial** [comment]
@nickmccomb @rheng001  have you find any solution?

**Comment by jgcmarins** [comment]
@miguelbassila looks like we found a solution.
Question: should we fix it on lib or just improve README?

**Comment by miguelbassila** [comment]
@jgcmarins I think it's easier to improve README for now but we could try to patch a fix on https://github.com/facebook/react-native/blob/master/Libraries/ActionSheetIOS/RCTActionSheetManager.m#L134, which is the native class ActionSheetIOS uses, to check if url is absent before try to call `RCTConverter`

would be a pleasure to do both 😄

**Comment by jgcmarins** [comment]
@miguelbassila PR's are welcome \o/
We can do it and release a new version as soon as possible.

**Comment by jgfidelis** [comment]
Ain't  it easier to do on the RNShare lib something like:
```
const { url } = options;
let safeUrl = url;
if (!url || url.length === 0) {
  safeUrl = 'MY_RANDOM_URL';
}
...call native code...
```

**Comment by jgcmarins** [comment]
@jgfidelis great
