### ISSUE TITLE
react-native-share doesn't work properly for facebook

### ISSUE THREAD

**Issue by zoranmarjanovic** [react-native-share/react-native-share#307]
0
down vote
favorite
I'm trying to upload base64 image and to set message, title and caption, and it seems that it doesn't work, basically what happens is that image has been uploaded, but rest of params are ignored. Any help?

Here is the part of code

```
const shareOptions = {
    title: "React Native",
    message: "Hola mundo",
    url: result,
    subject: "Share Link"
}

....

Share.open(shareOptions)
```

Also I have tried to share to email end message and title are filled. Is there some limitations for facebook?

**Comment by zoranmarjanovic** [comment]
stackoverflow link https://stackoverflow.com/questions/51315063/react-native-share-doesnt-work-properly-for-facebook

**Comment by jgcmarins** [comment]
Check this guid to share base64: https://github.com/react-native-community/react-native-share#share-remote-pdf-file-with-gmail--whatsapp-ios

**Comment by zoranmarjanovic** [comment]
@jgcmarins, I don't have a problem with image, it is uploaded, but other fields, like, title, caption, message, ... Basically I have tried with some link as url param, and it is the same, link is shared but everything else is ignored.

**Comment by lizhuoyuan** [comment]
So what should I do to solve this problem

**Comment by zoranmarjanovic** [comment]
Nothing, based on this docs https://developers.facebook.com/policy/#socialplugins facebook is little bit restricted about the way how you can do share through 3rd party applications
