### ISSUE TITLE
Facebook iOS not working

### ISSUE THREAD

**Issue by ilcesco** [react-native-share/react-native-share#384]
### Steps to reproduce
1. Use `shareSingle`

This is what I am doing:
```
const shareOptions = {
      url: picture.uri, // <<<< dynamic
      social: social === 'instagram' ? Share.Social.INSTAGRAM : Share.Social.FACEBOOK,
    };

    Share.shareSingle(shareOptions)
      .then((res) => { console.log(res); })
      .catch((err) => { err && console.log(err); });
```

### Expected behaviour
Open the Facebook app to share the image.

### Actual behaviour
Safari will open and I have the following image: `href should represent a valid URL`.
The `console.log` of the promise tells me that the application is not installed (instead it is installed).
![screenshot 2018-10-17 at 17 44 58](https://user-images.githubusercontent.com/38096561/47098912-705bd900-d234-11e8-8f4b-662298e3752b.png)

### Environment
- **React Native version**: 0.57.1
- **React Native platform + platform version**: iOS 12

### react-native-share
**Version**: master (1.1.2)

**Comment by jgcmarins** [comment]
could you try master version?
could you provide a repo to reproduce?

**Comment by ilcesco** [comment]
Yes, just need some time for it. I will give you one ASAP.

**Comment by ilcesco** [comment]
> could you try master version?  ----> **Yes**
> could you provide a repo to reproduce? ----> Yes, have to create a small project for it. I'll do ASAP.

**Comment by ilcesco** [comment]
@jgcmarins  So, here I am again.
You can check a repo example here: https://github.com/IronTony/RNShareExample
I had already linked this example. On android everything is working super-fine, both Facebook and Instagram.
_On iOS nothing works._
**Facebook** gives back this: `href should represent a valid URL` opening Safari instead of the lates Facebook app installed on iOS.
**Instagram** opens the latest app, but everytime it seems that I am not logged in (this works on Android).

**Comment by jgcmarins** [comment]
@ilcesco, thanks.
I'll take a look as soon as possible.

**Comment by ilcesco** [comment]
@jgcmarins With the latest version of Instagram release today (22 oct) seems working again on iOS.
Facebook still not working

**Comment by ilcesco** [comment]
@jgcmarins Hi, any news about this problem? Just to know also if I can help

**Comment by jgcmarins** [comment]
Still didn't get into it, sorry.

**Comment by KarenMosavat** [comment]
under share button function you can use facebook share function very easy and its work on IOS
facebook link:
[https://developers.facebook.com/docs/react-native/sharing/]
sample:
         <Button iconSrc={{ uri: FACEBOOK_ICON }}
                  onPress={()=>{
                    ShareDialog.canShow(shareLinkContent).then(
                      function(canShow) {
                        if (canShow) {
                          return ShareDialog.show(shareLinkContent);
                        }
                      }
                    )
            }}>Facebook</Button>

**Comment by gypsicoder** [comment]
I am also having the same type of issue. When I share URL in SingleShare in facebook it even don't show the image and other meta data. It's working in android.

**Comment by gypsicoder** [comment]
Did anyone have fixed the problem or I am the only one facing the issue? :P

**Comment by MateusAndrade** [comment]
@gypsicoder i remember to be using this without any problem at a project sometime ago. Did you tried the last version on npm or the master?

**Comment by gypsicoder** [comment]
@MateusAndrade  I am not facing problem in sharing. It's just not showing the image, title and description from meta data. It's showing image and other things in android perfectly.

**Comment by navasiloy** [comment]
You can use `Linking.canOpenURL('fb://')` to detect if it's installed or not

**Comment by jonasgroendahl** [comment]
Not working for me either, i tried react-native-fbsdk but I get prompted to login into facebook. I'm not sure what's the best way to get the single share option with facebook is currently for react native

**Comment by MateusAndrade** [comment]
Hi @jonasgroendahl , would you mind sharing the version that you are using. Also, a sample code would help us. 😄

**Comment by jonasgroendahl** [comment]
This is what I tried following the example here:

import Share from 'react-native-share';

const shareOptions = {
    title: 'Share via',
    message: 'some message',
    url: 'some share url',
    social: Share.Social.FACEBOOK
};
Share.shareSingle(shareOptions);

The version is 3.3.0

**Comment by matthiasthomas** [comment]
Experiencing the same issue. Instagram is working fine but facebook just opens up Safari with `href should represent a valid URL`. 

Here's the code:
```javascript
Share.shareSingle({
 url: asset.assetUri,
 social: Share.Social.FACEBOOK,
});
```

**Comment by Asalem1** [comment]
What @matthiasthomas pointed out worked for me. All i had to do was edit the `Info.plist` to include `<string>fb</string>` as an property of the `LSApplicationQueriesSchemes` array. For clarity, I had to add the key AND array to the Info.plist in order to get Facebook sharing to work properly since it didn't exist by default.
