### ISSUE TITLE
iOS: shareSingle on instagram open camera even if photo url (base64) is passed to url parameter

### ISSUE THREAD

**Issue by atlkuk** [react-native-share/react-native-share#389]
### Steps to reproduce
```
RNFetchBlob.fs.readFile(path, 'base64')
.then(result => {
    const shareOptions = {
         url: `data:image/jpeg;base64,${result}`,
         social: Share.Social.INSTAGRAM
    };
Share.shareSingle(shareOptions)
.then((data) => console.log(data))
.catch((error) => console.log(error));
```

### Expected behaviour
Instagram should show sharing with my photo already loaded

### Actual behaviour
Instagram show camera to catch a new photo

### Environment
- **React Native version**: 0.57.2
- **React Native platform + platform version**: iOS 12.0.1

### react-native-share
**Version**: 2.4.2

**Comment by yeomann** [comment]
maybe it is something Instagram default behavior now 🤔 ?

**Comment by atlkuk** [comment]
I don't think so. On android I can share my photo as before.

**Comment by ahilles107** [comment]
i have this same issue - no solution yet ;/

**Comment by Desintegrator** [comment]
same

**Comment by ethanyuwang** [comment]
same issue here

**Comment by ethanyuwang** [comment]
Has anyone solved this?

**Comment by Vikas-Sharma7** [comment]
Still happening.

**Comment by MateusAndrade** [comment]
Sharingan with a URL works?

**Comment by pragadeeshk** [comment]
Same issue still happening

> Sharing with a URL works?

It doesn't even open the share window.

**Comment by jgcmarins** [comment]
is this related: https://github.com/react-native-community/react-native-share/issues/232
?

**Comment by MateusAndrade** [comment]
> is #232 related?

Its possible, when i was working with rn-share trying to send a base64 was problematic with some apps. I decided instead, to send the relative image Path. By doing this, It Works on most of the cases.
