### ISSUE TITLE
Improve automated tests

### ISSUE THREAD

**Issue by jgcmarins** [react-native-share/react-native-share#391]
- [ ] use [react-native-testing-library](https://github.com/callstack/react-native-testing-library)
- [ ] setup on circle ci

follow this: https://github.com/entria/ReactNavigationRelayModern/pull/32

**Comment by mikehardy** [comment]
if/when we set up on CircleCI, it's possible to do ios builds. We need to make sure we do debug and release builds I think as it's clear that they can have completely different header, framework, and link search paths. I've seen the same in other libraries where debug is good and release doesn't work...

**Comment by mikehardy** [comment]
@MateusAndrade ☝️

**Comment by jgcmarins** [comment]
- [ ] it should run build on ci

**Comment by mikehardy** [comment]
It should run *debug and release* build on CI :-). That's the key. Note that lots of repos (like netinfo) have the ios build working well, but I don't think even they do the release version. Not sure it is possible (with all the cert management required...ugh iOS) but it should be a goal. That's what got us with v1.2.0 - debug was fine but iOS release build blew up
