### ISSUE TITLE
Error While building the project with both rn-fetch-blob and react-native-share

### ISSUE THREAD

**Issue by NawazKhanMd** [react-native-share/react-native-share#399]
### Steps to reproduce
I have rn-fetch-blob and react-native-share both installed after both installations am getting this below error when I try to build

### Actual behaviour

D:\BFM Mobile\New Vpp\Visionplanner_BFM_Mobile\android\app\src\main\AndroidManifest.xml:17:13-76 Error:
        Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.visionplanner_bfm_mobile.fileprovider) from AndroidManifest.xml:17:13-76
        is also present at [:rn-fetch-blob] AndroidManifest.xml:38:13-60 value=(com.visionplanner_bfm_mobile.provider).
        Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:15:7-23:20 to override.
D:\BFM Mobile\New Vpp\Visionplanner_BFM_Mobile\android\app\src\main\AndroidManifest.xml:22:17-50 Error:
        Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/filepaths) from AndroidManifest.xml:22:17-50
        is also present at [:rn-fetch-blob] AndroidManifest.xml:43:17-55 value=(@xml/provider_paths).
        Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml:20:13-22:53 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

### Environment
- **React Native version**: "0.57.3",
- **React Native platform + platform version**: Android 8.0

### react-native-share
**Version**: npm version or "master"  "^1.1.3"

### Link to repo (highly encouraged)
https://github.com/

**Comment by mikehardy** [comment]
I use both of these projects at the same time as well. I have not seen this, so it seems you have something specific to your project in the AndroidManifest.

There's a suggestion to add tools:replace attributes to resolve the issue, what was the result when you tried that?

**Comment by mikehardy** [comment]
Also worth noting you linked to a page on manifest mergers that is marked as outdated and automatically redirects you to the current information, have you read the updated document? https://developer.android.com/studio/build/manifest-merge

**Comment by NawazKhanMd** [comment]
@jgcmarins @mikehardy 

look at this repository I just added both the plugins and while building am getting the same error

https://github.com/NawazKhanMd/myexamples/tree/master/share_three

**Comment by jgcmarins** [comment]
If any of packages is removed, build process pass?

**Comment by NawazKhanMd** [comment]
Yes

**Comment by jgcmarins** [comment]
the [troubleshooting](https://github.com/react-native-community/react-native-share#troubleshooting) docs with rn fetch blob didn't help?

**Comment by maxkomarychev** [comment]
I have similar problem

A bit mor context:
rn-fetch-blob from master (commit https://github.com/joltup/rn-fetch-blob/commit/70fcb3a2c448cbd480a0e75ad8f027a4a10263c8)
react-native-share 1.1.3

**Comment by maxkomarychev** [comment]
> the troubleshooting docs with rn fetch blob didn't help?

the troubleshooting section is not very relevant since it is related to the workaround of totally different issue, in our case android app does not event build

**Comment by yeomann** [comment]
how about you try @NawazKhanMd  to install react-native-share first and the make a build to see. if you are linking properly or not. If your build is a success that means the error might be from blob.

**Comment by NawazKhanMd** [comment]
@yeomann  I f i have only one package app builds fine, if both are installed and linked, i get the issue, its reproducing in https://github.com/NawazKhanMd/myexamples/tree/master/share_three

**Comment by NawazKhanMd** [comment]
@jgcmarins  This is not listed in Trouble Shooting docs

**Comment by NawazKhanMd** [comment]
I have resolved the issue by removing

Provider Tag in AndroidManifest file of rn-fetch-blob. Event though that tag is removed, all the features of rn-fetch blob are working. am a lil confused, removing that must raise big issues but it didnt.

am worried cuz if someone does npm install and AndroidManifest is recreated with provide tag and issue is reproduced

**Comment by NawazKhanMd** [comment]
We need a solution to this....

**Comment by mikehardy** [comment]
I see this comment on the related rn-fetch-blob issue: https://github.com/joltup/rn-fetch-blob/issues/230

https://github.com/joltup/rn-fetch-blob/issues/230#issuecomment-438028912

I don't think anyone would disagree with a good solution - and that proposal may have merit but it seems most of the effort is in the fetch-blob repo - https://github.com/joltup/rn-fetch-blob/compare for new PRs with them ?

**Comment by NawazKhanMd** [comment]
@mikehardy yeah I guess both issues are raised by me 

i know the solution is found, but is it possible to know why it came, i dont understand many paople claimed they have both the dependencies and never face the issue, Why now.

**Comment by mikehardy** [comment]
A good question and it might just be your specific mix of library versions - even if standard from the repos the upgrades within the repos are ongoing. You might just be first? Though I use them myself. I'm not aware of provider changes (in the Android framework) recently though, so it's puzzling, yes.

**Comment by maxkomarychev** [comment]
@NawazKhanMd people don't have these issues in their projects because "provider" thing was added into `react-native-fetch-blob` few months ago, I bet they use older version. I did not have this problem until I updated both share and blob :)

**Comment by maxkomarychev** [comment]
I guess it started here: https://github.com/joltup/rn-fetch-blob/commit/a88b59f0e9f62330a5f2a5a7921b6869ba7228b3
If you try to downgrade rn-fetch-blob one commit before it will work fine

**Comment by NawazKhanMd** [comment]
I dont understand the clash between two

The only thing they have in common is `android.support.FILE_PROVIDER_PATHS`

apart from that everything is different, different filepaths different name.

is this a limitation from android?
`android.support.FILE_PROVIDER_PATHS`   is this should only be one of the third party packages?

**Comment by indapublic** [comment]
@NawazKhanMd Had same error. Just remove new section from `AndroidManifest.xml`

> <provider
>         android:name="android.support.v4.content.FileProvider"
>         android:authorities="com.carggo.carrierapp.provider"
>         android:grantUriPermissions="true"
>         android:exported="false">
>         <meta-data
>           android:name="android.support.FILE_PROVIDER_PATHS"
>           android:resource="@xml/filepaths" />
>       </provider>

**Comment by TimurAsayonok** [comment]
@indapublic did you try share image after your changes?

**Comment by TimurAsayonok** [comment]
@indapublic Can you try send send image? Because I have crash, and think that delete this part in not a good solution

**Comment by jgcmarins** [comment]
@TimurAsayonok does this crash has any stack trace?

**Comment by TimurAsayonok** [comment]
@jgcmarins No, Does not. Just default message alert that Messaging app has stopped.

**Comment by indapublic** [comment]
@TimurAsayonok `base64` or `path`?

**Comment by TimurAsayonok** [comment]
@indapublic `path`

**Comment by indapublic** [comment]
@TimurAsayonok It works. Unfortunately, it's enterprise project and I can't provide demo for this.
My main idea is that we have same record `FILE_PROVIDER_PATHS` in `rn-fetch-blob` so we don't need to duplicate it for `react-native-share`

**Comment by indapublic** [comment]
@TimurAsayonok btw. are you tried in simulator?

**Comment by TimurAsayonok** [comment]
@indapublic Yes, I tried in simulator, and if I use `base64` it's works (more or less) because for it we use `rn-fetch-blob` which uses `FILE_PROVIDER_PATHS` for getting image by uri from phone.
But if you try to use `path` using `FILE_PROVIDER_PATHS` from `rn-fetch-blob` it's shouldn't work

**Comment by indapublic** [comment]
My code is about file downloading using `rn-fetch-blob` with `fileCache: true` and sharing it with `path`. Seems it's not your case :)

**Comment by TimurAsayonok** [comment]
@indapublic Do u save this file on phone? and do u use Share.open({ url: path }) for sharing?

**Comment by TimurAsayonok** [comment]
I think, that part with creating `FILE_PROVIDER_PATHS` in application AndroidManifest.xml is not a good adea. Because I try to comment FileProvider part in rn-fetcg-blocl lib, and got Error While building the project with `react-native-image-crop-picker` lib (because this lib use FileProvider in it's AndroidManifest.xml )

**Comment by indapublic** [comment]
@TimurAsayonok you are correct about
> Do u save this file on phone? and do u use Share.open({ url: path }) for sharing?

**Comment by TimurAsayonok** [comment]
@indapublic maybe my problem is that I don't share photo from `Download/` folder. We have this instruction in our xml file `<external-path name="myexternalimages" path="Download/" />`

When I try to share photo with path `"file:///data/user/0/com.my_app/cache/react-native-image-crop-picker/IMG_20181126_173001.jpg"` I got error in Sentry `{"error":"Failed to find configured root that cont…"}`

**Comment by indapublic** [comment]
So you use `react-native-image-crop-picker` too.
Could you create some demo?

**Comment by TimurAsayonok** [comment]
@indapublic Yes I use `react-native-image-crop-picker`. Unfortunately I can't create demo =(

**Comment by TimurAsayonok** [comment]
looks like that all ways merge to this issue https://github.com/react-native-community/react-native-share/issues/218 #

**Comment by jgcmarins** [comment]
Awesome!
We could improve README with this steps... What do you think?

> I'm using `react-native-share`, `react-native-image-crop-picker` and `rn-fetch-blob`
> What do you think about it?

I think it is great! Certainly a real production scenario.
My suggestion: improve [example](https://github.com/react-native-community/react-native-share/tree/master/example). Add those libs there, so we could have a more complex example with real production scenario.

**Comment by indapublic** [comment]
@TimurAsayonok I'll try to reproduce it on my private project and check. Awesome! Thanks

**Comment by indapublic** [comment]
Agreed, example would be helpful definitely

**Comment by TimurAsayonok** [comment]
@indapublic @jgcmarins Awesome! Let me know after your changes

**Comment by jgcmarins** [comment]
@TimurAsayonok nice! PRs are welcome \o/

**Comment by jgcmarins** [comment]
we already have a section for `filepaths` on [Android Install steps](https://github.com/react-native-community/react-native-share/blob/master/README.md#android-install).
if it makes sense, we could improve that or add alternative solution.

**Comment by TimurAsayonok** [comment]
> we already have a section for `filepaths` on [Android Install steps](https://github.com/react-native-community/react-native-share/blob/master/README.md#android-install).
> if it makes sense, we could improve that or add alternative solution.

But if we change  `filepaths` name to `provider_paths.xml` it will fix `Error While building the project`

Adding `<root-path name="root" path="." />` will help in case if you use `react-native-image-crop-picker`

**Comment by zeekay18** [comment]
I solved this by removing the provider declaration from the manifest file
