### ISSUE TITLE
:react-native-share:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by prabhu73** [react-native-share/react-native-share#405]
### Steps to reproduce
Step 1: npm install --save react-native-share
Step 2: npm link
Step 3: npm link react-native-share
Step 4: Killall node -9
Step 5: sudo react-native run-android

### Expected behaviour
It should execute/build the project 

### Actual behaviour
> Task :react-native-share:compileDebugJavaWithJavac FAILED
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/ShareFiles.java:8: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/ShareFile.java:10: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:6: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:91: error: cannot find symbol
    public void open(ReadableMap options, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
                                           ^
  symbol:   class Nullable
  location: class RNShareModule
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:91: error: cannot find symbol
    public void open(ReadableMap options, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
                                                                               ^
  symbol:   class Nullable
  location: class RNShareModule
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:108: error: cannot find symbol
    public void shareSingle(ReadableMap options, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
                                                  ^
  symbol:   class Nullable
  location: class RNShareModule
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:108: error: cannot find symbol
    public void shareSingle(ReadableMap options, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
                                                                                      ^
  symbol:   class Nullable
  location: class RNShareModule
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:134: error: cannot find symbol
    public void isBase64File(String url, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
                                          ^
  symbol:   class Nullable
  location: class RNShareModule
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/RNShareModule.java:134: error: cannot find symbol
    public void isBase64File(String url, @Nullable Callback failureCallback, @Nullable Callback successCallback) {
                                                                              ^
  symbol:   class Nullable
  location: class RNShareModule
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/ShareFiles.java:161: error: cannot find symbol
                    finalUris.add(FileProvider.getUriForFile(reactContext, authority, file));
                                  ^
  symbol:   variable FileProvider
  location: class ShareFiles
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/ShareFiles.java:166: error: cannot find symbol
                finalUris.add(FileProvider.getUriForFile(reactContext, authority, new File(uri.getPath())));
                              ^
  symbol:   variable FileProvider
  location: class ShareFiles
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/ShareFile.java:135: error: cannot find symbol
                return FileProvider.getUriForFile(reactContext, authority, file);
                       ^
  symbol:   variable FileProvider
  location: class ShareFile
/Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/ShareFile.java:143: error: cannot find symbol
            return FileProvider.getUriForFile(reactContext, authority, new File(uri.getPath()));
                   ^
  symbol:   variable FileProvider
  location: class ShareFile
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/prabhudas/StudioProjects/TilaWithReactJS/node_modules/react-native-share/android/src/main/java/cl/json/ShareFiles.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
13 errors

FAILURE: Build failed with an exception.

### Environment
- **React Native version**:
- **React Native platform + Android 8.0**: Android 8.0, etc

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by jgcmarins** [comment]
looks like it didn't link correctly

**Comment by prabhu73** [comment]
I have used the following commands to build and link

Step 1: npm uninstall react-native-share --save-dev
Step 2: npm install --save react-native-share
Step 3: npm link
Step 4: npm link react-native-share
Step 5: Killall node -9
Step 6: react-native run-android

After the last command, I got the above build error

**Comment by jgcmarins** [comment]
`npm link` will duplicate all previous linkable libraries
just `npm link react-native-share` is enough

**Comment by umkhan65** [comment]
I'm having the same issue with react-native@0.57.4

**Comment by umkhan65** [comment]
I was using rn-share@v2 then I downgrade to rn-share@v1 to make it work with react-native version less 0.60

**Comment by jgcmarins** [comment]
rn 60 and beyond only works with v2

**Comment by abh1abii** [comment]
+1
