### ISSUE TITLE
Sharing to Gmail app sets body as subject

### ISSUE THREAD

**Issue by kennym** [react-native-share/react-native-share#414]
### Steps to reproduce
1. Call share dialog with `title`/`subject` set to `test`, and set `body` param to `test body`
2. When opening with Gmail app, the subject line and body will be set to `test body`, effectively ignoring the subject/title params

### Expected behaviour
Email subject set to 'test'

### Actual behaviour
Email subject set to 'test body'

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: iOS 12.1.2

### react-native-share
**Version**: 1.1.3

**Comment by SergeyNedayvoda** [comment]
+ 1

**Comment by rlemasquerier** [comment]
Same issue here, occurring on iOS only.

**Comment by nartjie101** [comment]
+1

**Comment by kennym** [comment]
any comment?

**Comment by MateusAndrade** [comment]
> any comment?

You can give a try ate the latest version? I suspect this is something related on how the app handle params on both ios and android, when calling Share.

You can provide the sample code that you used in this test?

**Comment by VivekSharma-zymr** [comment]
same issue facing. did any one got solution for this? 
Any other alternative to handle share to all installed apps including gmail.

**Comment by kennym** [comment]
@MateusAndrade share anything on iOS with your library to the Gmail app... you'll see what we mean.

**Comment by MateusAndrade** [comment]
> @MateusAndrade share anything on iOS with this library to the Gmail app... you'll see what we mean.
> 
> Basically using the same code you provide in the README.

Im going to give a try with this today. Thanks for your feedback. :smile:

**Comment by sitanshu-zymr** [comment]
Any ETA, To fixing this? Its a kind of eyecatcher thing.

**Comment by sitanshu-zymr** [comment]
@here Any ETA?

**Comment by mikehardy** [comment]
As soon as you PR a change to the example that lets others test I'm guessing :-). Asking for ETAs in open source is like heading to the charity food center and asking why they aren't hurrying up with your free stuff right?

**Comment by sitanshu-zymr** [comment]
Ok I will try.

**Comment by dungkv-1044** [comment]
same issue :( 
occurring on ios :(

**Comment by MateusAndrade** [comment]
> same issue :(
> occurring on ios :(

HI @dungkv-1044 recently we landed a PR that handle this. You can gave a look at this here: https://github.com/react-native-community/react-native-share#sharesingleoptions-in-ios--android

#557

**Comment by thisisablock** [comment]
with the latest master

on Android, everything is fine.
on iOS the target email address and subject is not filled.

const options = {
      url: blob,
      email: 'hello@world.com',
      subject: 'Hellol',
      type: 'application/pdf',
      social: Share.Social.EMAIL
}

**Comment by MateusAndrade** [comment]
@thisisablock you can try pass a ```share_subject```to the options? This was implemented on #38

**Comment by thisisablock** [comment]
@MateusAndrade 

made a retest on the latest master branch on iOS 13.1.1

const options = {
  url: blob,
  email: 'hello@world.com',
  subject: 'Hellol',
  type: 'application/pdf',
  social: Share.Social.EMAIL
}

on iOS 13.1.1 Subject is now working. 
But the email sender is still not working on iOS. 
Android works as expected.

**Comment by leteach** [comment]
I am having the same issue. Any word on a fix?

**Comment by nehaj2995** [comment]
target email not setting in android ,how do I fix this ?

**Comment by RadoAz** [comment]
Hi! Any updates here? We have react-native-share 3.0.0 and bug is still here.

**Comment by MateusAndrade** [comment]
> Hi! Any updates here? We have react-native-share 3.0.0 and bug is still here.

Hi @RadoAz ? Which payload are you passing to Share?

**Comment by RadoAz** [comment]
On iOS. PDF file
const options = {
            message: 'message.',
            type: type,
            url: filePath
          };

**Comment by Gazfay** [comment]
Any updates? Still have this issue in 3.1.2.

**Comment by AlixBou** [comment]
The issue is still present on 3.2.0

Code used : 
Share.open({
      message: 'message',
      subject: 'subject',
    });

Result on the native mailer of ios 13 : 
![image](https://user-images.githubusercontent.com/54619037/78884329-0738d880-7a5b-11ea-9e37-31f8f8a13a88.png)

Result on gmail : 
![image](https://user-images.githubusercontent.com/54619037/78884312-0011ca80-7a5b-11ea-94b6-96858e99b004.png)

**Comment by KisaneNeko** [comment]
Anyone had luck finding a workaround for this issue? Config proposed by @thisisablock did not change anything for me - subject is still replaced with message in gmail app

**Comment by jozan** [comment]
I'm seeing this issue only on iOS and Gmail app. Gmail app seems to ignore `type` or `filename` on iOS. I suspect that sharing a file from filesystem could work but I haven't tested that.

```js
Share.open({
  url: fileRef.current, // 'data:application/pdf;base64,<my pdf file data>'
  title: 'PDF-file',
  type: 'application/pdf',
  subject: 'PDF-file',
  filename: 'PDF-file.pdf',
})
```

This work for any other app I have tested on iOS. On Android this works with Gmail.

**Comment by johnvalari** [comment]
Any workaround for this issue?

**Comment by MateusAndrade** [comment]
> Any workaround for this issue?

The @jozan answer doesn't work for you?

**Comment by johnvalari** [comment]
@MateusAndrade I'm not sharing any file. Just texts and that doesn't look like a workaround. @jozan confirmed it is still problematic in Gmail.

**Comment by hieuhoit** [comment]
still present on 3.7.0

**Comment by sergiulucaci** [comment]
hei guys, after a quick search I found a few issues related to this:

* https://stackoverflow.com/questions/37953826/uiactivityviewcontroller-unable-to-set-subject-when-sharing-to-gmail-app
* https://stackoverflow.com/questions/29765806/uiactivityviewcontroller-gmail-share-subject-and-body-going-empty

So it might be a gmail bug instead. Just try share a iOS note (from **Notes**) app via GMAIL. The entire body will be set as subject.

**Comment by d-patira** [comment]
Probably put a lot of empty space in front of the message, that will at-least clear off the subject field in iOS Gmail app.

For eg: 
const space = `
`;

Share.open({
title: "your title here",
subject: "your subject here",
message: space+ 'your message here'
})

**Comment by Dror-Bar** [comment]
In regard to Gmail ignoring title / subject - this seems to be a bug with gmail app and not with this library. You can test this on your device - try to share a note and you will notice it has no subject (while sharing with apple email app has a subject).

**Comment by clemaccountable** [comment]
Any chance to re-open this issue? This bug is still happening

**Comment by Jaseyacey** [comment]
Is there any progress here? Still an issue

**Comment by MorganTrudeau** [comment]
You can start your message with "\n" so the subject is blank. Let the user enter their own subject. Arguably better.

**Comment by HyopeR** [comment]
I tried it for Android and Ios. This bug still persists for Ios.

1- On Android phones, gmail correctly takes the "Subject" field.
2- On IOS phones, gmail takes "Message" field instead of "Subject" field.

**Comment by dimaokk** [comment]
same problem
