### ISSUE TITLE
Sharing csv file in base64 downloads the file

### ISSUE THREAD

**Issue by sdvig** [react-native-share/react-native-share#419]
We want to implement the following functionality:
When the user interacts with the app, they input data.
They have the option to export this data as csv file. And instead of saving it on the mobile device, we thought to allow the user to share this file (to private email e.g). Because this data is private and we didn't want it to be stored on the device itself.
So when exporting it, we convert it to base64 and call Share.open method with the encoded string as url property. 
What happens is that the file first being downloaded in two copies (eg. `2040398370351.csv` and another file with similar name to the Downloads folder `/storage/emulated/0/Download`).
I wonder if this is a bug or intended to work so, or mb any advice to our use case. How to avoid these files being stored on the device?

### Steps to reproduce
1. Convert csv file to base64
2. Try to share the file (just opening the menu is enough)
3. Check Downloads folder (I use a file manager app)

### Expected behaviour
No files stored on the device.

### Actual behaviour
The one explained above ^^^

### Environment
- **React Native version**: 0.56.0
- **React Native platform + platform version**: Android 6.0.1

### react-native-share
**Version**: 1.1.3

### Code
```
export default async function openShareDialogAndExport() {
  let data
  const labels = settings.export
  try {
    data = getDataAsCsvDataUri()
    if (!data) {
      return alertError(labels.errors.noData)
    }
  } catch (err) {
    console.error(err)
    return alertError(labels.errors.couldNotConvert)
  }

  try {
    await Share.open({
      title: labels.title,
      url: data,
      subject: labels.subject,
      type: 'text/csv',
      showAppsToView: true
    })
  } catch (err) {
    console.error(err)
    return alertError(labels.errors.problemSharing)
  }
}
```

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-share/blob/master/android/src/main/java/cl/json/ShareFile.java#L118

Should probably call [java.io.File.deleteOnExit()](https://developer.android.com/reference/java/io/File.html#deleteOnExit()) ?

**Comment by pavelustenko** [comment]
Issue still present

**Comment by MateusAndrade** [comment]
> Issue still present

Do you mean sharing a file and deleting this after sharing?

**Comment by jfr3000** [comment]
Hi, has there been any progress on this?

**Comment by MateusAndrade** [comment]
> Hi, has there been any progress on this?

Have you tried the latest version ?

**Comment by jfr3000** [comment]
Not yet, because this was marked as stale and closed without reference to a fix. I guess I'll give it a try?

**Comment by emrebarutcu** [comment]
Issue still exists. I tried to share an image with base64 data and after share, I saw file exsists in download folder.

**Comment by henrik-d** [comment]
We also have the problem, that an image gets created in the download folder. We noticed it, because sharing failed for some users with the following exception:
```
MediaProvider: Permission to access file: /storage/emulated/0/Download/my_filename.png is denied
System.err: java.io.FileNotFoundException: /storage/emulated/0/Download/mydailyinput.png: open failed: EACCES (Permission denied)
```

**Comment by MateusAndrade** [comment]
> We also have the problem, that an image gets created in the download folder. We noticed it, because sharing failed for some users with the following exception:
> 
> ```
> MediaProvider: Permission to access file: /storage/emulated/0/Download/my_filename.png is denied
> System.err: java.io.FileNotFoundException: /storage/emulated/0/Download/my_filename.png: open failed: EACCES (Permission denied)
> ```

Are you using a `FileProvider` setting with your application?

**Comment by henrik-d** [comment]
@MateusAndrade What is a `FileProvider` in this context? I'm not aware that we're using one.
