### ISSUE TITLE
Message gets repeated for each image(whatsapp only)

### ISSUE THREAD

**Issue by ghost** [react-native-share/react-native-share#421]
### Steps to reproduce
1. Share multiple images with message on whatsapp
 
### Expected behaviour
I expect the message to not be repeated for each image.

### Actual behaviour
The message is appended to each image.

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: Android 5.0

### react-native-share
**Version**: 1.1.3

A code snippet:

```
let shareImageBase64 = {
   message: "Hello"
    urls,
    social: Share.Social.WHATSAPP
  };

  Share.open(shareImageBase64);
```

For each of the image urls, the message gets appended.
I would like to send multiple images with the message appearing just once.

**Comment by LohithaYalavarthi** [comment]
Any Solution for this?

**Comment by jgcmarins** [comment]
Which version of React Native and React Native Share are you facing this?

**Comment by MateusAndrade** [comment]
I dont think if this is possible, since it relies on how WhatsApp handle the sharing actions. But, i recommend giving a look at WhatsApp docs, etc. If you find anything that can help you with that, please let us know. :smile:

**Comment by Pankti16** [comment]
Did you find any solution?

**Comment by MateusAndrade** [comment]
@Pankti16 unfortunately i dont find anything that can help with that, since this looks related to WhatsApp handling share. 😢

Do you know if there is any application that can handle sharing multiple images with different message to whatsapp?

**Comment by Pankti16** [comment]
No, I don't know about any such application, But if its react-native you
can try sending all images in one share call and then make another share
call in its response, to send a message. It is happening in Mesho
application.

**Comment by LohithaYalavarthi** [comment]
Hi guys sorry for the late reply, I am using  "react-native": "^0.59.10", How to make another share call in response means? without opening the WhatsApp again. Can we? , without asking the user to click again the WhatsApp icon?

**Comment by LohithaYalavarthi** [comment]
I am using react-native-share <= 1.2.1:

**Comment by Pankti16** [comment]
No, the user will have to click the WhatsApp icon again.
