### ISSUE TITLE
[Facebook] Sharing with Image

### ISSUE THREAD

**Issue by a-koka** [react-native-share/react-native-share#434]
I realize that not everyone wants to integrate with Facebook but given it's one of the largest social media platforms, is it worthwhile considering a better intgration so that images can be shared when sharing on Facebook?

### Steps to reproduce
Use a `file://` url and notice how `Share.open` will not populate the Facebook post with an image. `Share.shareSingle` actually fails to open the webpage.

### Expected behaviour
This may require an integration with Facebook, but if present, sharing on Facebook is quite easy like below.
```
import { ShareDialog } from 'react-native-fbsdk';

const photoUri = 'file://' + '/path/of/photo.png'
const sharePhotoContent = {
  contentType: 'photo',
  photos: [{ imageUrl: photoUri }],
}
ShareDialog.show(sharePhotoContent);
```

### Environment
- **React Native version**: 0.57.8
- **React Native platform + platform version**: iOS 12

### react-native-share
**Version**: 1.1.3

**Comment by jgcmarins** [comment]
This makes sense.
Maybe we could think about having both implementation, to keep old apps working.
We could use a parameter to open facebook share implementation v2.

**Comment by a-koka** [comment]
After looking into this further, looks like this works as expected on Android. Is this just a limitation on iOS? I'm new here and wasn't sure if this used to work at some point and recently broke.

Also, I'm a big fan of the `Share.open` method which lets the user select the app. My suggestion above would require a knowledge that we're sharing on Facebook. Just wondering how to accommodate for that.

Lastly, since I'm new, I'm not sure if I understand the proposal for a v2 version. Are you referring to the underlying Facebook API usage and is that different on iOS and Android? As I share above, this does work as expected on Android.

Thanks again for staying on top of all issues.

**Comment by jgcmarins** [comment]
Great!

v2 idea would be to use `react-native-fbsdk`

**Comment by jgcmarins** [comment]
Great!

Join our slack channel so I can give you more instructions: https://join.slack.com/t/rn-community/shared_invite/enQtMzY0MDgxODcwOTYyLWEwNWY3Njc0Mzg1MzllYWVhNTU4NTY5MGY5NjQ2ZWM1MGFkY2QzMTljYWY2NzE0NTU4MmM3NTBkY2ZiZmIzMWY

**Comment by a-koka** [comment]
Done! Let me know if you have trouble finding me.

**Comment by murtraja** [comment]
@a-koka are you working on this?

**Comment by a-koka** [comment]
@murtraja This is not as trivial as it seemed at first.

Firstly, FB has some permission issues where it won't let you post both an image and a description/text at the same time. That last time I checked, this just isn't possible using `react-native-fbsdk`.

Secondly, The original proposal was to modify the `share` functionality and use `fb-sdk` if Facebook app was selected. From what I gathered, there is no callback once the app is selected so we can't quite control what happens next. I could be wrong on this but I wasn't able to get much help from the Slack channel so I gave up.

I am personally resolving to a custom UI in my app which let's the user select from a list of apps, and then have complete control over the workflow. The first problem is still a big issue.

**Comment by murtraja** [comment]
@a-koka, I am doing the exact same thing. Also, using react-native-fbsdk will involve signing up for a facebook developer key, which I don't like. When I first saw this issue, I assumed that we aren't able to share images via Facebook, but when I tried, I could share multiple images without the need of any external SDKs which was a win. Hence, I see no need for the integration.

Thanks,

**Comment by manujbahl** [comment]
How can I get the local file url for an online image?

**Comment by murtraja** [comment]
@manujbahl, you need to download the image first. I am using rn-fetch-blob
```javascript
      const path = ((isAndroid)? dirs.DownloadDir : dirs.DocumentDir) + '/' + fileName;
      const res = await RNFetchBlob                                                                                                                                                                                                                                                                                                                                                                     
        .config({
          path,
          session: SESSION_NAME,
        })
        .fetch('GET', imageUrl)
      paths[i] = res.path()
      if(isAndroid) {
        paths[i] = 'file://' + paths[i]
      }
```

**Comment by manujbahl** [comment]
what about iOS?

**Comment by jgcmarins** [comment]
I guess that `rn-fetch-blob` works fine for both Android and iOS
