### ISSUE TITLE
Not work multi sharing on android

### ISSUE THREAD

**Issue by RussianDragon** [react-native-share/react-native-share#435]
![screenshot 2019-01-24 at 15 08 23](https://user-images.githubusercontent.com/12259067/51677214-e5843a80-1fe9-11e9-945f-64e70772225f.png)
Hi.
I have problem with multi sharing on android.
Version react-native-share: 1.1.3

```
 await Share.open({
            title: "Screen photos",
            urls: [`${pathToCamera}/QA_portrait.jpg`,
            `${pathToCamera}/QA_landscapeLeft.jpg`,
            `${pathToCamera}/QA_landscapeRight.jpg`]
        });

```
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <cache-path path="Camera/" name="QA_portrait.jpg" />
  <cache-path path="Camera/" name="QA_landscapeLeft.jpg" />
  <cache-path path="Camera/" name="QA_landscapeRight.jpg" />
</paths>

```
```
 ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }

```

but share single file is OK for android

```
 await Share.open({
            title: "Screen photos",
            url: `${pathToCamera}/QA_portrait.jpg`
        });
```
But, i don't have problem with multi sharing for iOS.

What should I do?

**Comment by jgcmarins** [comment]
This is a warning.
I can't see nothing related to `react-native-share` on stack trace.

**Comment by RussianDragon** [comment]
> This is a warning.
> I can't see nothing related to `react-native-share` on stack trace.

But I don't see sharing popup. Only warning...

**Comment by jgcmarins** [comment]
is it happening on both android and ios?
is there a stack trace error?

**Comment by RussianDragon** [comment]
> is it happening on both android and ios?

Only android

> is there a stack trace error?
The same in the warning

I/System.out: ERROR
    Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
W/ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
    Object {
      "error": "Attempt to invoke virtual method \'boolean java.lang.String.equals(java.lang.Object)\' on a null object reference",
    }

**Comment by jgcmarins** [comment]
possible a bug, do you have a reproducible repo?

**Comment by RussianDragon** [comment]
I understand what my problems.
**It first:** Not uniform documentation.
You ride begin 

> Put this in AndroidManifest.xml where applicationId is something that you have defined in android/app/build.gradle:

`android:authorities="${applicationId}.provider"` 

Then:

> For example: Replace the com.example.yourappidhere below with the applicationId that is defined in your android/app/build.gradle

`return "com.example.yourappidhere.provider";`

If you know what you do - is Ok, but i see this library in first time after searcher and I do not have time for a detailed study - is problem

if call method and have not correctly settings, you send _text_, but not _image_
```
 await Share.open({
            title: "Screen photos",
            url: `${pathToCamera}/QA_portrait.jpg`
        });
```
sending multiple files causes an error, because not join text (i so think)

**It second:**
Don't have exemple inside documentation.
How tune file filepaths.xml ? 
* What names i reading inside files?
* How do they relate paths library react-native-fs (for exemple)?

I found solution in other Issues 
` <root-path name="root" path="." />`
and for demo it is Ok, but not for production solution.

**Please! Modify the documentation...**

**Comment by jgcmarins** [comment]
@RussianDragon I appreciate your feedback!

You can check our example app here: https://github.com/react-native-community/react-native-share/tree/master/example

> **Please! Modify the documentation...**

Sure! Do you mind to open a PR with improvements you've listed? Feel free to modify any part of documentation adding informations you believe that are important.
Thank you!

**Comment by evanjmg** [comment]
I'm having the same issue

**Comment by priti-nimble** [comment]
Not work multi sharing on android #435
i have same issue please give solution as soon as possible i need it in my project i am facing in android only
