### ISSUE TITLE
Unable to share an Animated Image (GIF) on iOS

### ISSUE THREAD

**Issue by mimic-trades** [react-native-share/react-native-share#438]
### Steps to reproduce
1. Save a GIF locally on the device
2. Use Share.open() on iOS

### Expected behaviour
Sharing successfully the GIF on Social Medias. Watching a preview of it inside messaging chats.

### Actual behaviour
On Android works very well using only the base64.

On iOS: If I share the base64 nothing will be shared.
Instead, following the Troubleshooting on the Readme I used the file path directly:
- On Telegram the image is shared in a weird way, like a file.
- On Whatsapp is shared only the text.

`let shareOptions = {
                                        title: 'Share via',
                                        type: 'image/gif',
                                        message: 'this is an  animated GIF',
                                        url: response.path
                                    };`

### Result sharing the GIF on Telegram:
![image](https://user-images.githubusercontent.com/41375329/51826608-bde1ea80-22e7-11e9-9024-9a00320040c0.png)

### Result sharing the GIF on Whatsapp:
![image](https://user-images.githubusercontent.com/41375329/51826717-039eb300-22e8-11e9-91c5-e92ce7517b53.png)

### react-native-share
**Version**: 1.1.3

**Comment by univers3** [comment]
I'm having the same problem!
It's very frustrating because this issue turns the module totally useless for iOS and GIFs 😢

**Comment by mimic-trades** [comment]
I tried even with other mime types, or by removing the message, but nothing works! 😞

**Comment by univers3** [comment]
Anyone solved this issue? I'm still stuck here!

**Comment by AlicanAkyol** [comment]
If you want to share image or gif file, you can remove message. It runs.

**Comment by MateusAndrade** [comment]
Sharing files and the message on WhatsApp don't seen to work on IOS. There some issues that have the same problem sharing base64, or the image url. This looks like something related to WhatsApp.

**Comment by AlicanAkyol** [comment]
@MateusAndrade not only whatsapp but also Facebook and etc.

**Comment by MateusAndrade** [comment]
> @MateusAndrade not only whatsapp but also Facebook and etc.

Only works with base64?

**Comment by Mavenic** [comment]
Yes, it does not work on IOS, the share single for email doesn't work too.
it becomes something like this when base64 is used:

![1694cf49-aff3-477f-b0b1-156a10add9a3](https://user-images.githubusercontent.com/1584324/85055127-bb24b580-b1ba-11ea-9453-e7d1fbf75241.jpg)

**Comment by Mavenic** [comment]
> If you want to share image or gif file, you can remove message. It runs.

No it doesn't, when there is no `message` param it doesn't work at all

**Comment by Mavenic** [comment]
It's been a year, I'm surprised this issue is still open.

**Comment by mikehardy** [comment]
I'm not surprised at all. I'm constantly surprised at developers consuming open source libraries without rolling up their sleeves and really working on them to fix their problems though, leads to issues just sitting out there waiting for "someone" to do "something" 🤣  - so they sit

**Comment by Mavenic** [comment]
Fair enough, but not everybody is good at everything.

**Comment by Henry23** [comment]
;(
