### ISSUE TITLE
Pass a caption to instagram on Image sharing [Feature request]

### ISSUE THREAD

**Issue by lbnlrnt** [react-native-share/react-native-share#461]
Hi, 

First, thanks for this cool package.

I was reading  #310 

And I'm facing the same issue with : 
`"react-native": "0.58.5",`
`"react-native-share": "^1.1.3",`

But I believe there is even a better way than "degrade gracefully" to solve this.

While not achieving to share anything with react native (at the beginning), I went native like native native. (then i came back from my native dreams)

And in swift I succeed to pass a caption to instagram:

```swift
func postImageToInstagramWithCaption(imageInstagram: UIImage, instagramCaption: String, view: UIView) {
        // called to post image with caption to the instagram application
        
        let instagramURL = NSURL(string: kInstagramURL)
        
        if UIApplication.shared.canOpenURL(instagramURL! as URL) {
            
            let jpgPath = (NSTemporaryDirectory() as NSString).appendingPathComponent(kfileNameExtension)
            
            do {
                try imageInstagram.jpegData(compressionQuality: 1.0)?.write(to: URL(fileURLWithPath: jpgPath), options: .atomic)
                
            } catch {
                
                print(error)
            }
            
            let rect = CGRect(x: 0, y: 0, width: 612, height: 612)
            let fileURL = NSURL.fileURL(withPath: jpgPath)
            documentInteractionController.url = fileURL
            documentInteractionController.delegate = self
            documentInteractionController.uti = kUTI
            
            // adding caption for the image
            documentInteractionController.annotation = ["InstagramCaption": instagramCaption]
            documentInteractionController.presentOpenInMenu(from: rect, in: view, animated: true)
        } else {
            
            /// display some message about how it didn't work
            let r = UIAlertController(title: kAlertViewTitle, message: kAlertViewMessage, preferredStyle: .alert)
            
            print(r)
        }
    }
```

( [Thanks to this SO](https://stackoverflow.com/questions/36406515/post-uiimage-to-instagram-using-swift-similar-to-slcomposeviewcontroller), tested and worked in my swift code)

Can't say how to achieve this in Kotlin/Java for android, but there is way to pass caption (according to the kotlin master in my team):

[Useful infos here](https://www.instagram.com/developer/mobile-sharing/)

So yeah that's not Obj-C (as i can see that your native code is Obj-C) but you can as well link these functions too in some way. You might even know better than me how to do so : 

[Swift](https://facebook.github.io/react-native/docs/native-modules-ios#exporting-swift)
[Mixed code source Obj-C / Swift](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html)

I'm really not a native mobile dev, so I cannot submit a pull request. But I can give you the fruits of my researches in the native world.

Note : This way of sharing to instagram also show facebook / twitter / snapchat / whatsapp ... as an option to share, and you can add more field to add caption to facebook for example (without breaking instagram sharing)

**Comment by webmasterdragon** [comment]
Thanks for sharing @lbnlrnt .
I think react-native iOS is objective-c, so how to test your posting with react native?

**Comment by lbnlrnt** [comment]
The things is to link the swift code with objective C, following [this](https://facebook.github.io/react-native/docs/native-modules-ios#exporting-swift), I guess.
Then create the objective C module for react native. But I would not be able to do it myself. Not yet really try/succeed to do so, so this is quite blurry to me.

**Comment by lbnlrnt** [comment]
Re-reading this, i think the all function is not even mandatory. I feel like it is "just" to add :

`["InstagramCaption": instagramCaption]`

To the dictionary in Obj-C because it seems that it is what Instagram is waiting for (looking for in the call) and it may be just a new key in the optional parameter as per "subject" to  email in this options :

```javascript
const options = {
  subject: "for email",
  instagramCaption: "for insta"
}
Share.open(options)
```

**Comment by absolutvodka8888** [comment]
> lbnlrnt

not working anymore
