### ISSUE TITLE
shareOptions - is url really reaquired?

### ISSUE THREAD

**Issue by compojoom** [react-native-share/react-native-share#462]
Today I noticed that whenever someone tries to share over whatsapp the whole app is attached as a zip file to the message.
The code we had looks like this:
```
    let shareOptions = {
      subject: subject,
url: '',
      message: I18n.t('friends.shortShareMessage', {url: URL})
    }

    Share.open(shareOptions).catch(() => {})
```

I didn't want to have the url attached to the message, so that is why it was set to an empty string and that was working fine in the past. 

Once I removed the url from the shareOptions completely the share on whatsapp didn't contain the whole app. However flow complains that url is required. Is it really required or not?

I see that urls is set to optional, but url is not. However it works without having an url...

**Comment by ThibaultJanBeyer** [comment]
In my experience, not providing the url will crash on android. Which seems like a bug.
