### ISSUE TITLE
[Android] Unable to share files - "Request contained no data"

### ISSUE THREAD

**Issue by Cnordbo** [react-native-share/react-native-share#520]
### Steps to reproduce
1. Create file using react-native-fs (.csv)
2. Use the path from react-native-fs as the url (`file:// + $path`)
3. `Share.open({url: pathWithFilePrefix, title: "MyData.csv"})`
4. Share to Google Disk

### Expected behaviour
File to be exported/uploaded

### Actual behaviour
![image](https://user-images.githubusercontent.com/385693/59188985-3b144a80-8b79-11e9-99ed-9564caf1d1e2.png)

### Environment
- **React Native version**: 0.59.9
- **React Native platform + platform version**: Android 9? (Api 28)

### react-native-share
**Version**: 1.2.1

Full code: 
```js
exportCsv = async () => {
    let data = this.getCsvData();
    var path = RNFS.DocumentDirectoryPath + "/MyData.csv"; 

    // path = "/data/user/0/com.myApp/files/MyData.csv"

    try {
      RNFS.writeFile(path, data, "utf8");
    } catch (err) {
      Alert.alert("Export failed", "Failed to write file to disk");
      return;
    }

    try {
      let editedPath = "file://" + path;
      await Share.open({
        url: editedPath,
        type: "text/csv",
        title: "MyData.csv"
      });
    } catch (err) {
      // Fall trough
    }

    try {
      await RNFS.unlink(path);
    } catch (err) {
      console.log("Unable to delete locally stored file", err);
    }
  };
```

**Comment by MateusAndrade** [comment]
@mikehardy this looks related to #517 .

@Cnordbo you can try removing `title` and/or type?

**Comment by MateusAndrade** [comment]
#521 can be related

**Comment by mikehardy** [comment]
I am starting to think that the example app needs a specific example for each provider and each type of share (image, text, with title etc). Not to complicate things (though it would at first), but so the community could share - in a functional way - how each one works since they seem to have so many differences (like you can do this for whatsapp on android, but not ios)...

Maybe a dropdown of providers and then a bunch of tick-boxes / text entries for how to share it (tick box for title, and enter it here, tick box for content and enter it here, or tick this box to include this sample image) etc.

Could still be just a single App.js but would expose all these differences.

Because my hunch is that google drive just has a quirk.

**Comment by Cnordbo** [comment]
Just for clarifying, the app doesn't crash - just gives this alert. 
Although it gives the same response as #517 mentions. 

As for my case on #521, I wouldn't say they are related? The issues are using two different methods, where #521 was the approach tried when the method in this issue failed. (base64 from file on disk vs direct filepath on disk)

**Comment by Cnordbo** [comment]
I created a repository that showcases this error in its simplest form.

https://github.com/Cnordbo/RNShare-reproduction-of-extension-error

Im unfamiliar with how to debug this in android studio / java, but I'm looking into it, will try to help out the best I can, but this is currently beyond my knowledge.

This also includes the suggested fix by @MateusAndrade without success.

**Comment by MateusAndrade** [comment]
> I created a repository that showcases this error in its simplest form.
> 
> https://github.com/Cnordbo/RNShare-reproduction-of-extension-error
> 
> Im unfamiliar with how to debug this in android studio / java, but I'm looking into it, will try to help out the best I can, but this is currently beyond my knowledge.
> 
> This also includes the suggested fix by @MateusAndrade without success.

I will try giving a look at the repo this week. Thanks for sharing your example. 😄

**Comment by Cnordbo** [comment]
Stepping trough the application, it seems like the error is within `android.webkit.MimeTypeMap;`
Its terrible at mimetype mapping actually. (tried several)

![image](https://user-images.githubusercontent.com/385693/59278043-928de580-8c61-11e9-8bdf-7d97bacac185.png)

Switching to `text/comma-separated-values` fixes the issue as a workaround for my case. 

I found this mimetype by looking at the getMimeTypeFromExtension("csv"), and so this might help others facing the same issue. 

There is some mention about the same thing here: 
https://stackoverflow.com/questions/44667125/getmimetypefromextension-returns-null-when-i-pass-json-as-extension

- But fixing it in Android Q? Seems like it would be a big enough issue to fix in a patch for Pie and the others as well ?

**Comment by mikehardy** [comment]
Unfortunately the idea of android successfully getting a patch out and having vendors release it is laughable (c.f. Project Treble etc). And you'd still have to deal with react-native supporting down to API16, so best to have a workaround and go with it. Great work stepping through though! This information should help others

Should this remain open, as in, is there anything the react-native-share can do?

**Comment by Cnordbo** [comment]
As this will fail for all older versions, and we are talking almost all basic types here, (text, csv, json), might i suggest setting up an internal mapper for the most common types if the call to MimeTypeMap returns `null` ? 

Mimetypes: https://www.freeformatter.com/mime-types-list.html

These numbers from October 2018 indicates that the issue will be present on a lot of systems. 
![image](https://user-images.githubusercontent.com/385693/59282389-231bf400-8c69-11e9-9ec3-35835cadfa15.png)

I can try to do a PR if the feature is wanted.

**Comment by mikehardy** [comment]
A PR like that sounds useful, but behold the power of the community: https://github.com/jshttp/mime-types :-)

So I think the PR would just be adding that dependency, and implementing the lookup in react-native-share to bind mime-types and react-native-share together?

**Comment by bojanmitevski** [comment]
I managed to solve this issue by passing the pdf file path to the url param from sharing options.
sharePDf = async (pdfPath) => {
//Be sure that  PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE is already granted
const shareOptions = {

        url: 'file://'+pdfPath,
        mimeType: 'application/pdf',
        title: 'Pdf test'
        };

Platform.OS === 'ios' ?   
          Share.open(shareOptions)
        :
          this.sharePDFWithAndroid(pdfPath, 'application/pdf');
}

My share function for android is :

sharePDFWithAndroid(pdfPath, type) {
    const { fs, fetch, wrap } = RNFetchBlob;
      RNFetchBlob.fs.readFile(pdfPath, 'base64').then(
         base64Data => {
          base64Data = `data:${type};base64,` + base64Data;
           Share.open({ url: base64Data });
        });
    }

After a lot of research, I found out that only base64 data for pdf file can be shared using react-native-share. Is not possible to share using url with "file://...pdfPath....".

I hope that someone will find this helpfull.

**Comment by Cnordbo** [comment]
Issue still persist, right? I dont think the lib. has fixed this yet.

**Comment by MateusAndrade** [comment]
@Cnordbo do you tried  @bojanmitevski suggestion?

**Comment by Cnordbo** [comment]
@MateusAndrade - Yes, got it working using the following code, which seems to be doing the same thing as @bojanmitevski (This is what triggered #521 , which has been resolved)

But the issue still exists (not beeing able to use `file://` or a common API), even tho there is a workaround for it. 
I believe if there should be a workaround, it should be in the library (automatically loading file based on base64 when using file://) - or the library should mention this in the documentation. 

```js
      try {
        const content = await RNFS.readFile(path, "base64");
        Share.open({
          url: "data:text/comma-separated-values;base64," + content
        });
      } catch (err) {
        console.log("Failed to get base64");
      }
```

**Comment by jgcmarins** [comment]
I don't think it's possible to share base64 using `file://` approach.

**Comment by jameshuimin** [comment]
> @MateusAndrade - Yes, got it working using the following code, which seems to be doing the same thing as @bojanmitevski (This is what triggered #521 , which has been resolved)
> 
> But the issue still exists (not beeing able to use `file://` or a common API), even tho there is a workaround for it.
> I believe if there should be a workaround, it should be in the library (automatically loading file based on base64 when using file://) - or the library should mention this in the documentation.
> 
> ```js
>       try {
>         const content = await RNFS.readFile(path, "base64");
>         Share.open({
>           url: "data:text/comma-separated-values;base64," + content
>         });
>       } catch (err) {
>         console.log("Failed to get base64");
>       }
> ```

this is work for me。but，How to set the XLS file type？text/xls  ？？

**Comment by jameshuimin** [comment]
> > @MateusAndrade - Yes, got it working using the following code, which seems to be doing the same thing as @bojanmitevski (This is what triggered #521 , which has been resolved)
> > But the issue still exists (not beeing able to use `file://` or a common API), even tho there is a workaround for it.
> > I believe if there should be a workaround, it should be in the library (automatically loading file based on base64 when using file://) - or the library should mention this in the documentation.
> > ```js
> >       try {
> >         const content = await RNFS.readFile(path, "base64");
> >         Share.open({
> >           url: "data:text/comma-separated-values;base64," + content
> >         });
> >       } catch (err) {
> >         console.log("Failed to get base64");
> >       }
> > ```
> 
> this is work for me。but，How to set the XLS file type？text/xls ？？

I finally solved the problem of android sharing excel files.Here is the full code。
```
import XLSX from 'xlsx'
import {
    writeFile,
    readFile,
    unlink,
    DocumentDirectoryPath,
    ExternalDirectoryPath,
} from 'react-native-fs'
import { Platform } from 'react-native'
import { Toast } from '@ant-design/react-native'
import Share from 'react-native-share';


/**
 * excel
 * @param data
 * @param fileName
 */
const exportExcel = (data: Array, fileName: string) => {
    let ipt = new Promise(function(resolve, reject) {
        try {
            const output = str => str
            const path = Platform.select({
                ios: `${DocumentDirectoryPath}/`,
                android: `${ExternalDirectoryPath}/`
            })
            const fileType = 'xls'
            if (data && data.length > 0) {
                let ws = XLSX.utils.aoa_to_sheet(data)
                let wb = XLSX.utils.book_new()
                XLSX.utils.book_append_sheet(wb, ws, fileName)
                const wbout = XLSX.write(wb, {
                    type: 'base64',
                    bookType: fileType
                })
                const file = `${path}${fileName}.${fileType}`
                writeFile(file, output(wbout), 'base64')
                    .then(res => {
                        console.log(file)
                        wxShareFile(fileName, file, resolve, reject)
                        // resolve(file)
                    })
                    .catch(err => {
                        Toast.fail(err)
                        console.log(err)
                        reject(err)
                    })
            } else {
                alert('没有可分享的数据')
            }
        } catch (e) {
            console.log(e)
            reject(e)
        }
    })

    return ipt
}

const wxShareFile = async (fileName, filePath, resolve, reject) => {
    readFile(filePath,"base64").then((res)=>{
       console.log(res)
        const dataUri = `data:application/vnd.ms-excel;base64,${res}`;
         Share.open({
            url: dataUri,
        });
         // unlink(path);

    })

}



export { exportExcel }
```

**Comment by jgcmarins** [comment]
@jameshuimin awesome!
Do you think we should add some information to [README](https://github.com/react-native-community/react-native-share/blob/7f125ea4e6aaf6111d4f550dd2375fe77a068a85/README.md)?

**Comment by jameshuimin** [comment]
> @jameshuimin awesome!
> Do you think we should add some information to [README](https://github.com/react-native-community/react-native-share/blob/7f125ea4e6aaf6111d4f550dd2375fe77a068a85/README.md)?

Yes, I think you should want to add some tips in《 Url format when sharing a file 》something like it :   .xls->application/vnd.ms-excel   .Xml-> text/ xml   .zip-> application/ x-zip    .mp3-> audio/x-mpeg-3.

**Comment by Cnordbo** [comment]
> I don't think it's possible to share base64 using `file://` approach.

True, this is the workaround :)

**Comment by jgcmarins** [comment]
> Yes, I think you should want to add some tips in《 Url format when sharing a file 》something like it : .xls->application/vnd.ms-excel .Xml-> text/ xml .zip-> application/ x-zip .mp3-> audio/x-mpeg-3.

Awesome!
Mind sending a PR? I can help on the review \o/

**Comment by roaringUnicorn** [comment]
I'm having the same problem when i try to share a file.
It's clearly not a permission problem, as all my other FS call work fine.

When I try to share an url like this : `url: 'file:///storage/emulated/0/MyApp/myFile.html'`
I end up with different error:
Telegram : Unable to share file
Slack: unable to send
Email: simply no file attached

I tried to use base64 workaround, but I cannot set a filename (#611 ?).
I currently cannot share a file on android for now...

Work fine on iOS.

**Environment:**

Android 9
OxygenOS 9.0.9

`react-native-share` 1.2.1
`react-native` 0.59.5,

Using `react-native-fs`  2.13.3 for reading b64 file

**Comment by xkevin190** [comment]
I have this same problem of @roaringUnicorn  react-native 0.59.9 and react-native-share1.2.1

if you try to use with base 64 it generates a file with a random name .null

**Comment by roaringUnicorn** [comment]
I finally made it work, I was simply missing a FileProvider implementation.
The documentation could be more explicit about that.

**Comment by jgcmarins** [comment]
@roaringUnicorn good news.
Just let me know what can be improved on docs.
Thanks.

**Comment by ugrdursun** [comment]
> > > @MateusAndrade - Yes, got it working using the following code, which seems to be doing the same thing as @bojanmitevski (This is what triggered #521 , which has been resolved)
> > > But the issue still exists (not beeing able to use `file://` or a common API), even tho there is a workaround for it.
> > > I believe if there should be a workaround, it should be in the library (automatically loading file based on base64 when using file://) - or the library should mention this in the documentation.
> > > ```js
> > >       try {
> > >         const content = await RNFS.readFile(path, "base64");
> > >         Share.open({
> > >           url: "data:text/comma-separated-values;base64," + content
> > >         });
> > >       } catch (err) {
> > >         console.log("Failed to get base64");
> > >       }
> > > ```
> > 
> > 
> > this is work for me。but，How to set the XLS file type？text/xls ？？
> 
> I finally solved the problem of android sharing excel files.Here is the full code。
> 
> ```tsx
> import XLSX from 'xlsx'
> import {
>     writeFile,
>     readFile,
>     unlink,
>     DocumentDirectoryPath,
>     ExternalDirectoryPath,
> } from 'react-native-fs'
> import { Platform } from 'react-native'
> import { Toast } from '@ant-design/react-native'
> import Share from 'react-native-share';
> 
> 
> /**
>  * excel
>  * @param data
>  * @param fileName
>  */
> const exportExcel = (data: Array, fileName: string) => {
>     let ipt = new Promise(function(resolve, reject) {
>         try {
>             const output = str => str
>             const path = Platform.select({
>                 ios: `${DocumentDirectoryPath}/`,
>                 android: `${ExternalDirectoryPath}/`
>             })
>             const fileType = 'xls'
>             if (data && data.length > 0) {
>                 let ws = XLSX.utils.aoa_to_sheet(data)
>                 let wb = XLSX.utils.book_new()
>                 XLSX.utils.book_append_sheet(wb, ws, fileName)
>                 const wbout = XLSX.write(wb, {
>                     type: 'base64',
>                     bookType: fileType
>                 })
>                 const file = `${path}${fileName}.${fileType}`
>                 writeFile(file, output(wbout), 'base64')
>                     .then(res => {
>                         console.log(file)
>                         wxShareFile(fileName, file, resolve, reject)
>                         // resolve(file)
>                     })
>                     .catch(err => {
>                         Toast.fail(err)
>                         console.log(err)
>                         reject(err)
>                     })
>             } else {
>                 alert('没有可分享的数据')
>             }
>         } catch (e) {
>             console.log(e)
>             reject(e)
>         }
>     })
> 
>     return ipt
> }
> 
> const wxShareFile = async (fileName, filePath, resolve, reject) => {
>     readFile(filePath,"base64").then((res)=>{
>        console.log(res)
> //You can search for MIME Types using Google to find the corresponding Types of files
> // something like it : .xls->application/vnd.ms-excel .Xml-> text/ xml .zip-> application/ x-zip .mp3-> audio/x-mpeg-3.
>         const dataUri = `data:application/vnd.ms-excel;base64,${res}`;
>          Share.open({
>             url: dataUri,
>         });
>          // unlink(path);
> 
>     })
> 
> }
> 
> 
> 
> export { exportExcel }
> ```

Thanks for a good solve! One thing, do you have a method to rename the final file name ? It exports with random numbers filename i guess its timestamp. Have a solution for this ?
