### ISSUE TITLE
Share Image to Instagram with a message

### ISSUE THREAD

**Issue by souljacker** [react-native-share/react-native-share#591]
Is it possible to do it?

I read #461, but it's not clear if that is already implemented.

**Comment by jgcmarins** [comment]
[It should be possible to do that](https://www.instagram.com/developer/)

**Comment by MateusAndrade** [comment]
I was reading about that and find that [this](https://developers.facebook.com/docs/instagram/sharing-to-feed/) should work on that cases. Btw, i need to give a look on how rn-share are handling this to see if we can improve that.

**Comment by josh-deprogram** [comment]
I don't see how this would be possible. The Instagram API only excepts `Image asset` or `File assets` in the content request there is no value for Captions?

**Comment by EnclaveAnthony** [comment]
So now, we don't have any solution for share images with a message to Instagram?

**Comment by mikehardy** [comment]
Well, if there is an API somewhere, and code exists anywhere, it can be done right? I'm not being sarcastic but I am specifically saying: the solution may be that you do it and earn the Internet Fame(tm) associated. Someone has to code these things, could be you...

**Comment by jgcmarins** [comment]
We once had instagram implementation, you can find merges and reverts here: https://github.com/react-native-community/react-native-share/pulls?utf8=%E2%9C%93&q=is%3Apr+instagram+
