### ISSUE TITLE
Implementing Custom UI

### ISSUE THREAD

**Issue by sepowitz** [react-native-share/react-native-share#595]
Hey There,

Thanks for the great lib!

In the README there are visual examples of a custom share sheet UI implementation, but I can't seem to find any examples in the repo itself, or any documentation on how to implement a custom share UI. 

Are there any good examples you could point me towards, or share?

Specifically, I would like to trigger a custom share dialog, instead of the native ios/andorid dialog.

Thank you!

**Comment by MateusAndrade** [comment]
Hi @sepowitz you can give a look at: https://github.com/react-native-community/react-native-share/blob/master/components/Sheet.js. It accepts any ```children``` the sheet action.

Btw, at the components folder: https://github.com/react-native-community/react-native-share/tree/master/components you can see the components used to reproduce this sheet.

**Comment by sepowitz** [comment]
Hi @MateusAndrade thank you for the quick response.

I had seen those components, but it's not clear how they relate to the rest of API. As the sheet only seems to render children, with no additional functionality.

Is the idea that you would render some custom UI and use the ```Share.singleShare``` method to share via a single channel? Ultimately we're trying to avoid showing any native share UI/dialog, if possible. 

Any additional info would be really appreciated!

Thanks again.

**Comment by MateusAndrade** [comment]
> Thanks again.

As i remember you will end calling the ```Share.singleShare```or a similar method. This components are used to achieve a similar approach to a IOS share. I can gave a look at this later to help you with that. 😄

**Comment by danielbenedykt** [comment]
I want to achieve this also,  but no luck.
I cant find a method to list all possible shares,  or how to customize it.
Any examples you can share?

**Comment by vaibhavhrt** [comment]
https://github.com/yeomann/react-native-share-android-test/blob/master/App.js

**Comment by prashant0231** [comment]
Hello guys I have to add image preview in while sharing the image, how can I achieve that feature
