### ISSUE TITLE
Create site like react-native-camera

### ISSUE THREAD

**Issue by enieber** [react-native-share/react-native-share#597]
## Describe the Feature

the lib react-native-camera created the [web site](https://react-native-community.github.io/react-native-camera/)

## Possible Implementations

follow the layout implemented in react-native-camera site

**Comment by MateusAndrade** [comment]
Hi @enieber. We are planning to implement this, but due to a lack of time i dont set this.  Thanks for remember me. 😅

For anyone interested, please give a look at: [https://docusaurus.io/](docusaurus).

**Comment by LunguIonut007** [comment]
I wanted for some time to take a look at docosaurus and this looks like a good place to start. May I take this task?

**Comment by MateusAndrade** [comment]
> I wanted for some time to take a look at docosaurus and this looks like a good place to start. May I take this task?

Actually we already have docs using docusaurus, but we would be happy with improvements on that
