### ISSUE TITLE
Share video in SnapChat only opens the app, don't open a video in it though

### ISSUE THREAD

**Issue by cherenkor** [react-native-share/react-native-share#614]
### Steps to reproduce
1. create a function with code: 
```
	Share.shareSingle({
    	url: `data:video/mp4;base64,${videoBase64Data}`,
    	type: 'video/mp4',
    	filename: 'Video',
    	social: 'snapchat',
 	})
```
2. Run it on press Button

### Expected behaviour
It should open a SnapChat app and pass a selected video to the SnapChat app

### Actual behaviour
Only opens a SnapChat app without passing video. No errors are showing.

### Environment
- **React Native version: 0.61**:
- **React Native platform + platform version**: Android all versions

### react-native-share
**Version**: 2.0

### Link to repo (highly encouraged)
https://github.com/

https://github.com/cherenkor/harmix-react-native

**Comment by jgcmarins** [comment]
does it happens on both platforms?

**Comment by cherenkor** [comment]
I've tried only on Android - real device and simulators

**Comment by Andrfas** [comment]
I got this working in my app.
We're providing path to local file in `url` field. You can try to do the same by writing the video to file storage.
Our `type` field is the same as yours.

**Comment by cherenkor** [comment]
> I got this working in my app.
> We're providing path to local file in `url` field. You can try to do the same by writing the video to file storage.
> Our `type` field is the same as yours.
> 
> By the way I had the same Snapchat behavior as yours when my app was not able to find the video.

But I share successfully the same url in instagram, twitter, facebook, messenger, , email though
