### ISSUE TITLE
Preview Image not displaying

### ISSUE THREAD

**Issue by danielfein** [react-native-share/react-native-share#617]
I've tried this with many configurations of `url`, `urls`, etc.

### Steps to reproduce
1. Call Share.open
2. Set url: base64

```
const result = await Share.open({
            title: 'Share via',
            message:
              `I think you would like ${name}, check it out on Tabs App. https://tabs.page.link/app`,
            url: base64,
          }).then((res) => { console.log(res) })
          .catch((err) => { err && console.log(err); });
```

### Expected behaviour
I would like users to be able to share Text with other users, and a preview image to show here (but not necessaril ypart of the actual share). I have seen this many times and it is the default behavior for iOS apps. I would at least expect to see an image that the user is sharing as a preview on the modal that pops up.

<img width="364" alt="Screenshot 2019-10-28 14 45 05" src="https://user-images.githubusercontent.com/1616865/67707810-8cd73900-f991-11e9-83e7-0371df1e81b2.png">

### Actual behaviour
Currently it shows a "T" as if to represent that it's only text. When I go to actually send the SMS, etc it embeds the image.

I've seen the image be represented properly in other apps, it's not exactly obvious why it's not happening here. 

### Environment
- **React Native version**: 0.61.2"
- **React Native platform + platform version**: iOS 13.1

### react-native-share
**Version**: master

### Link to repo (highly encouraged)
https://github.com/

**Comment by MateusAndrade** [comment]
Did you tried sharing the image relative path, instead of the ```base64```?

**Comment by danielfein** [comment]
Hi @MateusAndrade same issue with the image URL and base64. It's not a local file btw.

**Comment by SteFF1997** [comment]
Have the same problem, in some social network `url` just was add preview to share message inside this social network.
But it doesn't resolve a problem with preview image at native share view on iOS.

**Comment by marf** [comment]
Hello, we have the exact same problem! Any solutions?

**Comment by vuhoangp** [comment]
i've the same problem !

**Comment by thiname** [comment]
We encounter the same problem, do you have a solution ?

**Comment by SPLAYER-HD** [comment]
Hi, 
Did nobody find a solution?

**Comment by AmirDiafi** [comment]
+1

**Comment by jdturnbull** [comment]
+2

**Comment by dtchiong** [comment]
+3

**Comment by rodrigo-lima** [comment]
+4

**Comment by mikehardy** [comment]
I can reopen this, sure, but PLEASE STOP SPAMMING WITH +N COMMENTS.
They are not useful.
Useful == a PR to fix the bug
Thank you :-)

**Comment by anisurrahman072** [comment]
Still issue is there 😞.
+5

**Comment by jkincheloe33** [comment]
Still seeing this issue 😢  it's also seems to be an issue in the native share api
+6

**Comment by mikehardy** [comment]
@jkincheloe33 @anisurrahman072 there is a comment above that is directed at you:

I can reopen this, sure, but PLEASE STOP SPAMMING WITH +N COMMENTS.
They are not useful.
Useful == a PR to fix the bug
Thank you :-)

Open Source means you are the developer. You are the maintainer. There is no code fairy to fix things for you. We're all people with limited time.

If this affects you replace the word "seems" with "I pulled the repo and altered may app to use it locally, I added some debugging statements and traced things, I discovered...." etc etc.

Do the work

**Comment by miridih-jslee01** [comment]
Did you set prefix for base64?

```typescript
Share.open({
    message,
    url: `data:image/jpg;base64,${base64}`,
});
```

**Comment by phanindraVarmaG** [comment]
Is anybody found a solution for this ?

**Comment by rafaelmaeuer** [comment]
Hasn't anyone found a solution for this? I tried:

```js
activityItemSources: [
  ...,
  thumbnailImage: {
    type: 'url',
    content: image
  }
]
```
with 
```js
image = `data:image/png;base64,${base64StringOfImageData}`
```
and
```js
image = `data:${base64StringOfImageUrl}`
```
but no success with any of them...

**Comment by bpeck81** [comment]
+ 7

**Comment by dmilin1** [comment]
Here's a fix that should work in most situations. Instead of sharing the image as base64, download it as a file, then share the file and clean up after.

```
const fileName = new URL(mediaUrl).getBasePath().split("/").pop();
const file = new File(`${Paths.cache.uri}/${fileName}`);
if (file.exists) {
  file.delete();
}
await File.downloadFileAsync(mediaUrl, file);
await Share.share({
  url: file.uri,
});
file.delete();
```
