### ISSUE TITLE
Does open with url: "file://<file_path>" work on Android?

### ISSUE THREAD

**Issue by tststs** [react-native-share/react-native-share#629]
I try to share a PDF file from the file system but it just doesn't work.

* i double checked if the file exists
* i asked for permission to read storage and it is allowed by the user
* when sharing it e.g. with google drive it always says that there is "no data" to share
* i render the PDF before sharing it so i also know that the file is not empty or corrupt

Also the docs are a bit unclear about if it's even possible to do this.
As in the docs for url: `URL you want to share (only support base64 string in iOS & Android ).`

Does this mean only sharing a string is possible like: `url: "data:<data_type>/<file_extension>;base64,<base64_data>"` is possible? because scrolling down a bit it is stated that you can directly pass a file by using`file://...`

My options:

`const options = {"filename": "test.pdf", "url": "file:///data/user/0/com.x.x/files/6cfe208c-1b45-4fac-af0f-aadb7e678a6b.pdf"}`

Edit:
There are no errors. It resolves with success

Thanks in advance!

**Comment by jgcmarins** [comment]
Android share with file path should work.
Possibly we're facing a bug since there are few issues reporting this behaviour.
Thanks for all information you've provided.
Are you testing this with real device or emulator?

**Comment by tststs** [comment]
hey!

testing on a real device:
* galaxy s9
* Android 9

if you need any other information don't hesitate to ask. For now i'm using the fallback by reading the file with `rn-fetch-blob` then share it via base64 string.

**Comment by jgcmarins** [comment]
@tststs great, thanks for your reply.
I don't know if I will be able to dig into this problem.
Feel free to share more information or bring up a solution.
I'll be glad to help with code review.

**Comment by capslock35** [comment]
any updates on this ?

**Comment by jgcmarins** [comment]
As far as I remember, sharing using file path is working fine.
You can test it with our [example](https://github.com/react-native-community/react-native-share/blob/master/example).

**Comment by Alvee9** [comment]
> As far as I remember, sharing using file path is working fine.
> You can test it with our [example](https://github.com/react-native-community/react-native-share/blob/master/example).

The example given there doesn't use file path, rather it uses data URLs with base64 encoded strings which doesn't have any issue. The only problem in this scenario is that url with path like "file://<file_path>" doesn't work. (NB: It works fine on ios)

**Comment by anastely** [comment]
@jgcmarins hey, I faced something same,
when URL be like this `"/storage/emulated/0/Downloads/Bill765.pdf"` it does not work so I can't share this PDF

But when URL be like this `"/data/user/0/com.lmaalam_admin/cache/Bill197994929333884192053.pdf"`
it's working fine!

So I'm forced to use the first file URL for other functionality and want to share it in this package, any idea about this?

**Comment by olessavluk** [comment]
Hi 👋

I also have this issue, when sharing file using local path - other applications do not receive it.
**Logcat show** `NULL` (`clip={text/plain NULL}`) instead of file:
```
03-23 00:34:02.875  2548  3704 I ActivityManager: START u0 {act=android.intent.action.SEND_MULTIPLE typ=text/plain flg=0xb080001 cmp=org.telegram.messenger/org.telegram.ui.LaunchActivity clip={text/plain NULL} (has extras)} from uid 10192 on display 0
03-23 00:34:02.875  2548  3704 I ActivityManager: Ignoring FLAG_ACTIVITY_NEW_DOCUMENT, launchMode is "singleInstance" or "singleTask"
```

I have created reproducible repo - https://github.com/olessavluk/sharebug
1. run it
2. click button "Share text.txt"

@jgcmarins any chance you could take a look?

**Comment by nirre7** [comment]
I've got the same issue with Samsung galaxy s9+, android 10.
Works with a pixel simulator though. Very weird...

**Comment by enesozturk** [comment]
I have the same issue. Is there anybody solved the issue? I have text file and trying to share it with path like **file:///data/user/0/com.myapp/files/my_file.txt** but not working in (just) **android**

**Comment by taduyde** [comment]
I met the same issue on android. we can't share with local file ""/data/user/0/com.lmaalam_admin/cache/Bill197994929333884192053.pdf"", we have to convert it to base 64.

**Comment by enesozturk** [comment]
> I met the same issue on Android. we can't share with local file ""/data/user/0/com.lmaalam_admin/cache/Bill197994929333884192053.pdf"", we have to convert it to base 64.

Thanks for the idea. I will check and share the result soon.

**Comment by nirre7** [comment]
Hi again.
i created a pull request that should enable sharing of files on secondary storage, i.e sd cards: https://github.com/react-native-community/react-native-share/pull/754

**Comment by taduyde** [comment]
> Hi again.
> I created a pull request that should enable sharing of files on secondary storage, i.e sd cards: #754

Hi @nirre7,
Your pull request is fixed for sharing issue: file://<file_path> on android. is that right?

**Comment by MateusAndrade** [comment]
> Your pull request is fixed for sharing issue: file://<file_path> on android. is that right?

Hey @taduyde would you mind helping us testing that? 😄

**Comment by nirre7** [comment]
> Hi @nirre7,
> Your pull request is fixed for sharing issue: file://<file_path> on android. is that right?

It depends on where the file(s) are. If the file is on secondary storage like a sd card then it should work.

For more information https://developer.android.com/reference/androidx/core/content/FileProvider there is different configs on android to enable "access" to different locations.

But like @MateusAndrade said would be great if you could help us test it, it might be that we need to add more configuration to handle different scenarios/usecases.

**Comment by taduyde** [comment]
Hi @nirre7, @MateusAndrade, 

I already tested this pull request, but that pull request not help we resolve this issue with local file as here: /data/user/0/com.lmaalam_admin/cache/Bill197994929333884192053.pdf

**Comment by nirre7** [comment]
> local file 

The PR fixes secondary storage for example sd cards, i.e not "local files". 
More information => https://developer.android.com/reference/androidx/core/content/FileProvider#SpecifyFiles

Im guessing (!) that the config your scenario needs is:
> <files-path name="someName" path="/" />

https://developer.android.com/reference/androidx/core/content/FileProvider#SpecifyFiles

**Comment by MateusAndrade** [comment]
@taduyde probably you need to transform your file on a base64 before sharing that. There are been some problems when passing `file` whenever you call the `open` that we need to investigate. 😿 

I think this can help you: https://github.com/react-native-community/react-native-share#share-remote-pdf-file-with-gmail--whatsapp-ios

**Comment by kaioduarte** [comment]
Just tested the new version with mentioned PR and it's working for local files and files of the same package (/data/user/0/com.myapp), for different package it throws an error: `(Permission denied)`

## Local file:
![local-file](https://user-images.githubusercontent.com/11046907/78832671-8e4a6a00-79e3-11ea-96e1-1ff2d291a6ea.gif)

## Same package:
![ScreenRec-20200408-214632](https://user-images.githubusercontent.com/11046907/78833256-79220b00-79e4-11ea-9a70-e4961fab5b3a.gif)

## File from different package:
![local-file-different-package](https://user-images.githubusercontent.com/11046907/78832823-d23d6f00-79e3-11ea-84e3-040ef58de749.gif)

**Comment by enesozturk** [comment]
> > I met the same issue on Android. we can't share with local file ""/data/user/0/com.lmaalam_admin/cache/Bill197994929333884192053.pdf"", we have to convert it to base 64.
> 
> 
> 
> Thanks for the idea. I will check and share the result soon.

Converting file to **base64** before share solved my issue. Thanks!

**Comment by coolvasanth** [comment]
I have a local Image that needs to be shared. For ex in My react native project, I have a Image named Resources/1.png I want to share this Image. How can I achieve it?

**Comment by nasreekar** [comment]
> > > I met the same issue on Android. we can't share with local file ""/data/user/0/com.lmaalam_admin/cache/Bill197994929333884192053.pdf"", we have to convert it to base 64.
> > 
> > 
> > Thanks for the idea. I will check and share the result soon.
> 
> Converting file to **base64** before share solved my issue. Thanks!

I have tried converting it to base64 using fetch blob but I'm seeing an error saying that the file or directory doesn't exist. Cannot share file on Android only. iOS is working fine. 

`shareBill = async (title: string) => {
    const billPdfPath = this.props.billPdfDataFetched?.path;

    if (!billPdfPath) {
      return;
    }

    const newPath = `${RNFetchBlob.fs.dirs.CacheDir}/${title}_bill.pdf`;

    await RNFetchBlob.fs.cp(billPdfPath, newPath);

    const shareOptions = {
      title: title,
      subject: `${strings('bill.emailSubject')} – ${title}`,
      message: `${title} bill`,
      url: `file://${newPath}`,
      type: 'application/pdf',
      failOnCancel: true,
    };

    try {
      await RNShare.open(shareOptions);
      track(EVENTS.BILL_SHARE);
    } catch (err) {
      track(EVENTS.BILL_SHARE, false);
    } finally {
      RNFetchBlob.fs.unlink(newPath);
    }
  };`
