### ISSUE TITLE
SMS/iMessage support on iOS

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [react-native-share/react-native-share#715]
## Describe the Feature
Add the ability to share text and images to the iOS Messages app/iMessage. It looks like Android SMS is supported, is it possible to do the same for iOS? 

## Possible Implementations
From apple docs [SMS links](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/SMSLinks/SMSLinks.html) are possible for sharing text. 

~~I don’t see further documentation on how to implement image share,~~ but working production example of this exists – check out activity sharing on the [iOS Strava app](https://apps.apple.com/us/app/strava-run-ride-swim/id426826309). 

UPDATE: Looks like you can manage attachments using https://developer.apple.com/documentation/messageui/mfmessagecomposeviewcontroller

## Related Issues
2017: Issue closed because it did not seem possible https://github.com/react-native-community/react-native-share/issues/150 
2019: Mention of fixing android and iOS https://github.com/react-native-community/react-native-share/pull/459#issuecomment-472196060

**Comment by perpetuatingcuriosity** [comment]
Has anyone been able to confirm it is possible to implement iMessage image sharing?

**Comment by emroot** [comment]
yeah that would be great addition to the library.

**Comment by durgapt** [comment]
Yeah, We need this support too.

**Comment by MrXyfir** [comment]
+1

**Comment by andyrobert3** [comment]
+1

**Comment by mikehardy** [comment]
+1s are facile and do nothing. PRs are how the open source world moves forward. Someone propose a PR and then the feature will exist

**Comment by MrXyfir** [comment]
I disagree. It lets maintainers and potential contributors looking for a project know what features the community wants and they can use that to prioritize their next actions. Obviously if it's really a crucial feature to you then you may need to go further with a PR but for someone like me who thinks this would be a nice-to-have, a +1 is sufficient. And sure I could just like the original comment (which I did), but sometimes these threads go stale and are closed without recent comments.

**Comment by mikehardy** [comment]
I am a maintainer. It just annoys us with notifications.
Use reactions, not comments please.

**Comment by andyrobert3** [comment]
Planning to do this, give me a month or two to try to support this

**Comment by MrXyfir** [comment]
By the way, for anyone needing a quick solution, [expo-sms](https://docs.expo.io/versions/latest/sdk/sms/) will let you do this.

For an even quicker but more limited solution:

```ts
import { Linking } from 'react-native';
const phone = '16195550100';
const text = encodeURIComponent('Hello world!');
Linking.openURL(`sms:${phone}&body=${text}`)
```

Although I'm not sure if that works on Android.

**Comment by andyrobert3** [comment]
@mikehardy Is it possible to write it in Swift instead here for this feature? Thinking that we should maybe write all the newer code in Swift to slowly migrate the codebase to Swift instead of Obj-C

**Comment by mikehardy** [comment]
I wouldn't want to make a call like that personally, I'm stronger on the android side (so I don't have good "taste" for iOS side) and @MateusAndrade does 99% of everything around here right now so should be the sole opinion, in my opinion

I can say that from experience, as long as there aren't a lot of PRs outstanding, it's probably easier to just convert the whole thing at once. I feel that way about javascript -> typescript and android -> kotlin conversions anyway. Not sure how the interop story is on obj-c -> swift in reality over time.

**Comment by yagudaev** [comment]
@MateusAndrade I also won't have time sadly. Got a few projects and the mobile app is now a lower business priority 😢.
