### ISSUE TITLE
I have updated the info.plist file but apps are not reflecting when I'm trying to share

### ISSUE THREAD

**Issue by Nextt1** [react-native-share/react-native-share#729]
This is what my `info.plist` file looks like.

`<key>LSApplicationQueriesSchemes</key>`
`<array>`
`   <string>facebook</string>`
`   <string>whatsapp</string>`
`   <string>twitter</string>`
`   <string>googleplus</string>`
`   <string>instagram</string>`
`   <string>instagram-stories</string>`
`   <string>email</string>`
`</array>`

But when I'm calling the following code 

`
Share.open({message: "Message"})
            .then((res) => { console.log(res) })
            .catch((err) => { err && console.log(err); });`

It only shows the message and reminders app in iOS. I did follow these steps https://github.com/react-native-community/react-native-share#ios-install-using-pods but it's not working. What am I missing here?

**Comment by MateusAndrade** [comment]
@Nextt1 which version are you using?

**Comment by Nextt1** [comment]
@MateusAndrade  I'm using `react-native` version `0.61.5` and `react-native-share` version is `3.0.0`

**Comment by MateusAndrade** [comment]
> @MateusAndrade I'm using `react-native` version `0.61.5` and `react-native-share` version is `3.0.0`

What happens when you try calling `Share` without setting this QuerySchemes? Also, you can give a try at the example app?

**Comment by Nextt1** [comment]
Even if I remove `QuerySchemes` nothing changes. The example app is behaving in the same manner. Not seeing anything.

**Comment by MateusAndrade** [comment]
> Even if I remove `QuerySchemes` nothing changes. The example app is behaving in the same manner. Not seeing anything.

Which iOS version are you using?

**Comment by chpq95** [comment]
can i know why instagram and twitter is not listed when i click share. am i missing something @MateusAndrade

**Comment by MateusAndrade** [comment]
> can i know why instagram and twitter is not listed when i want to share the video in android
> . Am i missing something @MateusAndrade

Which version you are using from share and android?

**Comment by Nextt1** [comment]
My rn-share version is 3.0.0 and OS version is 13.3. When I tested on iPhone 6 which has 12.4.5 OS, It didn't show any app in which I can share something.

**Comment by chpq95** [comment]
> > can i know why instagram and twitter is not listed when i want to share the video in android
> > . Am i missing something @MateusAndrade
> 
> Which version you are using from share and android?

Im using the latest share 3.1.1 and my android is 8.0.

**Comment by chpq95** [comment]
btw this is my filepaths.xml
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <cache-path name="cache" path="wimyx/videos" />
</paths>
```

and this is my path /data/user/0/com.wimyx/cache/wimyx/videos/VID_1584601137552_enhanced.mp4

**Comment by MateusAndrade** [comment]
> btw this is my filepaths.xml @MateusAndrade
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <paths xmlns:android="http://schemas.android.com/apk/res/android">
>   <cache-path name="cache" path="test/videos" />
> </paths>
> ```
> 
> and this is my filepath /data/user/0/com.project/cache/test/videos/video.mp4

Did you tested this, trying to share a image, or event a simpler text instead of a video?  My personal phone is a Android `8.0.0`. I will try to  give a look at this testing your case. 🤔

**Comment by chpq95** [comment]
if i share a simpler text all the apps like twitter and instagram is listed. i just solved this by dowgrade rn-share to 2.0.0 and now twitter and instagram is listed when i want to share the video 😅

**Comment by MateusAndrade** [comment]
> if i share a simpler text all the apps like twitter and instagram is listed. i just solved this by dowgrade rn-share to 2.0.0 and now twitter and instagram is listed when i want to share the video 😅

This is really strange,  maybe this can be related to some change between: https://github.com/react-native-community/react-native-share/compare/v2.0.0...v3.1.1.

Btw, i will try this on my phone and will talk with if i found anything. 😅

**Comment by chpq95** [comment]
Hi @MateusAndrade does version 2.0.0 support instagram stories in ios when using Share.open?

**Comment by MateusAndrade** [comment]
> Hi @MateusAndrade does version 2.0.0 support instagram stories in ios when using Share.open?

As i rember, Instagram Stories was introduced on 2.0.0(remove due to a error on iOS) and reverted back on 3.0.0. @chpq95 can you confirm if 3.0.0 works for you?

Looks like we have a issue #726, that can be related to these changes. I would be glad if you can help me looking at that. 😃

**Comment by chpq95** [comment]
yup i try 3.0.0 before i try 3.1.1. also not working @MateusAndrade
