### ISSUE TITLE
Cannot share image in base64 to telegram

### ISSUE THREAD

**Issue by bestspyever** [react-native-share/react-native-share#737]
### Steps to reproduce
1.` const url = 'data:image/jpeg;base64,' + base64string;`
2. ```
const options = {
  title: 'React Native',
  url: url,
  subject: 'Share Link', //  for email
}; 
```

Share.open(options);
3. And loading takes forever

### Expected behaviour
Image loaded succesfully

### Actual behaviour
Image loading takes forever

### Environment
- **React Native version**: "^0.61.5"
- **React Native platform + platform version**: iOS 13.3.1

### react-native-share
**Version**: npm version or "master" "^3.1.0"

**Comment by MateusAndrade** [comment]
Hi @bestspyever , could you provide more info? What happens when you try calling Share to telegram? Thanks! 😃

**Comment by bestspyever** [comment]
> Hi @bestspyever , could you provide more info? What happens when you try calling Share to telegram? Thanks! 😃

![photo_2020-03-20 15 16 10](https://user-images.githubusercontent.com/11487678/77166971-d6016400-6abd-11ea-89ec-8679dd402a1c.jpeg)
![photo_2020-03-20 15 16 09](https://user-images.githubusercontent.com/11487678/77166983-da2d8180-6abd-11ea-9b78-3475ad2ae01e.jpeg)
![photo_2020-03-20 15 16 07](https://user-images.githubusercontent.com/11487678/77166984-dac61800-6abd-11ea-9a6d-9e9dc67b56d1.jpeg)

**Comment by bestspyever** [comment]
I tap share, then choose telegram, and then choose dialog and permanent loading

**Comment by MateusAndrade** [comment]
Did you tried sharing a file or a text instead? To see if this throws this Error?

**Comment by bestspyever** [comment]
Text was shared succesfully.

**Comment by Spyspyspy** [comment]
Any ideas how deal with it?

**Comment by vforvasile** [comment]
Yesterday I tested on Android and it worked (2.4MB img)

I used only the URL in base64 format, without subject or other params.

**Comment by Spyspyspy** [comment]
Still can reproduce it in iPhone.  My code is 
` const options = Platform.select({
          ios: {
            activityItemSources: [

             {
                placeholderItem: { type: 'url', content: url },
                item: {
                default: { type: 'url', content: url },
              },
            },
          ],
        },
        default: {
          activityItemSources: [

            {
               placeholderItem: { type: 'url', content: url },
               item: {
               default: { type: 'url', content: url },
             },
           },
         ],
        },
      });
  Share.open(options);`

**Comment by ecaepsey** [comment]
Hello, what about whats app?

**Comment by Neck1T** [comment]
Any updates?

Same problem - telegram infinite loading when share the image
Android works fine

**Comment by Spyspyspy** [comment]
iOS still issue

**Comment by Spyspyspy** [comment]
> Hello, what about whats app?

Did not test

**Comment by MateusAndrade** [comment]
@Spyspyspy I was trying to find a reference to the Telegram Share but I don't find any reference about that. Would you mind sharing your payload and the call that you are making to `Share`?

**Comment by soia** [comment]
> ### Steps to reproduce
> 1.` const url = 'data:image/jpeg;base64,' + base64string;`
> 2. ```
> const options = {
> title: 'React Native',
> url: url,
> subject: 'Share Link', // for email
> };
> 
> ```
> 
> Share.open(options);
> 3. And loading takes forever
> 
> ### Expected behaviour
> Image loaded succesfully
> 
> ### Actual behaviour
> Image loading takes forever
> 
> ### Environment
> - **React Native version**: "^0.61.5"
> - **React Native platform + platform version**: iOS 13.3.1
> 
> ### react-native-share
> **Version**: npm version or "master" "^3.1.0"
> ```

Hi)
Did you find a solution to the problem you described?
If yes, please write to me in telegram @iamsoia

**Comment by youngSt4r1** [comment]
Hi, 
i had the same issue and i solved it: 
`function sharing() {
		if (isOnline) {
			console.log('you have internet!');
			viewshot.current.capture().then(async (uri) => {
				const sharedUriMessage = `data:image/jpeg;base64,${uri}`;
				console.log('uri', uri);
				const shareOptions = {
					type: 'image/jpeg',
					message: sharedMessage,
					url: Platform.OS === 'android' ? 'file://' + uri : uri,
				};
				console.log('Share: ', Share);
				await Share.open(shareOptions)
					.then((res) => ({error: '', payload: res, success: true}))
					.catch((err) => ({error: (err && err.error) || 'User did not share', payload: {}, success: false}));
			});
		} else {
			Alert.alert('you have no internet!');
		}
	}`

**Comment by Chiinyee** [comment]
Any solution?

**Comment by lochmatij** [comment]
thanks to @youngSt4r1
i have used saving to cache before sharing image to telegram

```
import RNFS from 'react-native-fs';

RNFS.writeFile(`${RNFS.CachesDirectoryPath}/name.png`, base64, 'base64');
const shareOptions = {
                // title: 'React Native Share Example',
                // message: 'Check out this photo!',
                url: `${RNFS.CachesDirectoryPath}/name.png`,
                type: 'image/png',
                // subject: 'Check out this photo!',
            };
Share.open(shareOptions);
```

**Comment by akjesto** [comment]
I have also got the same issue while share base64 image to telegram.I am using the version  "react-native-share": "^7.3.2",.
It shows infinite loading while sharing an image on iOS.

**Comment by ksielyov** [comment]
Telegram can`t share normally, it just shares url, without message, title etc
![Снимок экрана 2022-05-30 в 17 58 07](https://user-images.githubusercontent.com/47862601/170997235-3ac75c5f-602c-4004-aae7-2f05b906a1c2.png)
.
But whatsapp can share it as expected

**Comment by Mukhammadali** [comment]
This worked perfectly for me

```
await RNFS.writeFile(
  `${RNFS.CachesDirectoryPath}/qrcode.png`,
  param.base64.replace('data:image/png;base64,', ''), // make sure to strip out data: part, if it is removed, then no need for  .replace() part
  'base64',
);
await Share.open({
  url: `${RNFS.CachesDirectoryPath}/qrcode.png`,
  type: 'image/png',
});

```

**Comment by mrserfr** [comment]
This worked for me

`    async share() {
        await Share.open({
            filename: 'image.jpg', <- you have to add file name and telegram whatsapp will start to work
            type: 'image/jpg',
            url: YOUR_BASE64_JPG
        })
            .then((res) => {
                if (!res.dismissedAction) {
                    this.closeModal();
                }
                console.log(res);
            })
            .catch((err) => {
                err && console.log(err);
            });
    }`

**Comment by hduykhang** [comment]
> This worked perfectly for me
> 
> ```
> await RNFS.writeFile(
>   `${RNFS.CachesDirectoryPath}/qrcode.png`,
>   base64String.replace('data:image/png;base64,', ''), // make sure to strip out data: part, if it is removed, then no need for  .replace() part
>   'base64',
> );
> await Share.open({
>   url: `${RNFS.CachesDirectoryPath}/qrcode.png`,
>   type: 'image/png',
> });
> ```

it works for me, thanks.
