### ISSUE TITLE
Add ability to add Detox `testID` to the Share view on Android

### ISSUE THREAD

**Issue by thomas-coinjar** [react-native-share/react-native-share#741]
## Describe the Feature
If I want to test whether the share dialog is open on Android using Detox, the framework can not find any text (i.e. title)

## Possible Implementations
Add ability to add the Detox `testID` to the options 

```
Share.open({
  url: uri,
  testID: "share-dialog"
})
.then(() => {
})
.catch(error => {
});
```

## Related Issues
N/A

**Comment by MateusAndrade** [comment]
Do you mean passing a testing `testID` to the native dialog called from the System?

**Comment by thomas-coinjar** [comment]
Yes, that's correct. 

I would like to check (with Detox) whether the dialog is open or not.

```
it('should check if the share dialog is open', async () => {
  await expect(element(by.id('share-dialog'))).toBeVisible();
});
```

**Comment by MateusAndrade** [comment]
This is really interesting, i don't think on testing this behaviour on any previous scenario. 🤔 

When you call the `.open` method on iOS, are you able check if the `Native` dialog appears? What do you think about sharing this implementation? Maybe we can improve this package attending this need. 😄

**Comment by thomas-coinjar** [comment]
In my scenario I have a share button in the top bar that invokes "sharing" of a receipt.

Obviously I want to test whether the button does indeed open the share dialog. This would be the end of the test.

**Comment by nekhaly** [comment]
I have the same

> Yes, that's correct.
> 
> I would like to check (with Detox) whether the dialog is open or not.
> 
> ```
> it('should check if the share dialog is open', async () => {
>   await expect(element(by.id('share-dialog'))).toBeVisible();
> });
> ```
> 
> Right now I can check certain characters on iOS (such as "Copy" when the dialog is open) but I tried to detect the `title` prop on Android and other texts (such as Gmail, or Dropbox) but Detox failed to read them.
> 
> The safest option would be to check against the `testID` prop that is built-in in few native components like `View`, `Text`, `TextInput`, `Switch` and `ScrollView` in React Native already.

I do the exact same in my app and struggle much now in testing with Android. Would be a great add-on to the package.

**Comment by Sonakshi997** [comment]
I am facing the same issue. Please let me know if there is a way to detect the Share dialog screen whenever we click on a Share button.
