### ISSUE TITLE
Can't upload image on Instagram Feed

### ISSUE THREAD

**Issue by vemiliogp** [react-native-share/react-native-share#745]
Hi, 

Can't upload image on Instagram Feed, I tried with Instagram Story and Direct and it worked successfully, but Instagram Feed no.

I receive the following message: **the image cannot be uploaded**.

**React native versión: 0.59.9**
**React native share: 1.2.1** 

I try with base64:

```
    const configOptions = { 
      fileCache: true,
      path: fs.dirs.DownloadDir + `/$${file.name}`
    };

    config(configOptions).fetch('GET', image).then(resp => {
      filePath = resp.path();
      return resp.readFile('base64');
    }).then(async base64Data => {
      base64Data = `data:image/${file.extension};base64,` + base64Data;

      await Share.shareSingle({
        url: base64Data,
        social: Share.Social.INSTAGRAM,
        filename: `/${file.name}`
      });
    })
```

And try with file:

```
   const configOptions = { 
      fileCache: true,
      path: fs.dirs.DownloadDir + `/$${file.name}`
    };

    config(configOptions).fetch('GET', image).then(resp => {
      filePath = resp.path();
      return resp.readFile('base64');
    }).then(async base64Data => {
      // base64Data = `data:image/${file.extension};base64,` + base64Data;

      await Share.shareSingle({
        url: `file://` + filePath,
        social: Share.Social.INSTAGRAM,
      });
    })
```

Please, I need help, very thanks.

**I try adding type or filename and nothing.**

**Comment by MateusAndrade** [comment]
Hey @vemiliogp, could you please try our last version? Since [v1.2.1](https://github.com/react-native-community/react-native-share/releases/tag/v1.2.1) we got A LOT of changes.

[Here](https://github.com/react-native-community/react-native-share/compare/v1.2.1...v3.1.2) you can look at the changelog between this version, and our last version.

**Comment by vemiliogp** [comment]
Yes, I tried upgrading react native version 0.60.0 and react native share 3.1.2 and nothing :(, only with Instagram Feed

**Comment by kensenjohn** [comment]
Hi, I'm having the same issue as well with `await Share.shareSingle`. I am able to upload image to Instagram Story. However when I select Feed I get the error message "Unable to load image." 

Unfortunately no other information or logs. I checked using `adb logcat` as well and could not find anything.

```
      const localImageBase64 = response.base64();
      const localImagePath = `data:image/jpeg;base64,${localImageBase64}`;

      await Share.shareSingle({
        title: 'Share to',
        url: localImagePath,
        social: Share.Social.INSTAGRAM,
        forceDialog: true,
      }).catch((err: any) => { err && console.log(err); });
``` 

The value in localImagePath was a valid base64 string.

**Comment by fatihfordev** [comment]
+1

**Comment by kikemarto** [comment]
+1

**Comment by MateusAndrade** [comment]
> Yes, I tried upgrading react native version 0.60.0 and react native share 3.1.2 and nothing :(, only with Instagram Feed, i don't know what else to try.

I will give a look at our example now, testing this. 😃

**Comment by MateusAndrade** [comment]
> I'm using the latest version `3.1.2`

Did you test passing a file directly, as @vemiliogp did? I need to debug this because on my Android phone the option to feed doesn't appear. 😢

**Comment by kensenjohn** [comment]
> Did you test passing a file directly, as @vemiliogp did? I need to debug this because on my Android phone the option to feed doesn't appear. 😢

@MateusAndrade 
I'm seeing the same error

I tried directly share a file to Instagram Feed, it opens up Instagram briefly. The  quickly closes out and show the message `Unable to load image`. This is the exact same behavior as before. This has not changed.

This is my code that I used.

```
// using the `react-native-fs` library to get the directory
const deviceLocalPathToFile = `${RNFS.DocumentDirectoryPath}/test.jpg`;
console.log('file path::', deviceLocalPathToFile); // output in console => `file path:: file:///data/user/0/com.myapp/files/test.jpg`

RNFetchBlob.config({
    fileCache: true,
    path: deviceLocalPathToFile, 
  }).fetch('GET', 'https://www.example.com/test.jpg')
  .then(async response => {

        // Trigger the share to Instagram here.
  	await Share.shareSingle({
  	    title: 'Share to',
            url: `file://${deviceLocalPathToFile}`, // testing for android only there append `file://`
            social: Share.Social.INSTAGRAM,
            forceDialog: true,
  	)}.catch((err: any) => { err && console.log(err); });
  });
```

Please let me know whether I can help with anything else.

_I may be wrong and I'm guessing here_. 
Is it possible that something changed on the Instagram app?
My app was originally using `react-native-share::version 2.2` and it was working perfectly. 5-6 days ago with version 2.2 I noticed that sharing to Instagram Feed was broken. I came here and saw your suggestion to upgrade to `3.2.1`.
I upgraded to `3.2.1`. This upgrade did not fix the problem either.


Note: When using above code to share a file directly to **Instagram Stories**, nothing happens. It does not open instagram. It silently fails. I do not see any error message as well. I did not investigate this further. It is possible this is user error on my end. But just wanted to let you know about this. 
However sharing to Stories work perfectly if I upload using the 'base64' string instead of the file directly.

**Comment by MateusAndrade** [comment]
I was thinking on that @kensenjohn , but I don't have time to look on this and test some change. I did a quick look at our implementation to call the Intent on Android, and it looks fine compared to Instagram [guide](https://developers.facebook.com/docs/instagram/sharing-to-feed) about sharing to feed.

If you can help me on that, i think we need debug the following files:

https://github.com/react-native-community/react-native-share/blob/master/android/src/main/java/cl/json/social/ShareIntent.java

https://github.com/react-native-community/react-native-share/blob/master/android/src/main/java/cl/json/social/InstagramShare.java

**Comment by kensenjohn** [comment]
@MateusAndrade Sorry, that was my note from my previous comment. It does not work for Instagram Stories as well.

>Note: When using above code to share a file directly to Instagram Stories, nothing happens. It does NOT open instagram. It silently **Fails**. I do not see any error message as well. I did not investigate this further. It is possible this is user error on my end. But just wanted to let you know about this.

Sharing a file using the path to Instagram Stories fails and it does not work.

**Comment by kensenjohn** [comment]
@MateusAndrade I had a few hours this afternoon so I gave it a shot, however I could not get my Android Studio to run in debugger mode. Therefore had a hard time figuring out what was happening in the Native Java code.

I'm going to stop for now and let you take over. I hope this helps you to proceed with your debugging.

I will share the code snippets which will make it possible for you to see the `IG Feeds` option to appear.

The below snippets of code are added to `example/App.js`

**The Code**
1. I added a new button `Share via IG Share Sheet`
```
        <View style={styles.button}>
          <Button onPress={shareToInstagramViaShareSheet} title="Share via IG Share Sheet" />
        </View>
```
2. I created a new function `shareToInstagramViaShareSheet` with the options.
```
  /**
   * This will display the Instagram Sharesheet from which you
   * can select one of the following three options
   *
   * 1. Direct: This will let you send image direct message to an individual contact on IG
   * 2. Feed: Open up the Instagram Feed with the image
   * 3. Stories: Open up the Instagram Story with the image.
   */
  const shareToInstagramViaShareSheet = async () => {
    const shareOptions = {
      title: 'Share image to one of these Instagram options.',
      social: Share.Social.INSTAGRAM,
      url: images.image1,
    };

    try {
      const ShareResponse = await Share.shareSingle(shareOptions);
      setResult(JSON.stringify(ShareResponse, null, 2));
    } catch (error) {
      console.log('Error =>', error);
      setResult('error: '.concat(getErrorString(error)));
    }
  };
```

3. Now when you run the example and tap on the button you should see the `Feeds` option.

**Screenshots**
![Screenshot_20200405-160316](https://user-images.githubusercontent.com/700520/78510037-0997eb80-7758-11ea-9a86-e49adbec3ca2.png)

![Screenshot_20200405-160423](https://user-images.githubusercontent.com/700520/78510041-0e5c9f80-7758-11ea-929d-ce138575e4fa.png)

**Comment by vemiliogp** [comment]
Yes @MateusAndrade, I tried with file and nothing. :/

**Comment by vforvasile** [comment]
This is an Instagram error with their last update. Android thread [here](https://developers.facebook.com/support/bugs/1326888287510350/) with more info.

Temporary workaround: join Beta program and install latest Beta update, it should work!

**Comment by garethmatson** [comment]
I'm still seeing this issue post `136.0.0.34.124`

**Comment by MateusAndrade** [comment]
> 136.0.0.34.124

Which version of rn-share are you using?

**Comment by ismaelbarry** [comment]
Hi all! Just checking in if anyone was able to find a solution to this of if the problem has been resolved. Thanks!

**Comment by chiny20035** [comment]
Hi all!!! I can't upload multiple images on Instagram Feed. If I used 'urls' attribute Instagram displays Story section.

**Comment by jinghongchan** [comment]
I'm having the same issue as well, the follow opens up Instagram and shares my latest photo in my **Photo Library**, and NOT the url that I passed in.

```
const shareOptions: ShareSingleOptions = {
        title,
        url: imageUri,
        social: Share.Social.INSTAGRAM,
      };
Share.shareSingle(shareOptions);
```

**Comment by MaxSaveskul** [comment]
It's not completed, still shares my latest photo in Photo Library, and NOT the url that passed in.
