### ISSUE TITLE
Implement sharing on TikTok

### ISSUE THREAD

**Issue by gcrozariol** [react-native-share/react-native-share#752]
## Describe the Feature
Create the ability for user to share videos through TikTok.

## Possible Implementations
Implement sharing on TikTok's feed, sending parameters like title and the video itself.

## Related Issues
No issues here.

**Comment by kaioduarte** [comment]
@gcrozariol if you don't mind, I'd take this =)

**Comment by gcrozariol** [comment]
> @gcrozariol if you don't mind, I'd take this =)
> 
> EDIT: I can just implement this for Android, because I don't have access to MacOS.

Totally! Do you mind if I have access to your progress while implementing this feature? I would like to learn the process. Also, I have access to macOS, so if I understand the concept, I might be able to implement this feature for iOS as well. :)

**Comment by MateusAndrade** [comment]
Hey @gcrozariol, @kaioduarte I just assign this issue to both of you guys. Please, let me know if there is anything that I can help! 🎉

**Comment by kaioduarte** [comment]
Sure @gcrozariol! First I need to figure out how to send medias without SDK, because it's possible to send them from my gallery app.

**Comment by kaioduarte** [comment]
I still don't know what is going on with TikTok, I've tested even a Flutter package that worked well and I took a look at the source code, and they aren't that different.

The Intent action of this package with the code below is `android.intent.action.SEND_MULTIPLE` instead of `android.intent.action.SEND`, I've logged both in Android and JS and found a weird behavior: If you pass `url` as param and it'll be interpreted as `urls`. You can reproduce that with the following code.

```jsx
import React from 'react';
import {Button, View} from 'react-native';
import Share from 'react-native-share';

export default function App() {
  async function shareVideo() {
    const shareOptions = {
      // hard coded path
      url: 'file:///storage/emulated/0/Download/VID_125220907_031943_531.mp4',
      type: 'video/mp4',
    };

    console.log(JSON.stringify(shareOptions, null, 2))

    try {
      await Share.open(shareOptions);
    } catch (error) {
      console.log('Error =>', error);
    }
  }

  return (
    <View style={{
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center'
    }}>
      <Button onPress={shareVideo} title="Share video" />
    </View>
  );
};
```

Logcat of code above (I added some logs in Java side):
```
ReactNativeJS: {
ReactNativeJS:   "url": "file:///storage/emulated/0/Download/VID_125220907_031943_531.mp4",
ReactNativeJS:   "type": "video/mp4"
ReactNativeJS: }
System.out: <=== OPTIONS ===>
System.out: type
System.out: urls
ActivityManager: START u0 {act=android.intent.action.SEND_MULTIPLE typ=video/mp4 flg=0xb080001 cmp=com.zhiliaoapp.musically/com.ss.android.ugc.aweme.share.SystemShareActivity clip={video/mp4 U:content://com.debug.rnshare.fileprovider/rnshare1/VID_125220907_031943_531.mp4} (has extras)} from uid 10282
```

I've modified a bit the source code in order to fix this bug, the action is almost the same of Flutter (second line) but still not working.
```
I ActivityManager: START u0 {act=android.intent.action.SEND typ=video/mp4 flg=0xb080001 cmp=com.zhiliaoapp.musically/com.ss.android.ugc.aweme.share.SystemShareActivity clip={video/mp4 U:content://com.rnshare1.rnshare.fileprovider/rnshare_sdcard/storage/emulated/0/DCIM/Camera/VID_20200331_114217.mp4} (has extras)} from uid 10281
I ActivityManager: START u0 {act=android.intent.action.SEND typ=video/* flg=0xb080001 cmp=com.zhiliaoapp.musically/com.ss.android.ugc.aweme.share.SystemShareActivity clip={video/* U:content://com.example.flutter_share.shareextend.fileprovider/%252Fstorage%252Femulated%252F0%252FPictures%252FScreenrecords%252FScreenRec_20200408_214632.mp4} (has extras)} from uid 10279
```

Any thoughts @MateusAndrade?

**Comment by MateusAndrade** [comment]
@kaioduarte sorry for the late reply, I have been on a busy week. Can you share your implementation? I can test this locally to see what's happening.

Btw, quickly looking at the source code this can be related to this:

https://github.com/react-native-community/react-native-share/blob/11a8ee49037c2c6ad9d06e1b9703fb267bae24da/android/src/main/java/cl/json/social/ShareIntent.java#L174-L178

https://github.com/react-native-community/react-native-share/blob/11a8ee49037c2c6ad9d06e1b9703fb267bae24da/android/src/main/java/cl/json/social/ShareIntent.java#L128-L163

This is happening on iOS?

**Comment by kaioduarte** [comment]
@MateusAndrade I only changed the code to fix the action disparity and there is already an [open PR](https://github.com/react-native-community/react-native-share/pull/770) to handle this, so not worth to share my implementation. I'll try this PR locally as soon as I can and I'll give you some feedback.

Regarding iOS I can't tell you, because I can only test on Android env.

Thanks!

**Comment by MateusAndrade** [comment]
Hey @kaioduarte I just merged #770. Can you tell me if this works for you know?

Also, I can test your implementation of TikTok locally if this help you.

**Comment by kaioduarte** [comment]
> Hey @kaioduarte I just merged #770. Can you tell me if this works for you know?
> 
> Also, I can test your implementation of TikTok locally if this help you. 

Ok, I'm gonna test it! And about the implementation we don't need to do anything special nor use SDK, a simple file sharing is enough (since it works in Flutter's lib), we just need to find what is blocking that. That's why I was just trying to make the actions consistent 😅.

**Comment by kaioduarte** [comment]
@MateusAndrade @gcrozariol after a long time I got time to get into this again 😅!

Just tested the latest version of TikTok and `react-native-share` and the sharing is working properly without any change. I tested on Android 8.1 (AOSP) and 10 (MIUI). Can you guys test this minimal repro on iOS?

```js
import React from 'react';
import {Button, View} from 'react-native';

import Share from 'react-native-share';
import ImagePicker from 'react-native-image-picker';

export default function App() {
  function share() {
    ImagePicker.launchImageLibrary({ mediaType: 'video'}, async res => {
        if (res.error) {
          console.log('error while picking video');
          return;
        }

        try {
          await Share.open({
            url: `file://${res.path}`,
            type: 'video/mp4',
          });
        } catch (error) {
          console.log(error);
        }
    });
  }

  return (
    <View style={{flex: 1}}>
      <Button onPress={share} title="Share" />
    </View>
  );
}
```

**Comment by MateusAndrade** [comment]
@kaioduarte sure! Looking at your example, probably you will need something likes this: https://github.com/joltup/rn-fetch-blob/wiki/File-System-Access-API#dirs because the fileSystem on iOS is different from Android.

**Comment by kaioduarte** [comment]
@MateusAndrade oops, I was not aware about that, but anyway I don't have any Apple device to test this. Let's wait for somebody that can 😉

**Comment by MateusAndrade** [comment]
> @MateusAndrade oops, I was not aware about that, but anyway I don't have any Apple device to test this. Let's wait for somebody that can 😉

No problem, btw if you want to set at our README.MD that we support TikTok would be really good(at least for Android). 😅

**Comment by SethuSenthil** [comment]
> @MateusAndrade oops, I was not aware about that, but anyway I don't have any Apple device to test this. Let's wait for somebody that can 😉

I would love to help! I'll document the issues and hopefully a solution!

**Comment by GhostCrawl3r** [comment]
Hey Guys,

Just following this up. Does this support TikTok on android/IOS now? - I couldn't see any mention in the docs. 

Cheers,

**Comment by alexandruenache19** [comment]
Hi @MateusAndrade @kaioduarte  @gcrozariol,

Is there any update regarding sharing on Tiktok?

**Comment by kaioduarte** [comment]
Hi @alexandruenache19! Sorry for the delay, I've been not using RN for a while but in my last test on Android it was working fine out of the box.

See the comment with an example https://github.com/react-native-share/react-native-share/issues/752#issuecomment-633915927

**Comment by aftabaminzoobiapps** [comment]
> @MateusAndrade @gcrozariol after a long time I got time to get into this again 😅!
> 
> Just tested the latest version of TikTok and `react-native-share` and the sharing is working properly without any change. I tested on Android 8.1 (AOSP) and 10 (MIUI). Can you guys test this minimal repro on iOS?
> 
> ```js
> import React from 'react';
> import {Button, View} from 'react-native';
> 
> import Share from 'react-native-share';
> import ImagePicker from 'react-native-image-picker';
> 
> export default function App() {
>   function share() {
>     ImagePicker.launchImageLibrary({ mediaType: 'video'}, async res => {
>         if (res.error) {
>           console.log('error while picking video');
>           return;
>         }
> 
>         try {
>           await Share.open({
>             url: `file://${res.path}`,
>             type: 'video/mp4',
>           });
>         } catch (error) {
>           console.log(error);
>         }
>     });
>   }
> 
>   return (
>     <View style={{flex: 1}}>
>       <Button onPress={share} title="Share" />
>     </View>
>   );
> }
> ```

When I tried to share a video to WhatsApp it threw me an error.

**Comment by ami9000** [comment]
Share.open works for TikTok on iOS as well. But is there a way to get Share.shareSingle to work for TikTok too?  That's what looks missing in the `react-native-share` library.

**Comment by alexandruenache19** [comment]
> Share.open works for TikTok on iOS as well. But is there a way to get Share.shareSingle to work for TikTok too? That's what looks missing in the `react-native-share` library.

Same here

**Comment by notRly** [comment]
Trying to share an image to TikTok

```
      Share.open({
             url: 'data:image/svg;base64,.......',
             title: 'Something,
             type: 'image/svg',
             failOnCancel: false,
         })
```

Sharing work for Snapchat and Instagram but for TikTok I'm getting an empty preview on iOS and not having a TikTok option on Android at all. 

Could you please give me a hint — what am I doing wrong? 

![97583922-84806680-1a08-11eb-8d48-098388638f5a](https://user-images.githubusercontent.com/2182254/97729612-ec57af80-1ae3-11eb-903d-44a17c21ca05.jpeg)

**Comment by SethuSenthil** [comment]
> Trying to share an image to TikTok
> 
> 
> 
> ```
> 
>       Share.open({
> 
>              url: 'data:image/svg;base64,.......',
> 
>              title: 'Something,
> 
>              type: 'image/svg',
> 
>              failOnCancel: false,
> 
>          })
> 
> ```
> 
> 
> 
> Sharing work for Snapchat and Instagram but for TikTok I'm getting an empty preview on iOS and not having a TikTok option on Android at all. 
> 
> 
> 
> Could you please give me a hint — what am I doing wrong? 
> 
> 
> 
> ![97583922-84806680-1a08-11eb-8d48-098388638f5a](https://user-images.githubusercontent.com/2182254/97729612-ec57af80-1ae3-11eb-903d-44a17c21ca05.jpeg)
> 
> 

You can't share images in TikTok, only videos

**Comment by NS-BOBBY-C** [comment]
What is the status of this? I'd be willing to pick this up. TikTok now supports images being shared to it

**Comment by vforvasile** [comment]
@NS-BOBBY-C any updates?

**Comment by NS-BOBBY-C** [comment]
My focus shifted elsewhere. I haven't implemented it for my own work yet, but when I get around to it I will keep you all posted!

**Comment by Lg0gs** [comment]
@NS-BOBBY-C 
Keep in mind that the iOS part uses PHAssets for sharing. I spent a week before I figured it out. Just FYI

**Comment by Lg0gs** [comment]
@gcrozariol @kaioduarte @GhostCrawl3r @alexandruenache19 @ami9000 @vforvasile 
Hi guys, I implemented [this](https://github.com/Lg0gs/react-native-tiktok) library that supports sharing videos on both platforms, also authorization works there. You can check it

**Comment by Gavsum** [comment]
Any update on this?  Looks like TikTok is visible in `share.Open` but not `share.singleShare`?

**Comment by EstebanFuentealba** [comment]
@Gavsum you need implement "social/TikTokShare.java) and override `open` method with this data https://developers.tiktok.com/doc/video-kit-sharesheet-sharesheet-for-android

**Comment by ryderSiva** [comment]
Hi guys, I need to implement sharing image and video from react native app to tiktok. Do Anybody have any idea about this.

**Comment by OskarEichler** [comment]
Is there any update on this?

https://developers.tiktok.com/doc/share-kit-ios-quickstart-v2

**Comment by mikehardy** [comment]
Why do people ask for updates when it's clear (as everything is all out in the open) that there are no updates, and yet no one actually invests the effort and posts a PR? That's just not how open source works.

If you want an update you have to be the update.

**Comment by hotairbag** [comment]
have a link?
