### ISSUE TITLE
Can I enable sharing on only certain specific platforms

### ISSUE THREAD

**Issue by samgermain** [react-native-share/react-native-share#755]
I only want sharing in Facebook messenger, Instagram DM, Snapchat, Whatapp, messaging, email and other DM platforms. Can I do this?

I know that you can use `Share.shareSingle` to share on only one platform, but I'm wondering how to only give the option of sharing on about 5 or 6 platforms. It would look like `Share.open` but with some of the options removed

**Comment by MateusAndrade** [comment]
Hey @samgermain, this is really interesting. What do you think about a `exclude` on `Activities`? Currently, we don't this, but this should be a nice addition.

**Comment by samgermain** [comment]
@MateusAndrade Absolutely! I'd even be willing to try to implement it myself, but I feel like I might need some guidance as to what files/functions to look at. I've never contributed to open source before so there's that also.

**Comment by MateusAndrade** [comment]
> @MateusAndrade Absolutely! I'd even be willing to try to implement it myself, but I feel like I might need some guidance as to what files/functions to look at. I've never contributed to open source before so there's that also.

If you need any help, please let me know. Maybe you can start with small changes, like docs, etc. 😄

**Comment by samgermain** [comment]
@MateusAndrade I'll most likely need help. Can you let me know what files/functions to look at though

**Comment by samgermain** [comment]
@MateusAndrade  I have no idea what I'm doing. Can you give me some guidance as to where to look

**Comment by samgermain** [comment]
@MateusAndrade I don't think I serve any use trying to implement this

**Comment by rohitkum28** [comment]
Even I am looking for a way to restrict share to a few apps only. Is this possible currently?

**Comment by sensoft2207** [comment]
@MateusAndrade Yes, This functionality is very usefull, Specially for this type of library. Is there any solution for this ? Right now I am working on post sharing on specific social media. I had seen one enum in library that shows Some social media naming.

**Comment by samgermain** [comment]
@sensoft2207 Are you trying to implement it yourself? If it's not too much to ask, would you be able to summarize what you've looked at so far that might be useful for trying to implement this? You mentioned an enum that you think might be of use? Is there anything else you think might be of use? 

I'm trying to implement it also and if I figure it out, I could let you know how to do it in return

**Comment by MateusAndrade** [comment]
Currently calling `shareSingle` only open a specific app with the Native dialogue. But, we this [ShareSheet](https://github.com/react-native-community/react-native-share/tree/master/components), that is a simple component.

Btw @sensoft2207, I was discussing with @samgermain an way to handle this calling the native dialogue on this issue.

**Comment by samgermain** [comment]
@sensoft2207 @rohitkum28  I realized a work-around is to create an overlay component when your share button is pressed, and inside your overlay you can have your facebook button, instagram button ... which are each linked to a shareSingle operation

**Comment by MateusAndrade** [comment]
> It'd be nice to have a feature that just does this though

You can have a look at: https://github.com/react-native-community/react-native-share/tree/master/components

**Comment by jgcmarins** [comment]
Hello, what's the status of this one?
cc @samgermain @MateusAndrade

**Comment by Goldyukol** [comment]
There was such a function in this library

**Comment by nolife08021** [comment]
Hi, do this feature available now? I would like to share with few selected app only

**Comment by parthasarathi95** [comment]
same here, i want to include only Fb, tiktok, instagram, youtube and X
