### ISSUE TITLE
Unable to share image+text IOS

### ISSUE THREAD

**Issue by sashaskuku** [react-native-share/react-native-share#760]
### Steps to reproduce

code looks like that:

await RNShare.open({
	message: singleItem.name,
	url: imageLink
		});

### Expected behaviour
Share image AND text

### Actual behaviour
This code sends only text. If I remove message at all - it sends image only. 
I tried also to use base64 to send Image with no success.
### Environment
- **React Native version**:"0.61.2",
- **React Native platform + platform version**: iOS 9.0

### react-native-share
**Version**: 2.0.0

**Comment by meetyourdev** [comment]
i am facing this issue as well

**Comment by MateusAndrade** [comment]
This happens only on iOS on a specific app? I remember having a similar issue on WhatsApp. I ended removing the message param on iOS. 😢 

#474

**Comment by hungneox** [comment]
I had similar issue when sharing pdf + text to Slack. Does anyone has the same issue?

**Comment by FrederickEngelhardt** [comment]
Same issue experienced with messages app. It works for me with emails.

**Comment by MateusAndrade** [comment]
> Same issue experienced with messages app. It works for me with emails.

Which platforms are you facing this? Probably this is a problem with the target app. Unfortunately, I faced this on a project and decided to share only the image(it was receipt screen).

**Comment by joedivittorio** [comment]
Seeing a similar issue on iOS. If you add an image AND text, the iOS messages app only uses the image. Able to send only text or only an image but not both on the messages app. Seeing the same behavior on other apps as well like WhatsApp and Slack.

For the mail app, the subject, text, and an image all work as expected with the same parameters.

This is all using the method `RNShare.open`

**Comment by agnieszkabugla** [comment]
I have the same issue on iOS when I want to share an image + message:
- via whatsapp -> only message is shared
- via messanger -> only image is shared
- via mail -> works as supposed, message and image are shared

```

shareSingleImage = async () => {
    const url = 'https://awesome.contents.com/';
    const title = 'Awesome Contents';
    const message = 'Please check this out.';

    const shareOptions = {
      title: 'Share file',
      url: `data:image/png;base64,${this.state.base64}`,
      subject: title,
      message: `${message} ${url}`,
      failOnCancel: false,
    };

    try {
       await Share.open(shareOptions);
    } catch (error) {
      console.log('Error =>', error);
    }
  };
```

**Comment by MateusAndrade** [comment]
Hi @agnieszkabugla, thanks for sharing that. Right now, I think this is some specific implementation calling the activity to WhatsApp that is causing that. To fix that for me, I decided to share the message or the image only when sharing on iOS.

Can you confirm, that this happens when using `Share.single({})`?

**Comment by arieldossantos** [comment]
I'm experiencing the same issue on iOS when using `Share.open({})` and I choose WhatsApp.

**Comment by YathaarthJamwal** [comment]
I have the same issue with RNShare v3.5.0. I am using Share.single() for WhatsApp. It send the url base64 image as text appended after the message text. File path in place of base 64 also is sent as text. This happens only in iOS. On android it works perfectly. Any help?

RN: "0.62.2"

**Comment by MateusAndrade** [comment]
Hi @YathaarthJamwal. We can follow my suggestion at #555 . What do you think?

**Comment by sungsong88** [comment]
Has anybody got to figure out any workaround for this issue??

**Comment by MateusAndrade** [comment]
> Has anybody got to figure out any workaround for this issue??

Which apps are you facing this issue? Unfortunately, I choose to share only the image when the user is sharing from iOS.  :/

**Comment by tarbundiyahitesh21** [comment]
**Share.shareSingle(options)** share image on **whatsapp** is not working while **Share.open(options)** working perfectly.
any solution in ios?

I tried many solution like:
=> pass base64 data in url
=> pass image path in url
this all option perfectly working on facebook sharing but whenever we try on whatsapp is not working.

**Comment by heletrix** [comment]
When I try to send urls of local files and message to iPhone Messages it sends either photos or message, and only very rarely it sends both. 
Appear only on the iOS 14. On the iOS 12 works good.

**Comment by DooaRashidAnsari** [comment]
Any leads on this issue? As we are facing similar situation on IOS when trying to share both text and image

**Comment by TrppnBstrds** [comment]
Hi guys,
how do other apps manage to have such a nice share object in Whatsapp (e.g. sharing a tweet to whatsapp has a thumbnail of a user, a description, etc. and below the deep link to the tweet)...
Is there any way to do this by using this lib?
![IMG_F81E40F39938-1](https://user-images.githubusercontent.com/53033838/165351400-3e0fe617-117b-4323-a2b7-0d0c8b338336.jpeg)

**Comment by mikehardy** [comment]
Would you believe that doesn't have anything to do with this lib? That's a content snippet that you can get for "free" with things like [@react-native-firebase/dynamic-links](https://rnfirebase.io/dynamic-links/usage) where your app is connected to web servers that can generate micro-sites with the correct tags so that when you do social share, the apps hit the site and get a pretty preview

It's an area of quite some stuff to learn - here's the search I'd start with https://search.brave.com/search?q=social+share+preview

**Comment by EstebanFuentealba** [comment]
@TrppnBstrds you need implements OG Tags and Twitter cards en your site 

**Resources**
- https://ogp.me/
- https://developers.facebook.com/docs/sharing/webmasters?locale=es_ES
- https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

**Debug**
- https://developers.facebook.com/tools/debug/

**Comment by akjesto** [comment]
I am using the version  "react-native-share": "^7.3.2". Still, this version shows an issue like being unable to share both base64 image and text.

 RNShare.open({
      message: 'text',
      url
});

How to solve this issue?

**Comment by codeitout32** [comment]
> I am using the version "react-native-share": "^7.3.2". Still, this version shows an issue like being unable to share both base64 image and text.
> 
> RNShare.open({ message: 'text', url });
> 
> How to solve this issue?

have you tried this https://react-native-share.github.io/react-native-share/docs/share-open#lsapplicationqueriesschemes-ios-only
can you tell us what does it fixed or not?

**Comment by gustavolsilvano** [comment]
Hello @codeitout32 . I tried this solution but still don't manage to send text and image on iOS to Whatsapp. To telegram it just keeps on loading but does not work.
