### ISSUE TITLE
 cl.json.RNShareModule.SHARES.instagram-stories

### ISSUE THREAD

**Issue by TheGuy68** [react-native-share/react-native-share#765]
Hi i've just initiated a new app and used the simplest examples from the docs. 

So the share via whats app works fine. 
But as soon as I try and use the Instagram example near to the bottom of the page I get this error: 
 
cl.json.RNShareModule.SHARES.instagram-stories

Theres not much about it on google except one thread which was never resolved.

**Comment by MateusAndrade** [comment]
Hey @TheGuy68 , would you mind sharing the logs that you got from this error? Also, sharing your implementation would help us a lot. 😄

**Comment by TheGuy68** [comment]
well theres not really much to show.
Like I said before. 
This is a basic installation and a brand new react native app and running the example from the docs:

import Share from 'react-native-share';

```
const shareOptions = {
    method: Share.InstagramStories.SHARE_BACKGROUND_AND_STICKER_IMAGE,
    backgroundImage: 'http://urlto.png',
    //stickerImage: 'data:image/png;base64,<imageInBase64>', //or you can use "data:" link
    backgroundBottomColor: '#fefefe',
    backgroundTopColor: '#906df4',
    attributionURL: 'http://deep-link-to-app', //in beta
    social: Share.Social.INSTAGRAM_STORIES
};
Share.shareSingle(shareOptions);
```

And the logs is pretty much what I put the the message above, Other than its wrapped in an object like so: 

```
Object {
    "error": "No enum  constant cl.json.RNShareModule.SHARES.instagram-stories"
}
```

**Comment by MateusAndrade** [comment]
Which platform you are using? I mean Android, iOS?

**Comment by TheGuy68** [comment]
yeah I'm on android. Any timeline of when you think you'll be supporting this feature on android?

**Comment by jgcmarins** [comment]
@TheGuy68 we're accepting PRs that land this feature into Android

**Comment by nataly-chobat** [comment]
Unfortunately faced the same issue, have you found any solution @TheGuy68 ?

**Comment by nataly-chobat** [comment]
The error above was fixed once I updated version from 3.0.0 to 3.7.0 but instagram share on android still does not work

**Comment by retyui** [comment]
@TheGuy68 

Please update to the latest version 

```diff
-react-native-share@^3.x.x
+react-native-share@^3.7.0
```

**Comment by codervss** [comment]
Getting the same error after upgrade too.
Someone Please help

**Comment by mariaaxime** [comment]
I'm having the same issue with `react-native-share@^3.7.0`

```
2020-09-02 16:15:10.745 5957-6093/xxx.xxx E/ReactNativeJS: │ Error: undefined
2020-09-02 16:15:10.750 5957-6093/xxx.xxx E/ReactNativeJS: │ 'error: ', 'No enum constant cl.json.RNShareModule.SHARES.instagramstories'
```

**Comment by retyui** [comment]
стоп
