### ISSUE TITLE
Implement scoped storage support for Android 10

### ISSUE THREAD

**Issue by stoica94** [react-native-share/react-native-share#787]
## Describe the Feature

Implement `scoped storage` functionality for devices with Android 10.
Right now the fix is to add `android:requestLegacyExternalStorage="true"` in Manifest but this is temporary and it will be deprecated in future releases. 

This is only related to sharing media. Text works fine

## Possible Implementations

I don't really know right now because I'm not familiar with the implications but I'm happy to contribute if I am offered some guidance or info about what needs to change 

Maybe this article helps: https://heartbeat.fritz.ai/implementing-scoped-storage-in-android-10-4b657280c066

## Related Issues

https://github.com/react-native-community/react-native-share/issues/650#issuecomment-567435224

**Comment by anjalsaneen** [comment]
Is there anyone looking into this. From May 5 Android Playstore won't allow `android:requestLegacyExternalStorage`?

<img width="1107" alt="Screenshot 2021-04-22 at 12 21 42 PM" src="https://user-images.githubusercontent.com/43947967/115668900-4d5e9280-a365-11eb-9e51-4db90946ea8f.png">
