### ISSUE TITLE
Share image and message on ios not working

### ISSUE THREAD

**Issue by marcoburrometo** [react-native-share/react-native-share#831]
Hello,

I'm trying to share image and message in ios but with no luck using version 3.7.0.

here is my code:
```
const base64Image = await RNFS.readFile(
        'file://'+imgUrl',
        'base64',
      );
      await Share.open({
        url: 'data:image/png;base64,'+base64Image,
        title: _t('trip_recap.share_title'),
        message: 'message text',
      });

```
If i use both message and url i only see message.

Can anyone help?

**Comment by MateusAndrade** [comment]
Hi @marcoburrometo , in which applications you are facing this issue? I remember having a similar issue on WhatsApp on iOS.
#474

**Comment by marcoburrometo** [comment]
> Hi @marcoburrometo , in which applications you are facing this issue? I remember having a similar issue on WhatsApp on iOS.
> #474

Whatsapp, Facebook and instagram.

**Comment by MateusAndrade** [comment]
> > Hi @marcoburrometo , in which applications you are facing this issue? I remember having a similar issue on WhatsApp on iOS.
> > #474
> 
> Whatsapp, Facebook and instagram.

You can try passing the absolute URL? 🤔

**Comment by marcoburrometo** [comment]
> > > Hi @marcoburrometo , in which applications you are facing this issue? I remember having a similar issue on WhatsApp on iOS.
> > > #474
> > 
> > 
> > Whatsapp, Facebook and instagram.
> 
> You can try passing the absolute URL? 🤔

An absolute URL of a hosted png? Or something like `'file://'+imgUrl',` instead of the base64 string?

**Comment by mohammad** [comment]
Has there been a resolution to this problem? I'm facing the same issue where I'm passing a base64 image that is procured via `canvas.getDataURL()` as the value for the `url` key.

**Comment by MateusAndrade** [comment]
> Has there been a resolution to this problem? I'm facing the same issue where I'm passing a base64 image that is procured via `canvas.getDataURL()` as the value for the `url` key. I'm running into this when using `Share.open`

You can try sharing the absolute file url, but if you want to share the filed directly you would need to convert this to a file and save that to your device. Also, which canvas implementation are you using?

**Comment by mohammad** [comment]
Using [this](https://github.com/iddan/react-native-canvas) package for React Native Canvas. What do you mean by the absolute file URL – is the base64 value not sufficient? Thank you for the help so far!

**Comment by cristianoccazinsp** [comment]
Any luck? Similar issue here.

**Comment by redko-o** [comment]
Same issue

**Comment by McSam94** [comment]
Same issue. Any update?

**Comment by merissaacosta** [comment]
I am running into the same issue.

**Comment by th0r0nd0r** [comment]
I'm having the same issue. Anyone find a fix?

**Comment by rpc1910** [comment]
same issue. Any solution?
