### ISSUE TITLE
Share to telegram is not working on ios

### ISSUE THREAD

**Issue by Zhark10** [react-native-share/react-native-share#835]
### My code:
const onSharePress = async () => {
    const res = await Share.open({
      url: base64image ('data:image/png;base64,...'),
      message: 'Some text',
    })
    
   console.log(res)
}

### Actual behaviour
When you choose telegram from the list of social networks, there is an endless loader (IOS)

### Environment
- **React Native version**: 0.61.5
- **React Native platform + platform version**: IPhone 7

### react-native-share
**Version**: 3.7.0

**Comment by rodrigogirao** [comment]
Same with me 
- React Native version: 0.62.2
- React Native platform + platform version: IPhone 8, iOS 13.5.1

**Comment by MateusAndrade** [comment]
Hi @rodrigogirao , @Zhark10. Anyone can share the payload that is being passed to Share?

**Comment by rodrigogirao** [comment]
Hi @MateusAndrade I've tried to share a converted base64Image that I read with `rn-fetch-blob`
```js
RNFetchBlob.config({
      fileCache: true,
    })
      .fetch('GET', imageUrl)
      .then((resp: FetchBlobResponse) => resp.readFile('base64'))
      .then(base64Data => Share.open({ url: `data:image/png;base64, ${base64Data}` })),
```
When I share to Telegram stays in this loading and do not finish share
![IMG_6F872A13E2E2-1](https://user-images.githubusercontent.com/2385859/89309812-47dfe180-d64a-11ea-9097-6a3f267a6d52.jpeg)

**Comment by Zhark10** [comment]
Will this problem be resolved or is it necessary to change the library?

**Comment by diegobugs** [comment]
Still not working

**Comment by PrimulaX** [comment]
This problem still not resolved.
While sharing in telegram this loading indicator keeps forever.

**Comment by mikehardy** [comment]
@PrimulaX interesting! What did you see when you added console output to the node_modules javascript and .m files then watched the logs in Xcode while launched on a real device? Curious what the root cause is and it looks like you have a reproduction so you could nail it and make a PR

**Comment by PrimulaX** [comment]
@mikehardy here is Xcode logs while canceling action sheet:
```
2021-07-12 22:10:42.789146+0400 Elevator[23535:1040507] [core] SLRemoteComposeViewController: (this may be harmless) viewServiceDidTerminateWithError: Error Domain=_UIViewServiceErrorDomain Code=1 "(null)" UserInfo={Terminated=disconnect method}
2021-07-12 22:10:43.307272+0400 Elevator[23535:1042137] [ShareSheet] connection invalidated

```
But that gives me nothing, actually Xcode logs nothing while loading telegram action sheet.

**Comment by mikehardy** [comment]
@PrimulaX 

> What did you see when you **added console output to the node_modules javascript and .m files** then watched the logs in Xcode while launched on a real device?

emphasis added

**Comment by PrimulaX** [comment]
Actually I tried that but did it wrong way I guess.

**Comment by sebazh** [comment]
Any chance to fix this issue? It still happens

**Comment by mikehardy** [comment]
@sebazh have you done the work? Please share your findings:

https://github.com/react-native-share/react-native-share/issues/835#issuecomment-878499175

**Comment by sebazh** [comment]
@mikehardy yes, it works if you stick to this answer: https://github.com/react-native-share/react-native-share/issues/737#issuecomment-696822362

**Comment by mikehardy** [comment]
Hmm if doing an intermediate cache save works seems like a PR to the docs might help folks...
