### ISSUE TITLE
Possibility to specify custom action extensions?

### ISSUE THREAD

**Issue by isbaek** [react-native-share/react-native-share#836]
## Ask your Question

Hi there,

Is there a possibility to support custom action extensions? For example, Twitter has something like this which they've specified in the share menu:
![IMG_2877](https://user-images.githubusercontent.com/2745549/88984422-8caaf780-d29b-11ea-883c-7d58e9247cc3.jpg)

I believe this comes from extending the actions listed in `UIActivityViewController`, was wondering if this was a possibility.

Thanks guys.

**Comment by NirmalsinhRathod** [comment]
Any update on this ?
