### ISSUE TITLE
Sharing a Base-64 encoded PDF on Android is broken on targetSdk 29

### ISSUE THREAD

**Issue by WaterCityFlame** [react-native-share/react-native-share#839]
### Steps to reproduce
1. Change your android/build.gradle so the following lines use version 29: 
```
        buildToolsVersion = "29.0.0"
        compileSdkVersion = 29
        targetSdkVersion = 29
```
2. Add a button or something to share a PDF file that was base-64 encoded
```javascript
/*options like */
const options = {
    url: "date:application/pdf;base64, /*something,something,file */"
    type: "application/pdf"
}

/* on press function like: */
onPress = () => {
         Share.open(options)
              .then((res) => {
                  console.log(res);
              })
              .catch((err) => {
                  err && console.log(err);
              })
}
```
3. Build your app
4. Press the button
5. Allow file system access when Android asks
6. Select an app to share it with (I use GMail usually)

### Expected behaviour
I expect the selected app to open with the PDF file. E.g. GMail should have it already attached to a new message

### Actual behaviour
The selected app opens, but there is no PDF. E.g. GMail opens to write a new message, but there is no attachment

### Environment
- **React Native version**: "0.63.2" - in another project using "0.61.5" I also reproduced this 
- **React Native platform + platform version**: Android 10.0

### react-native-share
**Version**: 3.7.0 - the one you get running `npm i react-native-share --save`

### Link to repo
https://github.com/WaterCityFlame/PdfSharingAndroid
The branch target-sdk-28 shows that it **does** work when your targetSdk is 28. 

### Other Questions You May Have: 
**Does this impact all base-64 encoded files or just PDFs?"** I don't actually know, will try to reproduce that tonight. 
**Does using the "filename" option instead of the "url" option fix it?"** Nope. I don't have a work-around at present
**If you include other options, do they work?"** message does, don't know about others.

**Comment by adrianm86** [comment]
Sharing png and jpeg images with base64 in react-native 0.63.2 also does not work.
I've updated to this new version of react-native and it doesn't work anymore.

**Comment by WaterCityFlame** [comment]
@adrianm86 what's in your android/build.gradle file at the moment? My working theory was that the cause was the targetSdk, not the react-native version directly (although RN may update that)

**Comment by adrianm86** [comment]
Yes, I also have targetSdk 29.
Since version 0.63 of react-native the default Android targetSdk is version 29.

**Comment by mutablestudio** [comment]
I'm experiencing the same issue but only in Release builds - when I run in debug mode the PDF attaches fine and I receive it correctly on the other end in my inbox. I'm on RN 0.62.2 and targetSDK 29. 

The share docs here say that URL only supports `base64 string in iOS & Android`. How are you reading the contents of the PDF and structuring the attachment? I'm using RNFS like so, see the contents def for url prop:

```
      RNFS.readDir(RNFS.DocumentDirectoryPath) // On Android, use "RNFS.DocumentDirectoryPath" (MainBundlePath is not defined)
      .then((result) => {
        // stat the file
        return Promise.all([RNFS.stat(filePath.current), filePath.current])
      })
      .then((statResult) => {
        if (statResult[0].isFile()) {
          return RNFS.readFile(statResult[1], 'base64')
        }
        return 'no file'
      })
      .then(async (contents) => {
        const fileName = data.reports[props.index]+'_'+props.firstName+'_'+props.lastName
        contents = `data:application/pdf;base64,` + contents
        const ShareResponse = await Share.open({ 
          title: 'Share report', 
          filename: fileName,
          failOnCancel: false,
          saveToFiles: false,
          url: contents 
        })
      })
```

Seems odd that it works in debug but not release...

**Comment by mutablestudio** [comment]
I was able to resolve this by bumping the target and build tools in the `react-native-share` android gradle to `29` - now working w release builds, verified by several testers:

```
android {
    compileSdkVersion safeExtGet('compileSdkVersion', 29)
    buildToolsVersion safeExtGet('buildToolsVersion', '29.0.3')
    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion safeExtGet('targetSdkVersion', 29)
    }
    lintOptions {
        abortOnError false
        warning 'InvalidPackage'
    }
}
```

**Comment by agnieszkabugla** [comment]
After upgrading to targetSDK 29, `shareOpen` does not work on Whatsapp, facebook or instagram. It works on gmail though. 
All of it worked in previous Sdk version. Anyone found the solution? 
This is my function:
```
    // This function shares an image using the url param
    shareSingleImage = async () => {
        const title = `Mijn ${this.state.type} delen`;

        const shareOptions = {
            title: 'Share file',
            url: `data:image/png;base64,${this.state.base64}`,
            subject: title,
            failOnCancel: false,
        };

        try {
            await Share.open(shareOptions);
        } catch (e) {
            this.log.debug('Could not share measurements', e, null)
        }
    };
```

**Comment by WaterCityFlame** [comment]
@mutablestudio That's bizarre, but on the other hand, it looks like you may have found a fix for the issue :D I'm gonna see if that works in my test repo as well

**Comment by WaterCityFlame** [comment]
@mutablestudio I forked this repo and made a branch with your fix: at least in my PdfSharingAndroid test repo, it didn't fix the issue. You asked how other people were getting their base64 string: in the app where I originally ran into this, we have a custom library that builds pdfs and makes strings. I'd have to investigate it a little to figure out what it's using. On my test repo, it's just a hard-coded string. 

@agnieszkabugla no, doesn't look like there's a solution yet. I used react-native-share-pdf for my use case, but I don't love being dependent on something with one maintainer that's at version 0.0.5. Would rather see a fix here. 

The number of slightly-different reproductions of this bug is wild to me.

**Comment by MateusAndrade** [comment]
Hi @WaterCityFlame , would you mind sharing your fix with us? Also, I've been looking at some issues related to Flipper when handling `base64` with`react-native`. #797

**Comment by AnagramEngineering** [comment]
Looking at the fork of @WaterCityFlame 

https://github.com/WaterCityFlame/react-native-share/commit/322dab6e5a65ac15407e187f9b8cae04f4040db6

it seems `compileSdkVersion`, `buildToolsVersion` and `targetSdkVersion` in `android/build.gradle` have been updated to 29 but as she mentioned this did not do the trick for her - neither for me. 

What i see is this error: 

`java.io.FileNotFoundException: /storage/emulated/0/Download/Log_7_ramanga_2020_08_16_0943.txt.txt: open failed: EACCES (Permission denied)`

It seems it's caused by ShareFile.java (117): 

`
final FileOutputStream fos = new FileOutputStream(file);
`

Furthermore i found a workaround that seems to work (for now): 

Adding 

`android:requestLegacyExternalStorage="true"`

to the AndroidManifest.xml solves the Permission problems on my side. 


This is a workaround that will stop to work with Android 11. 

**Caution: After you update your app to target Android 11 (API level 30), the system ignores the requestLegacyExternalStorage attribute when your app is running on Android 11 devices, so your app must be ready to support scoped storage and to migrate app data for users on those devices.**

https://developer.android.com/training/data-storage/use-cases

**Comment by WaterCityFlame** [comment]
@MateusAndrade At work? Switched to using https://github.com/MadeinFrance/react-native-share-pdf which I would rather not do because it looks like it's not being actively maintained like this project is. I don't know how that will handle android 11+ but it works for now. In the test repo, switching the `targetSdk`, `compileSdk` and `buildToolsBersion` of the **whole app** to 28 worked. If you want to be able to keep updating your app in google play after early November you need to be using 29, so that's not a good fix.

@AnagramEngineering well, that gets us better info on root cause anyway, thanks for figuring it out. I wondered if scoped storage was the issue here

**Comment by pinheiroRafa** [comment]
> Looking at the fork of @WaterCityFlame
> 
> [WaterCityFlame@322dab6](https://github.com/WaterCityFlame/react-native-share/commit/322dab6e5a65ac15407e187f9b8cae04f4040db6)
> 
> it seems `compileSdkVersion`, `buildToolsVersion` and `targetSdkVersion` in `android/build.gradle` have been updated to 29 but as she mentioned this did not do the trick for her - neither for me.
> 
> What i see is this error:
> 
> `java.io.FileNotFoundException: /storage/emulated/0/Download/Log_7_ramanga_2020_08_16_0943.txt.txt: open failed: EACCES (Permission denied)`
> 
> It seems it's caused by ShareFile.java (117):
> 
> `final FileOutputStream fos = new FileOutputStream(file);`
> 
> Furthermore i found a workaround that seems to work (for now):
> 
> Adding
> 
> `android:requestLegacyExternalStorage="true"`
> 
> to the AndroidManifest.xml solves the Permission problems on my side.
> 
> This is a workaround that will stop to work with Android 11.
> 
> **Caution: After you update your app to target Android 11 (API level 30), the system ignores the requestLegacyExternalStorage attribute when your app is running on Android 11 devices, so your app must be ready to support scoped storage and to migrate app data for users on those devices.**
> 
> https://developer.android.com/training/data-storage/use-cases

Resolved for me

**Comment by robert-hung-mox** [comment]
Google has now restricted the usage of `requestLegacyExternalStorage` flag and requires any app that currently uses it to either:
1. Use the preferred method of Scoped Storage (Storage Access Framework or Media Store API)
2. Use `MANAGE_EXTERNAL_STORAGE` permission and complete the `All Files access permission declaration` in Play Console from May 5th
3. Remove the `All files access permission from your app entirely`

Anyone have any suggestions on how to avoid needing broad storage access?

We suspect the culprit is this [LOC](https://github.com/react-native-share/react-native-share/blob/v5.1.1/android/src/main/java/cl/json/ShareFile.java#L125).
