### ISSUE TITLE
(iOS) Name of pdf file when saved (PDF document) 

### ISSUE THREAD

**Issue by Ajbadenhorst** [react-native-share/react-native-share#842]
Does anyone know how to set/customize the name of the PDF file when saved on iOS?

Base64 PDF Url -> Save to files(ios) -> PDF document Name

![image](https://user-images.githubusercontent.com/37651247/89401450-97d7aa80-d715-11ea-8239-36527bdbb734.png)

**Comment by CyberMew** [comment]
I am having this question as well, but upon reviewing the code it doesn't seem to be able to take in `filename` parameter at all and use it. This is verified by the feature list here for iOS: https://react-native-community.github.io/react-native-share/docs/share-open. I do not know enough of iOS share sheet with base64 files to determine if this is technically possible to be done or not.

The alternative is for you to convert it to file with a proper filename and share it out, and delete the file once done. Might want to take a look at RN Fetch Blob if you haven't.

**Comment by MateusAndrade** [comment]
Hi @CyberMew, @Ajbadenhorst , passing the `filename` on iOS hasn't any effect on changing that? Also, would you mind sharing the config passed to `rn-share` @Ajbadenhorst ?

**Comment by CyberMew** [comment]
@MateusAndrade for base64 files it has no effect and as per the table in the documentation it is not supported.
