### ISSUE TITLE
Sharing a base64 PDF requires external permissions

### ISSUE THREAD

**Issue by CyberMew** [react-native-share/react-native-share#843]
Android.

### Steps to reproduce
1. Convert PDF to base64
2. Share.open

### Expected behaviour
There should be no requesting. If needed it should have an option to save to it's own internal folders, share that out, and delete after. No popup requesting for permissions.

### Actual behaviour
Requesting WRITE_EXTERNAL_STORAGE permission when trying to share the base64 PDF to e.g. Gmail.

### Environment
- **React Native version**: 0.61.5
- **React Native platform + platform version**: Tried it on Android 11.

### react-native-share
**Version**: 3.1.1

**Comment by MateusAndrade** [comment]
Hi @CyberMew , the file that you are trying to share is saved internally on your project inside the `react-native` side, or it's stored in the native side?

**Comment by CyberMew** [comment]
Hi @MateusAndrade, not sure what you mean but the file is first stored in cache directory via RNFetchBlob and then converted to base64 and shared. It is stored via react native side using RNFetchBlob. And as per https://github.com/react-native-community/react-native-share/blob/master/android/src/main/java/cl/json/ShareFile.java#L112 it is requesting for external permissions.

**Comment by CyberMew** [comment]
Looks like this is solved in 4.0.0?
