### ISSUE TITLE
Share.single not working

### ISSUE THREAD

**Issue by AkshatS2196** [react-native-share/react-native-share#845]
Issue ->  Possible Unhandled Promise Rejection (id: 0):
TypeError: _reactNativeShare.default.single is not a function. (In '_reactNativeShare.default.single(shareOptions)', '_reactNativeShare.default.single' is undefined)

**Comment by Asalem1** [comment]
Should be resolved with this PR:

https://github.com/react-native-community/react-native-share/pull/850
