### ISSUE TITLE
shareSingle: email and attachments not working

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-share/react-native-share#846]
### Steps to reproduce
1. Call `shareSingle` with the following options:
```
{
    message,
    subject,
    email,
    social: Share.Social.EMAIL,
    url: "file:// some path",
    type: 'application/octet-stream'
}
```

2. Observe email app being opened

### Expected behaviour
The email should contain both message and the file included in `url`. However, on iOS, this will just append the file URI to the end of the message. On Android, the attachment is included just fine.

Additionally, if we use `open` instead of `shareSingle` and pick the email client, the file is included just fine on both iOS and Android, but if we do this, we cannot set the email to address.

### Actual behaviour
File attachments should work on both android and iOS

### Environment
- **React Native version**: 0.62.2
- **React Native platform + platform version**: iOS 10+, Android 6+

### react-native-share
**Version**: 3.7.0

### Link to repo (highly encouraged)
-

**Comment by cristianoccazinsp** [comment]
Additionally, `Share.open` should set the default email when `email` is given, just like `shareSingle` (which is by the way incorrectly documented).

**Comment by IndianNative** [comment]
This isssue is now consistent in both android and ios, email doesn't attach the attachment

**Comment by peterchen2cfa** [comment]
any update on this?
