### ISSUE TITLE
Share.open options are not working well (title, icon does not show)

### ISSUE THREAD

**Issue by aborile** [react-native-share/react-native-share#848]
## Ask your Question

I want to use `Share.open()` with my custom values, but it does not work as expected.
In iOS, `activityItemSources` option goes well but it does not display icon that I want to show.
Moreover in android, title does not come up and I can see just only messages and url. (In addition, I want to show message only in sharesheet and share the url value only, but android shows and shares both message and url. Isn't there any options to customize it?)

**This is a capture that what it goes like**

![image](https://user-images.githubusercontent.com/37267486/91420976-522f7d00-e890-11ea-9773-91b2ecee5fb3.png)

and **this is my code**
```
const onShare = async () => {
    try {
      const url = 'https://real-value-to-share-with'
      const title = 'HI THIS IS TITLE'
      const message = 'and this is just a message'
      const icon = 'data:<data_type>/<file_extension>;base64,<base64_data>'
      const shareResponse = await Share.open(
        Platform.select({
          ios: {
            failOnCancel: false,
            activityItemSources: [
              {
                placeholderItem: { type: 'text', content: message },
                item: { default: { type: 'url', content: url } },
                linkMetadata: { title, originalUrl: message, icon },
              },
            ],
          },
          default: { failOnCancel: false, message, url, title, },
        }),
      )
      console.log(shareResponse)
    } catch (error) {
      console.error(error)
    }
  }
```

**What I want to do**
* show title and message individually
* distinguish value to show in ShareSheet from value to share with (just like what iOS does now)
* (optional) show custom icon

**What I use**
|libraries|version|
|--------|-------|
|react-native|0.63.2|
|react-native-share|^3.7.0|
|typescript|^3.8.3|

**Comment by nkjaiswal** [comment]
+1

**Comment by fritzfr** [comment]
For me, nothing shows (on iOS 13.7 Simulator and Phone). It's just a blank white screen.

**Comment by aborile** [comment]
I found that in ios, regardless of `icon` option,
if there is any `url` or `originalUrl` option, it just shows *__default url icon__*

![image](https://user-images.githubusercontent.com/37267486/93156227-a9639780-f742-11ea-8196-452e24f5419f.png)
```
linkMetadata: {
            title: 'Title',
            originalUrl: 'originalUrl',
          },
```
![image](https://user-images.githubusercontent.com/37267486/93156262-c1d3b200-f742-11ea-9e38-91d0eafe8cac.png)
```
linkMetadata: {
            title: 'Title',
            url: 'url',
          },
```
![image](https://user-images.githubusercontent.com/37267486/93156466-327ace80-f743-11ea-9f10-bccc6dce3844.png)
```
linkMetadata: {
            originalUrl: 'originalUrl',
            url: 'url',
          },
```

.

but if not, (if there is `title` only or no options exist) it shows the *__app icon__*

![image](https://user-images.githubusercontent.com/37267486/93156289-cd26dd80-f742-11ea-972e-dde83110deb1.png)
```
linkMetadata: {
            title: 'Title',
          },
```
![image](https://user-images.githubusercontent.com/37267486/93156318-de6fea00-f742-11ea-961c-a16c855323e6.png)
```
linkMetadata: { },
```

all above case, I didn't give any `icon` or `image` options
does there anyone know that is this bug or not??

**Comment by MateusAndrade** [comment]
Hi, @aborile thanks for sharing that with us. Looking at the native code that handles this, possible it related to this part:

https://github.com/react-native-community/react-native-share/blob/06bfa5ed58be5a7248c1a1f1bd1273ea4ea46505/ios/RNShareActivityItemSource.m#L269-L280

Could you help us debugging that with our example app? Since we've implemented this feature with have been with a lack of documentation/examples explaining how this works. You can follow this [guide](https://react-native-community.github.io/react-native-share/docs/contributing#using-the-example-app) to run our example app.

**Comment by reyalpsirc** [comment]
@MateusAndrade Any news about this?

**Comment by smn-snkl** [comment]
Any update? Having the same issue.

**Comment by RafaelA977** [comment]
It's the same for me. I am unable to customize the title, icon on ** android **.
I used the following configs:
`Share.open({
     title,
     message,
})`
And displayed as:
![image](https://user-images.githubusercontent.com/34536550/113839438-bc9e8900-97a0-11eb-9b84-0182f099152b.png)

**Comment by th0r0nd0r** [comment]
any updates on this?

**Comment by guy-shahine** [comment]
The issue should remain open as it is not resolved and no answer from the authors

**Comment by mikehardy** [comment]
Well, the thing about the stale bot is that it is on *objective* measure of how much the community cares.
No one apparently cares enough to propose a PR, so it is *objectively* not interesting. Real time actually passed. Nothing happened.
Or someone would have proposed a PR.
Open Source software is not magic, it requires effort.

**Comment by pehagg** [comment]
Off topic for this issue, but can't resist to comment on @mikehardy 's comment, which I totally agree with, btw.

There's a lot of RN developers out there that don't have experience in native at all. Maybe this is the reason why there's such low interest in posting PRs to RN repos in general? There's also some projects which have an unsurmountable amount of process to get a PR in. I spend 8-9 hours each workday writing software or solving software related problems for business, I rarely have the energy to spend more time on top of that to jump process hoops for sometimes extremely trivial PRs.

**Comment by mikehardy** [comment]
Here it's basically post a PR, if it looks good it gets merged. A bot releases it automatically. No need to presume failure before trying. If the work day consumes all energy... But the work involves using the module that needs the languishing feature, perhaps work should prioritize and pay for your time working on the feature. I think that's the most common (and most sustainable) open-source support case for people and biz. Either way, cheers 😁

**Comment by jrhager84** [comment]
Has anyone been able to get this to work? The documentation isn't very clear on their either.

**Comment by myshine112** [comment]
hi, @aborile .
I have the same issue as you. 
did you solve that issue?

**Comment by aborile** [comment]
> hi, @aborile . I have the same issue as you. did you solve that issue?

Sorry for late reply. Unfortunately, I did not solve this issue yet :(
I just shared without any icon or image, just pure text

**Comment by melyux** [comment]
Dead project
