### ISSUE TITLE
Instagram Stories - No Success Callback (iOS only)

### ISSUE THREAD

**Issue by AechDub** [react-native-share/react-native-share#857]
### Steps to reproduce
1. Attempt to share to instagram stories
2. Return to app
3. Notice no success callback is triggered.

### Expected behaviour
As other share behaviours, a success callback should trigger

### Actual behaviour
We have a thread waiting for return that never completes.

### Environment
- **React Native version**: 0.62.2
- **React Native platform + platform version**: iOS 13.6.1

### react-native-share
**Version**: 3.7.0

### Link to repo (highly encouraged)
n/a

**Comment by AechDub** [comment]
Stalebot shouldn’t drop tickets like this. We have people who have made actions on this to follow. :)

**Comment by MateusAndrade** [comment]
> Stalebot shouldn’t drop tickets like this. We have people who have made actions on this to follow. :)

Hi @AechDub, did you find what was causing that at your project? I think it's related to other issues with Instagram Shar. If you found anything that may help us debugging that It would be great to add this to the docs(or maybe finding a fix) 😃

**Comment by ksairi** [comment]
@MateusAndrade @AechDub 
Hi all! I'm having an strange issue with this lib, I take a any example that should work like this one:
```
try {
          const shareOptions = {
            method: Share.FacebookStories.SHARE_BACKGROUND_AND_STICKER_IMAGE, // iOS only
            backgroundVideo: 'URI_TO_MP4', // Android only (uri to a local file)
            backgroundImage: 'http://urlto.png', // url or an base64 string
            stickerImage: 'data:image/png;base64,<imageInBase64>', // or you can use "data:" url
            backgroundBottomColor: '#fefefe',
            backgroundTopColor: '#906df4',
            attributionURL: 'http://deep-link-to-app', // in beta
            appId: '219376304', // facebook appId
            social: Share.Social.FACEBOOK_STORIES,
          };

          await Share.shareSingle(shareOptions);
        } catch (e) {
          console.log(e);
        }
```
and I don't get any response at all, no errors on catch and if I do 
```
       const response = Share.shareSingle(shareOptions);
       console.log(response)
```
`{}` gets printed
This is happening with `Share.Social.*`, This is in iOS 14.1 and latest lib version
any ideas?
