### ISSUE TITLE
Cannot share image on whatsapp iOS, even without message.

### ISSUE THREAD

**Issue by krrevilla** [react-native-share/react-native-share#861]
### Steps to reproduce
I’m trying to share an image to whatsapp. According to https://github.com/react-native-community/react-native-share/issues/280#issuecomment-581819939, you cannot share message and image at the same time.

I’ve tried to share message only, and it is working.

```
        Share.shareSingle({
            message: ‘Hello’,
            social: Share.Social.WHATSAPP,
            whatsAppNumber: ''
        });
```

But if I tried to share an image only, it doesn’t work. Nothing is happening. Whatsapp not even opening.

```
        Share.shareSingle({
            url: fileUrl
            social: Share.Social.WHATSAPP,
            whatsAppNumber: ''
        });
```

I also tried using the **Share.open** then select **Whatsapp**, and it's working.
```
Share.open({ url: fileUri })
```

This issue only happens on iOS, it’s working on Android.

### Expected behaviour
Able to share image on whatsapp

### Actual behaviour
Not sharing image on whatsapp

### Environment
- **React Native version**: 0.62.2
- **React Native platform + platform version**: iOS 13.6

### react-native-share
**Version**: 3.7.1

**Comment by MateusAndrade** [comment]
Are you passing a base64 or an absolute path to a given image with the `fileUrl` param?

**Comment by krrevilla** [comment]
> Are you passing a base64 or an absolute path to a given image with the `fileUrl` param?

@MateusAndrade base64

**Comment by IrfanKhan01** [comment]
Try **3.7.0** version @krrevilla

**Comment by MateusAndrade** [comment]
Maybe this is related to some base64 changes between https://github.com/react-native-community/react-native-share/compare/v3.7.0...v3.7.1. Would you mind help us @IrfanKhan01?

**Comment by douglasjunior** [comment]
I tried on version v3.6.0, works on Android 10, but don't work on iOS 13.

I'm using `shareSingle` with `base64` for WHATSAPP and EMAIL.

```js
       Share.shareSingle({
            title: 'Foo',
            url: 'data:application/pdf;base64,....',
            social: Share.Social.WHATSAPP, // or Share.Social.EMAIL
        });
```

No erros on Xcode console, just don't work.

**Comment by IrfanKhan01** [comment]
@MateusAndrade  did you update RN version?

**Comment by MateusAndrade** [comment]
> @MateusAndrade did you update RN version?

Yep, In [3.8.0](https://github.com/react-native-community/react-native-share/releases/tag/v3.8.0), it was updated to `63.2.0`. Do you think this problem can be related to this?

**Comment by vajid-khan** [comment]
Hi, I am having similar issue on ios.
Using version 3.7.0
```
const options = {
            title: 'Title',
            subject: 'subject',
            url: `data:image/png;base64,${qrBase64}`,
            message: 'message',
        }

        Share.open(options)
            .catch(error => console.log({ error }))
```
I am selecting whatsapp from picker.
Its working fine on android

**Comment by AbdelkhalekESI** [comment]
Solving this by downgrade version to 3.7.0

**Comment by vinhnglx** [comment]
I'm having the same issue. Ony image can't share on whatsapp, pdf can

**Comment by vajid-khan** [comment]
To share images on ios via whatsapp, you just need to pass options without message attribute.
I had to put platform check
``` 
if(Platform.OS== 'ios'){
    delete options.message
}
```

**Comment by vinhnglx** [comment]
@vajid-khan thank you for your help. It works :)

**Comment by douglasjunior** [comment]
Base64 still not working, even without message.

```js
       Share.shareSingle({
            title: 'Foo',
            url: 'data:application/pdf;base64,....',
            social: Share.Social.WHATSAPP, // or Share.Social.EMAIL
        });
```

**Comment by vinhnglx** [comment]
@douglasjunior I'm using the filePath, not base64. Below is my function. It works for both image and pdf.
 
```
shareWithIOS = (url, title) => {
    const fs = RNFetchBlob.fs;
    let filePath = null;
    const configOptions = {
      fileCache: true,
      path:
        fs.dirs.DocumentDir +
        `/${title.split(".")[0]}.${this.getFileExtension(title)}`,
    };

    RNFetchBlob.config(configOptions)
      .fetch("GET", url)
      .then(async (resp) => {
        filePath = resp.path();

        let options = {
          type: this.checkShareFileMIMEType(title),
          url: `file://${filePath}`,
          subject: title,
        };

        await Share.open(options)
          .then((res) => {
            console.log(res);
            // remove the file from storage
            return fs.unlink(filePath);
          })
          .catch((err) => {
            err && console.log(err);
          });
      });
  };
```

Base64 is used when sharing on Android

**Comment by MateusAndrade** [comment]
> Hi, I am having similar issue on ios.
> Using version 3.7.0
> 
> ```
> const options = {
>             title: 'Title',
>             subject: 'subject',
>             url: `data:image/png;base64,${base64}`,
>             message: 'message',
>         }
> 
>         Share.open(options)
>             .catch(error => console.log({ error }))
> ```
> 
> I am selecting whatsapp from picker.
> With this on ios only message is passed not image
> Its working fine on android


Hi, @vinhnglx unfortunately on iOS it's not possible to share both image+message. 
> 




> Base64 still not working, even without message.
> 
> ```js
>        Share.shareSingle({
>             title: 'Foo',
>             url: 'data:application/pdf;base64,....',
>             social: Share.Social.WHATSAPP, // or Share.Social.EMAIL
>         });
> ```

Could you share which `react-native`, `react-native-share`, and which platforms version are you using? Recently due to flipper we had some problems using when we were sharing files with `base64` on iOS #797

**Comment by vinhnglx** [comment]
@MateusAndrade I'm using `"react-native": "0.62.2",` and `"react-native-share": "^3.8.3"`. 

The sharing files with `base64`, I only use for Android.

**Comment by mssha** [comment]
It seems like sharing to WhatsApp on iOS with Share.shareSingle only supports video and text.  Looking at WhatsAppShare.m, UIDocumentInteractionController is only used for video, and anything else is passed in as the text param.  

That means I can't share a local image to WhatsApp, right?  Am I missing something?

**Comment by livingmine** [comment]
@mssha no, you can, i'm using 3.6.0 and i'm able to shareSingle a **base64 image** to WhatsApp on iOS.

**Comment by mssha** [comment]
If I switch to share as a base64 image, shareSingle seems to launch the native share sheet with AirDrop, WhatsApp, and other options.  Is there no way to share an image directly to WhatsApp on iOS?  Sharing a video works the way I expect.

**Comment by livingmine** [comment]
@mssha can you show me your singleShare options?

**Comment by mssha** [comment]
hmm, actually sharing video to WhatsApp does the same thing.  I have this:

`const shareOptions = {
            title: "Share",
            url: fileUrl,
            type: "image/png",
            failOnCancel: false,
            social: "whatsapp",
            whatsAppNumber: "",
            message: "" }`

**Comment by livingmine** [comment]
@mssha try to get rid of the **type** option, also make sure that the **url** option is filled with base64 image prepended with `data:image/png;base64,` for me it's something like this ```url: `data:image/png;base64,${effect.imageBase64}```. Also please note, i'm using react-native-share: ^3.6.0.

**Comment by gemdevgit** [comment]
> If I switch to share as a base64 image, shareSingle seems to launch the native share sheet with AirDrop, WhatsApp, and other options. Is there no way to share an image directly to WhatsApp on iOS? Sharing a video works the way I expect.

Can you please let me know how you made the video share working?
