### ISSUE TITLE
Image Sharing not working on Android

### ISSUE THREAD

**Issue by aadityapaliwal94** [react-native-share/react-native-share#862]
### Steps to reproduce
1. I have installed the dependency in my react native project. It opens up the application intents to share. Once I select any app e.g. Gmail, it went there and sent the mail but when I try to open it, it returns Couldn't open the file. It worked really well in iOS.
2. This is my code which I am using for sharing.

` let shareData = {};
   
    const pathURL = Utils.resolvePath(getState().readComic.pathUrl, item.imageData.imageName);    

    let base64Image = "";
    try {
      const resp = await RNFetchBlob.fetch('GET', pathURL)  
      base64Image = "data:image/jpeg;base64,"+resp.data;
    } catch (error) {
      console.log("Error share Image : " + error);
    }  
      shareData.url = base64Image;

    const result = await Share.open(shareData)`

Even I tried with the example folder's base64 files though but it returns the same error.  

I have granted permission for Write/Read storage.

Edit 1 - 

I had tried to debug it. The following are the logs that I found. 

`2020-09-14 20:06:13.644 23707-23731/com.newput.tinyview E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading cl.json.RNShareFileProvider uri content://com.put.dview.rnshare.fileprovider/rnshare1/12645837892784.png from pid=22901, uid=1000 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
        at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:593)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:507)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:307)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
`

### Expected behaviour
It should share a valid openable image.

### Actual behaviour
It' sharing image but it's not a valid one. When I try on Google Photos, it says Error, Couldn't load image.

### Environment
- **React Native version**: 0.61.1
- **React Native platform + platform version**:  Android 8.1.0

### react-native-share
**Version**: 3.7.1

### Link to repo (highly encouraged)
https://github.com/react-native-community/react-native-share/

**Comment by MateusAndrade** [comment]
Hi, @aadityapaliwal94. This is happing with Google related apps: GMail, Drive, etc. I remember to have a similar problem but I don't remember what I did to solve or avoid this issue.

What happens if you try opening the file with `RNFetchBlob` and then "save" the file to one of these applications?

**Comment by tonyjara** [comment]
I'm having the same issue, if I use filepath it works on drive, but in gmail it sends me and unformatted file, it also doesn't work on twitter. When using the base64 it just does not work anywhere.

**Comment by IrfanKhan01** [comment]
I just downgrade it to **3.7.0** and it's working now

**Comment by MateusAndrade** [comment]
#861

**Comment by tonyjara** [comment]
> I just downgrade it to **3.7.0** and it's working now

OMFG it works!!!! What could've broke it in the later versions? Thank youu!

**Comment by alokjaiswal** [comment]
Upgrading to 4.0.0 works for sharing image or image with message

**Comment by waqaramjad** [comment]
Any update ?

**Comment by mikehardy** [comment]
@waqaramjad https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b
