### ISSUE TITLE
Share PDF from Base64 string always corrupted

### ISSUE THREAD

**Issue by PKFEric** [react-native-share/react-native-share#864]
We receive the base64 from an external endpoint and use this code:

function sharePDFWithAndroid() {
      let jsonsend = {
        "printOrder": isActionsALL.printOrder
      };
      fetch(Routers.RouterApiHttp+'general/GemerateBase64Pdf',
      {
        method: 'POST',
        body: JSON.stringify(jsonsend),
        headers:{
          'Content-Type': 'application/json'
        }
      })
      .then(res => {
        res.json();

      })
      .then(async base64Data => {
      console.log(base64Data);
      let Data = 'data:application/pdf;base64,' + base64Data.base64Pdf;
      console.log(Data);
      await Share.open({ url: Data });

      });
    }

The Data variable has this dummy PDF:

data:application/pdf;base64,JVBERi0xLjcKJeLjz9MKNSAwIG9iago8PC9GaWx0ZXIvRmxhdGVEZWNvZGUvTGVuZ3RoIDExNz4+c3RyZWFtCnicK+RyCuHSdzNUMNczVQhJ4zK20DMyVTC3NNczNlEISeHSCHYM9nUMUQhyDXH09FEI1vPR0wzJ4nIN4QrkKkTTa2hoomeGrNfd1czQxMzEwMw1uCbAJSDe3cffydEHzAzxDPA3VKhR8PMHEsGecDMBOdwiBAplbmRzdHJlYW0KZW5kb2JqCjQgMCBvYmoKPDwvQ29udGVudHMgNSAwIFIvTWVkaWFCb3hbMCAwIDU5NSA4NDJdL1BhcmVudCAyIDAgUi9SZXNvdXJjZXM8PC9Gb250PDwvRjEgNiAwIFI+Pj4+L1RyaW1Cb3hbMCAwIDU5NSA4NDJdL1R5cGUvUGFnZT4+CmVuZG9iagoxIDAgb2JqCjw8L1BhZ2VzIDIgMCBSL1R5cGUvQ2F0YWxvZz4+CmVuZG9iagozIDAgb2JqCjw8L0NyZWF0aW9uRGF0ZShEOjIwMjAwOTE2MTUxODQ0KzAwJzAwJykvTW9kRGF0ZShEOjIwMjAwOTE2MTUxODQ0KzAwJzAwJykvUHJvZHVjZXIoaVRleHSuIDcuMS4xMiCpMjAwMC0yMDIwIGlUZXh0IEdyb3VwIE5WIFwoQUdQTC12ZXJzaW9uXCkpPj4KZW5kb2JqCjYgMCBvYmoKPDwvQmFzZUZvbnQvVGltZXMtUm9tYW4vRW5jb2RpbmcvV2luQW5zaUVuY29kaW5nL1N1YnR5cGUvVHlwZTEvVHlwZS9Gb250Pj4KZW5kb2JqCjIgMCBvYmoKPDwvQ291bnQgMS9LaWRzWzQgMCBSXS9UeXBlL1BhZ2VzPj4KZW5kb2JqCnhyZWYKMCA3CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDMzMiAwMDAwMCBuIAowMDAwMDAwNjI1IDAwMDAwIG4gCjAwMDAwMDAzNzcgMDAwMDAgbiAKMDAwMDAwMDE5OSAwMDAwMCBuIAowMDAwMDAwMDE1IDAwMDAwIG4gCjAwMDAwMDA1MzUgMDAwMDAgbiAKdHJhaWxlcgo8PC9JRCBbPGUwNjU5NjJjY2UyZDIzNjg1MmQ1N2E2NzFkNGJiN2JlPjxlMDY1OTYyY2NlMmQyMzY4NTJkNTdhNjcxZDRiYjdiZT5dL0luZm8gMyAwIFIvUm9vdCAxIDAgUi9TaXplIDc+PgolaVRleHQtNy4xLjEyIGZvciAuTkVUCnN0YXJ0eHJlZgo2NzYKJSVFT0YK

When use Share.Open and send it through email the PDF is corrupted. If sended to the printer corrupted as well.

**Comment by MateusAndrade** [comment]
Hi, @PKFEric  which platform are you facing this?

**Comment by jdbaculard** [comment]
Me too

On android

**Comment by PKFEric** [comment]
Android 8.1

**Comment by AlexisEspejo** [comment]
solution: 

import Share from "react-native-share";
import RNFetchBlob from 'rn-fetch-blob';
import {PermissionsAndroid,Alert} from 'react-native';

  async function sharePDFWithAndroid() { 
      const { dirs } = RNFetchBlob.fs;
      RNFetchBlob.config({
        fileCache: true,
        addAndroidDownloads: {
        useDownloadManager: true,
        notification: true,
        mediaScannable: true,
        title: 'test',
        path: `${dirs.DownloadDir}/test.pdf`,
        },
      })
        .fetch('GET', 'URL', {})
        .then(async (res) => {
          const options = {
            title: "test",
            url: 'file://'+res.path()
          };
          await Share.open(options);
        })
        .catch((e) => {
          console.log(e)
        });
       
    }
  
   async function downloadFile (){
      try {
          const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
          if (granted === PermissionsAndroid.RESULTS.GRANTED) {
            await sharePDFWithAndroid();
          } else {
            Alert.alert('Permission Denied!', 'You need to give storage permission to download the file');
          }
        } catch (err) {
          console.warn(err);
        } 
    }

**Comment by AlexisEspejo** [comment]
>solution: 
>import Share from "react-native-share";
>import RNFetchBlob from 'rn-fetch-blob';
>import {PermissionsAndroid,Alert} from 'react-native';
>
>async function sharePDFWithAndroid() { 
>      const { dirs } = RNFetchBlob.fs;
>      RNFetchBlob.config({
>        fileCache: true,
>         addAndroidDownloads: {
>         useDownloadManager: true,
>         notification: true,
>         mediaScannable: true,
>         title: 'test',
>         path: `${dirs.DownloadDir}/test.pdf`,
>         },
>       })
>         .fetch('GET', 'URL', {}) 
>         .then(async (res) => {
>                  const options = {
>                                  title: "test",
>                                   url: 'file://'+res.path()
>                    };
>                 await Share.open(options);
>         })
>         .catch((e) => {
>                        console.log(e)
>         });
>     }
>   
>    async function downloadFile (){
>       try {
>           const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
>           if (granted === PermissionsAndroid.RESULTS.GRANTED) {
>             await sharePDFWithAndroid();
>           } else {
>             Alert.alert('Permission Denied!', 'You need to give storage permission to download the file');
>           }
>         } catch (err) {
>           console.warn(err);
>         } 
>     }

**Comment by AlexisEspejo** [comment]
```
solution:
import Share from "react-native-share";
import RNFetchBlob from 'rn-fetch-blob';
import {PermissionsAndroid,Alert} from 'react-native';

async function sharePDFWithAndroid() {
const { dirs } = RNFetchBlob.fs;
RNFetchBlob.config({
fileCache: true,
addAndroidDownloads: {
useDownloadManager: true,
notification: true,
mediaScannable: true,
title: 'test',
path: ${dirs.DownloadDir}/test.pdf,
},
})
.fetch('GET', 'URL', {})
.then(async (res) => {
const options = {
title: "test",
url: 'file://'+res.path()
};
await Share.open(options);
})
.catch((e) => {
console.log(e)
});
}

async function downloadFile (){
try {
const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
if (granted === PermissionsAndroid.RESULTS.GRANTED) {
await sharePDFWithAndroid();
} else {
Alert.alert('Permission Denied!', 'You need to give storage permission to download the file');
}
} catch (err) {
console.warn(err);
}
}
```

**Comment by 14BCS1464** [comment]
Here is the solution for  share the pdf for in android iOS both,


Note:= require the local path==>



//On Invite  ButtonPress
    const iosPDFShore = async (path) => {

        const shareOptions = {
            title: 'Share file',
            failOnCancel: false,
            saveToFiles: false,
            urls: [path], // base64 with mimeType or path to local file
        };


        try {
            const ShareResponse = await Share.open(shareOptions);
            setResult(JSON.stringify(ShareResponse, null, 2));
        } catch (error) {
            console.log('Error =>', error);
            setResult('error: '.concat(getErrorString(error)));
        }


    }

    const sharePDFWithAndroid=async (pdfPath, type)=>{
        // Share.open({ url: base64Data });
        const { fs, fetch, wrap } = RNFetchBlob;
        RNFetchBlob.fs.readFile(pdfPath, 'base64').then(
            base64Data => {
                base64Data = `data:${type};base64,` + base64Data;
                Share.open({ url: base64Data });
                RNFS.unlink(filePath);
            });
    }

    const  onSharePress=async ()=>{
        let options = {
            html: '<h1>TGenie Pdf Text</h1>',
            fileName: 'tGenieInvoice_'+uuid.v4(),
            directory: 'Documents',
        };

        let file = await RNHTMLtoPDF.convert(options)
        console.log(file.filePath);
        if(Platform.OS === "ios"){
            iosPDFShore(file.filePath)
        }else{
            sharePDFWithAndroid(file.filePath,'application/pdf')
        }
    }
