### ISSUE TITLE
Promise "open" is never resolved when canceling printing

### ISSUE THREAD

**Issue by douglasjunior** [react-native-share/react-native-share#865]
### Steps to reproduce
1. Open a image in Base64, like this:
```js
                 const openResult = await Share.open({
                        failOnCancel: true,
                        title: 'Some title',
                        url: 'data:image/jpg;base64,foobarbazz',
                        filename: 'file-name.jpg',
                    });
```

2. Select "Print" option.

![image](https://user-images.githubusercontent.com/1512341/93402889-5a118a00-f85c-11ea-8e25-cd8daaabbaae.png)

3. Then click on "Cancel" option.

![image](https://user-images.githubusercontent.com/1512341/93402936-83321a80-f85c-11ea-9986-2373a726159a.png)

### Expected behaviour

The promise should be rejected (failOnCancel=true) or resolved (failOnCancel=false).

### Actual behaviour

The promise never end.

### Environment

- **React Native version**: 0.61.5
- **React Native platform + platform version**: iOS 13.7

### react-native-share

**Version**: 3.8.0

### Link to repo (highly encouraged)

I don't think it's necessary.

**Comment by MateusAndrade** [comment]
Hi, @douglasjunior this is occurring with any base64?

**Comment by douglasjunior** [comment]
We only use jpg base64 here, to share and save to Photo Library.

**Comment by orels1** [comment]
@MateusAndrade we're passing base64 pdf and are getting the same results - promise stays unresolved

**Comment by douglasjunior** [comment]
Still happening.
