### ISSUE TITLE
Sharing image failed in React Native v0.63.2

### ISSUE THREAD

**Issue by kkCode** [react-native-share/react-native-share#869]
### Steps to reproduce
1.
```
Share.open({
    url:"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQAB......",
    type:"image/jpeg"
})
```
2.Select an app.

### Actual behaviour
The selected app failed to get resources.

### Environment
- **React Native version**: 0.63.2
- **React Native platform + platform version**: Android 10.0

### react-native-share
**Version**: npm version 3.8.2

**Comment by AbdelkhalekESI** [comment]
+1

**Comment by AbdelkhalekESI** [comment]
Solving this by downgrade version to 3.7.0

**Comment by MateusAndrade** [comment]
Hi @AbdelkhalekESI, which rn version are you using?

**Comment by AbdelkhalekESI** [comment]
> Hi @AbdelkhalekESI, which rn version are you using? 

0.62.2

**Comment by sebpapaechocharliekilo** [comment]
Same here, works on some android (probably android 9 only). 
In my case downgrade version to 3.7.0 did not solve anything. having the issue with 3.8.3 (react-native: 0.60.5)

**Comment by dfrancio** [comment]
same here. 
The approved PR "fix(android): avoid showing permissions prompt & migrate write location #871" will solve the problem.

The problem is that in API 29, getExternalStorageDirectory() is is deprecated. I've changed manually and it come back to work
