### ISSUE TITLE
Custom Share Options Based on Share App Used

### ISSUE THREAD

**Issue by macvalari** [react-native-share/react-native-share#875]
## Ask your Question
Hi All, Good Day!

First of all great library! I was wondering if it is possible to customize the option passed on `Share.open` based on the share app selected? How I understand the documentation, it is not possible because `option` are predefined before calling `Share.open`

What we wanted to achieve is for example have a different template for each share apps available such as email, messenger, IG, FB, Whatsapp, etc.

Appreciate all your feedback and help!

**Comment by gabcvit** [comment]
Hi @macvalari, as far as I understand I don't think it's possible to have different data being used for `Share.open` depending on which app has been selected. Once `Share.open` is called, the options has to be already filled in, as it highlights the correct apps depending on what kind of data has been inserted.

 I've also been looking for a solution like this, but unfortunately that's not yet possible for neither iOS nor android. I did find out a workaround that might be interesting for you app:
A solution would be implementing inside your app a menu which lists the main apps that you would like to have a special treatment in, and every one of them would trigger a special `Share.shareSingle` functionality for the app it's meant to. Make sure to have an "other apps" last option which triggers a more general `Share.open` with a more basic template which most apps can understand. This is the way that many apps treat their sharing functionality such as Spotify, Twitter, Pinterest and so on.

**Comment by macvalari** [comment]
Thanks for answering @gabcvit. For now, we would be delaying the feature and we might use the workaround you've mentioned. Appreciate the help.

**Comment by gabcvit** [comment]
@macvalari You're welcome! 😆
