### ISSUE TITLE
ios14 : Share file to disk : A "text" file is created if `message` variable is set

### ISSUE THREAD

**Issue by TomBerriot** [react-native-share/react-native-share#876]
### Steps to reproduce
1. (Maybe optional) Write a 64 based content on the iphone cache 
2. Use `Share.open` to share the file through its file path, with a `message`
3. Click the "Save on disk" option once the share modal appears

### Expected behaviour
There should only be one file proposed to be stored in the folder.

![Capture d’écran 2020-09-25 à 11 09 42](https://user-images.githubusercontent.com/11588007/94249171-cd339400-ff1f-11ea-91fb-682d01e9e4a1.png)

### Actual behaviour
There are two files created instead of one. 
One is the file (an excel) we expected to be stored, referenced by its file path previously.
The other file is called "text", containing the `message` variable encoded in a format.

This problem does not occur if the `message` variable is `null`.

#### Two files are proposed to be stored.
![Capture d’écran 2020-09-25 à 11 10 22](https://user-images.githubusercontent.com/11588007/94249224-e1779100-ff1f-11ea-9728-c73b3023eb69.png)

#### Result after share to disk
![Capture d’écran 2020-09-25 à 10 48 16](https://user-images.githubusercontent.com/11588007/94247915-0ec33f80-ff1e-11ea-9f2b-d0edd4e55c90.png)

#### "text" file content:
![Capture d’écran 2020-09-25 à 10 57 27](https://user-images.githubusercontent.com/11588007/94247836-f8b57f00-ff1d-11ea-9590-de794af4631b.png)

### Environment
- **React Native version**: 0.63.2
- **React Native platform + platform version**: iOS 14

### react-native-share
**Version**: 3.3.3

#### Our share method
```
export async function shareBlob(fileName: string, blob, subject: string, message: string) {
  const reader = new FileReader();

  reader.readAsDataURL(blob);

  reader.onloadend = async () => {
    const base64Result = reader.result as string;
    const base64Content = base64Result.split(',')[1];
    const temporaryPath = RNFS.TemporaryDirectoryPath + '/' + fileName;
    const readPathUrl = (Platform.OS === 'android' ? 'file://' : '') + temporaryPath;

    try {
      await RNFS.writeFile(temporaryPath, base64Content, 'base64');

      await Share.open({
        url: readPathUrl,
        failOnCancel: false,
        subject,
        message
      });
    } catch (exception) {}
  };
}

**Comment by TomBerriot** [comment]
I am not really knowledgeable on Objective C. Could someone confirm my issue or are we only a few sharing files and not just text ?

**Comment by beebzo** [comment]
Hi! I am having the same issue.

> I am not really knowledgeable on Objective C. Could someone confirm my issue or are we only a few sharing files and not just text ?

**Comment by jtvargas** [comment]
I'm having the same issue, if I add filename/message property it adds a .txt file, any solution?
