### ISSUE TITLE
Handle WhatsApp for Business in Android

### ISSUE THREAD

**Issue by livingmine** [react-native-share/react-native-share#877]
### Steps to reproduce
1. Use shareSingle with social: Share.Social.WHATSAPP option
2. Trigger the share function in device with [WhatsApp for Business](https://play.google.com/store/apps/details?id=com.whatsapp.w4b&hl=en) is **installed** but [WhatsApp Messenger](https://play.google.com/store/apps/details?id=com.whatsapp&hl=en) is **not installed**

### Expected behaviour
WhatsApp for Business should be automatically opened

### Actual behaviour
WhatsApp for Business is not opened. Instead a bottom sheet with different alternative options to share is shown.

### Environment
- **React Native version**: 0.62.2
- **React Native platform + platform version**: Android any versions

### react-native-share
**Version**: 3.6.0

Inspecting from the source code, i guess it is caused by the way the native android code check for the ability of the device to share something based on the package name not based on the ability of the device to execute the scheme like how it's done in iOS. Not sure if the same way of checking can also be done in Android, but if it is not, maybe also include the package name of WhatsApp for Business in the valid package name to execute Share.Social.WHATSAPP?

**Comment by vijaychouhan-rails** [comment]
How to share on WhatsApp Business app
