### ISSUE TITLE
SingleShare Instagram Android android.net.Uri.getScheme() null

### ISSUE THREAD

**Issue by marcusviniciusf** [react-native-share/react-native-share#881]
### Steps to reproduce
1. Single Share

### Expected behaviour
Open Instagram App

### Actual behaviour
Promise throws this error:
`{error: "Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference"}
`

### Environment
- **React Native version**: 0.62.2
- **React Native platform + platform version**: Android 9.0

### react-native-share
**Version**: ˆ4.0.1

Logcat prompts this: 
`09-30 02:14:58.728 25893 26008 I System.out: SHARE SINGLE METHOD
09-30 02:14:58.729 25893 26008 I System.out: com.instagram.android
09-30 02:14:58.748 25893 26008 I System.out: INSTALLED
09-30 02:14:58.750  1409 11244 E ActivityManager: Activity Manager Crash. UID:10284 PID:25893 TRANS:44
09-30 02:14:58.750  1409 11244 E ActivityManager: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
09-30 02:14:58.750  1409 11244 E ActivityManager: 	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermission(UriGrantsManagerService.java:1026)
09-30 02:14:58.750  1409 11244 E ActivityManager: 	at com.android.server.uri.UriGrantsManagerService.grantUriPermission(UriGrantsManagerService.java:767)
09-30 02:14:58.750  1409 11244 E ActivityManager: 	at com.android.server.uri.UriGrantsManagerService$LocalService.grantUriPermission(UriGrantsManagerService.java:1317)
09-30 02:14:58.750  1409 11244 E ActivityManager: 	at com.android.server.am.ActivityManagerService.grantUriPermission(ActivityManagerService.java:6248)
09-30 02:14:58.750  1409 11244 E ActivityManager: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2511)
09-30 02:14:58.750  1409 11244 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2763)
09-30 02:14:58.750  1409 11244 E ActivityManager: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
09-30 02:14:58.750  1409 11244 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:994)`

**Comment by devpascoe** [comment]
Just logged getting the same issue for android here https://github.com/react-native-share/react-native-share/issues/954
Did you end up finding out the cause @marcusviniciusf ?

**Comment by iamandiradu** [comment]
Having the same issue.

**Comment by reberthkss** [comment]
facing the same issue...

**Comment by ubaidimranofficial** [comment]
facing the same issue.

**Comment by JunDev76** [comment]
facing the same issue.
