### ISSUE TITLE
React Native callback type only permits a single invocation from native code

### ISSUE THREAD

**Issue by deepaktringapps** [react-native-share/react-native-share#882]
### Steps to reproduce

When press share action sheet will appear
Then select any one of the other application show "send" and "cancel" option
When press cancel button stoped the action and when close the actionsheet then app getting crashed

### Expected behaviour
have to close share action sheet

### Actual behaviour
App crashed

### Environment
- **React Native version**: 0.59.9
-  platform version**: iOS 11.3.3

### react-native-share
version 1.2.1
also checked with latest version 4.0.0

**Comment by jbristol-trav** [comment]
I am also facing this

RN: 0.61.2
iOS: 13.5
RN-Share: 4.0.2
