### ISSUE TITLE
SMS was not sent

### ISSUE THREAD

**Issue by arnasledev** [react-native-share/react-native-share#883]
Hey, so there are no steps to reproduce or repeat the same problem as it happens unexpectedly...

I'm using this library for sharing the link or the text with the link in my app. Everything seems to work fine but sometimes people who use the app report this bug to me and I've faced the same bug a few times by myself. When you click on the share button and see the modal, no matter if you select a favourite person or you open the messages app and send the link - the message will never be sent and you will be returned to the app. No errors, no warnings, as everything goes through without the problems. Once I caught this behaviour when my app was on debug mode with my device and it didn't return any errors. The message never appears in your messages list as you didn't click the "send" button at all. It works like 90-95 times of 100. 

The message type is different all the time, either is iMessage or simple message..

My config:
```javascript
const options = Platform.select({
    ios: {
      activityItemSources: [
        {
          placeholderItem: {type: PlaceholderItemTypes.URL, content: url},
          item: {
            default: {type: PlaceholderItemTypes.URL, content: url},
          },
          subject: {
            default: title,
          },
          linkMetadata: {originalUrl: url, url, title},
        },
        {
          placeholderItem: {type: PlaceholderItemTypes.TEXT, content: message},
          item: {
            default: {type: PlaceholderItemTypes.TEXT, content: message},
            message: null, // Specify no text to share via Messages app.
          },
        },
      ],
    },
    default: {
      title,
      subject: title,
      message: `${message} ${url}`,
    },
  });

  Share.open(options).catch(noop);
```

### Environment
- **React Native version**: 0.63.2
- **React Native platform + platform version**: iOS 13.5.1 to 14.0.1 (different versions faced the same problem)

### react-native-share
**Version**: 3.8.3

**Comment by RoshaanAli** [comment]
Share.Social.SMS not working
it's taking me to playstore.
