### ISSUE TITLE
Cannot Share message with image base64 in Google Chat

### ISSUE THREAD

**Issue by husenCappital** [react-native-share/react-native-share#885]
**My code:**
const onSharePress = async () => {
const res = await Share.open({
url: base64image ('data:image/png;base64,...'),
message: 'Some text',
})
}

**Actual behaviour**
When you choose google chat from the list of social networks, there is an send only image message not attaching

**Environment**
React Native version: 0.63.2
React Native platform + platform version: Android (all versions)
react-native-share
Version: 4.0.0
Tell us what happens instead

**Comment by JDJBSPL** [comment]
Facing same issue.

**Comment by waqaramjad** [comment]
Same issue here any update ?

**Comment by aniketrex13** [comment]
Same issue here any update?
