### ISSUE TITLE
Share a local video to WhatsApp not not working 

### ISSUE THREAD

**Issue by aftabaminzoobiapps** [react-native-share/react-native-share#893]
node version 14 
windows10 64 bit 

` const openshare = async () =>{

      
   
                try{
                 await Share.open({
                  type: 'video/mp4',
                  url:`file://${props.source}`, // base64 with mimeType or path to local file
                })
              }catch(error){
                console.log('Eroror' , error)
              }
    `

this is my code. 

here are my props.source `file://storage/emualted/0/somefoler/anotherfolder/video.mp4`

**when I try to share this video file it shows an error message file format not supported.**

**Comment by joseomar10** [comment]
I had the same problem. Any solution ?
