### ISSUE TITLE
Android: Unable to open multiple image selection screen on Instagram

### ISSUE THREAD

**Issue by vishal264726** [react-native-share/react-native-share#898]
## Ask your Question
Hi,

I am trying to share multiple images on the Instagram application on the Android platform.

I am using the following code snippet:

`    
CameraRoll.getPhotos({
      first: 0,
    })
      .then((r) => {
        Share.shareSingle({
          url: r.edges[0].node.image.uri,
          social: 'instagram',
        });`

But, every time it is opening a screen with a single image selected and no option to select other images:

![Image from iOS (1)](https://user-images.githubusercontent.com/69193937/96971027-2ba95d80-1532-11eb-90e0-62de7bc82f82.jpg)

rather I want this screen: 

![Image from iOS (3)](https://user-images.githubusercontent.com/69193937/96971295-8cd13100-1532-11eb-88be-51aa1c342f85.png)

Any help will be really appreciated.

**Comment by GeekRishabh** [comment]
@vishal264726 Is it working on iOS?

**Comment by vishal264726** [comment]
@GeekRishabh Yes
