### ISSUE TITLE
singleShare doesn't work on IOS for Instagram

### ISSUE THREAD

**Issue by lavi-moolchandani** [react-native-share/react-native-share#900]
### Steps to reproduce
I am using the piece of code given below to share on instagram
const shareOptions = {
                  title: 'Join us!',
                  message: `Hey! checkout this cool app'
                  social: Share.Social.INSTAGRAM,
                  url: 'https://www.google.com',
                };
                // shareSuccessful();
                const response = await Share.shareSingle(shareOptions);

### Expected behaviour
should redirect to instagram and let the user share the link through messages.

### Actual behaviour
In android it opens the user's instagram contacts to let the user send the message directly but in IOS it just opens the App store page of instagram

### Environment
- **React Native version**: 0.62.2
- **React Native platform + platform version**: iOS 14

### react-native-share
**Version**: npm version 4.0.4

### Link to repo (highly encouraged)
https://github.com/

**Comment by lvillacin** [comment]
Same problem here! I'm trying to share to IG Stories and it works on Android but it just opens the App Store in iOS.

**Comment by CapitanRedBeard** [comment]
You have to add the query schema to your INFO plist file like someone suggested here: https://github.com/react-native-share/react-native-share/issues/454

Specifically do this:
```
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>instagram-stories</string>
		<string>instagram</string>
	</array>
```
Assuming you want instagram and instagram-stories deep link

**Comment by lvillacin** [comment]
@CapitanRedBeard Thank you! Do I also have to add something like that for Facebook Post Sharing?

**Comment by mtroskot** [comment]
For Facebook you need
`<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fb-stories</string>
		<string>fb</string>
	</array>`

**Comment by rewaant** [comment]
What it does: it opens the Instagram library to let you post an image from the camera roll. It displays the latest photo you took on camera rather than from the url supplied. However, you still need to select one/multiple from the camera roll.

What it should do: open the image directly, let you edit and post. It works on Facebook, Twitter but not on Instagram.

**Comment by lvillacin** [comment]
> For Facebook you need
> 
> ```
> <key>LSApplicationQueriesSchemes</key>
> <array>
> 	<string>fb-stories</string>
> 	<string>fb</string>
> </array>
> ```

Thanks man!

**Comment by skizzo** [comment]
Would be really handy for this to show up somewhere in the [docs](https://react-native-share.github.io/react-native-share/docs/install).. As handy as this package is, the docs are really badly made.

**Comment by mikehardy** [comment]
> As handy as this package is, the docs are really badly made.

The Official Open Source Edit of that statement is

> This package is handy, but the docs are pretty confusing, would you be open to a PR that cleans this area up?

I say that with :heart:  - documentation updates are especially welcome in open source packages normally since most people fix a bug and move on or add a feature and move on and over time the docs get more and more wooly / less coherent
