### ISSUE TITLE
Share via Gmail Subject and message are same IOS

### ISSUE THREAD

**Issue by deepaktringapps** [react-native-share/react-native-share#901]
### Steps to reproduce

Share via Gmail Application,
options: {
message: "message Text",
subject: "subject Text"
}

### Expected behaviour
In Gmail subject should be "Subject Text"

### Actual behaviour
In Gmail subject as "message Text"

### Environment
React native version 0.62.2
IOS: 13.3.3

### react-native-share
4.0.1

I can able to set subject and message for email share and issue only when sharing via Gmail application

**Comment by castalonirenz** [comment]
issue still persist

**Comment by ianjsikes** [comment]
Can we re-open this? I can confirm this is happening for me as well.
