### ISSUE TITLE
iOS: email not filled 

### ISSUE THREAD

**Issue by clems36** [react-native-share/react-native-share#905]
### Steps to reproduce

Call the following:

```js
Share.open({
      message: 'some message',
      subject: 'some subject',
      url: 'some base64',
      failOnCancel: false,
      email: 'e@mail.com'
    })
```

Then select an email app (tried the native iOS one and Gmail).

### Expected behaviour
I'd expect the `To` field to be filled in with `e@mail.com`.

### Actual behaviour
Everything is filled in correctly except the `To` field.
This works fine on android. 
I've also tried the `recipient` field but no luck on iOS.
I can't use the react-native's Linking with `mailto:` because i need to be able to use all the other apps for sharing.

### Environment
- **React Native version**: `~0.63.2`
- **React Native platform + platform version**: iOS 14.0.1

### react-native-share
**Version**: `4.0.2`

**Comment by saurabh874** [comment]
Hi @clems36  i am also facing same issue and i can not go with Linking.
did you get any solution for this?

**Comment by clems36** [comment]
Hi @saurabh874 unfortunately not, waiting for a maintainer to guide us here.

**Comment by saurabh874** [comment]
anybody have idea how to resolve it?

**Comment by clems36** [comment]
@mikehardy maybe you have an idea on this ?

**Comment by mikehardy** [comment]
In general for react native issues I encourage you to reach right in to the node modules and add console logging before native API calls that log all arguments and then to add same in native code before platform API calls. Compare what you see to what you expect based on documentation. It's what maintainer do, then you can pr the fix

**Comment by Zernach** [comment]
This issue still seems to be affecting me, even on version `8.2.1`

**Comment by proparnaampit** [comment]
is there any update on this? facing same issue.
