### ISSUE TITLE
share.SingleShare() does nothing if facebook App not installed . It should redirect to playstore.

### ISSUE THREAD

**Issue by ravi123saxena** [react-native-share/react-native-share#906]
Share.shareSingle(shareOptions)
                    .then((res) => { console.log(res) })
                    .catch((err) => { err && console.log(err); })

**Comment by t08-apporio** [comment]
hi @ravi123saxena. Were you able to figure something out for this?

**Comment by kaioduarte** [comment]
@ravi123saxena @t08-apporio I found out the issue by digging into the code. There are some social providers (Facebook, GooglePlus, Pinterest and Twitter) that are capable to share content via Web Intent. So you'll be only redirected to the Play Store (I didn't check the iOS implementation) if the provider does not has the Web Intent URL.

**Comment by vinayjohn183** [comment]
Does anybody have a solution for this issue?

**Comment by c0deWookiee** [comment]
if Share.shareSingle does not detect if a facebook app is installed, the package throws an error, and am no longer to discern whether or not a user has shared to the web

**Comment by mikehardy** [comment]
@jqn providing the same amount of information you have provided about the issue, I can say it's working fine (note: this is not actually meaningful though, it's information-free --> https://stackoverflow.com/help/how-to-ask)
