### ISSUE TITLE
Display Title and Message on iOS Share menu?

### ISSUE THREAD

**Issue by sopranolinist** [react-native-share/react-native-share#908]
## Ask your Question
I am trying to share a URL and display both a Title and a Message in the Share menu on iOS. I would also like to scrape the URL to extract the custom icon to display in the Share menu.

If I define my `title` and `message` locally in the code and then do:
```
const result = await Share.open({
        message,
        title,
        url,
      });
```
Then I get only the message displaying, no title, and no custom icon.
<img width="413" alt="Screen Shot 2020-11-09 at 1 15 51 PM" src="https://user-images.githubusercontent.com/42662464/98597368-c6719e00-228d-11eb-836e-c3cfc2766c12.png">
If I instead use `linkMetadata` in `activityItemSources` then I am able to scrape the URL to get the title and the icon, but it displays the share URL by default underneath the title and I can't figure out how to scrape the URL to get any sort of message to appear in place of the URL text.
```
const result = await Share.open(
        Platform.select({
          ios: {
            failOnCancel: false,
            activityItemSources: [
              {
                item: { default: { type: 'url', content: url } },
                linkMetadata: {
                  title,
                  // can I get a message here?
                  originalUrl: url,
                },
              },
            ],
          },
          default: { failOnCancel: false, url, title },
        }),
      );
```
<img width="416" alt="Screen Shot 2020-11-09 at 1 23 08 PM" src="https://user-images.githubusercontent.com/42662464/98598559-890e1000-228f-11eb-94d1-56b5e3b6d41e.png">

If I instead try to use my locally defined `message` by adding a `message` parameter directly on the `ios` object, then I get a weird default title and both my message and my URL text display below the title. Oh, and no custom icon anymore.

```
const result = await Share.open(
        Platform.select({
          ios: {
            failOnCancel: false,
            message,
            activityItemSources: [
              {
                item: { default: { type: 'url', content: url } },
                linkMetadata: {
                  title,
                  originalUrl: url,
                },
              },
            ],
          },
          default: { failOnCancel: false, url, title },
        }),
      );
```
<img width="416" alt="Screen Shot 2020-11-09 at 1 30 30 PM" src="https://user-images.githubusercontent.com/42662464/98599416-c7f09580-2290-11eb-8240-1f07b9352a80.png">

What am I missing here? I'm using `react-native-share` 4.1.0 and `react-native` 0.63.3 on iOS 14.1

**Comment by nathan-castlehow** [comment]
@sopranolinist  did you manage to solve this?
I am also having the same issue, the second i set a message i get the weird "Plain Text and 1 Link".
Also if i set a URL the url gets appended twice.

For now I'm just detecting platform and switching.

**Comment by chijiokeAtGS** [comment]
@sopranolinist did you figure this out? Thanks

**Comment by th0r0nd0r** [comment]
has anyone figured this out? I also want to display a title, message, and url all at once. It seems like it should be possible natively. something like this:
![IMG_3336](https://user-images.githubusercontent.com/29419913/115627508-fe0c5980-a2b3-11eb-8eae-d9b1b6933e08.jpg)

**Comment by mcraigie** [comment]
I tried for quite a while but there appear to be multiple different bugs blocking the use of this library on iOS. If I got one part working it meant another wouldn't, or what actually got shared was incorrect. I would love to find the time to write out a bunch of test cases, but I haven't been able to yet

It would be nice to have something like that in the documentation too, half a dozen examples of common usage with screenshots of the share sheet on iOS and Android side by side

**Comment by reberthkss** [comment]
Some progress on this ?

**Comment by mikehardy** [comment]
@reberthkss not that I'm aware of, I don't see any PRs from you or anyone advancing it?

**Comment by reberthkss** [comment]
> @reberthkss not that I'm aware of, I don't see any PRs from you or anyone advancing it?

Maybe i give a try on this.

**Comment by stevenzeck** [comment]
Does iOS allow you to customize the subtitle/message when sharing a link? Or is the best you can do is have your own title and it always uses the URL of the link you're sharing?

**Comment by gfaraj** [comment]
I'm also getting that, any ideas?

**Comment by UlasenkaUladzislau** [comment]
any progress?

**Comment by larryself** [comment]
Is there any progress on this matter?

**Comment by Nikualla1** [comment]
Why is this closed? 🧐

**Comment by chramos** [comment]
this package is dead

**Comment by mikehardy** [comment]
False.

This package doesn't do what you want perhaps, and you have not provided any of your time to resolve and or fix it: true
