### ISSUE TITLE
Missing email option ?

### ISSUE THREAD

**Issue by loiclouvet** [react-native-share/react-native-share#910]
When using Share.open or Share.singleShare, email attribute is not present in options

In source code, `index.js` file
```
type Options = {
  url?: string,
  urls?: Array<string>,
  filename?: string,
  filenames?: Array<string>,
  type?: string,
  message?: string,
  title?: string,
  subject?: string,
  recipient?: string,
  excludedActivityTypes?: string,
  failOnCancel?: boolean,
  showAppsToView?: boolean,
  saveToFiles?: boolean,
  appId: string,
};
```

In docs 
![image](https://user-images.githubusercontent.com/1736502/99063774-515fda80-25a5-11eb-886b-993475da51eb.png)

Filling options with email seems to work, is it still a valid option ?

When using typescript definitions :
In `@types/react-native-share/index.d.ts`
```
export interface Options {
    url?: string;
    urls?: string[];
    type?: string;
    message?: string;
    title?: string;
    subject?: string;
    activityItemSources?: ActivityItemSource[];
    filename?: string;
    saveToFiles?: boolean;
    excludedActivityTypes?: string;
    failOnCancel?: boolean;
    showAppsToView?: boolean;
}
```

### Environment
- **React Native version**: 0.63.3

### react-native-share
**Version**: 3.3.2

### @types/react-native-share
**Version**: 3.3.0

**Comment by petrbela** [comment]
While this is getting fixed, you may augment it locally in `@types/react-native-share.d.ts`:

```ts
import { Options } from 'react-native-share'

declare module 'react-native-share' {
  export interface Options {
    email?: string
  }
}
```
