### ISSUE TITLE
incompatable together 2 libs 

### ISSUE THREAD

**Issue by SnaiNeR** [react-native-share/react-native-share#913]
I think it happenes because we have put the same class implementation into two different files
<img width="845" alt="Снимок экрана 2020-11-19 в 21 35 09" src="https://user-images.githubusercontent.com/39980963/99695932-f734ad00-2aaf-11eb-87b8-8e7bcba1ac17.png">
Also there a same question [https://stackoverflow.com/questions/64856494/2-duplicate-symbols-for-architecture-arm64#](url)

If change react-native-share version from 4.1.0 -> 4.0.4 everything is fine
([https://github.com/react-native-share/react-native-share/compare/v4.0.4...v4.1.0]())
### Steps to reproduce
1. install latest versions of react-native-share (4.1.0) and react-native-sensors (7.0.2)
2. build ios app

### Expected behaviour
App is builded

### Actual behaviour
Error happenes on last build steps

### Platform
iOS

### react-native-share
**Version**: 4.1.0

### Link to repo (highly encouraged)
https://github.com/react-native-share/react-native-share

**Comment by yang093** [comment]
The same when using with 'react-native-social-share' package
duplicate symbol '_OBJC_CLASS_$_Utils' in:
    /Users/yang/Library/Developer/Xcode/DerivedData/test-fcwwhiggbjhhhdatlpuwbmppnfil/Build/Products/Debug-iphonesimulator/RNShare/libRNShare.a(Utils.o)
    /Users/yang/Library/Developer/Xcode/DerivedData/test-fcwwhiggbjhhhdatlpuwbmppnfil/Build/Products/Debug-iphonesimulator/RNShareUtils/libRNShareUtils.a(Utils.o)
duplicate symbol '_OBJC_METACLASS_$_Utils' in:
    /Users/yang/Library/Developer/Xcode/DerivedData/test-fcwwhiggbjhhhdatlpuwbmppnfil/Build/Products/Debug-iphonesimulator/RNShare/libRNShare.a(Utils.o)
    /Users/yang/Library/Developer/Xcode/DerivedData/test-fcwwhiggbjhhhdatlpuwbmppnfil/Build/Products/Debug-iphonesimulator/RNShareUtils/libRNShareUtils.a(Utils.o)
ld: 2 duplicate symbols for architecture x86_64
 
Change react-native-share version from 4.1.0 -> 4.0.4 doesn't work

**Comment by SnaiNeR** [comment]
@yang093 it's must work, did you removed package from node_modules and do npm install && pod install ?
in 4.0.4 Utils file is missing

**Comment by blueberry6401** [comment]
Same thing here, waiting for the fix.

**Comment by yangsamuellu** [comment]
> @yang093 it's must work, did you removed package from node_modules and do npm install && pod install correctly?
> in 4.0.4 Utils file is missing

Oh, no, i see the Utils file on your repository.   https://github.com/react-native-share/react-native-share/blob/v5.1.0/ios/Utils.m

**Comment by blueberry6401** [comment]
So what should I do to get this fixed??

**Comment by mikehardy** [comment]
@blueberry6401 perhaps propose a change to this repo that renames the Utils object (https://github.com/react-native-share/react-native-share/blob/master/ios/Utils.m and the .h file)  to something unambiguous like RNShareUtils

You can even try it by reaching right into node_modules/react-native-share/ios - moving the file to an unambiguous name (and altering the import statements of any files that import it!) and using `npx patch-package react-native-share` to save your changes.

If it works, you're set - make a PR here with the fix.

**Comment by Talha-Jawed** [comment]
<img width="847" alt="Screenshot 2021-05-01 at 11 07 43 PM" src="https://user-images.githubusercontent.com/39768820/116794302-76a9bc00-aae5-11eb-8ff3-c99ca793a765.png">

@mikehardy getting this error after rename the files name and import statements Utils to RNShareUtils. any solution ?

```
"react-native": "0.63.4"
"react-native-share": "^5.2.2"
"react-native-sensors": "^7.2.0"
```

**Comment by mikehardy** [comment]
It was hard to read that image - text copy/paste in here is much easier for me. I was able to though

Not sure exactly what's going on - seems like a file move should be easy? The best thing to do is post a draft PR so we can talk about actual code and get a close look at what's going on instead of guessing, is that possible?
