### ISSUE TITLE
Share PDF in gmail with IOS 14.1 isn't  working.

### ISSUE THREAD

**Issue by LeonardoRepetto** [react-native-share/react-native-share#914]
I'm trying to share a PDF in base64 using Gmail with IOS. I'm using this workaround in the [documentation](https://react-native-share.github.io/react-native-share/docs/share-remote-file "link"), but it isn't working.

If I use the snipped to share a PDF with the code:
```js
static sharePDFWith(fileUrl, type) {
  let filePath = null;
  const configOptions = { fileCache: true };
  RNFetchBlob.config(configOptions)
    .fetch('GET', fileUrl)
    .then(resp => {
      filePath = resp.path();
      return resp.readFile('base64');
    })
    .then(async base64Data => {
      base64Data = `data:${type};base64,` + base64Data;
      await Share.open({ url: base64Data });
      await RNFS.unlink(filePath);
    });
}
```
I can share a pdf but Gmail doesn't recognize a format for the file.
![image](https://user-images.githubusercontent.com/14285783/99921801-a0c3aa80-2d0b-11eb-952e-8748ada30223.png)

### Steps to reproduce
1. Open app in IOS
2. Click button Share pdf in base64.
3. Select Gmail.

### Expected behaviour
Share pdf with extension in GMAIL.

### Actual behaviour
Share pdf but without extension.

### Environment
- **React Native version**: 0.63.3
- **React Native platform + platform version**: iOS 14.1 and iOS 14.2

### react-native-share
**Version**: 4.1.0

**Comment by lucasroca** [comment]
Hi @LeonardoRepetto, I'm experiencing the same issue. Have you found a way to solve it?

**Comment by Paolo-Gambardella** [comment]
Hi ! Did someone find the solution ? I'm facing this issue and I don't find anything...

**Comment by wuluru1002320** [comment]
I got the same issue here... Is there any way to solve it ?

**Comment by msignes** [comment]
I got the same issue. Any way to solve?

**Comment by roman-myshchyshyn** [comment]
Experiencing same issue, any ways to fix it?

**Comment by jade-vandal** [comment]
same issue on my side

**Comment by chenop** [comment]
Same here...

**Comment by Dror-Bar** [comment]
Wait is this still not fixed? any solutions?
