### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by GuillaumeHemmen** [react-native-share/react-native-share#916]
Hello,

I think I found a bug, here are the details to reproduce it:

### Steps to reproduce
1. have your iOS device in a non-English language (eg dutch)
2. launch the app
3. click on the test button to share the sample pdf

### Expected behaviour
All the button should be in the language set on the phone.

### Actual behaviour
One button seems to be not translated (save to file, see attached screenshot)

![Simulator Screen Shot - iPhone 11 - 2020-11-30 at 12 32 29](https://user-images.githubusercontent.com/6839630/100605623-7aec6600-3308-11eb-80f8-4f28b39633e1.png)

### Environment
- **React Native version**: 0.63.3
- **React Native platform + platform version**: iOS 14.x

### react-native-share
**Version**: 4.0.x - 4.1.0

### Link to repo (highly encouraged)
https://github.com/GuillaumeHemmen/react-native-share-bug-translation

**Comment by Relax594** [comment]
Same for a german iPhone. All buttons are english except for "Mehr" (More) and "Bücher" (Books).

**Comment by GuillaumeHemmen** [comment]
Few findings on my side:

The language displayed is based on the value of `CFBundleDevelopmentRegion` in the `Info.plist` file and regardless if `CFBundleAllowMixedLocalizations` is set to true as per the documentation said to do.

**Comment by GuillaumeHemmen** [comment]
Issue is also present on 5.1.0.

I was not able to find anything useful in the iOS source code as far as I could go. Any help is more than welcome 😄

**Comment by GuillaumeHemmen** [comment]
Hello everyone,

I found the solution to the problem. The issue was not coming from the library but from the setup of the project in itself.
To have i18n support, you must indeed follow the lib's documentation to enable `CFBundleDevelopmentRegion` and `CFBundleAllowMixedLocalizations`, but you also need to fill in the languages your app support (in Xcode > project > general > localizations)
