### ISSUE TITLE
IG Story Single Share on Release Crashes

### ISSUE THREAD

**Issue by lvillacin** [react-native-share/react-native-share#917]
### Steps to reproduce
1. Use IG Story Share Single on release 
2. It closes app but does not open IG Story

### Expected behaviour
When you open IG Story Single Share on Release it should open IG Story to be able to Story it.

### Actual behaviour
In debug signing (development environment) it works. I am able to IG Story Single Share. However, whenever I compile my app for release, it just closes my app and does not open IG Story. This only happens in Android

### Environment
- **React Native version**: 0.63.3
- **React Native platform + platform version**: target sdk 29

### react-native-share
**Version**: "master"

**Comment by kaioduarte** [comment]
@lvillacin I just tried it on release mode and it's working.

```json
"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-share": "^4.1.0",
    "rn-fetch-blob": "^0.12.0"
  }
```
