### ISSUE TITLE
Subject is left empty when sharing with Mail app for the 2nd time

### ISSUE THREAD

**Issue by orels1** [react-native-share/react-native-share#918]
### Steps to reproduce
1. Set a `subject` in the `options` for `Share.open()`
2. on an iOS device or simulator (iPhone 11 on iOS 14 was used to test) press share button
3. select the `Mail` app (native mail client)
4. cancel the email creation and delete the draft to return to the share screen
5. click on the mail app again (through the same share dialogue)

Can also recreate this by cancelling any other sharing action and trying to share with Mail app 

### Expected behaviour

The email subject should still be populated when trying to share the second time

### Actual behaviour

The email subject is empty

### Environment
- **React Native version**: 0.63.3
- **React Native platform + platform version**: iOS 14.1

### react-native-share
**Version**: ^4.1.0

### Link to repo (highly encouraged)
Private repository, but can create a repro if needed (any basic create react native app will work)

This is a revival of #816 as that was closed due to inactivity, but it is still an issue

**Comment by jim-hays-root** [comment]
Can confirm that we're seeing this issue with our app as well

**Comment by durgapt** [comment]
I am observing this issue as well. Email Subject is not being added in while sharing. Attached my code snippet below
`const options = {
            title: shareOptions.title,
            message: shareOptions.message,
            subject: shareOptions.subject,
            failOnCancel: false,
        };

        Share.open(options)
            .then((res) => {
            console.log(res);
        })
        .catch((err) => {
            err && console.log(err);
        });`

**Comment by jeroenwouters** [comment]
We also have this issue when sharing a image, then we get a error the second time.

**Comment by orels1** [comment]
This is still an issue as of the current version (marking so the bit doesn't close it)

**Comment by jim-hays-root** [comment]
discussion

**Comment by bostnis** [comment]
I've upgraded to 7.0.0 version but still encountering this issue,
any solutions?

**Comment by orels1** [comment]
This is still an issue 😔

**Comment by orels1** [comment]
At this point we moved on from doing this, so this will be the last time id bump this issue.
For anyone else who's still having it - its now on you to keep this alive

**Comment by MateusAndrade** [comment]
> At this point we moved on from doing this, so this will be the last time id bump this issue. For anyone else who's still having it - its now on you to keep this alive

Sorry for the inconvenience, 691e370a991b68cad57c65e720f255575be4185d should prevent this from being close 😅
