### ISSUE TITLE
Instagram Stories for Android

### ISSUE THREAD

**Issue by anandbatjargal** [react-native-share/react-native-share#919]
### Steps to reproduce
 React Native Share Version is 4.0.4     

    const shareOptions = {
      method: Share.InstagramStories.SHARE_BACKGROUND_IMAGE,
      backgroundImage: <string url of image>,
      backgroundBottomColor: "#fefefe",
      backgroundTopColor: "#906df4",
      social: Share.Social.INSTAGRAM_STORIES,
      ...Platform.select({
        // Necessary due to bug in
        // node_modules/react-native-share/android/src/main/java/cl/json/social/SingleShareIntent.java
        android: {
          forceDialog: true,
        },
      }),
    };

    Share.shareSingle(shareOptions)
      .then((res) => {
        console.log(res);
      })
      .catch((err) => {
        err && console.log(err);
      });

### Expected behaviour
1. Android app should open Instagram and the image should be there to be sent as a Instagram Story.
NOTE: I am able to do Instagram Story share with iOS, after allowing it in the .plist file, but on Android it doesn't work. 

### Actual behaviour
2. It fails to open the Instagram application.

### Environment
- **React Native version**: 0.63.3

### react-native-share
**Version**: 4.0.4

**Comment by kaioduarte** [comment]
@anandbatjargal I think your trying to use a URL from web and it's not valid (accordingly to the docs: **The Uri needs to be a content Uri to a local file on the device.**)

Try this

```js
import React from 'react';
import {StyleSheet, View, Button} from 'react-native';

import RNFetchBlob from 'rn-fetch-blob';
import Share from 'react-native-share';

const App = () => {
  const share = async () => {
    try {
      const cache = await RNFetchBlob.config({
        fileCache: true,
        appendExt: 'jpg',
      }).fetch('GET', 'https://source.unsplash.com/random');

      const shareOptions = {
        method: Share.InstagramStories.SHARE_BACKGROUND_IMAGE,
        backgroundImage: `file://${cache.path()}`,
        social: Share.Social.INSTAGRAM_STORIES,
      };
      await Share.shareSingle(shareOptions);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <View style={styles.container}>
      <Button title="Share" onPress={share} />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default App;
```

**Comment by anandb7248** [comment]
@kaioduarte Hey this is super super helpful! Thank you!

**Comment by anandb7248** [comment]
@kaioduarte I see so this method saves the image locally, we would need to delete the image after sharing right?

**Comment by kaioduarte** [comment]
Exactly @anandb7248, you need to unlink the created file after send it.

**Comment by sumit-neosoft** [comment]
Having the same issue, i am try to send the local path of the Image after saving it to Local
