### ISSUE TITLE
Share.shareSingle not firing Success and Failure Callbacks at correct time

### ISSUE THREAD

**Issue by sumit-neosoft** [react-native-share/react-native-share#926]
### Steps to reproduce
1. Install the plugin in a project
2. Use Share.shareSingle with Share.Social.WHATSAPP
3. Triggering the function

### Expected behavior
Should return the callbacks of success or failure after a user completes the action.
### Actual behavior
The callbacks are fired with {message: undefined, app: undefined} as soon as the function is triggered. No callback after the action is canceled/completed.

### Environment
- **React Native version**:0.61.4
- **React Native platform + platform version**: iOS 11+, Android 5.0+

### react-native-share
**Version**: ^3.7.0

**Comment by jossydeleon** [comment]
Any update on this?

**Comment by pavelglebov** [comment]
+

**Comment by mikehardy** [comment]
@pavelglebov did you mean to subscribe to the issue using the button on the right vs adding a comment that creates notifications for everyone?

**Comment by Graig123git** [comment]
Is there any Update on this ?

**Comment by Graig123git** [comment]
@pavelglebov did you find any workarounds ?
