### ISSUE TITLE
Attribution URL for Instagram Stories

### ISSUE THREAD

**Issue by demic-dev** [react-native-share/react-native-share#927]
Hi, I'm using this module for sharing images to Instagram Stories.
In the shareOptions there is the attributionURL. For what is used?

If I want that Instagram, like stories with Spotify songs, has the link to the application and on the top of the screen "play on", how could I add?

Thanks :)

**Comment by Cetger** [comment]
I think it doesnt work on android. I have the same issue but i couldnt any solution for it. If i dont find any solution for it, I will write my native module according to facebook developer docs.

**Comment by dandre-hound** [comment]
Did anyone figure out a solution here?

**Comment by reberthkss** [comment]
would like to know if we made some progress on this.

**Comment by mikehardy** [comment]
"we" implies that you have contributed a PR or something? :-) - I don't see anything
It's open source, what you see is what you get. If you see nothing you don't have to ask: there's nothing

**Comment by reberthkss** [comment]
@mikehardy good to know that you reply issues when they hurt your ego :D
.
I will give a try to made this improvement anyway. Thanks!

**Comment by mikehardy** [comment]
Oh please don't misunderstand, I don't have an ego about open source participation. I just don't like receiving notifications saying "hey this software I got for free doesn't seem to do what I want, can you help me more for free?". It's more of a compensation for effort involved thing vs sense of entitlement to maintainers attention that some users have.

I would sincerely love to collaborate on any PR you come up with, and will do anything I can to help you get it merged if it's a reasonable improvement

**Comment by MarcHbb** [comment]
@mikehardy 
Hello !
I think a lot of people is waiting for this feature, it would be incredible ! I would like to help, but i don't know anything about native code and stuff...
Do you think this feature will be feasible ? If that's the case, do you know if there is a way to be notified about the progress ? 
Thank you for the work that has been done so far 🙏🏼

**Comment by mikehardy** [comment]
You have commented here, so now you'll be notified of progress. I've no idea if it's feasible sorry. I knew nothing of react-native native code until my business needed something and I just tried it and got it done. It will likely only be done if you or someone else is similarly motivated

**Comment by Pietro-Putelli** [comment]
Hi, I'm using the attributionURL with an https://www.site.com/, but it doesn't work on instagram story, someone knows why?
Thank you

**Comment by ebellumat** [comment]
2024 and this still a issue? I mean, this is Spotify story share and this works for Apple Music too, why this not work for us? 
![image](https://github.com/react-native-share/react-native-share/assets/26942680/a2dc0f92-8e6d-4a0c-938e-ed03d38dec10)

**Comment by pierroo** [comment]
any of you guys managed to have the attributionurl working?
