### ISSUE TITLE
Share.Social.EMAIL not adding url to the mail body in iOS. Android works as expected 

### ISSUE THREAD

**Issue by t08-apporio** [react-native-share/react-native-share#932]
### Steps to reproduce
1. 
```
const emailOptions = {
title: "title",
message: "message",
url: "https://example.com/to-some-page",
social: Share.Social.EMAIL,
subject: "subject"
}
```
2. 
```
Share.shareSingle(emailOptions)
.then(response => handleResponse(response))
.catch(error => alert(error));
```
### Expected behaviour
Should fill the email's subject and fill the message body with "message" and "url" of the emailOptions together

### Actual behaviour
Only "message" is present in the body

### Environment
- **React Native version**: 0.63.4
- **React Native platform + platform version**: iOS 14.0

### react-native-share
**Version**: 4.1.0

### Link to repo (highly encouraged)
https://github.com/

**Comment by t08-apporio** [comment]
Included the url in the message attribute of the emailOptions

**Comment by andyrobert3** [comment]
@t08-apporio I still face this issue, it isn't technically solved but you just made a workaround via the message field

**Comment by andyrobert3** [comment]
Could you re-open it if it is still an issue, I can try to make a PR if is indeed an issue for others

**Comment by mikehardy** [comment]
A PR won't work well unless you can reproduce it @andyrobert3 but that would be awesome. If you confirm you can reproduce definitely can reopen!

**Comment by andyrobert3** [comment]
@mikehardy any steps on how to file an issue?
I found the culprit in the code

**Comment by mikehardy** [comment]
Just open a PR no worries

**Comment by andyrobert3** [comment]
@mikehardy 
https://github.com/react-native-share/react-native-share/pull/1049

My first time contributing to open source, lmk if I can do more to help maintain this project!

**Comment by mikehardy** [comment]
@andyrobert3 champion! :smile: :trophy:
