### ISSUE TITLE
Android copy action is returning app as undefined

### ISSUE THREAD

**Issue by jdnichollsc** [react-native-share/react-native-share#937]
Hello folks, thanks for this awesome lib!

Please check details of a issue I have from Android:

### Steps to reproduce
1. Call `Share.open` from Android
2. Choose copy action
3. `response.app` is returning `undefined` 

### Expected behaviour
Return `app` property with a value like `com.google.android.apps.docs/com.google.android.apps.docs.drive.clipboard.SendTextToClipboardActivity` when the promise is resolved

### Actual behaviour
Returning `undefined` as value of `app` prop.
```ts
Share.open({
  message: myUrl,
  failOnCancel: false
}).then((res) => {
  console.log(res.app) // returns undefined from Android
})
```

### Environment
- **React Native version**: 0.61.2
- **React Native platform + platform version**: Android 10

### react-native-share
**Version**: ^3.7.0

Thanks in advance and merry Christmas! <3

**Comment by zaydion** [comment]
any updates here? i've noticed that on copy results in a fail (goes to `.catch` block):

```js
Share.open({ url })
  .then((res) => {
    console.log('success')
  })
  .catch((e) => {
    console.log('fail/error') // on copy lands here for android saying url wasnt shared
  })
```

**Comment by rkritskiy** [comment]
any updates here?

**Comment by ahelord** [comment]
any updates here?
