### ISSUE TITLE
Sharing to Instagram yields "Something Went Wrong"

### ISSUE THREAD

**Issue by mikeho** [react-native-share/react-native-share#942]
### Steps to reproduce
1. Called RNShare.open() passing in a URL to a local image file
2. Selected Instagram on the subsequent native iOS Activity Sheet to select sharing to Instagram

### Expected behaviour
The expectation is that the Instagram native share screen would appear.

### Actual behaviour
I get a UIAlertView titled "Error", with the content saying "Something Went Wrong"

(please note, when I select any other option or app on the iOS Activity Sheet, it works fine / as expected.  I can share to LINE, send as an email, post in iMessage, etc., and it works as expected -- so the only issue appears to be with selecting Instagram specifically)

### Environment
- **React Native version**: 0.63.3
- **React Native platform + platform version**: iOS 14.2.1 on a iPhone 12 Mini, with the latest version of the Instagram app

### react-native-share
**Version**: 3.8.5

**Comment by hamart** [comment]
Same problem. @mikeho Did you find any workaround?

**Comment by mikeho** [comment]
Yeah, it looks like https://github.com/react-native-share/react-native-share/issues/923 is a potential workaround -- however, it only works for images. :-/

**Comment by ff-joaquin-rojas** [comment]
This is happening to me if user has not sign in instagram... On the other social networks it shows messages like "You must log in first..." etc, but on instagram it only displays that message. The error is triggering in the package itself so there's no way to change the message or so.

**Comment by mikeho** [comment]
No, this is happening regardless.  I am logged into IG, and I'm still seeing the issue.

It looks like there was a change either to iOS or the IG App / API itself which no longer accepts a URL to a local file asset to post, and instead, now requires the asset to be a base64 encoded string.  This is a workaround for images which is mentioned in #923, but it won't work for videos.

Interestingly enough, even Apple's own apps are broken.  If you try and Share-to-IG an image attachment that you get in the Messages or the Mail app, you will get the same "Something Went Wrong" alert.

**Comment by jossydeleon** [comment]
Change Instagram app permissions to "Allow all images" instead of "Selected image"

**Comment by aouse** [comment]
> Change Instagram app permissions to "Allow all images" instead of "Selected image"

Do you mean the the settings of the app on the device? There is no option for "Allow all images" or "Selected images" in there.

**Comment by mikeho** [comment]
That's not the issue anyway.

This is an issue with the IG App, itself, and likely something FB will not be fixing.

(You will notice even Apple's apps like Messages, Mail and Photos have the same issue -- they are unable to Share to IG)
 
The workaround posted above and mentioned in #923 is the best workaround for images (for now, until there's an official fix from FB (unlikely) or until FB shuts this share mechanism down for good (more likely)).

And then there's basically no option for Videos anymore.

Since this is an issue with IG's app specifically and not really anything with the React Native Share library, I'm closing out this ticket.

**Comment by jossydeleon** [comment]
> > Change Instagram app permissions to "Allow all images" instead of "Selected image"
> 
> Do you mean the settings of the app on the device? There is no option for "Allow all images" or "Selected images" in there.

Uninstall IG, then Install it again. Try to post and Image and select permission Allow access to all images.

`/**
   * Share the content in Instagram
   **/
  const shareToInstagram = async (data) => {
    let cache = null;
    const image = data.logo;
    try {

      //Get url extension of file
      const extension = getUrlExtension(image);

      cache = await RNFetchBlob.config({
        fileCache: true,
        appendExt: extension
      }).fetch("GET", image, {});

      const gallery = await CameraRoll.save(cache.path(), "photo");

      const shareOptions = {
        social: Share.Social.INSTAGRAM,
        url: gallery,
      };

      const shareResponse = await Share.shareSingle(shareOptions);
      console.log("Share to IG Response: " + JSON.stringify(shareResponse));
    } catch (error) {
      throw error;
    } finally {
      //Clean cache
      if (cache) cache.flush();
    }
  };
`
