### ISSUE TITLE
'React-Native-Share' Library fails to compile on Web

### ISSUE THREAD

**Issue by bick111** [react-native-share/react-native-share#943]
I've been creating **react-native app** to **share** text or images to social platforms. 
I've used **React-Native-Share** library to serve the purpose of my application. 
This library is working fine for iOS & Android but when I'm running it on Web. 
I'm facing compiling failed error (Syntax Error). 
It seems like React-Native-Web cannot parse the syntax used by this library. 

Please see the attached screenshot
<img width="1048" alt="Screenshot 2020-12-28 at 12 36 16 PM" src="https://user-images.githubusercontent.com/11553875/103198576-aade5780-490e-11eb-805a-ddb708d30d45.png">

**Comment by MateusAndrade** [comment]
Hi @bick111 , thanks for sharing that. As far as I know, I don't know if `react-native-share` is compatible with `react-native-web`.  There is anything that you can share with to look after that?
