### ISSUE TITLE
Can I share Location

### ISSUE THREAD

**Issue by Anujmoglix** [react-native-share/react-native-share#945]
## Ask your Question
Any possibility to share location like WhatsApp ?

**Comment by mikehardy** [comment]
I don't believe there is anything stopping you from integrating a GPS package, and using the coordinates in a standard URL format to share a map URL to any of the popular online mapping engines?

**Comment by MateusAndrade** [comment]
As @mikehardy sad, I think you will need a package to get the coordinates of your user, and then share these coordinates.
