### ISSUE TITLE
Error while sharing a video to Instagram Stories

### ISSUE THREAD

**Issue by HugoBA** [react-native-share/react-native-share#949]
Hello,  I have issues while trying to share a background video to Instagram Stories

### Steps to reproduce

```
const shareOptions = {
method: Share.InstagramStories.SHARE_BACKGROUND_VIDEO,
backgroundVideo: "https://media.snapmyride.com/output/GDBORNAND/AIRBAG/2020/03/14/GDBORNAND-AIRBAG-20200314-145504-AA20031414550489.mp4", //or any local video URI
backgroundBottomColor: '#fefefe',
backgroundTopColor: '#906df4',
social: Share.Social.INSTAGRAM_STORIES
};

Share.shareSingle(shareOptions);
```

### Expected behaviour
Redirect to Instagram with the video as a story

### Actual behaviour
![IMG_9374](https://user-images.githubusercontent.com/5486891/104842794-b2839180-58f9-11eb-8f64-e60063241c1f.PNG)

### Environment
React Native version: 0.63.3
React Native platform + platform version: iOS 14.3
React-native-share version: 3.7.0

I could share an image to Stories without any problem, but I can't make it work for videos...
Any idea? I'm available if you need any additional information!
Thank you

**Comment by Lg0gs** [comment]
same issue here

**Comment by Lg0gs** [comment]
@ishangupta01 
`node_modules/react-native-share/ios/InstagramStories.m file`, change line **162** to 

> NSData *const backgroundVideo = [NSData dataWithContentsOfURL:[NSURL URLWithString:URL]];
