### ISSUE TITLE
WeChat Support

### ISSUE THREAD

**Issue by outofmemory** [react-native-share/react-native-share#950]
I've noticed that wechat is not supported yet ... 
Will it be accepted if I make PR for that ？

**Comment by MateusAndrade** [comment]
> I've noticed that wechat is not supported yet ...
> Will it be accepted if I make PR for that ？

Sure! New PR's are welcome! 🚀

**Comment by outofmemory** [comment]
I mean, we can add WeChat to social lists such as facebook/twitter... instead of the default way

**Comment by outofmemory** [comment]
> > I've noticed that wechat is not supported yet ...
> > Will it be accepted if I make PR for that ？
> 
> Sure! New PR's are welcome! 🚀 . Btw, do you know if the default share behavior doesn't work for WeChat?

I mean, we can add WeChat to social lists such as facebook/twitter... instead of the default way

**Comment by outofmemory** [comment]
> > > I've noticed that wechat is not supported yet ...
> > > Will it be accepted if I make PR for that ？
> > 
> > 
> > Sure! New PR's are welcome! 🚀 . Btw, do you know if the default share behavior doesn't work for WeChat?
> 
> I mean, we can add WeChat to social lists such as facebook/twitter... instead of the default way
what we need most is GenericSingleShare which we can specify params(e.g. ComponentClass/PackageName/WebLink...) when calling the function.

**Comment by KingAmo** [comment]
any update on this feature ?
