### ISSUE TITLE
shareSingle whatsapp doesn't open specified number

### ISSUE THREAD

**Issue by edersonfaccin** [react-native-share/react-native-share#952]
Hi guys, i am testing this package, but in one test i saw than the function shareSingle whatsapp same putting the parameter whatsAppNumber doesn't opened the number, i have than choice then whatsapp number manuality

Someone can fix this bug?

My code

const shareOptions = {
  title: 'Share via',
  message: 'hello, this is a message',
  url: imagem1,
  social: Share.Social.WHATSAPP,
  whatsAppNumber: "5548999999999",  // country code + phone number
}

const shareResponse = await Share.shareSingle(shareOptions)

Thanks

**Comment by deepanshu-shopG** [comment]
Hey @edersonfaccin 

I faced the same issue few days back, got solved when I upgraded to v4.0.1. I guess, this functionality was added later
Might be useful to you

**Comment by edersonfaccin** [comment]
> Hey @edersonfaccin
> 
> I faced the same issue few days back, got solved when I upgraded to v4.0.1. I guess, this functionality was added later
> Might be useful to you

t

**Comment by edersonfaccin** [comment]
Hello @deepanshu-shopG, thanks for your reply, I updated this package to the latest version and I continue with the problem. Did you make a different code than the one I posted? Thanks

**Comment by SheikhJuned** [comment]
hey @deepanshu-shopG shame issue coming for me. I have react-native-share ==4.1.0 version. please share your code if working for you.

**Comment by deepanshu-shopG** [comment]
Hey @edersonfaccin, same code is working for me.

**Comment by edersonfaccin** [comment]
Seriously @deepanshu-shopG ?, it still doesn’t work with me :(
With me, open the window to choose the type of sharing yet, what I wanted was to already attach the image and open it in the last contact in the whatsappnumber parameter. But without any problems, I thank you for the availability my friend :D

**Comment by manjunathgk22** [comment]
same issue, any update on this ?

**Comment by andyrobert3** [comment]
@edersonfaccin @manjunathgk22 is this happening on iOS or Android?

**Comment by edersonfaccin** [comment]
> @edersonfaccin @manjunathgk22 is this happening on iOS or Android?

Hi bro, I tested it on android device

**Comment by andyrobert3** [comment]
> > @edersonfaccin @manjunathgk22 is this happening on iOS or Android?
> 
> 
> 
> Hi bro, I tested it on android device
> 
> 

taking a look, be back with a fix

**Comment by qasimgit** [comment]
facing same issue.,  any update on this issue?

**Comment by edersonfaccin** [comment]
@qasimgit nothing yet here :(

**Comment by andyrobert3** [comment]
@qasimgit i have been swamped with work, haven't had the chance to take a look :(

I'll only be free in a couple of months time

**Comment by freakk101** [comment]
I have Kind of come up with a hack-fix, It works for my need. Sharing if it help you guys.

file android/src/main/java/cl/json/social/ShareIntent.java
` if (socialType.equals("whatsapp")) {
            if (options.hasKey("whatsAppNumber")) {
                String whatsAppNumber = options.getString("whatsAppNumber");
                String chatAddress = whatsAppNumber + "@s.whatsapp.net";
                // Below line will open the conversation screen
                this.getIntent().setComponent(new ComponentName("com.whatsapp", "com.whatsapp.Conversation"));
                this.getIntent().putExtra("jid", chatAddress);
            }
        }

        if (socialType.equals("whatsappbusiness")) {
            if (options.hasKey("whatsAppNumber")) {
                String whatsAppNumber = options.getString("whatsAppNumber");
                String chatAddress = whatsAppNumber + "@s.whatsapp.net";
                // Below line will open the conversation screen
                this.getIntent().setComponent(new ComponentName("com.whatsapp.w4b", "com.whatsapp.Conversation"));
                this.getIntent().putExtra("jid", chatAddress);
            }
        }
`

**Comment by freakk101** [comment]
I come up with following solution it works for my need, 

file: android/src/main/java/cl/json/social/ShareIntent.java

    if (socialType.equals("whatsapp")) {
            if (options.hasKey("whatsAppNumber")) {
                String whatsAppNumber = options.getString("whatsAppNumber");
                String chatAddress = whatsAppNumber + "@s.whatsapp.net";
                // below line will open whatsapp number
                this.getIntent().setComponent(new ComponentName("com.whatsapp", "com.whatsapp.Conversation"));
                this.getIntent().putExtra("jid", chatAddress);
            }
        }

        if (socialType.equals("whatsappbusiness")) {
            if (options.hasKey("whatsAppNumber")) {
                String whatsAppNumber = options.getString("whatsAppNumber");
                String chatAddress = whatsAppNumber + "@s.whatsapp.net";
                // below line will open whatsapp number
                this.getIntent().setComponent(new ComponentName("com.whatsapp.w4b", "com.whatsapp.Conversation"));
                this.getIntent().putExtra("jid", chatAddress);
            }
        }

**Comment by dietpizza** [comment]
@freakk101 can you tell me how i can manually patch this in? I don't know much about native modules so any help is appreciated.

**Comment by OAllanFernando** [comment]
Hey guys, in my case and I think this might be the case for everyone, was the number 

if the zap zap does not find the phone number he spawn to select a chat, so i remove the first 9 
Here the number can have a adicional 9, like

5544998102030
and works with
554498102030

The behavior is crazy because, the phone on whatsapp have the adicional 9.
I will try to find a recent registered number to test, i wonder if its caused by the original number register on their server, the 9 thing its kind new over here. 

https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil 
for you outsiders folks, perhaps had similar isues with the phone format and how whatsapp persists that

I think that is a subject for the sponsors
