### ISSUE TITLE
IOS : msg coming twice in body 

### ISSUE THREAD

**Issue by shrey-vs** [react-native-share/react-native-share#958]

**Comment by justinemignot** [comment]
Hello, 
I am facing the same issue. Here some more infos: 

**Phone**: Pphone 7, version: 12.4.1

**Code**: 
 ```
 await Share.share({
    message: 'I am the message',
    url: 'http://test.com',
    title: 'I am the title',
  })
```

**Sharing on Gmail:** 
![image](https://user-images.githubusercontent.com/33832992/106763622-50d06080-6637-11eb-9f81-be2645ba3f32.png)


Can you help us with that ? 
Thanks !

**Comment by justinemignot** [comment]
Hello, 
I am facing the same issue. Here some more infos: 

## Phone
iPhone 7, version: 12.4.1

## Code
 ```
 await Share.share({
    message: 'I am the message',
    url: 'http://test.com',
    title: 'I am the title',
  })
```

## Sharing on Gmail 
![image](https://user-images.githubusercontent.com/33832992/106763835-8412ef80-6637-11eb-91b1-a6d3845b9318.png)


On Android, everything works fine.
Can you help us with that ? 
Thanks !

**Comment by castalonirenz** [comment]
same here

**Comment by honorski** [comment]
Having the same issue on version 5.1.1 and 5.1.0 on iOS sharing on gmail app.

**Comment by galaxyfeeder** [comment]
After thinking a little and taking a look at the library, I suspect this might be a problem with the Gmail iOS app and not with this library in particular. Also I've tried with other applications installed on my iPhone and happens the same to all of them.

It does not make sense that the share works well with Whatsapp and with the Copy app of iOS but on Gmail, the library does not do anything special for this share case [it just launch the native share controller](https://github.com/react-native-share/react-native-share/blob/5d942045f389e88316984f31e9a2d45adea0107f/ios/RNShare.m#L253).

**Comment by antoinewg** [comment]
are you using `react-native-share` or Share from `react-native` @shrey-vs @honorski ?

**Comment by honorski** [comment]
> are you using `react-native-share` or Share from `react-native` @shrey-vs @honorski ?

@antoinewg react-native-share version 5.1.4

**Comment by antoinewg** [comment]
Okey actually, I was just asking because I had the issue with `react-native`. But now, both with `react-native-share` (^5.1.6) and `react-native` (0.63.3), I can't reproduce it.

I am not familiar with the library but after taking a look at this library, it seems indeed that the with the gmail app, as @galaxyfeeder suggests. My gmail iOS version is **6.0.210207**. Could you try with this version and see if it fixes it @honorski  ?
