### ISSUE TITLE
IOS : On sharing msg on gmail app on ios the msg comes twice in body. 

### ISSUE THREAD

**Issue by shrey-vs** [react-native-share/react-native-share#959]
.then(async (base64Str) => {
                const base64Data = `data:image/png;base64,${base64Str}`;
                const shareOptions = {
                    message: shareMsg,
                    url: base64Data
                };
                await Share.open(shareOptions);

**Comment by justinemignot** [comment]
Hello, isn't it a duplicate of https://github.com/react-native-share/react-native-share/issues/958 ? Thanks

**Comment by honorski** [comment]
Having the same issue on version 5.1.1 and 5.1.0 on iOS sharing on gmail app.
