### ISSUE TITLE
messenger share isnt available

### ISSUE THREAD

**Issue by kaneki666** [react-native-share/react-native-share#962]
in your documentation u said messenger is available..but its not
https://github.com/react-native-share/react-native-share/blob/5299d95aab25bfba6815e0f5455876897ed8ddc6/index.js#L207-L219

**Comment by kodie** [comment]
The Messenger option shows up but I get this error when selecting it:

```
{
  "line": 155952,
  "column": 33,
  "sourceURL": "http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false"
}
```

**Comment by kodie** [comment]
Sharing to messenger appears to work on an actual device for me, just not simulators.

**Comment by kaneki666** [comment]
I triee actual device
