### ISSUE TITLE
Allow to modify shared file name on iOS

### ISSUE THREAD

**Issue by norbertschuler** [react-native-share/react-native-share#963]
## Describe the Feature
It would be great if the shared file on IOS with the option `saveToFiles` could be named other then `file + extension` as currently done at https://github.com/react-native-share/react-native-share/blob/efa187500942187f5efcb46e1feac825c6b35ac5/ios/Utils.m#L42 

The file name might be derived from the data url like the extension is if provided e.g. with `data:application/json;name=test;base64,...` - not sure if it should only be given the file `name` or file `name + extension` for the name parameter.

**Comment by kg-currenxie** [comment]
We would really want this as well. Is this repo abandoned?

**Comment by mikehardy** [comment]
@kg-currenxie a quick look at the commit log indicates it's alive https://github.com/react-native-share/react-native-share/commits/main

In short: not abandoned, try a pull request, you'd be surprised how quickly things are merged here.

**Comment by kg-currenxie** [comment]
If i only knew objc :(

**Comment by mikehardy** [comment]
I knew nothing of objective-c when I started coding native modules in react-native. Open up Xcode and the apple documentation and give it a shot. It's still just programming a computer, and it's ugly (in my opinion) but objective-c is not hard. More importantly, no one will do things for you - if you need a feature, hack it up! :-)
