### ISSUE TITLE
Bug: Share intent should use setClipData(uri) for content:// uris on Android SDK >= 16

### ISSUE THREAD

**Issue by rejhgadellaa** [react-native-share/react-native-share#970]
### Steps to reproduce
1. Use the react-native-share library to share an image on Android 10 or higher.
2. Observe the system share menu

### Expected behaviour
The share dialog should show a preview of the image on Android 10 and higher. 3rd party share menu replacement apps like Sharedr (https://sharedr.rejh.nl) should be able to grant read permission to the app the user chooses.

### Actual behaviour
The share dialog does not show a preview of the image. 3rd party share menu replacement apps can not grant the read permission to the app the user chooses.

### Background information

`Intent.setClipData()` should be used when sharing files on Android 4.1 (SDK 16) and higher:
[Intent#ACTION_SEND](https://developer.android.com/reference/android/content/Intent#ACTION_SEND)

In [ShareIntent.java](https://github.com/react-native-share/react-native-share/blob/master/android/src/main/java/cl/json/social/ShareIntent.java), I can see that `putExtra(Intent.EXTRA_STREAM)` and `setFlags(FLAG_GRANT_READ_URI_PERMISSION)` are called, but `intent.setClipData()` is missing.

The quick fix is to add one line:

```
intent.setClipData( ClipData.newRawUri(null, imageUri) );
```

This makes sure that Intent.createChooser() copies the uri and flags to the chooser intent it creates:
[Intent.java#997 AOSP source code](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/android10-release/core/java/android/content/Intent.java#997)

You may want to look into this AOSP bug tracker ticket, it includes an example project and lots of background information:
https://issuetracker.google.com/issues/176280829

### Environment
- **React Native platform + platform version**: Pixel 3, Android 11

### react-native-share
**Version**: "master"

### Link to repo (highly encouraged)
https://github.com/

### Screenshots

An example of how it should look on Android 11 (notice the preview of the image on the share sheet):

![Android-11-Nearby-Share-1](https://user-images.githubusercontent.com/4703109/108676617-cd44b980-74e8-11eb-8a55-d705facf4ae6.jpg)

**Comment by rejhgadellaa** [comment]
Friendly ping, any chance this gets resolved?

**Comment by rejhgadellaa** [comment]
Friendly ping #2...?

**Comment by ohadkoronyo** [comment]
hey, this is still an issue. Could someone take a look at this one? Adding setClipData() for the intent seems to do the trick
