### ISSUE TITLE
Facing Issue while sharing in GMAIL( TO address bar is pre-populated)

### ISSUE THREAD

**Issue by satheesh116** [react-native-share/react-native-share#976]
Hi all, using react-native share when i am trying to send .png file in Gmail, the To address bar gets prepopulated with the filename of the file i need to share. So can anyone provide a workaround for this issue.

**Comment by jwinky** [comment]
I'm having this issue as well on Android, using the call:

```
Share.open({
    title: 'Share Title',
    url: `data:application/pdf;base64,${PDF_BASE64}`,
    type: 'application/pdf',
    filename: 'Attached Filename',
    subject: 'This is the subject',
    email: 'foobar@bazbat.net',
  });
```

<img width="473" alt="Screen Shot 2021-03-08 at 3 06 46 PM" src="https://user-images.githubusercontent.com/170736/110393819-1552f880-8020-11eb-9a90-276c137ff35c.png">

**Comment by satheesh116** [comment]
Thank you for your response. Your library is very useful to my project.
