### ISSUE TITLE
Migrate from jcenter

### ISSUE THREAD

**Issue by pke** [react-native-share/react-native-share#979]
Are the Android artifacts still publised on jcenter? Its going out of business in May and an alternative should be ready for that. The service had already outage today which made builds impossible.
Thanks!

**Comment by friederbluemle** [comment]
> Its going out of business in May

Wow, do you have a link to a reference/the announcement?

**Comment by pke** [comment]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by mikehardy** [comment]
There are no external gradle dependencies that I see? https://github.com/react-native-share/react-native-share/blob/master/android/build.gradle

I agree this is a big deal, I just don't see how it relates to react-native-share, I believe react-native-share is published completely (no other things needed) on npmjs.com

**Comment by pke** [comment]
As far as I understand it, the whole build chain is affected and this module uses `jcenter()` as artifact repository for its dependencies. It would have to be cleaned up, wouldn't it?

**Comment by mikehardy** [comment]
Point me to a specific external dependency defined in this package that uses jcenter, and I agree.
If you mean "this package uses react-native and react-native uses jcenter", that's a react-native issue, nothing actionable in this repository. Keyword: actionable, issues should be filed where they are actionable

**Comment by pke** [comment]
So you're saying the gradle files can continue to contain references to jcenter beyond May and it will just work and not throw a compile error because of the repo not being reachable?
Besides, removing the jcenter references wouldn't harm code cleanliness anyway I think.

**Comment by friederbluemle** [comment]
Interesting.. Thanks for the link @pke
I agree with @mikehardy though, it might become a problem for other repos, but react-native-share is not one of them. The Android Gradle plugin is fetched from the `google()` repository, and `react-native` is coming from the local `node_modules/` folder. There are no other dependencies fetched or published from/to `jcenter()`.

**Comment by pke** [comment]
So we could remove the references without problem?

**Comment by friederbluemle** [comment]
If it's causing issues then you can remove it locally. For simplicity these files should simply be kept aligned with the defaults that Android Studio generates for Android projects, _unless_ something is not working. As of today (2021-03-16), the latest stable version of Android Studio still creates build.gradle files with `jcenter()` in them. I'm pretty sure the team at Google is aware and we should see an update in one of the next releases.

**Comment by pke** [comment]
makes sense. As I said I know too little about the internals of a module build process. I just got a bunch of 502 from jcenter yesterday with a bunch of RN modules and wanted to raise awareness.

Should this ticket stay open as a reminder to check Android Studio changes?

**Comment by mikehardy** [comment]
Can't hurt to leave it open.

Here is current google status https://developer.android.com/studio/build/jcenter-migration

I quote in full:

> JCenter deprecation and end of service

> JFrog, the company that maintains the JCenter artifact repository used by many Android projects, recently announced the deprecation and upcoming retirement of JCenter. According to the announcement, JCenter will allow downloads of existing artifacts until February 1, 2022.
> 
> Developers who publish artifacts on JCenter should start migrating their packages to a new host, such as Maven Central.
> 
> In the near future, we will provide additional information about migrating Android projects away from JCenter on this page.

**Comment by pke** [comment]
please someone mark this as "discussion" so it stays open

**Comment by mikehardy** [comment]
No, it's unimportant now. JCenter is on record they will maintain read-only access indefinitely.

**Comment by mikehardy** [comment]
(that was a change for them, they relented to community tears/crying I think)
