### ISSUE TITLE
Shows `data` as filename for data URI shares

### ISSUE THREAD

**Issue by pke** [react-native-share/react-native-share#980]
### Steps to reproduce
1. Share a data:uri like `data:image/png;base64,...` as `url` argument
2. set `filename` to `test.png`

### Expected behaviour

Share action sheet displays filename as "test.png"

### Actual behaviour

Share action sheet displays "data" as filename.

### Environment

"react-native-share": "5.1.4"

Binaries:
    Node: 15.0.1 - ~/.nvm/versions/node/v15.0.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.0.3 - ~/.nvm/versions/node/v15.0.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/pkursawe/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.14.0 => 16.14.0 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found

**Comment by benglass** [comment]
We also need this feature

**Comment by pke** [comment]
This seems to be an important feature of the module and should not go unnoticed. Closing bugs automatically without the owner/contributors even checking it is not very helpful.

**Comment by jeroen-van-dijk** [comment]
Has anyone found any kind of workaround?
