### ISSUE TITLE
If the Share dialog is opened from a Modal, even Modal is getting dismissed when we close share dialog.

### ISSUE THREAD

**Issue by ShruthiRSalian** [react-native-share/react-native-share#981]
### Steps to reproduce
1. Open a Modal https://reactnative.dev/docs/modal 
2. That Modal will have button to open Share dialog window, On tap of the button Share dialog will open
3. When closing the Share dialog even modal is getting dismissed.

### Expected behaviour
Only the share dialog should get closed

### Actual behaviour
Both share dialog and modal is closed

**### Suggested fix:** 
In RNShare.m file 
Instead of closing controller,
[controller dismissViewControllerAnimated:true completion:nil];

we can close ActivityViewControlller.
[weakShareController dismissViewControllerAnimated:true completion:nil];
or
        if(weakShareController){
            // closing activity view controller
            [weakShareController dismissViewControllerAnimated:true completion:nil];
        } else {
            [controller dismissViewControllerAnimated:true completion:nil];
        }
Let me know if I can raise PR.

### Environment
**React Native platform + platform version**: iOS 9.0

### react-native-share
**Version**: "react-native-share": "^5.1.4"

### Link to repo (highly encouraged)
https://github.com/react-native-share/react-native-share

**Comment by geroale** [comment]
Same issue here

**Comment by ajaysaini-sgvu** [comment]
@MateusAndrade

**Comment by alex-ragin** [comment]
I confirm the issue as well. Rolling back to 4.1.2 (latest 4.x family release) fixes the issue.
