### ISSUE TITLE
Share.shareSingle in android 

### ISSUE THREAD

**Issue by luvyoon** [react-native-share/react-native-share#989]
## Ask your Question

Hi, 
I just wondering I am using share on Facebook and Instagram app.
The first time I share a picture, I call 

const ShareResponse = await Share.open(shareOptions);

and then change to 

const ShareResponse = await Share.shareSingle(shareOptions);
This is the only way for sharing to succeed and i dont know why.
Is there a good way?
please understand my poor english . Thanks in advance

**Comment by songhee24** [comment]
@luvyoon bro did you find a solution ?
