### ISSUE TITLE
Want to share multiple images with separate caption to each image Whatsapp

### ISSUE THREAD

**Issue by MSH786** [react-native-share/react-native-share#995]
## Ask your Question

I am using library, a good one, 
I just need little help, 

It is sharing multiple images with same caption, 

i just want to share multiple images with separate message (caption) to each image, 

suppose, if there is 5 images, then caption to 5 images is different not same.

In current situation, it share 5 images with same message (caption)

ThankYou.

**Comment by zuhairabbas870** [comment]
Hi there, i also have this issue,

is it solved or any suggestions?

**Comment by alit12** [comment]
Hey there, I am also having the same error. Please help me to solve this error.

**Comment by fiverr-start** [comment]
the same error,
kindly help us

**Comment by fiverr-start** [comment]
the same error,
kindly help us

**Comment by fiverr-start** [comment]
the same error,
kindly help us

**Comment by MSH786** [comment]
This is not solved still

**Comment by mikehardy** [comment]
@MSH786 @fiverr-start --> "kindly help us" is best written as "I'll look into this and post a PR" in an open source repository. Code up a solution and post it, then it will be fixed :-)

First step would be to see if Whatsapp even offers an API for this. It may not even be possible.
