### ISSUE TITLE
Share To Instagram stories never resolves promise

### ISSUE THREAD

**Issue by kristijantomic** [react-native-share/react-native-share#999]
Hi all,

Could anyone with experience using this lib to share on Instagram stories help me? If i try to share an image,  it shares it Instagram with success, but promise  never resolves :(.  Run on iOS only.
Any thoughts, anyone, thank you :)

Code snippet i have:
```javascript
      const options = {
        method: Share.InstagramStories.SHARE_BACKGROUND_IMAGE,
        social: Share.Social.INSTAGRAM_STORIES,
        backgroundImage: uri,
      };
      const res =  await Share.shareSingle(options);

     console.log({res}, 'Never happen');
```

**Comment by marcoalkema** [comment]
I have the same issue on Facebook Stories. The app loads fine, but also, the promise never seems to resolve.
